### ISSUE TITLE
60m and 11m Bands buttons are not visible

### ISSUE THREAD

**Issue by rvolchkov** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#10]
SunSDR2 DX
0.10.0 03112021
Windows 10

60m Band and 11m Band buttons are not visible, however, selecting the frequencies the bands are available and working and the button is visible.
[60_11.pdf](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/files/7502684/60_11.pdf)

**Comment by rvolchkov** [comment]
If these bands are allowed in your countries we add them. Please verify that with some kind of document or link to a document.

**Comment by rw4pan** [comment]
ESDR3. 
Надо бы добавить хотя бы 11 м.
Спасибо!

**Comment by rw4pan** [comment]
Если эти полосы разрешены в ваших странах, мы добавим их. Пожалуйста, проверьте это с помощью какого-либо документа или ссылки на документ.
Россия, Татарстан
