### ISSUE TITLE
Выход из программы ExpertSDR3

### ISSUE THREAD

**Issue by R7MU** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#101]
При выходе из программы, второй раз зайти невозможно, приходится выполнить - Снять задачу-ExpertSDR3, через диспетчер задач, Windows 10 Home, SunSDR2 QRP

**Comment by rvolchkov** [comment]
После закрытия рабочего окна ESDR3 и закрытия меню менеджера устройств, программа ESDR3 полностью не закрывается, она остается свернутой в трее Windows.
Достаточно его открыть и снова запустить программу.

**Comment by R7MU** [comment]
Спасибо!


чт, 25 нояб. 2021 г. в 17:15, Roman Volchkov ***@***.***>:
