### ISSUE TITLE
 RX2 bug

### ISSUE THREAD

**Issue by uc0a** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#102]
0.10.0 alpha
Win10 pro
SunSDR2DX
При работе двух приёмников на разных диапазонах, пропадает приём на RX2. Передача работает нормально на выбранную антену в BM
При работе на одном диапазоне RX1 и RX2 (без разницы на каком) всё работает нормально.

**Comment by uc0a** [comment]
Интересно на Win11 всё нормально

**Comment by ExpertSDR3** [comment]
Когда работаете двумя приёмниками на разных диапазонах нужно включить в трансивере ФНЧ на весь КВ диапазон или использовать автоматический выбор ФНЧ или ДПФ.
![frontend_dx](https://user-images.githubusercontent.com/93903520/143580792-de9e2781-f3a3-49a3-8e21-963bd5575dcf.png)
