### ISSUE TITLE
Где в ESDR3 находятся настройки E-Coder?

### ISSUE THREAD

**Issue by R7MU** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#103]
при вращении валкодера на 40м бегает по экрану "змейка" водопада, на других диапазонах нормально, как исправить и настроить кнопки и крутилки?

**Comment by ra4lp** [comment]
Провой клавишей мыши сначала по E-Cder на панели ,затем в окне где стрелоч
![Screenshot_8](https://user-images.githubusercontent.com/93971152/143533740-665a3301-34da-49b8-889b-27b6cdcb5300.png)
ка

**Comment by R7MU** [comment]
На диапазоне 40м не работает!!! SunSDR2 QRP
![image](https://user-images.githubusercontent.com/41430368/143552736-71646a21-fd93-4b11-be9b-3cebb3194666.png)
