### ISSUE TITLE
TCI from JTDX to ExpertSDR3

### ISSUE THREAD

**Issue by JamesWSchafer** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#105]
I am currently wanting to get TCI in JTDX (V 2.2.156) to work with ExpertSDR3 V 0.10.0.
I understand the TCI in ExpertSDR3 is an upgraded version and requires a possible update of TCI client in JTDX. 
I am using the latest version of JTDX. Is there a time frame of when JTDX will be upgraded to the version in ExpertSDR3.

**Comment by ExpertSDR3** [comment]
The author of JTDS is actively working on a new version that works with both ESDR2 and ESDR3. Preliminary versions can be downloaded from [here](https://drive.google.com/drive/folders/11GLHx4xmryoyw1GrpcaYY-5smybujc8M?usp=sharing). 
As soon as the work on the JTD is completed, you can download it from the official website.
