### ISSUE TITLE
Can't clear or update application auto-launch application path (a.k.a. "Features" in ESDR2)

### ISSUE THREAD

**Issue by williamscody** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#108]
Environment:
Intel Core i7-7700K CPU at 4.2GHz
AMD Radeon 580 Graphics Card
32GB RAM
Windows 10 Pro, version 21H1, 64-bit
SunSDR2DX, S/N EED06202100503, Firmware 72.8
ESDR3 0.10.0

Symptom:
When there is a previous path in the application auto-launch field, it cannot be cleared or edited.

Steps to reproduce:
1) Launch ESDR3
2) Select SETTINGS
3) Click on 4th icon from top (was called "Features" in ESDR2)
4) Clicking on any text in any of the path fields, whether active or not, does nothing.  It's impossible to clear or edit any path.

![Screenshot 2021-11-26 174241](https://user-images.githubusercontent.com/16505794/143662860-759c4905-cdb8-4545-b2f6-7a4266b943b1.jpg)

I discovered this when attempting to update the path of the first application to a new version of JTDX.  The workaround was to disable the first path, and add a new one at the bottom of the list.

**Comment by ExpertSDR3** [comment]
In the next version, it will be possible to remove the program from the list.
![app_lounch](https://user-images.githubusercontent.com/93903520/143679637-7e751b50-7726-41c0-a7bf-41c622850858.png)
