### ISSUE TITLE
E-Coder2 audio corrupted in EESDR3

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#109]
I have an E-Coder2 attached and am running EESDR3 0.10.0 Alpha (2 Nov).
SunSDR2DX is at version 72.8.

When activated, the audio from the regular PC soundcard is normal but the audio from the E-Coder2 headphones is chopped up without stopping. This is regardless of which mode is being used.

Only the audio received over TCI and the network suffers from this problem. The side tone from the CW generator sounds normal and not choppy.

I think this might be a E-Coder2 sound card issue. This does not happen with the audio in EESDR2.

**Comment by danweecc** [comment]
UPDATE: This does not happen all the time. I disconnected and reconnected the E-Coder2 and the audio is no longer choppy.

**Comment by ExpertSDR3** [comment]
these problems have been fixed, the fixes will be in version 0.11.
