### ISSUE TITLE
“Бросок” по мощности при включении на передачу

### ISSUE THREAD

**Issue by rvolchkov** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#11]
SS2DX
0.10.0
macOS
Pavel VK6NX

Есть небольшой “бросок” по мощности при включении на передачу - два раза в течение первых 6 секунд (на записи - https://mega.nz/file/CNwgCI6B#wd-ll6EJSicgurVKtcM7bnlXVMbmEaP_uAuKRJEyMug) при включении на передачу выдает 14.8 ватт и тут же “опускается” на 13.7. Уровень калибрации не важен - бросок все равно присутствует. В данном случае у меня выставлено ограничение не выше 15 ватт на 20 метрах - мои кастомные установки для моего внешнего PA. Собственно “бросок" критичен будет для всех solid state внешних PA на транзисторах типа BLF или MRF, поскольку они очень критичны к перегрузке по входу и им достаточно микросекунд перегрузки, чтобы сгореть. Равно как и недокачка им вредна - в этом случае не успеет отработать защита транзисторов по току. Я не уверен, отображает ли то что мы видим в UI реальный процесс (то есть есть ли бросок и снижение на самом деле) или это недостатки визуализации - но проверить стоит.
Бросок есть не только в Tune. Включен или выключен Use in tune - не влияет, во всяком случае на DX. Похоже бросок присутствует и при обычном включении, просто его сложно продетектировать. Я подключил очень точный power meter и сделал тире длиной в секунду - на первом тире видны колебания выходной мощности.

**Comment by VK6NX** [comment]
**English translation** : TX power above normal limit at first transmission

Every first transmission after switching band (or switching transceiver on) is encountering TX power above set limit. Can be seen on first 6 seconds of the screen recording: https://mega.nz/file/CNwgCI6B#wd-ll6EJSicgurVKtcM7bnlXVMbmEaP_uAuKRJEyMug - TX raised to 14.8W and then lowers to 13.7W. Calibration level does not matter, the "rise" still present. It also does not matter if "Use in Tune" option is On or Off.

I am not entirely sure if above described bump is just the current UI issue or the output power is certainly higher. I can see the described "bump" while using very precise external power meter, but still unsure if this is just mine DX behavior or other models are affected. At this stage and before acknowledgement I would recommend to set max TX limit a bit lower for those who has solid state external PAs.

In my particular example, the 15W limit is set on 20M band to meet maximum "drive power" requirements  of external PA. 

For the external PAs based on BLF and MRF MOSFETs it would be crucial to have the precise output PA  limit: to not overdrive the PA's input level and to not under-drive it (as under-dive can affect some MOSFETs high current protection mechanism).
