### ISSUE TITLE
EESDR3 with AAT-100 tuning never ends

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#110]
SunSDR2 DX firmware version 72.8, PCB revision 11
AAT-100 version1, revision 1
EESDR3 0.10.0 Alpha (2 Nov 2021)

Tune 25%
Drive 0%
ATU ON

When I activate TUNE it begins the process and completes with a dialog saying "Already Tuned" and I click on "OK" but the "Tune" does not go out. It stays activated in TX mode. In EESDR2 this does not happen this way. After the tuning, it goes back to RX mode. In the image below, you can see the TUNE still activate in orange colour and I do not heard any RX until I manually deactive TUNE.

![image](https://user-images.githubusercontent.com/13930571/143684256-9512fc22-fafa-4e5f-b75e-d2fa39c5e668.png)

**Comment by ExpertSDR3** [comment]
Perhaps you have the "ATU Stay on TX" function enabled.
![tune_mode](https://user-images.githubusercontent.com/93903520/143825653-f65afac3-c7cf-4de1-ac92-4e5944f770e6.png)

**Comment by danweecc** [comment]
Thanks! That was the problem. I think I misunderstood the "Stay on TX". I thought that meant that the ATU will track the TX frequency instead of the RX frequency. I guess it really means "Remain in TX after tuning".
