### ISSUE TITLE
E-Coder2 CW issues

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#111]
SunSDR2 DX version 72.8, PCB version 11
(These problems also occur with EESDR2)

1. The actual CW sending speed is much lower than indicated speed setting when using a paddle. So if I set CW speed to 46WPM in EESDR3, I get an actual speed of around 28WPM. In EESDR2 this happens in both low-latency and normal mode. In EESDR3 I cannot find the low-latency monitoring setting. The CW sidetone from the E-Coder2 that is output at the same time is much slowed that the CW sidetone heard on the soundcard output. It is as if the CW generator in the E-Coder2 is not synced with the EESDR3 CW generator even though they receive the same inputs. It's like connecting a paddle to two WinKeyers and set each of them to different speeds. There is a sync problem between the E-Coder2 code generation and the one in EESDR3 I think.

2. The CW elements sent seems to be shortened (but the pause appears to be ok). This problem only occurs in the sidetone generated by the E-Coder2 and can only be heard in the E-Coder2 output. At the same time, the CW heard from soundcard output has the element length correct according to the settings for CW sending.

3. When sending CW, the input detection is not reliable. There are frequent extra dits or dahs. Sometimes even after you let go of the paddle completely, the element continues to repeat. I have to tap the paddle again to stop this. I think the release of the paddle might not be caught by the software or hardware.

4. When sending CW using a logger via TCI, the sidetone does not appear in the E-Coder2 headphones output. It only appears on the normal PC soundcard output. This is a problem because it means that I need to listen to both E-Coder2 for the CW paddle sidetone, and to the PC for when CW is sent via TCI, or I will not know when the PC has finished sending.

**Comment by ExpertSDR3** [comment]
some problems have already been solved, the correct operation of the CW kernel depends on the firmware, with the release of version 0.11, a utility for updating the firmware in E-Coder2 will be released.
