### ISSUE TITLE
Increased IMD in V3 0.10.0

### ISSUE THREAD

**Issue by N8SDR007** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#112]
2 DX - V3 0.10.0 (newest release again missing build info # or version remark from an earlier V3 0.10.0)
Serial # EED06421900077
Firmware 72.8
PCB revision: 5 PA version: 13

Computer: AMD Ryzen 7
32 Gig ram
Windows 11 or Windows 10 (noted with either version)
GTX series Graphic running under Vulkan Mode /DX12 or Open GL - same issue

Increased IMD products with this newest release over past earlier releases
Bot on upper or lower SSB- mic driven at same output levels- using no internal processing (same audio chain as previous setup in earlier versions)

Also noted see this on others who also run 2DX radios and are using this release as well- more IMD than in previous releases on their signals as well.

I have also adjusted the filter taps to tighten the filter slope to a steeper cutoff and that hasn't helped- maxed them at 3800 taps (also is their new ratio since we can no longer max then to 8100 setting) It was nice when you could adjust filter taps in multiples of 1024

**Comment by ExpertSDR3** [comment]
fixed, fixes will appear in version 0.12.
