### ISSUE TITLE
E-Coder2 option sometimes disappears

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#113]
EESDR3 0.10.0 Alpha, 2 Nov 2021

I have E-Coder2 attached to the PC with EESDR3 running. The E-Coder2 is recognized upon start up and I can tune with the tuning knob/dial. At the bottom I can also see E-Coder2 show up in purple. After some time, if I click on this E-Coder2 button at the bottom, the button just disappears. I can still tune with the dial and the LED on the E-Coder2 is still on. I can still hear audio through the E-Coder2 output. It's just the button that has gone missing. This does not happen with E-Coder Plus, only with E-Coder2.

Steps to reproduce this:-
1. Run EESDR3
2. See that the E-Coder2 button appears at the bottom bar
3. Left-click the E-Coder2 button
4. Button disappears

**Comment by ExpertSDR3** [comment]
Fixed, there will be fixes in version 0.11.
