### ISSUE TITLE
E-Coder2 PTT generates a tone

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#119]
EESDR3 (as well as EESDR2) - all versions
Windows 10 64-bits
SunSDR2DX

When I close the PTT switch attached to the E-Coder2, I head a sidetone in the audio output from the E-Coder2 headphones. The audio from the computer does not have this tone. The tone also does not appear in the TX audio. It is as if the E-Coder2 is treating the PTT like a straight key in CW mode all the time and generating the sidetone. This does not happen with the E-Coder Plus, only with the E-Coder2.

**Comment by ExpertSDR3** [comment]
fixed, the fixes will be version 0.11
