### ISSUE TITLE
Термостат перестал работать

### ISSUE THREAD

**Issue by rvolchkov** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#12]
SS2PRO
0.10.0
Windows 10

Термостат перестал работать СОВСЕМ! При достижении температуры установленного значения Temperature Start вентилятор охлаждения не включается. При запуске ESDR2 с теми же настройками вентилятор включается и отключается при заданных температурных границах. (Скриншот "Temperature")
![Temperature](https://user-images.githubusercontent.com/90688941/140909672-85dc78a0-8dc5-4454-8ea3-413e54b09c2b.jpg)

**Comment by rvolchkov** [comment]
If the external fan is on at program startup, then PIN 7 is removed from the B.M. table as expected. However, the checkboxes are not. See the image attached. It may also be causing the issue with the automatic fan control that is not working (see other bug report). 
Enable automatic fan control. Shut the program down. Start program up and look at B.M. table. It will be missing 7 from the column header, but the column of buttons is still there.
Thanks, Richie.
![Uploading mw0llge_0_10_0.jpg…]()

**Comment by ExpertSDR3** [comment]
исправлено, исправления будут в релизе 0.10
