### ISSUE TITLE
ESDR3 нет переключения

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#123]
esdr3
 v 0.10.0 АLPHA
 Win 10-64Bit Ноme  
Transceiwer MB-1
MB-1 Utility  v 1.1.3
При использовании  внешней  звуковой карты ( или другой карты ПК ) выполняется команда  "включение" или "отключение " звука PC при этом эта команда дублируется в MB-1 Utility v 1.1.3  ( в виде пропадания или появления галочки ). но само действие не происходит при этом прослушивается  "обрабатывание"  реле 
![bandicam 2021-11-29 14-46-07-462](https://user-images.githubusercontent.com/93991940/143863841-15fd5fc9-d6bc-4af3-81e7-7492b6123f21.jpg)
![bandicam 2021-11-29 14-46-19-173](https://user-images.githubusercontent.com/93991940/143863842-ace72f6b-de77-4349-b82d-9350794ae1e3.jpg)

**Comment by ExpertSDR3** [comment]
Кнопки добавленные в ESDR3 управляют галками в MB1 Utility по аналогии с ESDR2.

**Comment by 1972igor** [comment]
да но звук не появляется  на карте ПК!!!
