### ISSUE TITLE
ESDR3 strong crackling noise during CW contest on Front Phone jack Audio 

### ISSUE THREAD

**Issue by hb9bun** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#126]
SunSDR2 DX
0.10.0 alpha
Windows 10

With a lot of load on the PC with ESDR3 audio from the SunSDR2 DX phones plug has heavy crackling noise. The noise seems generated by screen loading/display changes (probably caused by heavy changes due to incoming spots). The crackling happens as well when browser windows are loaded. 
ESDR2 at the same time has no such crackling with sample at 39 kHz, with sample rate at 312 kHz the audio from the SunSDR2 DX also has this crackling noise. 
The PC is perfomant enough, no visible issues with CPU load, RAM, SSD, Network or GPU load.

**Comment by ExpertSDR3** [comment]
We have created a discussion to solve this [problem](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/discussions/118)
