### ISSUE TITLE
VFO B is being wrongly restored from Memory

### ISSUE THREAD

**Issue by G4ENZ-Martin** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#128]
SunSDR2 Pro EED05401800600
Windows 10 + EESDR3 0.10.0 + FW 72.8

If a user switches to a previous frequency, VFO A is correctly restored but VFO B is not. The memory channel feature is also not correctly restoring VFO B frequency. 

To recreate this behaviour start with a clean configuration. The radio starts with both VFO A and VFO B on 1950kHz. Switch bands to 20m and both VFO A and VFO B are on 14100kHz. Now use the "previous frequency" control and the software correctly restores 1950kHz on both VFOs. Now use the "next frequency" control and the software correctly restores 14100kHz on both VFOs. Now use the "previous frequency" control again and VFO A is 14100kHz but VFO B is -12150kHz. Keep pressing Next and Previous frequency and VFO B will move the wrong way causing an increasing difference between the two VFOs.

This behaviour is also seen in the use of memory channels. Write 1950kHz to a memory channel then move to 14100kHz and write this to a memory channel. Now switch between the two memory channels and you will see that the VFO B frequency is wrongly changed on each move.

The image below is an example of the VFO B frequency after several jumps between the two memory channels.

![image](https://user-images.githubusercontent.com/94721418/144125054-562d1986-631d-4a1a-8966-aff9e113f143.png)

**Comment by ExpertSDR3** [comment]
fixed
