### ISSUE TITLE
Надписи не помещаются в рамки

### ISSUE THREAD

**Issue by rvolchkov** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#13]
При Application scale limit 100% некоторые надписи в установке панели не помещаются в кнопках. "Не самая главная деталь в самолёте", но всё-таки... (Скриншот "E-Coder")
![E-Coder](https://user-images.githubusercontent.com/90688941/140909931-516a0755-4d00-4405-b2de-e0d5656da106.jpg)

**Comment by ExpertSDR3** [comment]
исправлено
