### ISSUE TITLE
crackling on cw and ssb EESDR3  sample rate 312 khz

### ISSUE THREAD

**Issue by dl5rdq** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#130]
SunSDR2 DX
0.10.0 alpha
Windows 11
11th Gen Intel(R) Core(TM) i9-11900 
EESDR3 crackling with sample rate at 312 kHz audio from the SunSDR2 DX on CW and SSB

**Comment by ExpertSDR3** [comment]
[duplicate](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/issues/126)
