### ISSUE TITLE
ESDR3 knobs for Volume, Monitor, AGC, Drive, Tune not easy to control - selecting the round button may move it

### ISSUE THREAD

**Issue by hb9bun** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#131]
SunSDR2 DX
0.10.0 alpha
Windows 10

ESDR3 knobs can be selected with a mouse click and then e.g. Power can be changed with single percentage steps. When pushing the buttons for Drive, Tune, AGC, ... it often pushes the button up instead of just selecting it. As 5% more power can have a heavy influence on the PA output power, it would be good to be able to control this better (nice to have at the moment).

**Comment by N8SDR007** [comment]
Hover on it and use the mouse wheel up or down, much easier to control

**Comment by hb9bun** [comment]
Thank you. Works perfect. I am not used to work with the mouse wheel. 
73, Peter
