### ISSUE TITLE
работа регуляторов DRIVE TUNE показания Power METER мощность на выходе передатчика

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#132]
появление мощности на выходе передатчика и показания  индикатора "Power METER" появляются при установок ручек от 25% 
![bandicam 2021-12-01 10-02-02-053](https://user-images.githubusercontent.com/93991940/144187933-9e682ab2-1656-4ab7-bb34-640cc6750f68.jpg)
режим SSB и TUNE работа одинакова!!!
![Tune](https://user-images.githubusercontent.com/93991940/144188198-b80e63e5-8a1b-4de1-a6dd-ccf7cd8660b6.jpg)

**Comment by N8SDR007** [comment]
I have mentioned this a few times the two are no longer proportional in V3

In V2 if you set 25% for either the tune or the drive (you got almost identical peaks) no longer in V3- have tripped the Acom many a time and have to just make a chart- as they are no longer proportional or equivalate settings they are no equal on peaks

**Comment by ExpertSDR3** [comment]
Исправлено, теперь регулировка мощности выполняет более плавное изменение мощности, изменения появятся в версии 0.12.
