### ISSUE TITLE
OpenGL and ECoder

### ISSUE THREAD

**Issue by jmkr25** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#134]
By selecting OpenGL, ECoder remains off and not connected. No problem with DirectX or Vulcan. F1DJY

**Comment by danweecc** [comment]
I just tested my setup - EESDR3 Alpha 0.10.0 (2 Nov 2021) - along with my SunSDR2DX and E-Coder2. I put the graphics system to OpenGL and have no problem detecting the E-Coder2. Both the E-Coder Plus and E-Coder2 are detected in OpenGL mode. I am running on a Windows 10 64-bit system.

Summary: Cannot duplicate problem

**Comment by jmkr25** [comment]
Hello
Mine is ECoder only.
TRX is Sunsdr2Pro
ESDR3 0.10.0 24/11.
No problem with older versions !!

**Comment by IU4JNR** [comment]
> Hello Mine is ECoder only. TRX is Sunsdr2Pro ESDR3 0.10.0 24/11. No problem with older versions !!
> […](#)

Hi, I have the same setup and no issues at all.
Max
