### ISSUE TITLE
Не сохраняется местоположение окна программы ESDR3

### ISSUE THREAD

**Issue by UA0SM** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#136]
К компьютеру подключены два монитора. Перемещаю окно программы  на второй монитор, выключаю программу, перегружаю компьютер. 
После перезапуска компьютера окно программы не запоминается на втором мониторе, она снова появляется на первом мониторе. Система win10/64 ; SunSDR2 DX ; ESDR3 0.11.0

**Comment by ExpertSDR3** [comment]
исправлено
