### ISSUE TITLE
VFO does not correctly tune both VFOs when repeater on

### ISSUE THREAD

**Issue by IU4JNR** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#143]
When the repeater button is on, so the shift is active, tuning with E-Coder it changes the VFO A frequency only. Using the mouse wheel it works correctly chenging both VFOs.
EESDR3 V0.11 rel 2411
SunSDR2DX and SunSDR2 pro
Win11 Ryzen 7 5800x, 32Gb DDR4, SSD M2

**Comment by ExpertSDR3** [comment]
fixed, fixes will be in version 0.11
