### ISSUE TITLE
Scaling wrong on Linux

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#144]
EESDR3 0.10.10 03112021

In my Ubuntu 20.04 installation, I have a 1920x1080 display (100% scaling) but EESDR3 seems to detect this as a 4K display and enlarges everything such that it takes up more space than available on the screen.

**Comment by danweecc** [comment]
![image](https://user-images.githubusercontent.com/13930571/145552068-8ec388b1-80f8-4d1b-898e-88f4a5f5f77b.png)

![image](https://user-images.githubusercontent.com/13930571/145552116-626fc0c5-983a-4919-b156-dcabd12e694b.png)

**Comment by ExpertSDR3** [comment]
The Qt framework is responsible for scaling the program.
