### ISSUE TITLE
VFO B display random frequency when switching band 

### ISSUE THREAD

**Issue by IU4JNR** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#147]
When switching band with band selector  (also with a CAT connected logbook), the frequency shown on VFO B is random. It can be either a frequency inside an amateur band but mostly is a frequency outside,  sometimes is UHF, sometimes is ELF. It is really unpredictable.
SunSDR2 DX
EESDR 0.11 Rel 2411
Win11 Ryzen 7 5800x, 32 Gb DDr4, SSD M2

**Comment by ExpertSDR3** [comment]
fixed
