### ISSUE TITLE
PA button disappeared

### ISSUE THREAD

**Issue by IU4JNR** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#149]
The useful PA button disappeared from the menu.
EESDR 3 V 0.11.0 build 2411
SUNSDR2 DX

**Comment by ExpertSDR3** [comment]
In the settings, you can specify the operating mode of the PA, if You select save by band, then the inclusion will be available in the band manager.

![pa_button](https://user-images.githubusercontent.com/93903520/145758612-79492abb-dba6-41c7-b162-71fde9f42711.png)
