### ISSUE TITLE
Не запоминаются частоты Power corrrections

### ISSUE THREAD

**Issue by rvolchkov** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#15]
SunSDR2 137
0.10.0
Windows 10

В окне Colibartions не запоминаются частоты Power corrrections после перезагрузки. По Read вызов из ПЗУ производится. В принципе это не критично и пользуемся этим окном редко.
![ESDR3](https://user-images.githubusercontent.com/90688941/140911947-85330e0a-e9dd-49d9-a8cc-defd629ea553.jpg)

**Comment by ur0hq** [comment]
Аналогично.. после рестарта программы не сохраняются ранее записанные значения.
