### ISSUE TITLE
ESDR3 прекращает работу при передаче на 14 и 18 Мгц.

### ISSUE THREAD

**Issue by ub3dqy** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#150]
SUNSDR2DX, S/N EED06121000432
ESDR3 0.10.0 Alpha
Windows10Pro x64
Gigabyte X58A-UD7, Xeon X5675, RAM 24 GB, SSD Samsung 250 Gb, Nvidia NVS 315, трансивер подключен к роутеру Keentic Runner 4G.
При переходе на передачу на диапазонах 14 и 18 Мгц, программа ESDR3 вылетает. 
При работе в ESDR2 1.3.1 Upd 11 данной проблемы нет.

**Comment by ExpertSDR3** [comment]
К ESDR3 подключёны программы по TCI ?

**Comment by ub3dqy** [comment]
Да,  с другими программами связь по TCI. Но другие программы на это не влияют, ESDR3 вылетает даже если запустить только её и нажать кнопку TUNE, при мощности более 40Вт. Если установлена мощность до 40 Вт, сбои не наблюдались.

**Comment by ExpertSDR3** [comment]
fixed
