### ISSUE TITLE
Menu "Proc" Module "NOISE Cancellation" does not work correctly

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#153]
![Noise cancellation](https://user-images.githubusercontent.com/93991940/145703702-81419773-06d9-43ca-9239-fd8752a739bd.jpg)
Вместо того чтобы обнаруживать внешние шумы и подавать  равный, но противоположный, сигнал подавления. Данная система при включении рвёт звук !!! Не чётко выставлена работа чувствительности!!!
instead of detecting external noises and giving an equal, but opposite, suppression signal. This system breaks the sound when turned on !!! The sensitivity work is not clearly exposed!!!

**Comment by ExpertSDR3** [comment]
Приложите аудио фалы для примера с включённым и выключенным шумоподавителем.

**Comment by 1972igor** [comment]
https://user-images.githubusercontent.com/93991940/145781858-42f37be9-62a6-442d-af4d-8564cb38623a.mp4

**Comment by 1972igor** [comment]
вот слышно ! "Noise Cancellation" явно рвёт  звук его динамику , а не давит шумы!!!

**Comment by 1972igor** [comment]
![bandicam 2021-12-13 12-15-17-078](https://user-images.githubusercontent.com/93991940/145785945-840316d6-9f47-4889-95a7-4fc3faef6502.jpg)

**Comment by ExpertSDR3** [comment]
Система шумоподавления работает правильно, предназначена для подавления агрессивной помехи, шум пылесоса, шум проезжающих автомобилей итд. В условиях отсутствия таких помех включать его не нужно.
