### ISSUE TITLE
E-Coder2: CW paddle sending sometimes misses contact or gets stuck

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#156]
EESDR3 0.11.0 17122021
Windows 10 64-bit

CW sidetone monitoring with E-Coder2 is now much much better compared to before (which was unusable.) However, it sometimes seems to miss a dit or a dah, or it misses the release. When this happens, it will keep sending a string of dits or dahs because it doesn't know that you have released the key.

The weird thing is that this only happens on the sidetone coming from the PC. The sidetone coming from the E-Coder2 is perfect. So when the PC side is giving a string of dits or dahs because it missed the release, the audio from the E-Coder2 is normal - no false repetitions.

At the same time, the CW sidetone from the PC side always seems to be missing the last "dit" of a character but the sidetone from the E-Coder2 is perfect. It almost seems like the paddle is connected to two different keyers - one in the PC and one in the E-Coder2. The one in the PC appears to be missing some of the key-ups or key-downs and is generating incorrect keying while the keyer in the E-Coder2 is more accurate and responsive. I'm not sure how this can be fixed but it seems to be a problem with Windows latency while trying to catch the key level changes.

**Comment by ExpertSDR3** [comment]
A utility is being prepared that will update the panel firmware, the new firmware will fix errors in the panel operation
