### ISSUE TITLE
E-Coder2: Audio corruption in EESDR3 0.11.0 17122021

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#157]
EESDR3 0.11.0 17122021
Windows 10 64-bit

The audio from the E-Coder2 sometimes gets corrupted. If I disable and re-enable E-Coder2 from EESDR3 the problem is fixed, until it happens again. I've not been able to consistently make this happen.

**Comment by ExpertSDR3** [comment]
A utility is being prepared that will update the panel firmware, the new firmware will fix errors in the panel operation
