### ISSUE TITLE
RX gain correction does not update on RX2

### ISSUE THREAD

**Issue by LA9AKA** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#158]
Device: MB1
Software: SDR3 v0.10.0 alpha
OS: Win10 64

Example: If I select -25dB gain in Band Manager on 2m, RX1 immidiately updates with the correction. When I open RX2 it does not have the gain correction. If I change RX2 to another band, and go back again to 2m the gain correction is done. 

73
Hans Christian LA9AKA

**Comment by ExpertSDR3** [comment]
Fixed, the fixes will be in the public version 0.11.
