### ISSUE TITLE
TX over the air playback after recoding- output very low drive

### ISSUE THREAD

**Issue by N8SDR007** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#159]
Windows 11 
V3 0.11.0 Build 17122021

Over the Air Playback of recorded signal does not always work
most of the time there is VERY LOW output drive.
Do seeing a way to adjust TX playback gain levels to correct the output drive or audio structure of the recorded audio.

Side Note the Local playback level and quality seems correct it is just when attempting to playback Live over the air that no or very low output occurs

**Comment by N8SDR007** [comment]
Checking recorded TX audio playback while in TX- audio Mic meter average around -22 dipping to almost -30

Which produces no PA drive for rig-
Signals I recoded the stations were either slightly above noise floor or were well above noise floor like 15-20 dB-

**Comment by 1972igor** [comment]
Rick!My great friend ! I saw that the added ethereal tape recorder, its level is affected by the volume knob of the receiver! When this knob is set to the maximum, then the level of the tape recorder for transmission is good!!! It shouldn't be!
![bandicam 2021-12-17 22-44-04-196](https://user-images.githubusercontent.com/93991940/146599781-974f5aad-b610-44f9-9684-9aa688334316.jpg)

**Comment by 1972igor** [comment]
Rick!My great friend ! I saw that the added ethereal tape recorder, its recording level is affected by the volume knob of the receiver!

**Comment by N8SDR007** [comment]
Right
The recording level for making a recording or for playing that recording back over the air should not be effected buys volume control esp for recording

Recoding should be at the revived level right after the AGC threshold that is set.
Tx blackout over the Air should have its own tx pre recorded gain control

⁣Get BlueMail for Android ​

On Dec 17, 2021, 2:48 PM, at 2:48 PM, 1972igor ***@***.***> wrote:
>Rick!My great friend ! I saw that the added ethereal tape recorder, its
>level is affected by the volume knob of the receiver! When this knob is
>set to the maximum, then the level of the tape recorder for
>transmission is good!!! It shouldn't be!
>![bandicam 2021-12-17
>22-44-04-196](https://user-images.githubusercontent.com/93991940/146599781-974f5aad-b610-44f9-9684-9aa688334316.jpg)
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/issues/159#issuecomment-996992543
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by jmkr25** [comment]
After several tries this evening, I observed the same thing here. Correct recording level in transmission by turning the volume up.
73. F1DJY

**Comment by Kb2uka** [comment]
I'm having the opposite issue. Local playback, received audio is very low. Tx audio is perfect. 

Over the air no issues with either. Mac version.

**Comment by ExpertSDR3** [comment]
Fixed, the fixes will be in the public version 0.11.
