### ISSUE TITLE
Тема бага

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#16]
Описание Бага 
Программа ESDR3 имеет  переключение источника звука на передачу ( в том числе и VAC) переключение  производится , но отсутствует звук при передаче в том числе и по VAC

**Comment by 1972igor** [comment]
> Описание Бага Программа ESDR3 имеет переключение источника звука на передачу ( в том числе и VAC) переключение производится , но отсутствует звук при передаче в том числе и по VAC

**Comment by ExpertSDR3** [comment]
Повторяет #17
