### ISSUE TITLE
Почему так, если версия одна и таже от сегодняшнего числа???

### ISSUE THREAD

**Issue by ra4lp** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#160]
![Screenshot_18](https://user-images.githubusercontent.com/93971152/146589103-3399e98d-9cf4-4bd4-b8b7-94436335a491.png)
![Screenshot_19](https://user-images.githubusercontent.com/93971152/146589139-8180df67-0e23-4964-8ce2-8e83ee2d9b38.png)
У меня вместо динамика надпись MUTE.

**Comment by ExpertSDR3** [comment]
Не для всех устройств обновлён внешний вид кнопки, в публичной версии будет исправлено.
