### ISSUE TITLE
Vox button on E-Coder not operating

### ISSUE THREAD

**Issue by G4ENZ-Martin** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#161]
Windows 10 + SunSDR2 Pro EED05401800600
ExpertSDR3 V 0.11.0 Build 17121021

Define a button on the E-Coder to switch Vox. Nothing happens when you operate the button.

(The VOX is great - thank you)

**Comment by ExpertSDR3** [comment]
Fixed, the fixes will be in the public version 0.11.
