### ISSUE TITLE
Changing beyond Bandlimits and back changes VFO B of the RX to undefined values or increases VFO  B frequency 

### ISSUE THREAD

**Issue by hb9bun** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#162]
SunSDR2 DX
0.10.0 alpha
Windows 10

When e.g. switching VFO A from 10.149.500 to 10.150.500 VFO B goes e.g. 10.142.5 to 6.775.426 (as I move out of the 30m band). Putting then VFO A back 10.149.426, VFO B is increasing by 1 kHz,  
When going out of Band with VFO A, out of band VFO B is increased by 1 kHz,
When coming back with VFO A into the band, VFO B is decreased every time by 1kHz.
Probably the band memory is not reset properly for the out of band and the 30m ham band segment. 

With ESDR2 VFOB does not change at all when changing VFO A frequency. 

73, Peter

**Comment by hb9bun** [comment]
Probably same issue as #147.

**Comment by ExpertSDR3** [comment]
fixed
