### ISSUE TITLE
Low recorded receive audio

### ISSUE THREAD

**Issue by Kb2uka** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#163]
Eesdr3 v 0.11.0 mac iOs 
I9 iMac - 64gb ram
Sunsdr2dx

When pressing the record button on the main gui. 

During playback, tx audio gain is perfect, rx audio gain is very low.
Have not tested over the air playback yet. This is strictly at the local level. 

No other issues to report after 5 hours of use.

**Comment by ExpertSDR3** [comment]
The volume during playback depends on the volume knob.
