### ISSUE TITLE
 0.11.0 alpha - Age compensation  всегда включена.

### ISSUE THREAD

**Issue by bastonc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#165]
Не страшный баг, но выключатель возрастной компенсации - не работает и она всегда включена.
Прилагаю видео с демонстрацией эффекта  - https://youtu.be/5Cgxi8e0bKc

**Comment by ExpertSDR3** [comment]
Это не баг, компенсация работает вне зависимости от переключателя тонкомпенсации

**Comment by bastonc** [comment]
Да, приношу извинения. Просто выглядит как будто - это включатель функции age compensation ))
