### ISSUE TITLE
ExpertSDR3 Startup App - "Start" button displays incorrect state

### ISSUE THREAD

**Issue by williamscody** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#168]
Device: SunSDR2dx
S/N: EED06202100503
EESDR3 version 0.11.0, Build 17122021, Firmware version 72.8
Windows 11 Pro, version 21H2

Problem: 
In the ESDR3 startup application, the "Start" button in the 1st pane does not accurately reflect the main application's state.

Here's a screenshot of the problem, showing the "Start" button indicating "Stop" when in fact the main application is not running.
![2021-12-18 16_14_12-Settings](https://user-images.githubusercontent.com/16505794/146658016-e6ff5932-0fb8-4aaf-a043-824ca03f16e7.png)

Steps to reproduct:
1) Completely quit ESDR3 application
2) Launch ESDR3
3) Click Start button to launch the main application
4) Close the ESDR3 main application window by clicking "X" in the upper right corner
5) Witness that the ESDR3 startup application still shows the "Stop" button, when it should indicate "Start."

100% reproduceable.

**Comment by danweecc** [comment]
I've had this a few times but it seems to have resolved itself after a while.

**Comment by VK6NX** [comment]
Not applicable for Mac 10.15.7 - always shows correct state

**Comment by ExpertSDR3** [comment]
fixed, fixes will be in pubic version 0.11
