### ISSUE TITLE
 ESDR 3 v 0.11.0 Block "Proc" module "Processing"

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#169]
ESDR3 V0.11.0 Alpha
Win-10 Home 64
MB-1
Audobe Audition 1.5
наблюдаются различия в уровнях, при работе модуля "Processing" и его режима "BAYPASS" . А именно, модуль "Processing режим " разница составляет2,6 dB! При включении модуля "Processing" и положения Level 0 dB , уровень манятся НЕ ДОЛЖЕН !!!! Поэтому , программное усиление ( в прошивке "Processing") не трогая регулятор "Processing" LEVEL необходимо убавить на 2,6 dB!!! ( информации уровня по панораме и индикатора Mic meter не точны , т.к они не отстроены, но даже по ним видна разница в уровнях )
Englsn version 
there are differences in levels when the "Processing" module and its "BAYPASS" mode work. Namely, the module "Processing mode" the difference is 2.6 dB! When you turn on the "Processing" module and the Level 0 dB position, the level SHOULD NOT be attracted!!!! Therefore, the software gain (in the "Processing" firmware) without touching the "Processing" LEVEL controller must be reduced by 2.6 dB!!! ( the information of the panorama level and the Mic meter indicator are not accurate, because they are not built up, but even they show a difference in levels )
![in  -10 dB one Tone 1000 Gz](https://user-images.githubusercontent.com/93991940/146667319-ed3bf760-a34c-4464-a31c-c4e770b7286f.jpg)
![Preprocessing OFF ](https://user-images.githubusercontent.com/93991940/146667323-fc3b0a60-8098-4f53-ae35-b4f815cd448e.jpg)
![Preprocessing ON ](https://user-images.githubusercontent.com/93991940/146667324-f6e9eca0-58de-415e-b656-bd4277aedd9a.jpg)

**Comment by 1972igor** [comment]
я создал видео , где показано, что модуль Preprocessing https://www.youtube.com/watch?v=7FggRW8iaHw
I have created a video where it is shown that the Preprocessing module

**Comment by 1972igor** [comment]
P.S Я забыл указать, что когда мы изменяет регулятор Level от 0 dB до +20dB у нас уменьшается уровень основного тона и возрастают гармоники от основного тона !!!
English version of the text
I forgot to point out that when we change the Level control from 0 dB to +20dB, the pitch level decreases and harmonics from the pitch increase!!!
![bandicam 2021-12-19 22-28-35-774](https://user-images.githubusercontent.com/93991940/146688169-4d7192d3-732c-456c-a5af-a6f742d179d1.jpg)

**Comment by bastonc** [comment]
Так в гармониках и фича этого блока - это же исказитель и по уровням - при 0 дБ - тоже все корректно. В этом приборе Level - это не выходной уровень. Это дБ исказителя (точный алгоритм известен разработчикам). Отнесись к ним как к попугаям, где 20 дБ - это максимум влияния, 0 дБ - минимум влияния на звук.

**Comment by 1972igor** [comment]
какое корректно? ВЫ видите , что при 0 dB уровень идёт больше  на 2,5 dB ? чем в байпасе ! Вы видео то видели? поняли о чём я говорю вообще!???

**Comment by bastonc** [comment]
> какое корректно? ВЫ видите , что при 0 dB уровень идёт больше на 2,5 dB ? чем в байпасе ! Вы видео то видели? поняли о чём я говорю вообще!???

Я  в разы лучше Вас понимаю о чем говорю и Ваше видео посмотрел. Я имею аргументы, для того, что бы обосновать, что Ваше видео - раздувание из мухи слона. Хотя бы потому, что в реальной динамике - работе с микрофоном, уровень на вход подается с запасом, на уровне -9..-6 дБ, и плюс-минус 2 дб, это слезы, которые вообще не важны. Но вам это пока трудно понимать. Не будем разводить срачь на гитхабе. Извините, что не удержался и отреагировал.)) Желаю удачи

**Comment by ExpertSDR3** [comment]
Алгоритмы работы багами не являются, для обсуждения предложений и пожеланий и вопросов по работе тех или иных алгоритмов есть отдельная тема https://github.com/ExpertSDR3/ExpertSDR3-SUGGESTIONS/discussions

**Comment by 1972igor** [comment]
проблема в том, что когда включаем Procissing при установке level 0dB! уровень возрастает на 2,5dB! А этого быть не должно!!! В этом весь БАГ!!! ИСПРАВТЕ ПОЖАЛУЙСТА!!!
