### ISSUE TITLE
Break.In CW over SSB incorrect transmit frequency

### ISSUE THREAD

**Issue by G4ENZ-Martin** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#171]
**New issue in 0.11.0 17122021**

Select both SSB and Break.In

Operate Key and the transmitted CW is offset by 700Hz (current value for Pitch) <- This is correct behaviour

Now go to transmit with either VOX, TX or PTT. (After doing this, the problem happens.)

Operate the Key again and now the transmitted CW is offset by 0Hz <- This is wrong behaviour

Stopping transceiver and Starting transceiver will reset this behaviour.

https://user-images.githubusercontent.com/94721418/146756417-61fd0241-e6fc-407a-8d22-2b5aeea19d66.mp4

**Comment by ExpertSDR3** [comment]
Fixed, the fixes will be in the public version 0.11.
