### ISSUE TITLE
магнитофон работа  записи воспроизведения

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#172]
магнитофон записи, для передачи в эфир зависит  его уровень от регулятора громкости приёмника! Это не правильно!   
ПРОСЬБА ИСПРАВТЕ пожалуйста!
![магнитофон  (1)](https://user-images.githubusercontent.com/93991940/146772363-c3a87b0f-073c-44d9-aa8a-9b9d71822488.jpg)

**Comment by ExpertSDR3** [comment]
Исправлено, исправления будут в публичной версии 0.11.
