### ISSUE TITLE
60m Band with wrong frequency range for Switzerland 

### ISSUE THREAD

**Issue by hb9bun** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#173]
ESDR3 V11 alpha
Win10

60m is now a band option for Win Settings German (Switzerland), but the band range in ESDR3 for Switzerland is set too small. 
It should be 60m Band (5351.5 to 5366.5 kHz). 

This is also as it is in the IARU Region 1 bandplan. https://www.darc.de/fileadmin/filemounts/referate/hf/hf_r1_bandplan.pdf

73, Peter - HB9BUN

**Comment by ExpertSDR3** [comment]
Fixed, the fixes will be in the public version 0.11.
