### ISSUE TITLE
При включении трансивера S-metr показывает случайные значения

### ISSUE THREAD

**Issue by namer1956** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#174]
При нажатии на кнопку старт трансивера S-metr показывает случайные значения шума сигнала.
Это не зависит от шумовой обстановки в эфире. Если нажать на кнопку tx показания S-metr переходят к нормальному значению.
Может это замечание уже было? Я не нашел.
С уважением Ник.

**Comment by ExpertSDR3** [comment]
Можете приложить видео?

**Comment by namer1956** [comment]
Прилагаю видео.
--
Отправлено из Mail.ru для Android вторник, 21 декабря 2021г., 09:34 +03:00 от EE  ***@***.*** :

>Можете приложить видео?
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you authored the thread. Message ID:  @ github . com>

К этому письму приложены ссылки на следующие файлы:

1. VID20211221191959.mp4 (84.8 Мб)

Ссылка для скачивания файлов: https://cloud.mail.ru/stock/3KsdyfJMkLFJ4KcktA4TvkGp

Файлы будут храниться до 19.06.2022

**Comment by ExpertSDR3** [comment]
исправлено
