### ISSUE TITLE
sql

### ISSUE THREAD

**Issue by w4kap** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#175]
will there be a sql like in versio 2

**Comment by ExpertSDR3** [comment]
Please explain.

**Comment by 1972igor** [comment]
имелось в виду IQ файловый магнитофон!!!
it meant an IQ file recorder!!!

**Comment by ExpertSDR3** [comment]
In version 0.12, the recording of IQ signals has been added.

![iq_rec](https://user-images.githubusercontent.com/93903520/150540683-c2cbcad3-e3dc-4274-b22c-2cc640dd103c.png)
