### ISSUE TITLE
не правильная работа генератора одного - двух тонов

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#176]
ESDR3 V0.11.0 Alpha
Win-10 Home 64
MB-1
Audobe Audition 1.5
Замечен БАГ в работе звукового генератора одного и двух тонов в программе ESDR3 v 0.11.0 Alpha
произведены  измерения и сравнения работы звукового генератора одного и двух тонов в программе ESDR3  и программы ESDR2 v UP9
ПОЖАЛУЙСТА ИСПРАВТЕ!!!!
видео прилагается https://www.youtube.com/watch?v=u7eW7_tVkhg
english version text
ESDR3 V0.11.0 Alpha
Win-10 Home 64
MB-1
Audobe Audition 1.5
A BUG was noticed in the operation of the sound generator of one and two tones in the ESDR3 v 0.11.0 Alpha
program, measurements and comparisons of the operation of the sound generator of one and two tones in the ESDR3 program and the ESDR2 v UP9 program were made
PLEASE FIX IT!!!!
video attachedin the video clip, turn on the credits and set the desired language for translation
  https://www.youtube.com/watch?v=u7eW7_tVkhg

**Comment by ExpertSDR3** [comment]
В работе генератора ESDR3 нет ошибок:

![one_tone](https://user-images.githubusercontent.com/93903520/149894296-b81db753-7fb3-44cd-95ce-46f514fd5afe.png)

![two_tones](https://user-images.githubusercontent.com/93903520/149894353-d0c92175-6d22-46e4-98cc-f7a4dcccbcf3.png)

На скриншотах видно, что при одном тоне уровень сигнала 0 дБ, что соответствует максимальной амплитуде. При двух тонах амплитуда каждого вдвое меньше, чем при одном, что и видно на панораме, СКО мощность при двух тонах также снизится вдвое, это видно на MIC -метре, он отображает СКО мощность в полосе -3 дБ.
