### ISSUE TITLE
Voice recorder does not go TX

### ISSUE THREAD

**Issue by IU4JNR** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#178]
Voice recorder does record correctly but it does not TX the recorded audio. The playback (right click) works correctly.

https://user-images.githubusercontent.com/94228375/146948792-326475d5-56ed-4008-8ac4-02555bd596b7.mp4

**Comment by ExpertSDR3** [comment]
Fixed, fixes will appear in public version 0.11.
