### ISSUE TITLE
display at max zoom slow down - Random behaviour

### ISSUE THREAD

**Issue by IU4JNR** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#179]
The waterfall and the panadapter when zoomed in at max zoom slow down, zooming out just one step it speed up again. 
This happen randomly and ONLY using the E-Coder on both SunSDR2 DX with OpenGL API and SunSDR2 Pro with DirectX API,  ONLY using the E-Coder. Using the mouse it works fine. Changing the USB port type it doesn't change

ESDR3 v0.11.0 build 1712
Win11, Ryzen 7 5800x, 32Gb DDR4, SSD M2, Cisco 1G switch.

https://user-images.githubusercontent.com/94228375/146950065-2c0ac5a5-a28f-4e20-bded-44a29433f00d.mp4

https://user-images.githubusercontent.com/94228375/146957803-e387a8c4-aa7c-406c-acf2-10ffdd1528ab.mp4

**Comment by ExpertSDR3** [comment]
Fixed, fixes will appear in public version 0.11.
