### ISSUE TITLE
RX gain compensation issue

### ISSUE THREAD

**Issue by rvolchkov** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#18]
SunSDR2 DX
0.10.0 Alpha build 03112021
Windows 10

Having applied an RX gain compensation in Band Manager when selecting RX2 for the same band, RX gain compensation is not applied to RX2.
Set up an RX gain compensation in Band Manager (for me it is 2m band). Confirm that the RX gain compensation is correctly applied by checking the noise floor on the spectrum on RX1 (again for me, it works well). Select RX2 for the same band and mode as RX1. By comparing noise floor levels between RX1 and RX2, observe that the noise floor on RX2 does not have the RX gain compensation applied.
![20211105_091616](https://user-images.githubusercontent.com/90688941/140947239-398e00e2-2a33-46c5-a45f-2b6db99e5360.jpg)

**Comment by ExpertSDR3** [comment]
fixed, fixes will be in version 0.11
