### ISSUE TITLE
AAT-100 & SunSDR2 DX

### ISSUE THREAD

**Issue by ON3CQ** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#180]
Last days test with AAT-100 and SunSDR2 DX.
V2 no problem to use it at 40-30m perfect.
V3 0.11 it is not possible to tune the same antenna.
Is it possible to reset the memory of the AAT-100 on a particular band.
There is no option anywhere in V2 or V3.0.

**Comment by danweecc** [comment]
I have also noticed that the SWR readings given by EESDR3 is different from that given by EESDR2. As a result, under EESDR2 the ATU can find some solutions which cannot be found under EESDR3.

**Comment by ExpertSDR3** [comment]
The operation of the ATU does not depend on ESDR2/3. The ATU performs hardware matching with the antenna.
