### ISSUE TITLE
IMD 1-2kc into the upper side band while operating lower side band on 40 meters

### ISSUE THREAD

**Issue by Kb2uka** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#181]
Eesdr3 v0.11.0 
I9 iMac 
Sunsdr2dx 

Continuing to see IMD artifacts into the upper side band around 1-2kc above the selected frequency. I notice this mostly on 40 meters. 

All mic levels and inputs are the same from previous test. I still believe this a mic gain/metering issue and needs correction.

**Comment by N8SDR007** [comment]
Shoot for a -10 on the mic meter and report back please-

**Comment by 1972igor** [comment]
it is not possible to establish that the sound comes with a level of minus 10 dB!!! The Mic meter indicator gives incorrect information about the level of incoming sound readings are not linear at the lower aisles below zero this indicator lies in the readings!!! input 0 dB MIC LEVEL shows
0 dB input minus 5 dB MIC LEVEL
shows minus 2.5 dB input minus
10 dB MIC LEVEL shows minus 5 dB
entrance minus 15 dB MIC LEVEL shows
negative 7,5 dB MIC LEVEL shows
minus 20 dB MIC LEVEL shows minus 10 dB MIC LEVEL shows minus 25 dB MIC LEVEL shows minus 12 dB -30 dB input LEVEL of the MICROPHONE shows minus 30 dB MICROPHONE LEVEL shows minus 15 dB
entrance minus 35 dB MIC LEVEL shows minus 17 dB

**Comment by 1972igor** [comment]
ESDR3 V0.11.0 Alpha
Win-10 Home 64
MB-1
Audobe Audition 1.5
 it is not possible to establish that the sound comes with a level of minus 10 dB!!! The Mic meter indicator gives incorrect information about the level of incoming sound readings are not linear at the lower aisles below zero this indicator lies in the readings!!! input 0 dB MIC LEVEL shows
0 dB input minus 5 dB MIC LEVEL
shows minus 2.5 dB input minus
10 dB MIC LEVEL shows minus 5 dB
entrance minus 15 dB MIC LEVEL shows
negative 7,5 dB MIC LEVEL shows
minus 20 dB MIC LEVEL shows minus 10 dB MIC LEVEL shows minus 25 dB MIC LEVEL shows minus 12 dB -30 dB input LEVEL of the MICROPHONE shows minus 30 dB MICROPHONE LEVEL shows minus 15 dB
entrance minus 35 dB MIC LEVEL shows minus 17 dB

**Comment by 1972igor** [comment]
ESDR3 V0.11.0 Alpha
Win-10 Home 64
MB-1
Audobe Audition 1.5
it is not possible to establish that the sound comes with a level of minus 10 dB!!! The Mic meter indicator gives incorrect information about the level of incoming sound readings are not linear at the lower aisles below zero this indicator lies in the readings!!! input 0 dB MIC LEVEL shows 0 dB input 
minus 5 dB MIC LEVEL shows minus 2.5 dB
 input minus 10 dB MIC LEVEL shows minus 5 dB
entrance minus 15 dB MIC LEVEL shows negative 7,5 dB
 MIC LEVEL shows minus 20 dB MIC LEVEL shows minus 10 dB MIC LEVEL
 shows minus 25 dB MIC LEVEL shows minus 12 dB -30 dB
 input LEVEL of the MICROPHONE shows minus 30 dB MICROPHONE LEVEL shows minus 15 dB
entrance minus 35 dB MIC LEVEL shows minus 17 dB

**Comment by 1972igor** [comment]
ESDR3 V0.11.0 Alpha
Win-10 Home 64
MB-1
Audobe Audition 1.5
also, in the lower aisles below 0dB, the "BOOST" indicator does not correctly give information, the manufacturer left the solution of these issues for later!!!

**Comment by Kb2uka** [comment]
Upper and lower imd. 

Seems to also be happening in v2 now as well so not sure if there were changes made by firmware or the software. I tested with different amp, still happened with a different amp. 

https://youtu.be/asXVgrEhkJg

**Comment by N8SDR007** [comment]
There were no updates to firmware in the last releases
My V2 is clean, since you are experiencing this more so on 40M and on V2 suggests something has changed in your environment

I will note as i did weeks ago that the current last 2 releases of V3 are not as clean as prior and that has been mentioned numerous times the MIC gain and also the Processor sections gain structures are totally WHACKED

Igor my comment regarding the minus 10 to Doug was in respect that he is using Outboard audio setup so the only thing he has is the Mic input and from What I am experiencing here when I set to a level of around -10 that seems to clean up things and also produce smoother non clipping or harsh audio and cleaner IMD

**Comment by ExpertSDR3** [comment]
fixed, fixes will appear in version 0.12.

**Comment by Kb2uka** [comment]
That is great news. Thank you!
