### ISSUE TITLE
RadioSync (Sound input-output) not working

### ISSUE THREAD

**Issue by N8SDR007** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#184]
I updated the new V3 and Also the new release of Radio Sync which has the soundcard option

However, I cannot get the Soundcard option to Work, or even act like it is active (notice no GREEN indicator) in attached picture 

In the external Application I also get no input or output, 

Unless I go back to my old VAC workaround method for V3 I posted on the forum

Something is either missing to activate the option in TCI on V3 or I am an idiot? 

Being an Idiot at times wouldn’t be the first so you won't hurt my feelings

What the heck am I not figuring out here I mean usually I get this figured out quickly, or is something not yet setup in V3 to allow that option to get Audio

I do have rig control through the application and am able to change bands and key and unkey the radio, just not passing any audio either RX or TX?
![Sounmdcard not active](https://user-images.githubusercontent.com/94698375/147583305-dc0828cd-d52e-44a9-88e2-82e617bda115.jpg)

**Comment by N8SDR007** [comment]
Also note that after setting up and saving a profile for RigSync , the Soundcard Section does not SAVE! when closing and reopening the TCI and CAT sections save the information correctly but the Sound Card section does not save the settings

**Comment by G4ENZ-Martin** [comment]
It works for MME driver but not WDM-KS or WASAPI

![image](https://user-images.githubusercontent.com/94721418/147649872-b19bc469-476d-4361-94ac-507591f564d1.png)

**Comment by N8SDR007** [comment]
Even MME no go, here
Curious Martin, what version of VAC are you using. here it is version 4.65 I had issues with 4.66

I cannot get the Sound Card option light to ever turn green, nor do I get an input or output of the digital program.

I have tried starting them in various orders as well,

What Radio are you using, I do not believe it is a 2DX from a couple of your screen shots posted on the Forum 
So, I wonder if this function is broken in the coding of the 2DX model perhaps

**Comment by G4ENZ-Martin** [comment]
Old VAC here. 4.64.0.11315.  Never needed to upgrade.

Just tested with VB-audio Cable - that works MME but doesn't start with either WASAPI or WDM-KS.

With MME the latency is huge so probably not too useful for your VarAC even if you do get it to work.

**Comment by N8SDR007** [comment]
Thanks for the update

Yes that program is very very dependent on extremely low latency I do manage to get vac to work using the workaround method that I found several revisions ago and that seems to work for VAC

I posted that on the forum it will work with kms mme or wsapi

Thanks Martin
Cheers

⁣Get BlueMail for Android ​

On Dec 29, 2021, 5:56 AM, at 5:56 AM, G4ENZ-Martin ***@***.***> wrote:
>Old VAC here. 4.64.0.11315.  Never needed to upgrade.
>
>Just tested with VB-audio Cable - that works MME but doesn't start with
>either WASAPI or WDM-KS.
>
>With MME the latency is huge so probably not too useful for your VarAC
>even if you do get it to work.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/issues/184#issuecomment-1002535921
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by N8SDR007** [comment]
Okay Update

Since you got this working, I dove a bit deeper- thinking perhaps a corruption or some previous files were left over

I completely uninstalled and also removed all registry settings for V3 and the Radio Sync

rebooted and then did an install of both (again after removing all directories and Registry settings and folders for both applications)

it now appears to be working with Some digital applications and the and it does now initialize the sound card light to Green as well in Radio Sync

I will also now I now have a VOX button in V3 on RX1 that was missing before. 

thanks-

**Comment by G4ENZ-Martin** [comment]
Rick,

Only MME is starting for me. I have repeated the tests with a virgin configurations of 0.11.0 and RadioSync. Unless you tell me you have WDM-KS and WASAPI working, I think this needs to be an open issue for EE to look at.

73 Martin

**Comment by N8SDR007** [comment]
I got wdm ks to work but very unstable also levels are screwy

⁣Get BlueMail for Android ​

On Dec 29, 2021, 11:00 AM, at 11:00 AM, G4ENZ-Martin ***@***.***> wrote:
>Rick,
>
>Only MME is starting for me. I have repeated the tests with a virgin
>configurations of 0.11.0 and RadioSync. Unless you tell me you have
>WDM-KS and WASAPI working, I think this needs to be an open issue for
>EE to look at.
>
>73 Martin
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/issues/184#issuecomment-1002663565
>You are receiving this because you modified the open/close state.
>
>Message ID:
***@***.***>

**Comment by G4ENZ-Martin** [comment]
Rick,

I am not sure why but, RadioSync with WDM-KS is now working and very stable. I have used JTDX v2.2.157-32A as a test. Two instances one running directly over TCI audio and the other running through VAC and RadioSync with WDM-KS driver.  Comparing received WSPR signals (DT) with each, the RadioSync route is nearly always 0.1s later on decodes

VAC is looking happy...
![VAC](https://user-images.githubusercontent.com/94721418/147703230-79bae8e0-4504-432c-a205-83050397941e.jpg)

73

**Comment by N8SDR007** [comment]
Yes indeed odd,

 

G/L

 

Cheers
