### ISSUE TITLE
ESDR3: VFO A / VFO B frequency after band change

### ISSUE THREAD

**Issue by hb9bun** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#186]
ESDR3 V 0.11.0 alpha Build: 28122021
SunSDR2DX
Win 10

When switching from band to band using the band button, on some bands both VFOs change, on some bands just VFO A switches. In ESDR2 just the TX VFO frequency was changing to the new band. 
In ESDR3 sometimes both frequencies change, sometimes just VFO changes. Or even pushing 40m with Split on from the last 40m activity VFO B goes to 60m (see screenshot attached). 

I am not sure what the logic should be in ESDR3. 

73, Peter 

![2021-12-28 19_07_03-Window](https://user-images.githubusercontent.com/24924704/147594622-097d4d3a-6a2e-4ee6-949d-c3a72ee00277.png)

**Comment by ExpertSDR3** [comment]
Is third-party software connected via TCI to ESDR3?

**Comment by hb9bun** [comment]
I now explicitely disconnected all TCI devices connected to the SunSDR2 DX. 

Changing bands remembers all VFO A and VFO B settings per band now, **except on 2m**. 

server: dds:0,146250050;
server: if:0,0,0;
server: vfo:0,0,146250050;
server: if:0,1,10000000;
server: vfo:0,1,156250050;
server: agc_gain:0,80;
server: tx_enable:0,true;
server: drive:0,0;
server: split_enable:0,false;
server: if:0,1,0;
server: vfo:0,1,146250050;
server: dds:0,50372600;
server: if:0,0,-59600;
server: vfo:0,0,50313000;
server: if:0,1,-58273;
server: vfo:0,1,50314327;
server: agc_gain:0,81;
server: drive:0,73;
server: split_enable:0,true;
server: app_focus:false;
server: app_focus:true;
server: dds:0,146250050;
server: if:0,0,0;
server: vfo:0,0,146250050;
server: if:0,1,10000000;
server: vfo:0,1,156250050;
server: agc_gain:0,80;
server: tx_enable:0,true;
server: drive:0,0;
server: split_enable:0,false;
server: app_focus:false;
server: app_focus:true;
server: if:0,1,0;

Here you see what TCI sends when on 2m I change VFO B to VFO A, then change band to 6m and back to 2m. VFO B goes to 156'250.050 instead of going to the set 146'250.050.

**Comment by hb9bun** [comment]
With PA and SDC on, same behavior. In the SDC TCI protocol I see what happens when I switch from 2m to 6m to 2m -> 
the VFO B frequency on 2m is actively changing back to 156'250.000 after it was getting the right value from memory! 

Understood. 146.xxx was outside of the 2m band. Once I changed VFO A and B both to within 2m band everything worked as normal. But first I had to bring the 2m memory values to proper 2m values. Here how TCI looked. This issue is probably just that ESDR3 does not change to GEN when getting a out of band frequency from the memory.  

> dds:0,146250050;   / switched to 144 MHz
> if:0,0,0;
> vfo:0,0,146250050;
> if:0,1,10000000;
> vfo:0,1,156250050;    // wrong VFO B
> agc_gain:0,80;
> tx_enable:0,true;
> drive:0,0;
> split_enable:0,false;
> if:0,1,0;
> vfo:0,1,146250050;     // changed VFO B to VFO A frequency
> if:0,1,999;
> vfo:0,1,146251050;     // changed VFO B to 146'251.050
> if:0,1,1999;
> vfo:0,1,146252050;     // changed VFO B to 146'252.050


> dds:0,50372600;        // switched band to 6m
> if:0,0,-59600;
> vfo:0,0,50313000;
> if:0,1,-58273;
> vfo:0,1,50314327;
> agc_gain:0,81;
> drive:0,73;
> split_enable:0,true;


> dds:0,146250050;    // switched band to 2m
> if:0,0,0;
> vfo:0,0,146250050;
> vfo:0,1,146191777;                 // VFO B is on a different value than 146'252.050 !!!!!!!!!!!!!!!!!!!!!!!!!!
> tx_enable:0,false;
> if:0,1,10000000;
> vfo:0,1,156250050;                // VFO B is now on the strange 156'250.050 !!!!!!!!!!!!!!!!!  - this is happening immediately when 
> agc_gain:0,80;                       // ... switching!
> tx_enable:0,true;
> drive:0,0;
> split_enable:0,false;
> app_focus:false;

**Comment by hb9bun** [comment]
Bug?
With SDC and PA connected via TCI (no side effect): 
When VFO A and VFO B are both in the same band, band switching works fine. When VFO B is set to another band than VFO A and then bands are switched, it is possible that when changing bands suddenly VFO B is not changing to the new band! 

Worse: TCI sends info that VFO B is on 28'003.000 and ESDR3 shows VFO B on 7'074.000. 

What I did: 
- All bands with VFO A and VFO B properly within band.
- Put on 160m VFO B to a 10m frequency: 28'003.000
- Changed band with band button to 40m, then to 10m (and the VFO B was still shown on 40m (with TCI showing it on 10m). 

Please see attached screenshot. 

  
![2021-12-29 13_48_42-Window](https://user-images.githubusercontent.com/24924704/147664061-c5132c33-5f5f-4fb8-a63d-11616178966f.png)

**Comment by ExpertSDR3** [comment]
fixed, fixes will appear in version 0.12
