### ISSUE TITLE
ESDR3 with JTDX: Band switch issue

### ISSUE THREAD

**Issue by hb9bun** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#187]
ESDR3 V 0.11.0 alpha Build: 28122021
JTDX 2.2.157 64bit
SunSDR2DX
Win 10

Tested with multiple and most recent versions of JTDX. Using ESDR3 when switching bands from JTDX the TCI sequence causes VFO B first to switch a specific "random" frequency outside of the hambands. This is corrected in the same TCI sequence later. As other TCI device react negatively to out of band frequency, e.g. my RF-Kit PA goes immediately to standby on this command. 

Going from 10m to 15m switching triggered by chaning band in JTDX leads to the following server protocol: 
server: dds:0,21137600;
server: vfo:0,0,21074000;
server: if:0,1,-3903273;
**server: vfo:0,1,17234327;**
server: agc_gain:0,94;
server: tx_enable:0,false;
server: drive:0,66;
server: rx_filter_band:0,40,3670;
client: vfo:0,1,21075327;
server: if:0,1,-62273;
server: vfo:0,1,21075327;
server: tx_enable:0,true;

Probably an issue caused by how JTDX sends TCI, but as I have other strange behavior of the VFO frequencies when switching bands, I put it here as an issue too. I will also post the issue in the JTDX TCI forum. 

With ESDR2 JTDX with ESDR2 connected through TCI does not show such an issue. Tested it on another installation. Same effect with a VFO frequency out of band. In this case 13 MHz. 
![2021-12-28 19_23_57-Window](https://user-images.githubusercontent.com/24924704/147595793-a714ff4d-0233-4b0b-9a3d-a0470bfc0939.png)

73, Peter - HB9BUN

**Comment by hb9bun** [comment]
Here another example of a frequency change protocol from 30m to 40 and back to 30m. 

> dds:0,7133600;   // switching from 30m to 40m invoked in JTDX
> vfo:0,0,7074000;
> if:0,1,-3120273; // proper offset of 4'013'327 from DDS
> **vfo:0,1,4013327**; // when switching from 30m to 40m I see quickly this QRG on VFOB to then see 7.075 
> vfo:0,1,4013327;
> agc_gain:0,73;
> tx_enable:0,false;
> drive:0,73;
> tune_drive:0,70;
> rit_offset:0,-2820;
> rx_nb_enable:0,true;
> if:0,1,-58273;
> vfo:0,1,7075327;   // now VFO B has its proper frequency for the band
> tx_enable:0,true;


> dds:0,10195600;     // switching back to 30m in JTDX
> vfo:0,0,10136000;
> if:0,1,3003727;
> **vfo:0,1,13199327;**   // 13'199.327 (the frequency showing up in the VFO display quickly)
> if:0,1,3003727;
> vfo:0,1,13199327;
> agc_gain:0,76;
> tx_enable:0,false;
> drive:0,79;
> tune_drive:0,62;
> rit_offset:0,0;
> rx_nb_enable:0,false;
> if:0,1,-58273;
> vfo:0,1,10137327;  // VFO B has got its proper frequency 
> tx_enable:0,true;

During band change triggered via TCI from JTDX VFO B seems to get a wrong frequency first.  
I also attach a video showing how VFO B changes. The log above is the log of the SDC client running as well for logging purposes. 

73, Peter 

https://user-images.githubusercontent.com/24924704/147609401-e2b425f9-1f37-45f5-96c3-cfa64ba990d4.mp4

**Comment by hb9bun** [comment]
After an intense exchange with JTDX (not able to reproducing the error) and analyzing protocols, the conclusion is that this is either an issue with ESDR3 or with my ESDR3 configuration file. 
JTDX on band changes sends VFO commands for first VFO A, this triggers a band change, with **VFO B of ESDR getting to a "random" frequency** probably from the band stack memory. This is the issue.  
After that JTDX sends a VFO command to change VFO B, after that VFO B is correct again.
JTDX also sets the Drive for the band. These are the only 3 commands sent from the client. 

Something with the band stack memory for VFO B (or for the second VFO is not working correctly here. 

Here my message to JTDX in their forum to summarize as well as the last TCI protocol analysis attached as word file with comments. 

****************************************************** Summary to JTDX ********************
[ESDR3 band change from JTDX.docx](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/files/7790791/ESDR3.band.change.from.JTDX.docx)
[ESDR3 band change from JTDX.docx](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/files/7790792/ESDR3.band.change.from.JTDX.docx)

It is quite  obvious that the issue is not with JTDX. What happens is:

When the command to change VFO A arrives, ESDR is switching VFO  A to the new band and as a consequnce VFO B is refreshed from the band stack with an invalid frequency.

Then VFO is reset a bit later from JTDX (second part of the band change procedure) and VFO B in ESDR gets the correct frequency. This happens with every band change. Probably on my PC a bit slower so that there are quite some commands executed/communicated to the TCI clients in between. Also JTDX sets the power per band.

From my point of view JTDX does everything right, but there must be an issue either in my setup or in ESDR3 when retrieving the bandstack on band change triggered via the VFO call.

Please find a longer TCI log with band changes from 160 to 10m in steps showing this.

I will send this to SunSDR.

73, Peter
Am 29.12.2021 um 21:05 schrieb Arvo ES1JA via groups.io:
  
[ESDR3 band change from JTDX.docx](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/files/7790793/ESDR3.band.change.from.JTDX.docx)

**Comment by hb9bun** [comment]
Now tested with other TCI clients. When changing band with 5MContest or also with N1MM via SDC, they only send a VFO:0,0, ... command (they do not change VFO B). When the band is changed like that, VFO B gets strange settings.
This does not happen when bands are changed from the band buttons within ESDR3. This changes both VFO A and VFO B probably from the bandstack memory.

**Comment by ExpertSDR3** [comment]
fixed
