### ISSUE TITLE
switching audio between RX1 and RX2 partially broken when using E-Coder buttons

### ISSUE THREAD

**Issue by ok1dsz** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#188]
Hi
let say, that I have three E-Coder buttons configured as follows:
button A: "Listen RX1 only" 
button B: "Listen RX2 only"
button C: "Listen RX1 in left, RX2 in right". 

When using ExpertSDR3 0.10 or 0.11 the C button only works for the first time when the button was pressed after the RX2 was activated. If one of the RX is now muted by pressing button A or B, then nothing happens when pressing button C again afterwards. The previously muted RX remains muted and nothing else happens. It seems to work correctly in ExpertSDR2.

Regards
Zdenek OK1DSZ

**Comment by ExpertSDR3** [comment]
fixed, fixes will appear in version 0.12.

**Comment by ok1dsz** [comment]
Hi @ExpertSDR3 
no, it does not seem to be fixed in v0.12. The issue is still there, no change in the behavior is seen here. 
Any idea?
Thanks
Zdenek OK1DSZ
