### ISSUE TITLE
Clicking on spots on panorama does not change QRG (ESDR3 0.11.0 v281221)

### ISSUE THREAD

**Issue by rsaue** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#189]
Using ESDR3 0.11.0 v281221 on Win10 and Ubuntu Linux 21.10 with SunSDR2-DX. 

Spots from SDC and LogHX (in Win10) shows up on panorama but clicking on them does not change QRG and does not populate the QSO field in LogHX. (no data on this in TCI log view either). Same behavior in Win10 and Ubuntu Linux. Worked well on 0.11.0 v17.12.21. 

73 de LB2EG Richard

**Comment by N8SDR007** [comment]
Same results here as well

Windows 11 
SunSDr2DX

**Comment by ExpertSDR3** [comment]
These are not ESDR3 functions, contact the authors of SDC and LogHX

**Comment by ExpertSDR3** [comment]
really a bug

**Comment by ExpertSDR3** [comment]
we will publish ESDR3 with corrections in the coming days
