### ISSUE TITLE
ESDR3 crashes when I click the wave record button

### ISSUE THREAD

**Issue by rvolchkov** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#19]
SunSDR2 DX
0.10.0 
macOS

ESDR3 crashes 2 out of 3 times when I click the wave record button. I have to force quit the application and reboot.
I have the path set to an external hard drive.
[crash_report.txt](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/files/7510442/crash_report.txt)

**Comment by ExpertSDR3** [comment]
Repeated on macbook pro 13 2017 macOS Monterey, the bug was not detected, more information is needed. When the program crashes, a window appears with detailed information about the problem, you need to copy the text from there and attach it as a file for study.
