### ISSUE TITLE
VOX control button missing on RX1

### ISSUE THREAD

**Issue by N8SDR007** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#190]
No Option for VOX on RX1, but the button is there on RX2
![VOX missing from RX1](https://user-images.githubusercontent.com/94698375/147618896-40250786-d331-43b4-93d0-fb5eff13be54.jpg)

**Comment by ExpertSDR3** [comment]
VOX доступен только для AM/SSB/NFM

**Comment by N8SDR007** [comment]
even in VOICE MODES IT WAS MISSING

However, I have resolved this, by doing a complete uninstall -including all registry files and folders pertaining to V3 and then doing a complete re install
