### ISSUE TITLE
ESDR3 V0.11.0 Alpha BULD 28122021 не правильная работа Mic meter!!!! The Mic meter is not working correctly

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#193]
ESDR3 V0.11.0 Alpha BULD 28122021
Win-10 Home 64
MB-1
Adobe Audition 1.5
наблюдается неправильные показания индикатора Mic meter нижних приделах
на вход передатчика ( вход MIC PC ) был подан генератор 1000 Гц с входным уровнем 0 dB , при этом регулятор усиления
по микрофонному входу выставлен в 0 dB по усилению, затем входной уровень ослаблялся с шагом минус 5 dB на вход передатчика 
на вход подаём 0 dB MIC LEVEL показывает 0dB
на вход подаём минус 5 dB MIC LEVEL показывает минус 2,5dB
на вход подаём минус 10 dB MIC LEVEL показывает минус 5dB
на вход подаём минус 15 dB MIC LEVEL показывает минус 7,5dB
на вход подаём минус 20 dB MIC LEVEL показывает минус 10dB
на вход подаём минус 25 dB MIC LEVEL показывает минус 12dB
на вход подаём минус 30dB MIC LEVEL показывает минус 15dB
на вход подаём минус 35dB MIC LEVEL показывает минус 17dB
there is improper indicator Mic meter lower aisles
the input of the transmitter ( input MIC PC ) was filed generator 1000 Hz with an input level of 0 dB , the gain control
for microphone input is set to 0 dB on the gain and input level is attenuated with step minus 5 dB to the input of the transmitter 
the input is 0 dB MIC LEVEL shows 0dB
the input is minus 5 dB MIC LEVEL shows minus 2.5 dB
the input is minus 10 dB MIC LEVEL shows minus 5dB
the input is minus 15 dB MIC LEVEL shows negative 7.5 dB
the input is minus 20 dB MIC LEVEL shows minus 10dB
the input is minus 25 dB MIC LEVEL shows minus 12dB
the input is minus 30dB MIC LEVEL shows minus 15dB
the input is minus 35dB MIC LEVEL shows minus 17dB

**Comment by ExpertSDR3** [comment]
Дублирует #35
