### ISSUE TITLE
Самопрослушка в NFM

### ISSUE THREAD

**Issue by bosso4** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#194]
Коллеги, приветствую!
Раньше, совсем давно, это работало, хотя с искажениями, потом это стало невозможно, как нам говорили, но время идет... 
Сейчас это можно реализовать, хотя-бы на уровне "с искажениями" ? 
Спасибо.

**Comment by ExpertSDR3** [comment]
Пожалуйста, укажите с какого аудио выхода вы слушаете самоконтроль?

**Comment by bosso4** [comment]
Да, извините, слушаю напрямую с аппарата. С выхода "Телефоны", через наушники.

**Comment by ExpertSDR3** [comment]
Самоконтроль в NFM работает только с выхода звуковой карт ПК, так как в трансивер отправляется модулированный сигнал, на аудио выход трансивера подаётся сигнал передаваемый в эфир.
