### ISSUE TITLE
Sample rate change creates issue in remote client

### ISSUE THREAD

**Issue by rvolchkov** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#20]
SunSDR2 PRO
0.10.0 alpha
Windows 10

When working on a remote application, we try to change the sample rate, then after the change, you can hear a different frequency in the receiver, but touching VFO or clicking on the panorama causes the return to hearing the earlier frequency. These changes are only audible in the audio of the receiver. 
Regards, Daniel 3Z9AM.

**Comment by ExpertSDR3** [comment]
fixed, fixes will be in version 0.11
