### ISSUE TITLE
Notch Filter issue

### ISSUE THREAD

**Issue by Kb2uka** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#200]
Sunsdr2dx
V3 0.11.0
Build 30122021
IMac

On 40 meters only, when I turn on notch filter, I have 3 notches that do no appear and cannot be deleted. This only happens on 40 meters. Notch's work fine on all other bands. 

![image](https://user-images.githubusercontent.com/95453216/147778521-c6b60ce8-4249-4a8d-9b48-19535604c4f4.jpeg)

**Comment by Kb2uka** [comment]
This was not an issue in previous build.

**Comment by danweecc** [comment]
I am having this problem also in that I am unable to delete the notches I created. I can still move it around and vary the bandwidth but double right-clicking the notch no longer deletes it.

**Comment by Kb2uka** [comment]
Try clicking the mouse wheel. In my case on 40 there are 3 notches that I didn't create. There's no "yellow" line just 3 Freq's being botched out.

**Comment by ExpertSDR3** [comment]
fixed, fixes will appear in version 0.12
