### ISSUE TITLE
V3 Build 30122021 Notch Filters (some become invisible to delete)

### ISSUE THREAD

**Issue by N8SDR007** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#201]
After setting a notch filter you can remove some of them as like in previous releases, However the 1st one I created I cannot remove.
The yellow line used to click on it and remove it is invisible, I have tried hunting for it randomly but no go
This is on the Windows Version Alpha V3 30122021

see attached video 

https://user-images.githubusercontent.com/94698375/147779185-aadb7a53-2480-4649-ab4b-a5fe7ba6af0b.mp4

**Comment by ExpertSDR3** [comment]
Please attach the settings file.
Settings path: C:\Users\UserName\AppData\Local\Expert Electronics\ExpertSDR3\serial.json
the name of the settings file matches the serial number of the transceiver

**Comment by N8SDR007** [comment]
File attached

**Comment by 1972igor** [comment]
win 64-home
MB-1
I also have such a problem
у меня тоже такая проблема
[EED10421700095.json.zip](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/files/7838343/EED10421700095.json.zip)

**Comment by 1972igor** [comment]
серийный номер совпадает!

**Comment by ExpertSDR3** [comment]
fixed, fixes will appear in version 0.12.
