### ISSUE TITLE
Коэффициент выходной мощности 

### ISSUE THREAD

**Issue by ur0hq** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#202]
Не сохраняются после рестарта программы  прописанные коэффициенты выходной мощности по диапазонам    https://skr.sh/sBj0NDh5Us1

**Comment by danweecc** [comment]
You have to click on the "Write" before it will be saved and become effective. Mine is saved (EESDR3).

**Comment by ExpertSDR3** [comment]
duplicates #78

**Comment by ur0hq** [comment]
А вы предполагаете что я не нажимаю записать ??? ))))))))  нажимаю и во время рабочей сесии все нормально .. НО после рестарта програмы получаю опять цифру 20   .....  20 а не то что записывал !
