### ISSUE TITLE
Waterfall hides signals when 'scalable waterfall' is on and zoom is full out

### ISSUE THREAD

**Issue by DF2LH** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#203]
Hi everyone
While observing VHF beacons, I noticed this behaviour of the waterfall. To show it more reliably, I use a signal from my elecraft XG3 signal generator on 144.219.6 in this video:

https://www.dropbox.com/sh/7xrtlbj7hr3wxf6/AACq1d3aBDFxPRM8OsQCwfmGa?dl=0

SunSDR2DX EED06202100618
Windows 11
PC with Ryzen 7 3700x, 32Gb, Geforce GTX 750 Ti
ExpertSDR3 0.11.0 30122021 
(similar behaviour started with DirectX, Vulkan, OpenGL) 

vy 73 Thomas, DF2LH

**Comment by ExpertSDR3** [comment]
This behavior occurs due to the overlap of several pixels of the waterfall on top of each other, if you stretch the waterfall horizontally, the signal will be visible. This is a feature of the "Scalable waterfall" mode. If you turn off this mode, all signals will be visible.
