### ISSUE TITLE
ENCODER and Clibrenano NOT recognized in ubuntu 20.04

### ISSUE THREAD

**Issue by K6TWO** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#204]
I can option the panel in SDR3 but it is non responsive with ubuntu on 2 Dell computers. ColibriNANO not recognized in ubuntu.

**Comment by ExpertSDR3** [comment]
In linux, by default, USB HID devices are not accessible to programs because there are no access rights. To allow access, run the commands in the terminal:

_sudo chmod 664 /dev/hidraw*
sudo chgrp plugdev /dev/hidraw*_
