### ISSUE TITLE
RigSync V 1.0.0 VAC audio handoff is BAD

### ISSUE THREAD

**Issue by N8SDR007** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#205]
Something isn't right with Audio in the new RigSync application.

 What I found is this, sure use RigSync for CAT interface to TCI- But using my old method of making VAC work in V3 that is setup one VAC cable for the soundcard lineout setting- and use another VAC for MIC input, then select PC for the Mic source and you can control the level. Not only does this seem to be much more stable, in other tests when using VARAC or VaraHF when looking at BPS transfer speed I have tripled my average bps using this VAC workaround method then using the RigSync application, so yes something isn't correct in the handoff of Virtual Audio to TCI via RigSync.  Latency also seems to be slightly less with audio using this method as well over that done via RigSync.  Why does this method work so much better -  https://eesdr.com/en/forum-en/search?query=vac%20workaround&childforums=1  for virtual audio then via RigSync.

**Comment by N8SDR007** [comment]
There is spikes and other audio trash mixed in the VAC via RigSync audio interfacing. No matter which Audio methid you choose, MME, WDM-KS or WSAPI. all result in unstable audio.

**Comment by ExpertSDR3** [comment]
Fixed
