### ISSUE TITLE
Expert 3.0.11.0 Wont fully Start

### ISSUE THREAD

**Issue by INOV8TN** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#206]
Shows 'loading' circle -Stays in Task Manager. Doesn't Operating page. After trying several settings changes to Expert3 Expert2 stopped working with ColibriNANO.

Device name	DESKTOP-DFI56AM
Processor	Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz   2.67 GHz
Installed RAM	12.0 GB
Device ID	4DDE9E71-EEC8-4722-9688-8081D4F6804B
Product ID	00326-10000-00000-AA322
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 10 Home
Version	21H1
![EXPERT3 Troubleshooting 20220102](https://user-images.githubusercontent.com/25114242/147893989-f328e06e-92fd-4ec6-b427-61899b74f299.JPG)

Installed on	‎5/‎28/‎2021
OS build	19043.1415
Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by ExpertSDR3** [comment]
please contact technical support
