### ISSUE TITLE
E-Coder Plus <-> ESDR3

### ISSUE THREAD

**Issue by togivethesun** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#208]
Невозможно манипулировать CW 
с E-Coder_а Plus в ESDR3,
т.к. панель просто виснет ...

Не работают TONE, XIT, RIT с E-Coder_а Plus в ESDR3

Банальное нажатие MOX на панели E-Coder_а Plus
обязательно приведет к ее (панели) зависанию, 
возможно не с первого нажатия ...

Break.In_ом пользоваться не представляется возможным,
т.к. при его активации и первом же нажатии ключа 
также виснет панель ...

По сему,
при выпуске "Исправлений ESDR3 для E-Coder2" в январе 2022 года 
https://eesdr.com/images/software/ESDR3/ExpertSDR3%200.11.0%20alpha_%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D1%8F%20%D0%BE%20%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B8.pdf
не оставьте без внимания и нас,
простых пользователей панели E-Coder Plus,
пожалуйста !

Здесь:
SunSDR2pro,
E-Coder Plus,
ExpertSDR3 0.11.0 alpha build 30122021,
ОС WIN11x64 сборка 22000.348 

P.S. 
В ESDR2 претензий к работе 
панели E-Coder Plus 
нет

**Comment by rvolchkov** [comment]
В меню настроек панели не работают функции Tune IF as RIT, Tune IF as XIT

**Comment by togivethesun** [comment]
Теперь вышеизложенных проблем c панелью E-Coder Plus нет !
Software version: ExpertSDR3 1.0.2 beta 
Radio: SunSDR2PRO
Firmware: 86.8
Роман, обратите внимание пож. на время инициализации SdrApplication для ESDR3 !
ВисИт ровно 200 секунд при каждом запуске, затем стартует как ни в чем не бывало, и далее работает без проблем !
Вис никак не связан с FireWall !
ОS Windows 11 Pro 22H2 build 22621.1194
Есть ли какая либо возможность избавиться от такой задержки ?
DownDatе OS не планируется ... 
P.S. 
Такое же зависание (200 секунд) происходит при смене профиля .
P.P.S.
Как то связано с папкой
C:\Users\UserName\AppData\Local\Expert Electronics\ExpertSDR3
после удаления которой можно стартануть,
но далее вИс будет повторяться нарастающим итогом по времени,
вплоть до полной невозможности запуска ...

**Comment by rvolchkov** [comment]
@togivethesun посмотрите это пост на форуме - https://eesdr.com/en/forum-en/overall-software-operation/10173-freesing-several-minits-at-start

**Comment by togivethesun** [comment]
Роман, 
по всей видимости, 
причина этого неудобства 
(Freezing several minutes at start)
до смешного проста ...

Время запуска пропорционально размеру файла сохраненного профиля.
name_profile.eprof

Первоначально созданный файл профиля 
имеет размер 1,803KB (в моем случае).
При каждом UpDate этого профиля размер файла растет,
растет и время запуска ...
При достижении размера файла, после нескольких обновлений профиля, 
порядка 4,000KB (в моем случае),
старт не возможен !

Лечение -> 
создаем новый профиль
и наслаждаемся скорым стартом  ;)

P.S.
Спасибо за шикарный CW в крайних версиях ESDR3 !
