### ISSUE TITLE
Power correction is not retained - SunSDR2 Pro

### ISSUE THREAD

**Issue by IU4JNR** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#209]
On my SunSDR2 Pro the power correction is not retained and every power cycle, the power turn back to full (20). 
Using Band Manager power level correction is retained.
This happens on SunSDR2 PRO meanwhile on SS2DX works fine.

EESDR A0.11.0 build 2812
Win11, Ryzen5 5800X, 32Gb DDR4, SSD M2

**Comment by IU4JNR** [comment]
I want to correct my observation: the power correction is retained but is not correctly recalled after restart. Clicking to read button recall the correct set of power.

**Comment by ExpertSDR3** [comment]
duplicates #78
