### ISSUE TITLE
Auto position для панорамы не работает

### ISSUE THREAD

**Issue by rvolchkov** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#21]
SunSDR2 PRO
0.10.0
Linux Ubuntu

Auto position для панорамы не работает корректно в Linux. При переключении не выдерживается указанный position offset. Если клинкуть мышкой в сетку dbm - тогда отрабатывает уровень. В видео представлена пробелма https://youtu.be/b75RKA4AT9Q

**Comment by bastonc** [comment]
тут есть нюанс - position offset не работает только на открытом драйвере. 
С пропиетарным драйвером от производителя видеокарты - position offset работает корректно. 
Возможно это нормальное поведение, но на странице ExpertSDR нет упоминания, что для работы необходимо наличие пропиетарного драйвера в системе
