### ISSUE TITLE
ESDR3 0.11.0.Alpha BULD:30122021 the internal speaker in the MB-1 transceiver is not switched off отключение и включение внутреннего динамика в трансивере через кнопку SPK

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#210]
Win 10 - 64 Home
Transceiver MB-1
ESDR3 0.11.0.Alpha BULD:30122021
Не производится отключение и включение внутреннего динамика в трансивере через кнопку SPK
the internal speaker in the MB-1 transceiver is not switched off
![bandicam 2022-01-04 13-42-46-609](https://user-images.githubusercontent.com/93991940/148048147-4a892a49-ef09-4648-96cd-292012d46e90.jpg)

**Comment by SM4IVE** [comment]
I have a MB1  Win10pro ESDR3 0.11.0.Alpha BULD:30122021
I dont have that problem  my Speaker is off

**Comment by 1972igor** [comment]
after repeatedly restarting the program , the problem disappeared !!!
