### ISSUE TITLE
Некоректная работа ретрансляторного режима в ФМ (ошибка сдвига 600 Кгц)

### ISSUE THREAD

**Issue by c0nsul** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#211]
![Clip2Net Menu_220104191055](https://user-images.githubusercontent.com/3913429/148088769-749c95ee-98ce-4137-a024-6d7cb7cee780.jpeg)
![Clip2Net Menu_220104191143](https://user-images.githubusercontent.com/3913429/148088903-3bf42ed5-09ef-4814-bdcc-eb4363bc5398.jpeg)

При нажатии кнопки RPTR не происходит пересчет -600 Кгц от текущей основной частоты. Просто включается на TX на частоте установленной ранее.
скрин 1.

![Clip2Net Menu_220104185704](https://user-images.githubusercontent.com/3913429/148086798-b3f78009-62b6-4ee0-8937-62e6e9202a72.jpeg)

На скрине мы видем опорную частоту (RX) ретранслятора, от которой должен вестись отсчет (145,650 кгц). И случайный на набор цифр на месте частоты передачи (145.013).

Нажимаем кнопку RPTR :
![Clip2Net Menu_220104190016](https://user-images.githubusercontent.com/3913429/148087242-159480ad-a31e-4ab9-9ecc-608af18422fe.jpeg)
Вместо частоты передачи 145,050  (= 165,650 - 600) - видим непонятную частоту 145,017, что является некорректной работой.

**Comment by c0nsul** [comment]
![Clip2Net Menu_220104190433](https://user-images.githubusercontent.com/3913429/148087831-d65d1ffc-2826-4ae6-9c0f-625eeffc004b.jpeg)

**Comment by c0nsul** [comment]
пс. если включить RPTR режим, и начать менять частоту RX, то с изменением частоты происходит правильное изменение частоты TX (установленный шаг соблюдается).
![Uploading Clip2Net Menu_220104190757.jpeg…]()

**Comment by ExpertSDR3** [comment]
исправлено
