### ISSUE TITLE
CW SDC MACROS

### ISSUE THREAD

**Issue by py5hot** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#215]
THEARE ARE A BUG TO SEND SDC MACROS ON CW, WHEN SEND MB1 SEND PTT BUT NOT SEND THE CARACTERS, ON SSB WORK OKEY

**Comment by ExpertSDR3** [comment]
Please describe the setup and actions in more detail so that we can reproduce them ourselves.

**Comment by ExpertSDR3** [comment]
The solution to this problem is related to SDC, you can find the answers at the link:
https://groups.google.com/g/sdc-ut4lw?pli=1

**Comment by py5hot** [comment]
Hello

I use espr3 tci 40001
Also sdc tci 40001
Macros is active.
The problem is, when send SDC macros  CW, espr3 send ptt but not send
letters. Just ptt.

The solution to restart 2 or 3 times espr3 or restar mb1, not solve.

On ssb work Okey, go ptt and send voice, all Okey, but on CW not.

If you like to TeamViewer to see problem and setup, no problem.

Thank you so much for your attention
Best 73
PY5HOT Mike



PY5HOT Miguel ( MIKE )
EXPERT MB1 X 2
ICOM IC 7100
Kenwood TS 590SG
EXPERT SPE  2K FA



Em seg., 10 de jan. de 2022 09:40, EE ***@***.***> escreveu:
