### ISSUE TITLE
In split mode, frequency indicators in spectrum area can overlap

### ISSUE THREAD

**Issue by williamscody** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#220]
Environment:
Intel Core i5-9600K CPU at 3.7GHz
AMD Radeon 580 Graphics Card
32GB RAM
Windows 11 Pro, version 21H2, 64-bit (AND Windows 11 Pro, 64-bit)
SunSDR2DX, S/N EED06202100503, Firmware 72.8
ESDR3 0.11.0, build 30122021

Symptom:

While operating in SPLIT mode (for example, using JTDX for FT8, with JTDX "Split Operation" set to RIG), the frequency indicators of the main receiver and Split receiver can overlap, making both unreadable.

Ideally frequency indicators should be offset to avoid such a collision.

See attached photo.

![2022-01-10 22_05_29-ExpertSDR3 SunSDR2DX EED06202100503](https://user-images.githubusercontent.com/16505794/148885588-8e35d732-ef90-4717-ab74-80adac778a05.png)

**Comment by ExpertSDR3** [comment]
fixed, fixes will appear in version 0.12
