### ISSUE TITLE
glibc version mismatch with Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by w4rjw** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#221]
Thank you for the opportunity to beta test and provide feedback.
Here are my results:

System:
   Ubuntu 20.04.3 LTS (fully upgraded)
   Dell XPS17 9710 with i9 processor and 64GB memory
   SunSDR2pro is connected and operates normally under esdr2 v 1.3.1 update 11

Problem:
   esdr3 v0.11.0 fails to startup due to glibc mismatch

Details:

 robert@rjw:~/Downloads/ExpertSDR3 0.11.0$ ./ExpertSDR3.sh  /home/robert/Downloads/ExpertSDR3 0.11.0/bin/ExpertSDR3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/robert/Downloads/ExpertSDR3 0.11.0/bin/ExpertSDR3)
 /home/robert/Downloads/ExpertSDR3 0.11.0/bin/ExpertSDR3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/robert/Downloads/ExpertSDR3 0.11.0/bin/ExpertSDR3)
 /home/robert/Downloads/ExpertSDR3 0.11.0/bin/ExpertSDR3: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/robert/Downloads/ExpertSDR3 0.11.0/bin/ExpertSDR3)

Additional details:

 robert@rjw:~$ ldd --version
 ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31

 robert@rjw:~$ apt list --installed|grep libc6
 libc6-dbg/focal,now 2.31-0ubuntu9 amd64 [installed,automatic]
 libc6-dev/focal,now 2.31-0ubuntu9 amd64 [installed,automatic]
 libc6/focal,now 2.31-0ubuntu9 amd64 [installed,automatic]
 libc6/focal,now 2.31-0ubuntu9 i386 [installed,automatic]

 robert@rjw:~$ apt list --installed|grep libstdc++
 libstdc++-9-dev/focal-security,now 9.3.0-17ubuntu1~20.04 amd64 [installed,automatic]
 libstdc++6/focal-security,now 10.3.0-1ubuntu1~20.04 amd64 [installed,automatic]

**Comment by ExpertSDR3** [comment]
Please specify the BUILD version of the program

**Comment by w4rjw** [comment]
The program tested is identified as "ExpertSDR3 0.11.0.tar.bz2" with an upload date of Dec 17,2021.  Since the program does not launch in my environment, I am unable to read a build number from a program dialog, but here is what I find in the program binaries:

robert@rjw:~/Downloads/ExpertSDR3 0.11.0$ grep -r -i BuildNumber
Binary file bin/RemoteApplication matches
Binary file bin/ExpertSDR3 matches
Binary file bin/SdrApplication matches

robert@rjw:~/Downloads/ExpertSDR3 0.11.0/bin$ strings ExpertSDR3 |grep BuildNumber
BuildNumber
_ZL11BuildNumberB5cxx11

**Comment by w4rjw** [comment]
I found a later build from
  https://eesdr.com/en/software-en/expertsdr3-en
labeled  "ExpertSDR3 0.11.0 alpha build 30122021"

Running this version in my environment and I see that the glibc mismatch is fixed.
