### ISSUE TITLE
! Режим NFM фильтр переключается только на панораме,   в приёмнике фильтр не переключается!

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#223]
ESDR3 V0.11.0 Alpha
Win-10 Home 64
MB-1
Audobe Audition 1.5
обнаружил ещё один БАГ!!! Режим NFM фильтр переключается только на панораме, а по низкочастотной части  в приёмнике фильтр не переключается!
![bandicam 2022-01-15 21-31-21-820](https://user-images.githubusercontent.com/93991940/149633889-31122700-4921-47eb-8dd2-f71229fbc898.jpg)
![bandicam 2022-01-15 21-31-34-172](https://user-images.githubusercontent.com/93991940/149633891-a1a6c763-494e-4aa4-a67d-bc671db0791b.jpg)
![bandicam 2022-01-15 21-31-39-854](https://user-images.githubusercontent.com/93991940/149633892-3fa78c02-61ff-4aca-b851-4e44fb7c1103.jpg)
![bandicam 2022-01-15 21-31-44-675](https://user-images.githubusercontent.com/93991940/149633894-6abfd89a-c5e2-4ab8-85c8-ab607633a761.jpg)
![bandicam 2022-01-15 21-31-49-262](https://user-images.githubusercontent.com/93991940/149633896-fc4fdefd-5a68-4c03-8f95-2d349cbba8ec.jpg)
![bandicam 2022-01-15 21-31-53-389](https://user-images.githubusercontent.com/93991940/149633897-0f742300-bec8-4958-b0a3-f4f709db26fc.jpg)

I found another BUG!!! The NFM filter mode switches only on the panorama, and the filter does not switch on the low-frequency part in the receiver!

**Comment by 1972igor** [comment]
> ESDR3 V0.11.0 Alpha Win-10 Home 64 MB-1 Audobe Audition 1.5 обнаружил ещё один БАГ!!! Режим NFM фильтр переключается только на панораме, а по низкочастотной части в приёмнике фильтр не переключается! ![bandicam 2022-01-15 21-31-21-820](https://user-images.githubusercontent.com/93991940/149633889-31122700-4921-47eb-8dd2-f71229fbc898.jpg) ![bandicam 2022-01-15 21-31-34-172](https://user-images.githubusercontent.com/93991940/149633891-a1a6c763-494e-4aa4-a67d-bc671db0791b.jpg) ![bandicam 2022-01-15 21-31-39-854](https://user-images.githubusercontent.com/93991940/149633892-3fa78c02-61ff-4aca-b851-4e44fb7c1103.jpg) ![bandicam 2022-01-15 21-31-44-675](https://user-images.githubusercontent.com/93991940/149633894-6abfd89a-c5e2-4ab8-85c8-ab607633a761.jpg) ![bandicam 2022-01-15 21-31-49-262](https://user-images.githubusercontent.com/93991940/149633896-fc4fdefd-5a68-4c03-8f95-2d349cbba8ec.jpg) ![bandicam 2022-01-15 21-31-53-389](https://user-images.githubusercontent.com/93991940/149633897-0f742300-bec8-4958-b0a3-f4f709db26fc.jpg)
> 
> Я нашел еще одну ошибку!!! Режим фильтра NFM переключается только на панораму, а фильтр не переключается в приемнике!

**Comment by ExpertSDR3** [comment]
Это не ошибка, особенность работы NFM в том, что полоса НЧ сигнала не привязана в полосе в радиоэфире, полоса фильтра на панораме пропорциональна девиации частоты.

**Comment by 1972igor** [comment]
не должно так быть фильтр ДОЛЖЕН ПЕРЕКЛЮЧАТСЯ!!!!!

**Comment by 1972igor** [comment]
не должно так быть фильтр ДОЛЖЕН ПЕРЕКЛЮЧАТСЯ!!!!! И это должно быть видно! А фильтр в приёмнике в режиме NFM не переключается!!!
