### ISSUE TITLE
VFOB TCI frequency change has issues

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#225]
EESDR3 0.11.0 alpha 30122021
Windows 10 64-bit

When you send a command to change frequencies on VFOB, the VFOB goes to some unrelated intermediate frequency before eventually settling on the right frequency. This does not happen with VFOA nor does it happen in EESDR2. The problem can be demonstrated with JTDX running in "Rig" mode which produces a split mode operation. Below is a video demonstrating this problem (which does not happen in EESDR2):-

https://youtu.be/l_MTNIOwn6k

I've also had this problem happen when commanding VFOB to change frequencies, only with EESDR3.

**Comment by ExpertSDR3** [comment]
fixed, fixes will appear in version 0.12
