### ISSUE TITLE
Power correction starts with wrong value

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#229]
EESDR3 0.11.0 alpha 30122021
Windows 10 64-bit

When EESDR3 is started up, the 6M power correction level is showed wrongly. The current read state is this:-
![image](https://user-images.githubusercontent.com/13930571/149773721-210b953a-3cd4-4d2b-91f0-1aaf58f0ec39.png)

After EESDR3 is closed and re-started, it shows the 6M power to be 50.0 as follows:-
![image](https://user-images.githubusercontent.com/13930571/149773843-0dcb8ba6-a4af-4f1c-929a-724c51606f52.png)

This is, however, incorrect. After I perform a "Read", the power level reverts to the correct level as it was before the re-start of EESDR3.

**Comment by ExpertSDR3** [comment]
fixed
