### ISSUE TITLE
Full screen issue

### ISSUE THREAD

**Issue by rvolchkov** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#23]
SunSDR2 DX
0.10.0
Windows 10

Once clicked on the "full screen" icon (top right) it was not possible to move or reduce the screen, even clicking on the "Normal" icon. Restarting it didn't help.
Click on the full-screen icon and then click to "normal". I have a 2 monitor system. I started the program in DirectX and OpenGL mode but with no effect

**Comment by ExpertSDR3** [comment]
fixed, fixes will be in version 0.11
