### ISSUE TITLE
VFOB actual frequency differs from displayed

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#232]
EESDR3 0.11.0 alpha 30122021
Windows 10 64-bit

I've found some occasions when the radio is in split mode that the actual transmitted output frequency of VFOB is different from what is actually displayed on EESDR3 after it has been set via TCI. It appears that EESDR3 accepts the TCI frequency setting and displays it correctly but the actual frequency is set to something else. This is when you measure the actual RF output and it can be (and is usually) on a different band altogether.

**Comment by ExpertSDR3** [comment]
VFO B bugs fixed.
