### ISSUE TITLE
Expertsdr3 does not connect to Sunsdr2Pro

### ISSUE THREAD

**Issue by IM77KT** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#237]
Good afternoon,

I have installed the ESDR3 0.11.0 alpha version on the computer and I can't get it to connect to the SunSdr2Pro device.
Is there an installation guide for this new version of the ExpertSDR3 program?
If not, can someone point me to the steps to follow?
Thanks

**Comment by danweecc** [comment]
Might be good to try asking this on the forum. This is only for reporting bugs.

**Comment by IM77KT** [comment]
Thank you and excuse me, I'll ask the question in the forum.

All the best
