### ISSUE TITLE
Zoom position (blue triangle selection) on Mac - no native middle click in OSX

### ISSUE THREAD

**Issue by reflectingme** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#238]
**ExpertSDR3 0.11.0 aplha BUILD: 30122021**

The Zoom position indicator is moved by clicking and dragging on the blue indicator, or with a wheel click / middle button click - however, there is no native functionality for a mouse wheel or middle click on a Mac so the Zoom position can only be moved by selecting the blue triangle indicator and dragging to the new required position.  I have also attempted to use third party 'middle click' apps which also do not function (also not expected to).

Could there be an alternate method of selecting the zoom position on a Mac computer in ExpertSDR3, maybe with the use of a modifier key.

EDIT UPDATE:  For any Mac users wanting to use an app with this functionality, I have used an app called BetterTouchTool.  it used to be free, but is no longer free, though I have the free version from a previous license.  You can set any click combination to emulate a middle/whhel click and I can confirm this does work perfectly as an alternate.

![EESDR3_zone_position_osx](https://user-images.githubusercontent.com/47534300/151768300-323fda53-58e2-4967-851c-675cacdfb6cc.jpg)
.

**Comment by ExpertSDR3** [comment]
In version 0.12, the action performed by the middle mouse button will be duplicated by double-clicking with the left mouse button.

**Comment by reflectingme** [comment]
> In version 0.12, the action performed by the middle mouse button will be duplicated by double-clicking with the left mouse button.

That's great news.  Do you have any dev elopement plan dates as to when we can expect v0.12 to appear?  Curious, thanks.  GW3JVB

**Comment by ExpertSDR3** [comment]
We will try to release version 0.12 in February. Added the function of removing NOTCH filters on the panorama by double-clicking with the left mouse button.

**Comment by reflectingme** [comment]
I can confirm that double-clicking on a specific the NF works perfectly and removes those NOTCH filters that are double-clicked.  

**Zoom Position Indicator:** However, when double-clicking the frequency scale the blue triangle does indeed relocate to the selected frequency but its behaviour is not necessarily what is expected.  The indicator does not simply relocate to the selected position, but the screen waterfall and pan adapter also adjusts - which is somewhat unanticipated and I might say undesirable behaviour.  Would it not be prudent to simply have the zoom position indicator relocate to the selected frequency when double-clicked, and leave the screen as-is? Or if not, then maybe a user option to determine how the Zoom Position Indicator behaves.
