### ISSUE TITLE
VOX - Turning off whilst Vox is triggered, leaves in Transmit

### ISSUE THREAD

**Issue by G4ENZ-Martin** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#239]
Windows 10 Pro
SunSDR2 Pro
ESDR3 0.11.0 build 28122021

In SSB select VOX and start speaking so that the radio goes to transmit. Turn off VOX whilst the transmitter is in TX.  The transceiver will remain in transmit. (It should go to receive.)  Transmission can be stopped by pressing TX.  Now turn VOX back on and speak. The transmitter will **not** respond. Turn VOX off and on again and normal VOX operation is restored.

**Comment by ExpertSDR3** [comment]
fixed, fixes will appear in version 0.12.
