### ISSUE TITLE
Отображение частоты расстройки RIT&XIT

### ISSUE THREAD

**Issue by ub3dqy** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#241]
SUNSDR2DX, S/N EED06121000432
ESDR3 0.11.0 Alpha
Windows10Pro x64
Gigabyte X58A-UD7, Xeon X5675, RAM 24 ГБ, SSD Samsung 250 ГБ, Nvidia NVS 315, трансивер подключен к встроенной сетевой карте.
Не отображается частота расстройки при использовании RIT и XIT. Невозможно понять на сколько отстроился от основной частоты.

**Comment by danweecc** [comment]
I think you can right-click on the RIT and XIT buttons that should show the offset but a more direct display would be nice.

**Comment by ub3dqy** [comment]
> I think you can right-click on the RIT and XIT buttons that should show the offset but a more direct display would be nice.

Да, хотелось бы в режиме реального видеть частоту. Так же заметил, что при включении режима RIT в LogHX отображается частота смещения, но при её изменении в LogHX значение не меняется. При включении режима XIT частота смещения передачи отображается и изменяется в LogHX. Проблема в esdr или loghx не знаю. 

https://user-images.githubusercontent.com/95985610/152571667-64bc6a7e-f401-4b74-acc4-34dd96b89469.mp4
