### ISSUE TITLE
WIN10 64bit - frozen

### ISSUE THREAD

**Issue by dm1cg** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#242]
starting the programm , 
select SUNSDR START
It froze . only the SN in the header of the WIndows

![image_2022-02-01_20-39-50](https://user-images.githubusercontent.com/98891252/152162444-70ec2282-ca9f-4d67-89c1-19c46f16236c.png)

**Comment by IK2XDE** [comment]
Hello, try to start with OpenGL graphics API
I solve my problem......after some minutes Windows11 Freeze....i must to restart. (with directX)
With OpenGL all work fine.

73 de IK2XDE Andrea.
