### ISSUE TITLE
Режим USE IF в настройках E-Coder Plus

### ISSUE THREAD

**Issue by ub3dqy** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#245]
SUNSDR2DX, S/N EED06121000432
ESDR3 0.11.0 Alpha
Windows10Pro x64
Gigabyte X58A-UD7, Xeon X5675, RAM 24 ГБ, SSD Samsung 250 ГБ, Nvidia NVS 315, трансивер подключения к встроенной сетевой карте.
При включении режима USE IF в настройках E-Coder, происходит перемещение водопада  вместе с указателем частоты, чего не должно быть в данном режиме.

https://user-images.githubusercontent.com/95985610/152573144-504f229b-6a1a-4320-9d7a-eb8046cba32c.mp4

**Comment by ExpertSDR3** [comment]
Сперва нужно включить режим масштабируемого водопада, тогда не будет такого эффекта
![image](https://user-images.githubusercontent.com/93903520/152771170-8e9ec470-da70-4122-85fc-8786267bc74c.png)
