### ISSUE TITLE
Very loud short noise when changing band from 2M to 40/80M with NR on

### ISSUE THREAD

**Issue by reflectingme** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#249]
Software: ExpertSDR3 0.11.0 alpha BUILD: 30122021
Computer: iMac OSX Big Sur 11.6
Radio: SunSDR2DX

Unusual issue which may not be so easy to reproduce.

Listening to 2M, then when changing band to 40M/80M there is a **very** loud click/pop noise heard through both the headphones and speakers which nearly blew my eardrums it was so loud.  Seriously, it made me jump.  Not sure this should be happening.

Further testing shows that this only occurs when **NR** is enabled on both 2M and the band being moved to/from.

Only able to make a short video due to the 10MB upload limit.

https://user-images.githubusercontent.com/47534300/152803274-bd9cad84-52cb-4ddc-b699-24c0d74ee8d6.MOV

John
GW3JVB
.

**Comment by danweecc** [comment]
I suspect this is due to the AGC catching up. Can you try turning off AGC and lower the gain level to something lower?

**Comment by reflectingme** [comment]
> I suspect this is due to the AGC catching up. Can you try turning off AGC (on both bands on the modes that's there) and lower the gain level to something lower?

Sure, I am happy to try any testing for you but unless I am missing something here Dan, there's no viewable AGC for 2M that I can see?  I can turn the AGC OFF for HF bands, and also adjust the AGC slider in the top right, but this is not available for 2M.  So, not entirely clear what you want me to try exactly.  Could you elaborate please and I will take a look in an hour or.
Ta
**John - GW3JVB**

**Comment by reflectingme** [comment]
> I suspect this is due to the AGC catching up. Can you try turning off AGC (on both bands on the modes that's there) and lower the gain level to something lower?
UPDATE:
So further testing shows that the very loud click/pop occurs when switching from 2M NFM to any HF SSB mode.

**Comment by danweecc** [comment]
If it only happens going into HF, maybe disabling the AGC on the HF SSB mode and lowering the AGC gain manually might help? I initially didn't notice that you were working with 2m which does not have AGC control.

**Comment by danweecc** [comment]
I just did some tests - 2M NFM or USB switched to HF USB (15m and 20m) with AGC: NORM - no problem, no pop.

**Comment by reflectingme** [comment]
Very interesting Dan! 

Unfortunately, it is still the same here.  When switching from 2M NFM to 80/40 (LSB) the pop is awful.  And on top of this, if the squelch is low on 2M, the sound when switching from HF to 2M NFM is horrendous.  Could be quite damaging to sensitive eardrums.

https://user-images.githubusercontent.com/47534300/153023745-31de2bc8-36bf-4ad7-838c-42dc4b951563.MOV

.

**Comment by ExpertSDR3** [comment]
fixed
