### ISSUE TITLE
Problem with Zoom Position blue triangel

### ISSUE THREAD

**Issue by Sam-in-Texas** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#250]
I am using ExpertSDR3 version 0.11.0 alpha with  SunSDR2dx EED06121000417.  My operating system is Windows 11 on a DELL desktop PC.
I have been using ExpertSDR3 for more than a month with no problem. Than suddenly I began having problem with the Zoom Position blue triangle. I am unable to stop the blue triangle from adjusting the frequency whenever I use the mouse to change frequency on any band. 
Another problem occurred when I attempted to spit the frequency to work a DX station on 20meter that was listening 5-up.  The entire band became unstable and I could not use the radio on the 20meter band. I could not reset the software to factory default. I remove the software hoping that a fresh install would bring the new install back to the a fresh start. When the new installed finished, it was back to the same state it was before the uninstall.
There is not enough information on the use of that blue triangle. It doesn't seem to zoom anything.

**Comment by Sam-in-Texas** [comment]
Today I began experiencing the same problem described above. When I disable TCI all the problem goes away and everything operates beautifully. I am able to do split TX & RX.  It is evident that there is a compatibility issue with TCI.  I use TCI for rig interface between my N3FJP logging software and Expert SDR3.

**Comment by ExpertSDR3** [comment]
If the tuning frequency is set from TCI then the zoom cursor is automatically set to the filter frequency. This was done at the request of contestmen.

**Comment by ExpertSDR3** [comment]
In version 0.13, it will be possible to disable zoom cursor  following to the VFO from TCI.

![image](https://user-images.githubusercontent.com/93903520/169469920-0db8a3bf-3e32-4027-914b-f95e0b9afa27.png)
