### ISSUE TITLE
Mic is not working when using Trust PC USB headset

### ISSUE THREAD

**Issue by YO8TNB** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#252]
SUNSDR2DX, S/N EED06421900072
ESDR3 0.11.0 Alpha
Windows 10 Home x64
HP ProBook 450 G2 i5-5200U 1TB 8GB AMD R5-M255 2GB.
Transceiver is connected directly to this laptop.
The microphone does not work when using a Trust PC USB headset.
When the PC microphone input is selected, no sound comes from the microphone.
This headset works without problem with ESDR2.

**Comment by dd5md** [comment]
I have the same problem on macOS Monterey. When I plug the microphone into the MIC2 jack, it works, but the sound is not clean. The new equalizer is a big step backwards for me compared to the equalizer in ExpertSDR2. Unfortunately EE will stick with this equalizer which is a real shame.

**Comment by reflectingme** [comment]
Hi both - this looks to be a similar issue to the one I am experiencing currently and have reported as issue #254 

Unable to use any PC based microphone currently with ExpertSDR3.
