### ISSUE TITLE
Waterfall not reflecting some signals

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#253]
EESDR3 0.11.0 alpha 30122021
Windows 10 64-bit
SunSDR2DX

I noticed that some signals in the spectrum do not seem to produce a waterfall trace. The below is an example. I can hear it as a continuous tone but it doesn't appear on the waterfall in the 312kHz span. If I change to 156kHz or less, I can see the signal in the waterfall.

![image](https://user-images.githubusercontent.com/13930571/153131241-6a341499-4341-4b22-b315-00e1842be143.png)

**Comment by ExpertSDR3** [comment]
This is a feature of displaying the waterfall in scalable mode, this happens because several pixels of the waterfall fall on one screen pixel and the video card itself will choose which texture pixel to draw.
