### ISSUE TITLE
ExpertSDR3 0.11 leaves zombie background process after exiting

### ISSUE THREAD

**Issue by rkayakr** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#255]
ExpertSDR3 0.11
Windows 10 with all updates
Intel I7 CPU
NVIDIA MX150 video card with latest drivers

Double clicking on the SDR3 icon brings up the launcher window. 
Clicking on Start button starts SDR3 display.
Clicking on Stop button ends SDR3 display.
Clicking on launcher window exit box closes window and user application.
An ExpertSDR3 background process is left over and must be killed by the task manager before SDR3 is restarted.

**Comment by rkayakr** [comment]
Loaded SRD3 on another Win 10, I7 computer and it also left a zombie process after closing on that computer.

**Comment by rkayakr** [comment]
danweecc

Double click on the SDSR3 desktop icon and an initial  window pops up with a choice of APIs and a button labeled "Start". Task Manager shows one app named ExpertSDR3
Note the difference in Windows between an "App" and a "Process"

Click on "Start" in that initial window and the SDR3 display opens. Task manager now shows two ExpertSDR3 apps.

Press "Stop" in the initial window and the SDR3 display window disappears. Initial window still open. Task manager shows one ExpertSDR3 app.

Click on the x closing box in that initial window and it closes. There are now no windows associated with SDR3. Task manager shows zero ExpertSDR3 apps, but shows but one lurking, windowless, undead  ExpertSDR3 **Process**. (zombie)

Double click on SDR3 desktop icon and you get an error popup saying that there are other ExpertSDR3 instances running and no window opens.

In Task Manager select the lurking, windowless  ExpertSDR3 **Process** and "End task". The left over  **process** is killed and disappears from Task Manager.

You can now restart SDR3.

**Comment by danweecc** [comment]
I think you have missed out an important step. Closing the initial window does NOT close the starter app. What it does is send the app into the system tray. You need to close it from the system tray. Look at the bottom right of your task bar and click on the "^" to bring up the system tray. In there you can find the icon for EESDR3. It is easy to think that clicking the "x" on the initial app closes it - it does not. Click on the EESDR3 icon in the tray and it will pop right back up again. If you want to completely close it, just right-click on that icon and select "Quit".

![image](https://user-images.githubusercontent.com/13930571/153690891-72f390e1-e753-4d51-9d46-201571e20a88.png)

**Comment by rkayakr** [comment]
Thanks 
That works.
I have never seen an app does that and I didn't see any doc that mentioned that unexpected behavior. If you want you avoid unnecessary misunderstandings  you might warn people in the initial window that it doesn't exit as normally expected.

**Comment by danweecc** [comment]
No documentation for EESDR3 at the moment because it is in Alpha.
