### ISSUE TITLE
MB1 problem sending CW macros with both SDC and Log4OM. 

### ISSUE THREAD

**Issue by LA9AKA** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#259]
MB1 
ESDR3 v0.11.0 build 30122021 
Firmware 70.8
Win10 

Since the other bug report regarding this issue was closed (#215), I'll open a new one. The solution mentioned in the comments did not work for me (and PY5HOT), the problem is not only with SDC, but Log4OM also. 

SDC v15.24 - Sending CW macros, I can monitor the audio fine in ESDR3, but there is no output, only PTT. 
Log4OM v2.19.010 alpha - Same problem as SDC. I have been troubleshootng with G4POP and his conclusion is also that this is not a Log4OM issue. It's working fine on the SunSDR2DX. 

73
Hans Christian LA9AKA

**Comment by ExpertSDR3** [comment]
fixed
