### ISSUE TITLE
Остановка работы программы Esdr3  При максимальном увеличении масштаба панорамы приёмника

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#26]
При максимальном увеличении масштаба панорамы приёмника наблюдается остановка работы программы Esdr3 , плоть до полного  её закрытия, программа самопроизвольно закрывается либо зависает !!!!

**Comment by rvolchkov** [comment]
Дублирует задачу #5
