### ISSUE TITLE
Разница в яркости надписей и кнопок межу ESDR2 и ESDR3

### ISSUE THREAD

**Issue by R7MU** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#262]
Здравствуйте, скажите пожалуйста, будет ли изменена яркость надписей в ESDR3? На фото видна разница в яркости надписей в программах или как увеличить яркость надписей в третьей версии
![вид s2-s3](https://user-images.githubusercontent.com/41430368/154551187-afb42164-070b-46d5-9395-21e54ee68c4d.jpg)

**Comment by ExpertSDR3** [comment]
Это не баг
