### ISSUE TITLE
No audio from phone plug between 78-312Khz bandwidth - 0.12.0A

### ISSUE THREAD

**Issue by IU4JNR** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#264]
At BandWidth other than 39 Khz there is no audio from the phone plug. From PC soundcard is fine.

This is both on SunSDR2DX and SunSDR2 Pro
EESDR3 0.12.0
Build 1802 (check copyright disclaimer, it is still 2021)
Ryzen7 5800X
32GB DDR4
SSD M2

**Comment by IU4JNR** [comment]
my fault, Firmware update not applied

**Comment by reflectingme** [comment]
> And where did you get this version ? can I have a link ?Dove ha preso questa versione ? posso fare un riferimento ?

Version 12 alpha has been released for testers, Igor.  Public release usually follows a week or so later.

**Comment by 1972igor** [comment]
I was included in the list of testers, but the program was not sent to me! I find errors in the program and openly talk about these errors, which the manufacturer does not like!

**Comment by reflectingme** [comment]
> I was included in the list of testers, but the program was not sent to me! I find errors in the program and openly talk about these errors, which the manufacturer does not like!

Nobody was sent v12 Igor.  If you are a current tester you will have been sent an invite to a platform where membership will be approved and you will then have access to latest version.  If this is something you have not had but were expecting, perhaps you need to speak with EE.

**Comment by IU4JNR** [comment]
This is a pre-release A version. Check with EE to be included in the tester team.

Max alagna
________________________________
