### ISSUE TITLE
Spectrum does not center correctly when changing bands

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#265]
EESDR3 0.12.0 alpha 18022022
Windows 10 64-bit

In some conditions, EESDR3 does not detect that the receive frequency is out of the display and does not auto re-center it. To reproduce this condition:-

1. Start with 156kHz bandwidth in 20m band with center slightly shifted to the right as follows:-
![image](https://user-images.githubusercontent.com/13930571/154710571-b0d62d0e-2ecf-44a9-86a2-31de31006288.png)

2. Then switch to 30m and have the display centered as follows:-
![image](https://user-images.githubusercontent.com/13930571/154710653-4d66cdb8-3ff3-4982-b35a-dd8b7ddec2c1.png)

3. Next, change bandwidth to 39kHz:-
![image](https://user-images.githubusercontent.com/13930571/154710734-eb777622-c680-4b06-ace7-358417e2a7fa.png)

4. Now switch back to the 20m band and the center will be out of display:-
![image](https://user-images.githubusercontent.com/13930571/154710827-f36962ba-e358-43ce-a4dc-27b9dfcb2911.png)

At this point, the only way to reach the center is to increase the bandwidth until the receive frequency is visible again. Until that is done, no signal is received.

**Comment by ExpertSDR3** [comment]
fixed
