### ISSUE TITLE
[ExpertSDR3 0.12.0 /Linux] При импорте настроек модуля proc - не видит файла настроек

### ISSUE THREAD

**Issue by bastonc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#267]
ExpertSDR3 0.12.0 ОС Linux
Действия для воспроизведения бага
1. В модуле Proc - экспортировать настройки в файл на диске.
2. В модуле Proc нажать на импорт настроек.

**Ожидаемый результат:**
Выбор файла с настройками (экспортированного в п.1), импорт настроек
**Фактический результат:**
Не возможно выбрать файл настроек, т.к. диалоговое окно не видит данного файла.

Ниже скрин в котором в верхнем окне открыт обычный проводник, в котором файл виден (он есть)
В нижнем окне диалоговое окно импорта, в котором файла не видно (папка с файлом одна и та же)
![IMG_20220219_112017_784](https://user-images.githubusercontent.com/37752012/154794863-4ec7370d-d799-4b13-a7ef-5690fefe4479.jpg)

**Comment by ExpertSDR3** [comment]
В Linux не добавляется автоматически расширение файла .txp и файл сохраняется без расширения, поэтому при импорте настроек файл не виден в диалоговом окне. 
В программе добавлена проверка отсутствия расширения, и если его нет оно автоматически будет добавлено.

**Comment by bastonc** [comment]
Отлично, спасибо.
Как понимаю, если сейчас добавить расширение .txp - файл станет видным для импорта.
