### ISSUE TITLE
Sidetone on CW only available through "Monitor"

### ISSUE THREAD

**Issue by G4ENZ-Martin** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#268]
SunSDR2 Pro - FW 76.8
ESDR3 0.12.0 Build 18022022
Windows 10

With 0.11.0 sidetone was always available for CW. Either Macro over TCI or for manual CW from key. 
In 0.12.0 there is no sidetone unless you enable monitor.

**Comment by ExpertSDR3** [comment]
fixed, the fixes will be in the public version with the new firmware
