### ISSUE TITLE
Changing Spectrum speed causes a kind of screenshot.

### ISSUE THREAD

**Issue by IU4JNR** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#269]
Changing speed of spectrum in the setting/display tab, if you move the spectrum slider full to the right it  takes a "snapshot"  of the current peaks. It continues working but some peaks are still there and moves togeter with the VFO. To restore, restart or change in the BW is needed.
EESDR3 0.12.0A Build 1802
Win11 build22000
Ryzen7 5800x
32GB DDR4
SSD M2
https://user-images.githubusercontent.com/94228375/154799796-e2ebc0f4-1501-435d-8060-080477124c7f.mp4

.

**Comment by jmkr25** [comment]
F1DJY
Sunsdr2Pro
W11 21H2, EESDR3 0.12.0A Build 1802

I confirm that I made the same observation.

**Comment by ExpertSDR3** [comment]
fixed
