### ISSUE TITLE
S-meter and AGC

### ISSUE THREAD

**Issue by jmkr25** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#273]
F1DJY
Sunsdr2pro, W11, ESDR3 0.12.0
Twice in FT8 (JTDX and MSHV) the S-meter hangs at -10db and AGC in auto around 0 db. I couldn't notice the circumstance, but stopping the app doesn't solve anything, you have to stop then restart Sunsdr2Pro and everything is back to normal

**Comment by ExpertSDR3** [comment]
the same #274
