### ISSUE TITLE
More frequent disconnection with radio

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#275]
EESDR3 0.12.0 alpha 18022022
EESDR3 0.12.1 alpha 05032022
Windows 10 64-bit
SunSDR2DX firmware 76.8
SunSDR2DX firmware 78.8

I connect to the radio remotely over VPN and a 1Gbps fibre-optic link to my remote station. Ping time averages 5-6ms. Previously with EESDR3 0.11.0 and the 72.8 firmware, I rarely got disconnected (EESDR3 will power off by itself). Now, however, I am getting disconnected much more often (many times a day compared to days without disconnection before). It appears that EESDR3 0.12.0 is much more sensitive to latency and will disconnect more easily. Not sure if this is a bug but it is very inconvenient now as I can get cut off in the middle of a QSO.

I need to click on the "Power" button to reconnect, which always reconnects without issue.

**Comment by danweecc** [comment]
I've managed to capture the disconnect event in a Wireshark file:-
[Disconnect.zip](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/files/8197254/Disconnect.zip)

**Comment by danweecc** [comment]
This happens when latency is slightly higher (5ms) such as when EESDR3 is talking to the TCI client over a less than ideal Wi-Fi connection, or over the Internet.

**Comment by danweecc** [comment]
Further testing shows that the threshold latency is around 5ms. Anything at or above that will result in a disconnection after a 10-second timeout. Please increase this threshold considerably. Thanks.

**Comment by ramtej** [comment]
Same issue here!

**Comment by danweecc** [comment]
This problem has been fixed in EESDR3 0.13.0 build 01092022. Thanks!!
