### ISSUE TITLE
ANF, The sound is muffled

### ISSUE THREAD

**Issue by jmkr25** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#276]
F1DJY
Sunsdr2pro, 0.12.0, W11 21H2

ANF, introduces a decrease and distortion in the audio and does not seem to work as before

**Comment by Kb2uka** [comment]
I have noticed that as well, however, I feel like it works better than before. It not only notches out adjacent carriers but seems to quiet the signal as well without artifacts. 

Just my thoughts

Doug
Kb2uka

**Comment by ExpertSDR3** [comment]
work has been carried out of ANF, now the signal is less distorted when the tonal interference is suppressed

**Comment by jmkr25** [comment]
I had thought for a moment that it was due to my hearing aids. but in practice the audio volume decreases by -15db, while with NR it only decreases by -6db. It's not pleasant at all!

**Comment by f6ctt** [comment]
i'am not sure that ANF works better now, i confirm that  the signal drops enormously as you can see in the attached file

Uploading vy2ww.mp4…

NB : short video due to the limitation 10MB and no carrier to eliminate !

Joseph F6CTT

**Comment by ExpertSDR3** [comment]
Changes in the work of ANF and NR will be in the public version of ESDR3 0.12.

**Comment by jmkr25** [comment]
ANF ​​returned as before. Thank you
