### ISSUE TITLE
Unstable operation - example captured on video

### ISSUE THREAD

**Issue by G4ENZ-Martin** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#280]
SunSDR2 Pro FW 76.8
ESDR3 0.12.0 Build 18022022
Windows 11 Build 22000.527
AMD Ryzen 5 Pro 4650G 32GB RAM

In normal operation and whilst using Vox, after a random period of operation, both TX and RX will fail with very distorted audio heard both ways.  The attached video captures this behaviour.  Notice that the transmitted signal switches from being USB to LSB and the S-Meter jumps from -100dBm to -5dBm on RX noise.  The fault is only cleared by power cycling the SunSDR2.

The test source was a mobile phone using a Metronome to play a 100ms 900Hz tone every 2 seconds. This was then picked up by the station microphone. RF Output power was 2mW and the transmitted signal was monitored on an Airspy HF+

I have seen this failure happen as quickly as 1 minute and again I have operated for 45 minutes without failure.

https://user-images.githubusercontent.com/94721418/155117422-2d769d21-9a83-4bc6-ac23-e5c7f0dd72b3.mp4

.

**Comment by danweecc** [comment]
I suspect this is the same problem as what I also reported - with the gain suddenly going very high. If you notice, when the problem manifests, the receive gain goes so high and the noise floor goes from -100dB or less to -6dB. This high gain happens on both the receive path as well as the transmit path, leading to distortion in the transmitted signal and very loud received noise (if AGC is not active. If AGC is active, you are protected from this.)

**Comment by ExpertSDR3** [comment]
The problem of high receiver signal strength has been fixed, a public version 0.12 with firmware 77.8 is being prepared.

**Comment by ExpertSDR3** [comment]
fixed with firmware 78.8
