### ISSUE TITLE
Intermittent Buzzing Sound on CW signals

### ISSUE THREAD

**Issue by G3XLG** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#281]
Twice now I have left the SunSDR2DX running unattended on CW mode on 40M. On returning to the shack, I found all CW signals were a "buzz" rather than a normal signal. I switched OFF/ON the EESDR3 which cured the problem.
73 Ray G3XLG
SunSDR2-DX, Serial # EED06421900013, revision 5
Expert SDR3 Version 0.12.0 alpha Build 18022022
OS Windows 10 64Bit
PC Asus Mini  i7-8700T CPU at 2.46GHz, 16Gb RAM,

**Comment by G4ENZ-Martin** [comment]
On my SunSDR2 Pro, I normally listen to RX audio through the Phones socket on the radio itself. When the Buzzing occurs, it is only coming from this socket. The received audio through Line out or Sound Card is clean.  Muting the RX audio whilst the Buzzing is present silences the signal you are tuned to but a low frequency (~30Hz) rough Buzz continues to come through the Phones socket.  It seems as if this continuous rough Buzz is modulating the received audio heard through the Phones socket.

Also for me, restarting ESDR3 is the fastest cure.

**Comment by G4ENZ-Martin** [comment]
Issue is also in build 25022022
