### ISSUE TITLE
ColibriDDC S-meter

### ISSUE THREAD

**Issue by F1DJY** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#282]
F1DJY
ColibriNano
W11, 0.12.0.
Without antenna, Preamp 0Db, the S-meter displays S4. 
It would be nice to calibrate it. Thank you
<img width="379" alt="Capture d’écran 2022-02-22 132518" src="https://user-images.githubusercontent.com/16072964/155132053-fe79125d-ed04-4e36-b109-52e15a0f08ed.png">

**Comment by jmkr25** [comment]
With antenna
<img width="382" alt="Capture d’écran 2022-02-22 134945" src="https://user-images.githubusercontent.com/16072964/155135952-19470733-1767-4dd4-91b1-32fb1fc3d9a1.png">

**Comment by KP4AKB** [comment]
Noise floor is too high S-meter reads too high Caused by firmware

![S Meter too high](https://user-images.githubusercontent.com/96546367/156787364-420c2dbf-9ab7-49c6-b0f2-24066a95f297.jpg)

**Comment by ExpertSDR3** [comment]
Fixed

**Comment by rvolchkov** [comment]
Люди жалуются на показания S-метра в ESDR3 1.0.2 для DDC

**Comment by KP4AKB** [comment]
Спасибо за исправление

Ed Rios 

    On Thursday, January 12, 2023 at 05:22:35 AM EST, Roman Volchkov ***@***.***> wrote:  
 
 


Люди жалуются на показания S-метра в ESDR3 1.0.2 для DDC

**Comment by I1MMS** [comment]
I am using ColibriDDC with ESDR3 and the S meter with no antenna is stable at above S9.......

**Comment by KP4AKB** [comment]
I wonder if we could have a FW fix for the S-Meter issue. I am about to turn 80. Time is running short, Please
Ed Rios
KP4AKB/W8
Colibri DDC
