### ISSUE TITLE
eesdr switches mode 

### ISSUE THREAD

**Issue by VA3WU** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#284]
Running Windows 10 pro
 Expert version SDR3 0.12.0
Sunsdr 2 Pro EED05341700328

Frequency approximately 1 in 60 key ups.

radio will switch modes from usb to lsb upon keying the microphone. When I unkey the microphone my noise level goes from -135 dbm on 144 mhz to -20 dbm this is how I know this has happened.  the people listening know it has happened because the radio switched to lsb on transmit

It happens on key up only and at the start never happens during a transmission.

there is no indication on the radio during transmit. when switched to receive the -20dbm signal the mode selector still indicates usb.

to correct this issue press the power button on the transciever and push the power button on the software. a restart of the software is not required.

the s meter will read correct for me -135 dbm on 144 mhz. and I will be transmitting on the correct mode. until 50 or 60 transmits later it does it again.

I can leave the radio on all day receiving and it will not happened only after key up cycles does this happen

**Comment by ExpertSDR3** [comment]
fixed
