### ISSUE TITLE
MIC 2 audio at -24 db with no mic plugged in

### ISSUE THREAD

**Issue by VA3WU** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#285]
Mic audio present as noise on MIC 2
this is present on
Sunsdr 2 Pro EED05341700328

Sunsdr 2 DX EED06121000396

both started after new firmware. Used programs un install to remove all V2 and V3 software up to eesdr3 0.12.0

On both radios can unplug the Mic and still noise on the line all vac and headphone lines are shut off

**Comment by ea5ccy** [comment]
I have the same problem.

![image](https://user-images.githubusercontent.com/100173220/155584387-1a189ba9-1b96-4b56-9414-7b123ebf56a1.png)
