### ISSUE TITLE
wrong frequency set with JTDX 2.2.158win64

### ISSUE THREAD

**Issue by IZ0JNY** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#287]
SunSDR2 DX - EED06121000334
0.12 alpha - latest build 18022022
OS: Windows 11
i7 - 16gb RAM - SSD256mb
**Description:** 
I open ESDR3 and I'm at 7.162 LSB. I open JTDX 2.2.158win64. I select from ESDR frequency 7.074, and I god the error message "wrong TCI set RX frequency". I see from ESDR3 that I'm still at 7.164 MHz. Split is set, mode is changed from LSB to DIGU but frequency for TX and RX are not displayed correctly. 
https://1drv.ms/u/s!AqpeyOmYGiBQca30sxv5oh5_bIc?e=WvP3T6

But if I go on JTDX, I see that is correctly decoding signals (I also see signals on JTDX waterfall) and from audio output I hear the classic FT8 sound. https://1drv.ms/u/s!AqpeyOmYGiBQcltESzwEaCRz97E?e=9Wfci1

So according ESDR i'm at 7.164 but in reality I'm at 7.074. I think is a problem of TCI communication. 

Never happened with ESDR3 0.11.

**Comment by danweecc** [comment]
That might be a timing issue that should be fixed in 2.2.159. I think what was happening was that the TCI wasn't responding quickly enough. I'm currently testing 159-rc3 and not seeing these issues.
