### ISSUE TITLE
Проблема с внешним PA в режиме CW BreakIn --- Problem with ext. PA in CW BreakIn mode

### ISSUE THREAD

**Issue by alexloza1965** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#288]
Проблема с внешним PA в режиме CW BreakIn --- Problem with ext. PA in CW BreakIn mode

SUNSDR2Pro
ExpertSDR3_x64_0.11.0
Windows10Pro x64

При тестировании ExpertSDR3 в полудуплекном режиме ( CW - BreakIn )
обнаружил, что внешний PA не успевает переключиться в режим TX и в результате в PA срабатывает защита по КСВ либо по току.

Предполагаю что в ExpertSDR3 не корректо работает Ptt-CW delay, т.е. ПО абосолютно не обеспечивает задержку. Даже при установке её на максимум 50 мс. Прилагаю скриншот настроек BreakIn на ExpertSDR3:

![img-2022-02-19-18-32-59](https://user-images.githubusercontent.com/72507331/155712134-8e88955e-fca1-42ca-a9a2-a99195a2e82f.png)

Для информации, прилагаю скриншот настроек BreakIn на ExpertSDR2. Тут я работаю нормально и мой PA без проблем успевает перекинутся в режим TX. Зажержка установлена на макс. 30 мс.

![img-2022-02-19-13-45-07](https://user-images.githubusercontent.com/72507331/155712058-a8c86963-4ca1-4c04-bf19-025b0d2f790a.png)

in English:

When testing ExpertSDR3 in half-duplex mode (CW - BreakIn) I found that the external PA does not have time to switch to TX mode and as a result, the protection by SWR or current is activated in PA.

I assume that Ptt-CW delay is not working correctly in the ExpertSDR3, that is, the software does not absolutely provide a delay. Even if you set it to a maximum value of 50 ms. Attached is a screenshot of the BreakIn settings on ExpertSDR3:

For information, I attach a screenshot of the BreakIn settings on the ExpertSDR2. Here I work normally and my PA without problems manages to switch to TX mode. The lamp is installed at max. 30 ms.

**Comment by F5CWU** [comment]
same problem with a sdr DX using the last version of 0.12 and fast firmware. Changing Break-in delay does not have any influence on ptt timing !
