### ISSUE TITLE
Popping sound when changing bandwidths

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#293]
EESDR3 0.12.0 alpha 25022022
Windows 10 64-bit
SunSDR2DX

I noticed a popping sound when switching from 312kHz bandwidth to 39kHz bandwidth. The popping is also present from 156kHz to 39kHz but softer. There is no popping from 78kHz to 39kHz.

To reproduce:-

1. Set mode to USB/LSB/DIGIU/DIGIL
2. Turn AGC OFF
3. Set bandwidth to 312kHz and then change it to 39kHz

https://youtu.be/RnQ-RhABn0s

**Comment by ra4lp** [comment]
EESDR3 0.12.0 альфа 25022022
Windows 10 64-разрядная
SunSDRPRO

У меня хлопающего звука не наблюдается, а вот сама громкость при выборе 39кгц значительно меньше ,78 ,156 , 312 одинаковая.

**Comment by danweecc** [comment]
Problem still present in EESDR3 0.13.0 build 01092022.
