### ISSUE TITLE
60 meter no transmit

### ISSUE THREAD

**Issue by py5hot** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#294]
user mb1 last update espr3 25/02/2022, just receiver on 60 meters , no TX

**Comment by F5CWU** [comment]
same here on sdr dx. On band manager, all bands except thos in “regular ham bands” don’t have TX antennas. There’s just 1 column (rx antenna). Here 60m is managed as GEN and I meet the same problem as above.

**Comment by ExpertSDR3** [comment]
in one of the next versions, the 60M and 11M ranges will appear, they depend on the country, for this reason these ranges are disabled now
