### ISSUE TITLE
Using transverter in ADC IN/DAC OUT still keeps internal PA output active on A2 antenna port

### ISSUE THREAD

**Issue by twi42** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#296]
Hi,

I'm using SunSDR2 DX with a 70cm transverter connected to ADC IN/DAC OUT. I've configured it accordingly in ExpertSDR3 0.11.0 Band and Transverter managers (Band 1, LO frequency 404MHz). 

I am able to receive and transmit with ExpertSDR 0.11.0 and calibrate is with XVTR manager, but the problem is that the SunSDR2 DX still has the A2 antenna output and internal PA active (in addition to DAC OUT) when transmitting. With 100% drive setting, there's full 100W power on A2 (measured with wattmeter & dummy load), even though A2 is not enabled on any band or other setting in ExperSDR 0.11.0.

This is potentially dangerous behavior, as one may have an external PA, tuner and BPF/LPFs on A2 (I have them on A3).

73 de OH2TWI

**Comment by twi42** [comment]
I can confirm that this behavior is still present in 0.12.0 Alpha release.

**Comment by rvolchkov** [comment]
После общего обсуждения было принято переоткрыть этот баг репорт.
Видео ошибки https://1drv.ms/v/s!AscDQ5kIB0dbykAB9iUH9XDkU-Gz?e=g3Ea1R

**Comment by twi42** [comment]
Just to add, I have EE AAT-100 connected to SunSDR2DX port A2 and RS485, but it is not used or enabled. It is detected by EESDR3 though. (I'm using A3 towards RF2K-S, controlled with TCI).

**Comment by KC4CBQ** [comment]
I can confirm that this behavior is still present in 1.0.2 beta. PA still active on A2.

**Comment by twi42** [comment]
Tried with EESDR3 1.0.3, but the 70cm transverter options in XVTR manager are no longer accepted, even though RX/TX IF are well at 28MHz. Furthermore, BM peculiarly only allows ADC/DAC when these options are set.

<img width="851" alt="image" src="https://user-images.githubusercontent.com/24845020/218113808-194ec9f5-8459-4c5d-b6c4-7940d152df82.png">

**Comment by KC4CBQ** [comment]
You cannot put 432/438 you only have 1meg to work with it must be 431/432
on 10 meters you get 28.000 to 28.999 it took me some time to find this out
also.

Tom

**Comment by twi42** [comment]
Ok this makes sense, getting 1.7MHz max bandwidth, even with ADC/DAC ports. Can't work with common 432/434 repeaters then with this kind of transverter and SunSDR2DX?

<img width="850" alt="image" src="https://user-images.githubusercontent.com/24845020/218229286-f00992b4-446f-4e9a-819b-9f02c21366df.png">
