### ISSUE TITLE
Profile, option Import

### ISSUE THREAD

**Issue by ea1aha** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#297]
Opening the configuration tab, the Profile tab appears on the right, there you have the option to choose microphone 1, Microphone 2 or PC Microphone and at the bottom you have two tabs (Import and export). Are those options operative? I have tried to import several *.txp files and I don't see that those files are imported.

ExpertSDR3 Alpha 0.12.0 Build 25022022
FW 77.8

EA1AHA
Juan Carlos

**Comment by reflectingme** [comment]
Goo morning Juan - I have tried this and I am able to export and import top files as expected, so I assume the feature is operative.

Same version, firmware and build as you, though I am using an iMac on macOS Monterey 12.2

**Comment by ea1aha** [comment]
Can you send me one of your *.txp configuration files to test with the one that works for you?
I use Windows 10

Thanks

EA1AHA
Juan Carlos

**Comment by reflectingme** [comment]
> 

Just done on Telegram, Juan

**Comment by ea1aha** [comment]
Thanks, with your file it works, with the ones I had recorded before, no, thanks

**Comment by N8SDR007** [comment]
You are trying to import a recent (as in last couple ALPHA releases) of your profile correct- Not something from an Earlier version- as changes were made and the formats are NOT the SAME
