### ISSUE TITLE
Band 60 M

### ISSUE THREAD

**Issue by ea1aha** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#298]
I have installed the latest version of FW and the latest version 0.12.0, With previous versions, although the band of 60 was not displayed, entering through GEN could work in that band, but with version 0.12.0 I did not TX in that band, is it necessary to configure something so that TX in that band?  

EA1AHA
Juan Carlos

**Comment by ea5ccy** [comment]
It also does not allow transmission in the 11 meter band.

EA5CCY
Pedro

**Comment by reflectingme** [comment]
> It also does not allow transmission in the 11 meter band.
> 
> EA5CCY Pedro

Illegal in some countries to use Amateur Radio equipment to Tx on 11m would be the reason why this is the case, Pedro.

**Comment by ExpertSDR3** [comment]
the same #294
