### ISSUE TITLE
Saved Frequency indicator not present when stored

### ISSUE THREAD

**Issue by reflectingme** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#299]
**macOS Monterey 12.2**
<img width="254" alt="Screenshot 2022-02-27 at 09 37 01" src="https://user-images.githubusercontent.com/47534300/155877053-df88c634-538d-432a-bcb0-0a89f8984e9d.png">

I notice that the little green indicator that was used in ExpertSDR2 is no longer present for any saved frequencies when using ExpertSDR3 V0.12.0

The screenshot example shows a frequency saved for my local club net on 80M 3.704 - NARS80M - but nothing is indicated on the display at that frequency as previously in V2.

When clicking on the saved frequency in **Saved Stations Memory** this changes the band/frequency to that selected and works as expected.  It is only the indicator that I notice is no longer present.

<img width="1432" alt="Screenshot 2022-02-27 at 09 31 48" src="https://user-images.githubusercontent.com/47534300/155876887-612ad85e-9176-4b11-9a2e-f749210001d7.png">

**Comment by ExpertSDR3** [comment]
This feature has not been implemented yet

**Comment by reflectingme** [comment]
> This feature has not been implemented yet

OK, many thanks for the heads up.

Suggestion: I think it is always safest to post items such as this in the bug tracker area here on GitHub as users are not always aware if a certain feature has been implemented thus far or if there is an issue with its implementation.  Once you guys have clarified this type of report as belonging to the 'not yet implemented' group, it might be a good idea to move it to the GitHug suggestions section?

**Comment by ExpertSDR3** [comment]
This feature will be added in a future version.
