### ISSUE TITLE
переключении источника звука, на входе трансивера, при использовании VAC и других звуковых карт нет звука при передаче

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#30]
WIN 10
ESDR3 0.10.0 alpha
Transceiver MB-1
При переключении источника звука,( режим LSB ,USB ) на входе трансивера, при использовании VAC и других звуковых карт ( тип драйвера MME, WDM-KS, WASAPI) отсутствует сигнал на выходе передатчика ( вероятно отсутствует сигнал на входе ) хотя программа отображает, что переключение произведено!!!

**Comment by 1972igor** [comment]
![bandicam 2021-11-10 22-29-23-869](https://user-images.githubusercontent.com/93991940/141180536-4e92451e-4bec-4671-93aa-4fc51eb55c51.jpg)

**Comment by 1972igor** [comment]
> WIN 10 ESDR3 0.10.0 alpha Transceiver MB-1 При переключении источника звука,( режим LSB ,USB ) на входе трансивера, при использовании VAC и других звуковых карт ( тип драйвера MME, WDM-KS, WASAPI) отсутствует сигнал на выходе передатчика ( вероятно отсутствует сигнал на входе ) хотя программа отображает, что переключение произведено!!!

![bandicam 2021-11-10 22-29-23-869](https://user-images.githubusercontent.com/93991940/141196505-ebcfe7f6-3f52-4b43-906e-43e185489cdf.jpg)

**Comment by 1972igor** [comment]
> WIN 10 ESDR3 0.10.0 alpha Transceiver MB-1 При переключении источника звука(  где производить выбор источника входа показан на рисунке, затем нужно активировать вход нажатием кн наушников ( рядом с TCI  ) , ( режим LSB ,USB ) на входе трансивера, при использовании VAC и других звуковых карт ( тип драйвера MME, WDM-KS, WASAPI) отсутствует сигнал на выходе передатчика ( отсутствует сигнал на входе ) хотя программа отображает, что переключение произведено!!!

![bandicam 2021-11-10 22-29-23-869](https://user-images.githubusercontent.com/93991940/141196778-33a6f75f-b580-45db-ae4c-55be3be587ec.jpg)

**Comment by 1972igor** [comment]
> > WIN 10 Home
ESDR3 0.10.0 alpha сборка 03.11. 2021
 Transceiver MB-1 
![bandicam 2021-11-11 00-55-34-737](https://user-images.githubusercontent.com/93991940/141199936-114c3680-7b18-427f-bf2f-fcd60416caa1.jpg)
При переключении источника звука( где производить выбор источника входа показан на рисунке, затем нужно активировать вход нажатием кн наушников ( рядом с TCI ) , режим ( LSB ,USB ) на входе трансивера, при использовании VAC и других звуковых карт ( тип драйвера MME, WDM-KS, WASAPI) отсутствует отсутствует сигнал на выходе передатчика ( отсутствует сигнал на входе ) хотя программа отображает,  что переключение произведено!!!
> 
> ![bandicam 2021-11-10 22-29-23-869](https://user-images.githubusercontent.com/93991940/141196778-33a6f75f-b580-45db-ae4c-55be3be587ec.jpg)

**Comment by ExpertSDR3** [comment]
Этот баг уже исправлен, в релизе версии ExpertSDR3 0.10 будет исправлено

**Comment by 1972igor** [comment]
Спасибо ! СЛАВА ПРОГРАМИСТУ!!!
