### ISSUE TITLE
Panadapter slow down at max zoom after a transmission

### ISSUE THREAD

**Issue by IU4JNR** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#301]
With 0.12.0 fw 77.8 and 78.8 if i zoom to max, the visualization slow down dramatically.
This happens after a transmission, even a dit, on both sunsdr2dx and sunsdr2 pro.
It resume its correct behaviour only after the rig has been restarted.

Win11, 32gb ddr4, ssd, gtx1060oc.

**Comment by N8SDR007** [comment]
Originally, I posted I did not have this happen; I stand corrected

It does happen and is easy to reproduce
see attached video-Link https://drive.google.com/drive/folders/1G4FAp7Oio60lccEN2UQqG8OOVBohv9F1?usp=sharing

**Comment by williamscody** [comment]
This sounds exactly like my issue #94. Is your system using an AMD video card?

**Comment by N8SDR007** [comment]
No and processor but Nvidia GTX 1050Ti

Also I got caught up in the wpx contest so I will do video when I get home tomorrow sorry
Rick

⁣Get BlueMail for Android ​

On Mar 27, 2022, 10:31 PM, at 10:31 PM, williamscody ***@***.***> wrote:
>This sounds exactly like my issue #94. Is your system using an AMD
>video card?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/issues/301#issuecomment-1080117181
>You are receiving this because you commented.
>
>Message ID:
***@***.***>

**Comment by williamscody** [comment]
No worries Rick! I was contesting too!  I missed that the OP also was using NVIDIA. Hopefully this gets addressed soon.
