### ISSUE TITLE
GUI Frozen with interference

### ISSUE THREAD

**Issue by W3FRG** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#304]
I left the SunSDR2 Dx running with SDR3 V12 while I did other tasks outside the radio room.
When I returned it had this disturbing pattern on the screen (See attachment) pulsating on and off on all bands.
I was only able to stop it by pressing the TUNE button. 
That was my first try to ID the cause, other than shutting the radio down
I was unable to tune to another frequency, only change bands, radio was frozen.
![SDR3 V 12 Alpha](https://user-images.githubusercontent.com/94790391/156379770-9973839b-bd9f-4dd0-baf5-99925a45ca1d.jpg)
.

**Comment by sm6usu** [comment]
Same happen to me today waterfall exact same Tranceiver disconnect.
![ExpertSDR3 SunSDR2DX EED06202100558 2022-03-23 21_41_33](https://user-images.githubusercontent.com/101463570/159794323-8fb4658f-ebd5-4b97-a7e9-f79a51f9c549.png)

**Comment by danweecc** [comment]
Do you happen to be using Log4OM2?

**Comment by W3FRG** [comment]
No nothing else was in use.

Tom

**Comment by sm6usu** [comment]
PS I use Log4om all time
sm6usu Svante
