### ISSUE TITLE
Very poor quality when monitoring NFM audio

### ISSUE THREAD

**Issue by reflectingme** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#305]
macOS Monterey 12.2
Firmware 78.8
<img width="236" alt="Screenshot 2022-03-03 at 07 45 56" src="https://user-images.githubusercontent.com/47534300/156519595-9a16b8c4-f012-4734-8cbe-7016ef9ee776.png">

When Monitor is enabled and one is using NFM, the quality of the monitor audio is extremely poor, the sound is quite distorted and is though the modulation is incorrect.  

I can confirm that for me at least, Tx audio when Monitor is ON still works fine, and that this is a Monitor audio issue not a transmission issue.

Initially noticed this on 2M, but the issue occurs on any band when using NFM.

John - GW3JVB

.

**Comment by ExpertSDR3** [comment]
Monitoring from the transceiver to the NFM does not work, it works only through the PC sound card.
