### ISSUE TITLE
Can’t connect to remote running EESDR3 0.12 from iPad 

### ISSUE THREAD

**Issue by mmaseda12** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#306]
I can log in to the EESDR remote cloud server but the I just get a message that says connecting but never connects. Tried Safari, Chrome, and Edge browsers on iPad with same results. Also have the same problem when trying to connect with a Mac using Safari but I can connect using Chrome and Edge.

**Comment by mmaseda12** [comment]
Additional information as well as wireshark traces loaded on EESDR forum page

**Comment by N8SDR007** [comment]
Roman- I take this is still an open bug. in 08072022 as well?
