### ISSUE TITLE
jtdx with 0.12.0 via TCI : no modulation

### ISSUE THREAD

**Issue by HB9FAR** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#308]
MB1 EED 10261800175
Windows 10
SDR3 0.12.0 and 0.12.1

JTDX connected via TCI : Rx ok, ptt ok but no modulation while txing.
With 0.11.0 works perfectly

**Comment by danweecc** [comment]
This happens to me sometimes as well. I have to re-start JTDX in order to get things working again. I'm not sure if this might be more of a JTDX issue though.
