### ISSUE TITLE
ATU never stops tunning

### ISSUE THREAD

**Issue by rvolchkov** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#31]
SunSDR2 DX
0.9.0/0.10.0
Windows 10

ATU never stops tunning... It is in a continuous loop trying to tune, I can see the values around 1.1/1.2 but it never stops trying to tune... It seems to be in an infinite loop trying the same values over and over again. This happens both in mac and windows! I've tested with ESDR2 and it works just fine.

**Comment by diogocondeco** [comment]
Hi Roman,

Still no update on this? This still happens with the just released 0.11...

Best regards,
Diogo
