### ISSUE TITLE
Lost Connection

### ISSUE THREAD

**Issue by W3FRG** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#310]
Since the installation of SDR3 Alpha Ver 12 , I have been intermittently getting a "Lost Connection" error message.
The GUI stays open on the display but the radio Start Transceiver button needs to be turned back on.
I have gone through the PC's Device Manager and made sure all devices were not clicked ON to save power.

This has also occurred intermittently on previous versions, but NO ERROR MSG Appeared.
Only the Start/Stop Icon went dull, not highlighted.

Ping tests show 4.94ms Min, 5.74ms Max and 5.20ms Avg.

W3FRG

![Lost Connection](https://user-images.githubusercontent.com/94790391/156904730-13ca2a9b-98b2-465d-ac6e-9a12e5ab6f54.jpg)
.
With the download and installation of SDR3 V12.1, I am still experiencing the LAN Lost Connection error.
I must clk on the On/Off Icon to restart GUI.

3/10/2022   NOTE:  I have reloaded SDR3 V12.1 and have been running it all day without any new Lost Lan Connections.
I will continue running this configuration for the next two or three days and note any changes. 
My Ping was done in error since the radio is a Static Ip. The timing is 0 ms.

**Comment by danweecc** [comment]
Are you connecting using Wi-Fi, or LAN? I'm experiencing frequent lost connections since version 12 as well. I'm not sure if it is due to latency sensitivity or dropped packets. I only experience this when connecting over Wi-Fi or over the internet.

**Comment by W3FRG** [comment]
I am connected via LAN.
Identical hookup as EESDR3 ver 11 and previous.

Tom W3FRG

**Comment by danweecc** [comment]
Ok, that's interesting. I've been wondering if that might be happening for some. Have you tried the various registry mods to improve Windows network priority?

**Comment by W3FRG** [comment]
I'm not aware of any Registry Mods availability?
I have just gone through the "Device Mgr'' and checked all devices to
ensure that the "Power Management" was unchecked for Power savings.
I have also rotated the RJ45 cables in their slots.

**Comment by danweecc** [comment]
Try this and see if it helps:-
https://ttcshelbyville.wordpress.com/2017/10/14/network-throttling-index/?fbclid=IwAR10R0-WEUsGnWEfRFuy0pubmDDDWjRFT2CbSkcVSsCYCCM12yEpnFANHeo

**Comment by W3FRG** [comment]
Interesting.
I will investigate and try this later today when time permits.

Thank you
Tom

**Comment by W3FRG** [comment]
I was able to get to the chosen point, system profile, but was unable to
get the window shown to edit.

**Comment by danweecc** [comment]
I have a similar issue here:-
https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/issues/275

**Comment by sm6usu** [comment]
Same here
sm6usu
Windows 10 sdr v3 12.1
did not happen in V3 12.0
Svante sm6usu

**Comment by sm6usu** [comment]
So now I have see my tranveiver froze or disconnect when I for example pull the electric kontakt to a screen or similar I have a electrical bar with 6 outputs and if I unplug something the dirty way just pull the plug from somthing like another screen  my sunsdr screen  stops. I can restartstart it again just clicking on start button. So something when you get some kind of spikes in or near the electrical system seems to a problem in my case. (But the audio is now clean from the tranceiver whithout electrical cracling )
