### ISSUE TITLE
EESDR3/SunSDR connection crash when tuning RX2 via TCI while transmitting on RX1

### ISSUE THREAD

**Issue by ok1dsz** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#311]
Hi
running 1 piece of SunSDR2DX with FW 78.8, EESDR3 version 0.12 build 01032022, RadioSync 1.0.0 alpha, Virtual Serial Ports Emulator (64 bit) 1.1.5.458, SDC 15.23x64 and DXLog 2.5.31 on Windows 10.

There are three serial port pairs configured in the VSPE - for radio 1, radio 2 and OTSRP. 

DXLog runs in SO2R mode, each radio (CAT+CW/PTT) are connected to its dedicated com port pair. The other end of virtual com port pairs is connected to the RadioSync. 

OTRSP is connected using its dedicated com port pair from DXLog to the SDC OTRSP controller. Purpose of this OTRSP connection is to be able to switch audio from RX1/RX2 to the left/right ear, because such audio switching does not work properly in EESDR3 when using eCoder buttons (issue #188).

It all works fine (switching between R1 / R2, transmitting on R1 or R2, tuning RX1 or RX2 by clicking into bandmap etc.) until I try to tune the RX2 by clicking on the bandmap of the DXLog while I am transmitting on RX1. In 90% of cases the EESDR3 will lose connection to the SunSDR. Sometimes immediately, sometimes bit later when swithing back to RX on the RX1.

The problem can of course be caused by anything in that chain, but:
1) all that works fine with EESDR2
2) and even if there were some wrong data sent from the DXLog or any other of involved components in the chain of CAT connection, then it for sure should not lead to crash of connection between EESDR and the SunSDR TRX itself.

To return back to the normal operation in some cases it is enough to switch on the connection again just by "power" button in the EESDR3, but in some cases it was neccessary to power off/on the SunSDR TRX and also to restart the EESDR3.

Here is an extract of the TCI log as captured in the EESDR3. It shows some transmitting on TRX1 and at 08-24-13:746 there is visible the action of tuning of the RX2:

08-24-13:063 client: trx:0,true;
08-24-13:063 server: trx:0,true;
08-24-13:079 server: trx:0,true;
08-24-13:079 server: tx_enable:1,false;
08-24-13:094 server: tx_enable:1,false;
08-24-13:094 server: trx:0,true;
08-24-13:094 server: tx_enable:1,false;
08-24-13:111 server: tx_frequency:3537923;
08-24-13:111 server: tx_frequency:3537923;
08-24-13:111 server: tx_frequency:3537923;
08-24-13:165 client: keyer:0,true;
08-24-13:270 client: keyer:0,false;
08-24-13:306 client: keyer:0,true;
08-24-13:341 client: keyer:0,false;
08-24-13:376 client: keyer:0,true;
08-24-13:482 client: keyer:0,false;
08-24-13:518 client: keyer:0,true;
08-24-13:554 client: keyer:0,false;
08-24-13:660 client: keyer:0,true;
08-24-13:746 client: vfo:1,0,3551000;
08-24-13:746 server: vfo:1,0,3551000;
08-24-13:751 server: if:1,0,10625;
08-24-13:751 server: vfo:1,0,3551000;
08-24-13:751 server: if:1,0,10625;
08-24-13:766 client: keyer:0,false;
08-24-13:767 server: if:1,0,10625;
08-24-13:767 server: vfo:1,0,3551000;
08-24-13:801 client: keyer:0,true;
08-24-13:907 client: keyer:0,false;
08-24-13:943 client: keyer:0,true;
08-24-13:978 client: keyer:0,false;
08-24-14:013 client: keyer:0,true;
08-24-14:119 client: keyer:0,false;
08-24-14:333 client: keyer:0,true;
08-24-14:352 client: spot:BD4QA,CW,28009000,4289396607,Demo;
08-24-14:438 client: keyer:0,false;
08-24-14:545 client: keyer:0,true;
08-24-14:548 server: trx:0,false;
08-24-14:548 server: tx_enable:1,true;
08-24-14:564 server: trx:0,false;
08-24-14:564 server: tx_enable:1,true;
08-24-14:564 server: trx:0,false;
08-24-14:564 server: tx_enable:1,true;
08-24-14:579 server: trx:0,false;
08-24-14:579 server: tx_enable:1,true;
08-24-14:581 client: keyer:0,false;
08-24-14:687 client: keyer:0,true;
08-24-14:723 client: keyer:0,false;
08-24-14:758 client: keyer:0,true;
08-24-14:793 client: keyer:0,false;
08-24-14:828 client: keyer:0,true;
08-24-14:864 client: keyer:0,false;
08-24-14:970 client: keyer:0,true;
08-24-15:076 client: keyer:0,false;
08-24-15:288 client: keyer:0,true;
08-24-15:298 server: trx:0,true;
08-24-15:298 server: tx_enable:1,false;
08-24-15:314 server: trx:0,true;
08-24-15:314 server: tx_enable:1,false;
08-24-15:314 server: trx:0,true;
08-24-15:314 server: tx_enable:1,false;
08-24-15:394 client: keyer:0,false;
08-24-15:429 client: keyer:0,true;
08-24-15:535 client: keyer:0,false;
08-24-15:571 client: keyer:0,true;
08-24-15:676 client: keyer:0,false;
08-24-15:785 client: keyer:0,true;
08-24-15:797 server: trx:0,true;
08-24-15:797 server: tx_enable:1,false;
08-24-15:813 server: trx:0,true;
08-24-15:813 server: tx_enable:1,false;
08-24-15:813 server: trx:0,true;
08-24-15:813 server: tx_enable:1,false;
08-24-15:890 client: keyer:0,false;
08-24-15:925 client: keyer:0,true;
08-24-15:960 client: keyer:0,false;

Any idea?

73 
Zdenek OK1DSZ

**Comment by ExpertSDR3** [comment]
Can you attach a video that clearly shows this problem?

**Comment by ok1dsz** [comment]
Hi
it is not allowed to attach file over 10MB, so you can find the video here (15MB): [http://ok1dsz.nagano.cz/sdr/2022-03-12%2008-30-50.mp4](http://ok1dsz.nagano.cz/sdr/2022-03-12%2008-30-50.mp4)
You can see there:

00:02 F1 was pressed in DXLog, a CQ on TRX1 starts
output power is intentionally set to 0, but you can see the TX indication in the upper left corner

00:04 click on bandmap of TRX2, SunSDR has been tuned to desired freq
in the same time the transmission stops (although TX indication in the upper left corner is still active) and I can hear some relay switching (several times) inside of the TRX box

00:12 keying from DXLog finished, TX indication in the upper left corner was deactivated, but it does not start to receive anymore

00:19 message about lost connection

00:30 "Start transceiver" pressed and normal operation resumed
note: the fast flickering spectum is in the reality not there, it was somehow created only in the recording

00:38 connection to the TRX lost again
Between 00:30 and 00:38 I did nothing - no action on any control in DXLog or EESDR or eCoder

The video was taken with EESDR 0.12.1, SunSDR2DX FW 78.8.

Feel free to ask for any other info, screenshot of config etc.

73
Zdenek OK1DSZ
