### ISSUE TITLE
Failed to read device calibrations after Firmware update 78.8

### ISSUE THREAD

**Issue by tjasperme** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#314]
Running ExperSDR3 0.12.0 alpha  - Build 01032022
Device SunSDRpro 
Serial EED05131900617
PCB revision 4
OS Win10 Pro

**Comment by dd5md** [comment]
I have this error as well. With ExpertSDR3 0.12.0 alpha just like with ExpertSDR3 0.12.1 alpha.

Tested with my second SunSDR2 DX. My operating system is macOS 12.2.1 Monterey.

**Comment by tjasperme** [comment]
gone back to Firmware 72.8, then tried again 78.8 - no error message anymore.
