### ISSUE TITLE
IF options for E-Coder not working

### ISSUE THREAD

**Issue by hb9bun** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#315]
ESDR3 V 0.12.1 alpha Build: 05042022
SunSDR2DX
Win 10

I still miss the IF setting in E-Coder working as in ESDR2 - so allowing to move the Filter and keeping the waterfall stable - when moving frequency just a bit.

**Comment by ExpertSDR3** [comment]
The control of moving the filter across the panorama works.

![image](https://user-images.githubusercontent.com/93903520/157390556-e01bd7b9-9650-483e-b78a-80782a3828aa.png)

**Comment by hb9bun** [comment]
Thank you. Sure the "control" works, it gets green. But even with the control on the Waterfall under the moving filter does not stand still. Anything I do wrong? 
With ESDR2 it stands still and only the filter moves.

**Comment by hb9bun** [comment]
**Problem resolved:** 
As I have seen working IF on other installations and on a fresh install on another PC here, I did rename the AppData\Local file to get all settings reset, AND AFTER THAT **IF works just normal.** 
It was an issue in my EESDR3 settings that made it not work. 
I have a copy of my json file with all the settings if that should help.

**Comment by ExpertSDR3** [comment]
Fixed.
