### ISSUE TITLE
V12.1 60m for Switzerland not supported properly anymore

### ISSUE THREAD

**Issue by hb9bun** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#317]
ESDR3 V 0.12.1 alpha Build: 05032022
SunSDR2DX
Win 10

Since days ESDR3 V 0.12.1 worked normal on 60m with Swiss band limits. 

As other testers reported issues with 60m not available in some countries, I did a test with Windows Regional Settings for Norwegian(Norway). That worked normal on my PC. 

When I then switched back in Win10 to German(Switzerland) 60m still was available, but with wrong band limits (5351.5-5354). I did delete uninstall, delete all directories, restart the PC. No change. 

Using instead Regional settings English(United States) or German(Germany) everything is correct. 

I also then  switched to ESDR2 latest version. All ok with 60m with Switzerland settings. Then reinstalled ESDR3 12.0, all ok with 60m. 

Then reinstalled ESDR3 12.1 with above build and 60m limits were wrong again. 

I am very sure that 60m worked properly with German(Switzerland) settings after I installed 12.1 the first time and only now does not work anymore.

**Comment by hb9bun** [comment]
Confirmed: It seems like I did not test 60m after moving to 12.1. 
It does not set the band limits properly for all regional settings for Switzerland, so for German(Switzerland), French(Switzerland), Italian(Switzerland), for English(Switzerland), nor for German(Liechtenstein),

**Comment by ExpertSDR3** [comment]
fixed
