### ISSUE TITLE
"pink noise line" is wrong

### ISSUE THREAD

**Issue by rvolchkov** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#32]
The slope of the "pink noise line" is wrong - the correct slope would be 3 dB per octave (in the current EQ-graphic the slope is 6 dB per octave).

Test Setup:
PC: Win 10 Pro, 64 Bit (Version 21H1), CPU i9-10900 @ 2.8 GHz, RAM 32 GB
Graphic System: NVIDIA GeForce RTX 2070 SUPER
Monitor: DELL Ultrasharp U3818DW, 38”, 3840 x 1600, 59.994 Hz
TRX: Sun SDR2 Pro, Serial EED05351600204, PCB revision 4, Firmware 72.8, ESDR3 0.10.0.Alpha Build 03112021
RX: Sun ColibriNANO
E-Coder, 256 PPR (E-Coder2: Ordered, waiting for delivery)
Audio: Microphone & Speaker via MOTU/M2 ASIO Interface (connected via USB-C to PC)
CW-Paddle, PTT-Key connected via E-Coder (256 PPR)
PA: Gemini HF-1K, 1 KW LDMOS PA, 10 W Input / 1000 Watt output

**Comment by 1972igor** [comment]
WIN 10 Home
Transceiver MB-1
ESDR3 0.10.0 alpha Build 03112021
 Подтверждаю !!!  розовой шумовой линии» неправильный — правильный наклон будет равен 3 дБ на октаву

**Comment by ExpertSDR3** [comment]
Spectrum analyzer shows amplitude density, that's why the "Pink noise line" slope is 6 dB per octave, like the spectrum scope in the main ESDR3 window.
If the spectrum analyzer showed power density, then the slope would be 3 dB, but that's not the case.
