### ISSUE TITLE
AM carrier suppression issue

### ISSUE THREAD

**Issue by Kb2uka** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#321]
Sunsdr2dx 
V3 0.12.1
Mac iOS 

There appears to be AM carrier suppression of approximately 50%. Carrier to peak output power ratio should be 1:4. 100 watt carrier should produce 400 watt peak output. Currently, 100 watt carrier produces 200 watt peak. 

I believe the carrier suppression is set at 50%. Would be great if that could be dropped to 25%. 

Thank you!
Doug
Kb2uka

**Comment by N8SDR007** [comment]
It would be BEST PRATICE if the ability to CONTROL carrier LEVELS was an option! and again going back to this discussion https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/discussions/60
