### ISSUE TITLE
PA button not working correctly

### ISSUE THREAD

**Issue by w2ner** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#322]
The way I understand it, the PA button enables the keying of the amplifier, When PA button is off, tune still keys amplifier.  When this is fixed, it would be nice to have an option to automatically disable the amplifier keying when tune button is pressed.

**Comment by ea5ccy** [comment]
Have you try with  this buttom options?

![image](https://user-images.githubusercontent.com/100173220/159120991-51abe340-8b72-48b0-9b96-f7b9134d6baf.png)

EA5CCY - Pedro
