### ISSUE TITLE
EESDR3_12.1  MB-1 Low Level Audio Buzz Garbles RCV audio

### ISSUE THREAD

**Issue by N9PY** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#323]
Since installing alpha 12.1, the MB-1 will spontaneously develop a low-level audio buzz.  This buzz garbles all the receive signals audio.
If I X out the 12.1 program and hit start again, the problem is fixed.
If I ignore it, eventually it crashes with the message "Lost connection with MB-1!"
This happens more than once a day while the MB-1 is not touched.
73 Torrey N9PY

**Comment by W3FRG** [comment]
I have experienced this same anomaly of Buzzing Audio & Lost Connection on the SunSDR2 Dx.
However, the Lost Connection has reduced from original occurrences for unknown reasons.
Tom W3FRG

**Comment by N9PY** [comment]
Video Example

https://user-images.githubusercontent.com/100733783/158845165-c83d6918-2ec1-44ba-b79a-6ad0339b8f47.MOV
