### ISSUE TITLE
No ability to interface 4m Transverter

### ISSUE THREAD

**Issue by gi4fue** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#326]
It seems that the transverter forms only work for transverters of 70cm and above. Many of us in EU operate transverters in 4m band, it would be nice if we were able to have a transverter form for it. Using 10m band means that the CAT information sent to my Expert amplifier sets the amp to 10m and not 4m

**Comment by ExpertSDR3** [comment]
In version 0.13, the 4M band will appear, since there are no filters for this band in the transceivers, the reception and transmission will be carried out only through ADC and DAC.

![image](https://user-images.githubusercontent.com/93903520/168974641-563043f0-4c36-4d28-b303-996c9077dc07.png)
