### ISSUE TITLE
Can not enter positive repeater values 

### ISSUE THREAD

**Issue by w2ner** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#328]
RPTR button will not allow positive entries.  Negatives are fine, but will not give you the option to enter positives.

**Comment by N8SDR007** [comment]
Correct no abilities to add a positive value thus making 2M repeater mode almost USELESS!

Several versions back this wasn't the case, and you could add positive offsets

**Comment by w2ner** [comment]
I have this bug in with Roman

**Comment by ExpertSDR3** [comment]
Starting from version 0.13, it will be possible to set a positive frequency offset of the repeater.
