### ISSUE TITLE
Loose audio

### ISSUE THREAD

**Issue by W3FRG** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#330]
When using SDR3 V 12.1 and If I am tuning and listening on an HF Band and then tune outside of that band limits, I lose all audio.
I cannot regain any sound until I close down the radio and reopen using the START GUI.

Tom W3FRG

**Comment by danweecc** [comment]
hi Tom - the programmers will need:-

EESDR3 0.12.1 build number (I assume 05032022)
Radio you're using (I assume SunSDR2DX)
OS: (I'm assuming Windows 10 64-bit)
Steps to reproduce this (example of bands, mode, procedure)

**Comment by W3FRG** [comment]
Daniel,

You are correct on all points. 
The PC is a Dell 7040 i7

Have a great weekend,
Tom
