### ISSUE TITLE
Software ExpertSDR3_x64_0.12.1 fails to start on W10 system

### ISSUE THREAD

**Issue by INOV8TN** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#331]
Popup asking if OK to make changes shows up and when I give OK that's the last I hear from s/w.
Can't find any trace on Task Manager.

EXPERTSDR2  V1.3.1 Update 11 runs fine.

SDR SN: EED06202100559
Version: 72.8

**Comment by danweecc** [comment]
You need to upgrade the firmware to version 78.8 if you want to use EESDR3 alpha 0.12.1.

**Comment by INOV8TN** [comment]
Hummm...  Sounds like a good idea but when I go to ExpertSDR2 (Running a SunSDR2DX) --> Options --> Device and click on 'SDR firmware' the response is that "Firmware is up to date".

**Comment by danweecc** [comment]
EESDR2 and EESDR3 uses different firmware versions and are not compatible with one another. You have to choose one version that you want to use or you will need to keep flashing the firmware to match the EESDR version you're using. Doing this too often is not a good idea.

**Comment by INOV8TN** [comment]
Thank you all for giving me hope with your positive answers but I still don't have a path to running ExpertSDR3.
ESDR2 claims the firmware is up to date and offers no possibility of accessing, installing, or updating it. 
 
Today, 4/3/22  I downloaded and installed the latest ESDR3 for Windows, when it started, showed its splash screen and disappeared but continued running in the background. I used Task Manager to kill it twice.  Part of the installation was to present me with a series of questions for many of which I had no answers. Please see files 1-4

I found and ran the Firmware.exe file but it just gave me the blank Firmware Manager popup

![1 - A with blank Firmware Manager popup 2022-04-03 204723](https://user-images.githubusercontent.com/25114242/161470324-ec681607-c14f-4e4d-b5b4-17c6ac00ed56.jpg)

![1 - Call Letters and UserName 2022-04-03 203510](https://user-images.githubusercontent.com/25114242/161470325-42f13e6e-0169-48a1-8e30-941b849c47d0.jpg)

![2- Remote 2022-04-03 204101](https://user-images.githubusercontent.com/25114242/161470326-bd796007-369d-42d7-a1e2-d47d948f0901.jpg)

![3 - Expert Sync 2022-04-03 204228](https://user-images.githubusercontent.com/25114242/161470328-2b213f80-37a4-4966-a45a-daa26bc4bad9.jpg)

![4 - ESDR2 - Firmware Up to Date 2022-04-03 205644](https://user-images.githubusercontent.com/25114242/161470330-f871c9d8-7c63-4c50-8811-346b489ef375.jpg)

**Comment by INOV8TN** [comment]
I didn't mean to 'close' this issue.
