### ISSUE TITLE
********ExpertSDR3 Issues********

### ISSUE THREAD

**Issue by w2ner** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#332]
I will be updating this list as time goes on until resolved. 

 **Issues**
1. When saving to memory, it does not save the CTCSS or RPTR information.
2. RPTR will not allow positive values.
3. Mic filters do not seem to work
4. When you enable "Save By Band" for PA, the PA button is removed from toolbar, so you can't enable or disable the PA
5. If you switch from 39 khz to any other sample rate the RX audio stops. If you use the sound card audio, that works but nothing from the speaker output on the Sunsdr2. If you switch back to the 39 khz sample rate, audio returns. 
6. Antenna selections for A1, A2 or A3 do not work.
7. E-Coder settings are missing.
8. Shortcut menu missing

**Suggestions**
1. No split function control
2. Would be nice to have SQL control in SSB
3. Would be nice to have some kind of OP manual
4. Have button on toolbar for antenna selections.

Happens on both Windows and MAC
ExpertSDR3
Mac OSX Monterey M1 16 gig ram
Windows 10 Intel i5 64 bit 16gig ram

**Comment by danweecc** [comment]
EESDR version? OS version?

**Comment by w2ner** [comment]
EESDR V3 and macOS Monterey
    

Nick Riale
4827 Seabreeze Lane
Myrtle Beach SC 29579

**Comment by w2ner** [comment]
EESDR V3 and macOS Monterey 12.2.1
    

Nick Riale
4827 Seabreeze Lane
Myrtle Beach SC 29579
