### ISSUE TITLE
Drive level disparity between Tune and Drive - very different output levels

### ISSUE THREAD

**Issue by kingsqueak** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#333]
SunSDR2 DX - Windows 10 and also Ubuntu   EESDR3 0.12.1 build 05032022

A very large difference in drive level between Tune and Drive.

On Tune at **23.5**% I see 1200W out from my amplifier

With Drive at **57**% I only see about 900W out.

The watt meter is a peak reading watt meter and typically the output of Tune == Drive should be very close in output power.

I am using Mic.PC with ASIO for both mic and speakers with a Motu M2 interface.

I run several other radios with the same audio configuation (A TS-590sg and an Anan) and do not see this issue at all. My audio is heavily compressed before it gets to the radio so it should be driving it quite hard.

**Comment by N8SDR007** [comment]
Never has the Drive and Tune been linear in response- even in V2
