### ISSUE TITLE
Different Gain

### ISSUE THREAD

**Issue by sm6usu** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#335]
Why do I see gain level down bottom left corner as soon I hit ptt? I did get back to v3 0.11.0 and there is no gain showing. Also when using amplifire I can not use my earlier setting because it is overdriving, I have tried to find where to adjust this gain but have no luck with that. I have also get report that my audio is sometimes distiorsed. I get of my ptt and hit it again help get out of distorsion but it will come back later. Have never had distorsion before on my audio. What is this gain?

![ExpertSDR3 SunSDR2DX EED06202100558 2022-04-05 17_14_12_LI](https://user-images.githubusercontent.com/101463570/161790517-7c8375fd-3781-4dd5-bb69-73c7ed92475e.jpg)

**Comment by dd5md** [comment]
I have tried for a long time to get the equalizer settings to work the way they do in ExpertSDR2. Unfortunately, it doesn't even begin to sound like it does in EESDR2.

My audio is always overdriven and sounds unclean. The broadcast doesn't always sound the same either. I will wait until the full version and then test again.
