### ISSUE TITLE
ATU V3 0.12.1

### ISSUE THREAD

**Issue by ON3CQ** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#336]
I received the new cable for my ATU and it works now and firmware update for the ATU also.
The ATU also works as it should in V2 1.3.1 Update 11.
In V3 0.12.1 alpha the ATU keeps tuning and does not stop, do the test on the same band as in V2.
There is a setting in V3 to stop it from TXing when tuned i put this OFF.
I have to manually stop the ATU or it will continue to search for the correct SWR.
I suspect there is a problem with V3 0.12.1 alpha and the ATU.

73 Pat

**Comment by danweecc** [comment]
One temporary way to get around this is to hold the Tune power level at a higher level. I think EESDR reduces the power level so much that it cannot achieve a solution. What I do is to hold the Tune power level high with a mouse until it finds a solution. You will have to actively grab the button as it will keep moving around.

**Comment by ExpertSDR3** [comment]
In version 0.13, the ATU control algorithm will be fixed., The problem was a decrease in the output power of the transmitter during the ATU setup.
