### ISSUE TITLE
TCI Errors - vfo_limits & rx_anf_enable

### ISSUE THREAD

**Issue by iw7dmh** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#337]
![image](https://user-images.githubusercontent.com/87143145/162968705-7ba80fb4-2908-4bf8-8b3a-3af159b10f39.png)

- The **vfo_limits** command, in ExpertSDR3 returns "vfo_limits:0.0,800000000.0;" :  frequencies are floating point values and this break the parser.

![image](https://user-images.githubusercontent.com/87143145/162969238-5da759be-0788-4ab1-8655-747384d463fc.png)

- The **rx_anf_enable:0,true;** has effect on the receiver but the GUI isn't updated - The **ANF** button remains in the **ON** state

**Comment by ExpertSDR3** [comment]
Fixed, fixes will appear in version 0.13.
