### ISSUE TITLE
pink noise line" is wrong

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#34]
Win 10 - 64  Home
Transceiver MB-1
 ESDR3 0.10.0.Alpha Build 03112021
![noise Rozi](https://user-images.githubusercontent.com/93991940/141470338-0694b9e2-d506-45a2-ada9-9cc32041fd68.jpg)
![Noise-1 input Radio ](https://user-images.githubusercontent.com/93991940/141470397-28b7758c-4d9b-4bb7-b8eb-52dcee243c0c.jpg)

The slope of the "pink noise line" is wrong - the correct slope would be 3 dB per octave (in the current EQ-graphic the slope is 6 dB per octave).
![noise Rozi analiz RADIO](https://user-images.githubusercontent.com/93991940/141470173-597cf72c-fc1c-4090-9063-3fe96692f73e.jpg)

[noise Rozi](https://user-images.githubusercontent.com/93991940/141469053-302e3c63-1fca-474c-a4e6-8ee7be9e60f5.jpg)
На вход передатчика был подан с генератора сигнала розовый шум  и произведено сравнение  показания  наклонной линии на анализаторе спектра самого генератора и наклонной линии анализатора радио ! Наклонная анализатора  радио ( для настройки звука прорисована НЕ ВЕРНО!!!)

**Comment by ExpertSDR3** [comment]
Исправлено, исправления будут в релизе 0.10 .
![esdr3_pink_noise](https://user-images.githubusercontent.com/93903520/141781743-394a61ee-8e05-4c5e-8a2f-0df933073652.png)

**Comment by 1972igor** [comment]
Спасибо!!
