### ISSUE TITLE
Experts SDR3 and SunSDR2 Pro 2 meter issue

### ISSUE THREAD

**Issue by randydid** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#341]
On version v3, .12.x, when I am operating on 2 Meters, I key the mic (PTT) pedal, and I am able to TX into my amp. When I release PTT, the radio stays keyed (red LED on) and is transmitting some sort of RF and activates my amp but is way off frequency and the VSWR is 10:1+++ on my W2 wattmeter. I have to push the pedal several times to get it to come out of TX and sometimes I have to turn the power to the radio off completely. This does NOT happen on v2

**Comment by w2ner** [comment]
I have had issues with FM as well, V3 is not ready for prime time, by far.  Needs a lot of work.
