### ISSUE TITLE
E-coder и работа клавиши Lock

### ISSUE THREAD

**Issue by ub3dqy** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#342]
SUNSDR2DX, S/N EED06121000432
ESDR3 0.12.1 Alpha
Windows10Pro x64
Gigabyte X58A-UD7, Xeon X5675, RAM 24 ГБ, SSD Samsung 250 ГБ, Nvidia NVS 315, трансивер подключен к встроенной сетевой карте.
Есть следующие замечания:
На E-Coder не работает клавиша Tx/Play, при нажатии ничего не происходит.
При блокировка частоты (клавиша Lock) и включении расстройки невозможно отстроиться от основной частоты. Т.е. если я работаю на общий вызов и заблокировал частоту, что бы случайно не сдвинуться т.к. использую  E-Coder, и включаю расстройку что бы прослушать станцию отвечающую не на частоте, расстройка не работает пока не разблокирую клавишей Lock.

**Comment by ExpertSDR3** [comment]
Исправлено, исправления появятся в версии 0.13 .
