### ISSUE TITLE
ATU settings for AAT-100 does not update with band change

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#343]
SunSDR2DX firmware 78.8
AAT-100 version 1, revision 1
EESDR3 0.13.0 alpha 20052022
Windows 10 64-bit

Summary: the ATU settings with AAT-100 does not automatically update when changing bands on the radio.

Details: 
1. have my radio on 20m and use TUNE to tune the ATU to give a 1.0 SWR match. I verify this with a CW carrier.
2. I switch bands to 17m using the on-screen button
3. I put out a carrier and the SWR is high, so I use TUNE to tune the ATU to a 1.3 SWR. I verify this with a CW carrier.
4. I switch  bands back to 20m using the on-screen button
5. I put out a CW carrier and note that the SWR is now high! It should be tuned since I had already done this in step 1.
6. I press TUNE to tune the ATU again and get the message "Already tuned". SWR is now back to 1.0

It appears that ATU settings are not updating.

**Comment by ExpertSDR3** [comment]
fixed
