### ISSUE TITLE
Build: 20052022

### ISSUE THREAD

**Issue by N8SDR007** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#344]
Roman:

20052022 on 2DX as listed 

Fresh installs (as in no trace of a previous install- Files/folders or registry hooks) is unstable in Win11

Many out of the blue shutdowns, which also results in never writing changes to database (User selected or adjusted settings) and various warnings on attempted relaunches of "Can't Read Calibrations"

Oddly my Win11 User account is set as ADMIN
When setting the DEV to run as ADMIN as well the calibration error resolves, but if it shuts down unexpected then again settings are lost

Now If I install as an upgrade and use previous database and install created user account folders then all seems well, although I have experienced a few out of the bule shutdowns for no apparent reasons.

I suspect an installation RIGHTS issues with the DEV win installation esp. with Win11 when performing a Truely Fresh Install
if you perform install with current version and that uses previous database and user file/folders then it seems fine

Comments on Bugs fixed and listed as resolved: from this build
# 328 and #320 - 2M Positive offsets - is working as well as CTSS tones and values
# 321 AM carrier suppression does seem to be more constant 25% carrier level
#94 System Freezing @100% zoom - still happens but doesn't appear as often so some progress there and maybe be video driver related and at what refresh rate (Note I'm using 2 displays one at 170Hz the other @ 240ish refresh) more data needed to confirm with others who experienced this in group.

No E-coder here so cannot comment on those updates

**Comment by danweecc** [comment]
Also happening with Windows 10 64-bit (Intel i7-8700K, 32GB RAM).
