### ISSUE TITLE
SAM instead of AM on HF radio bands 

### ISSUE THREAD

**Issue by PE1BIW** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#348]
SunSDR Pro EED053551600275
ExpertSDR3 buld 0.1.21 alpha
MacOS 12.4
Mac Mini 2018 i7 16GB
Each time the tranceiver is tuned into one of the HF radio bands (120M, 90M, 75M, etc) on the mode AM
the software switches to SAM, even if SAM is off.
By switching SAM on and off again, the software switches to regular AM.
The next time entering a radio band, the same thing happens again.

**Comment by ExpertSDR3** [comment]
fixed
