### ISSUE TITLE
 RF spike in V3

### ISSUE THREAD

**Issue by ON3CQ** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#349]
This weekend we used the radio at the CW Contest station. When the radio go TX it gets a power peak and the amp switched to hot switching. I test delay 10 or 25 same. We installed version 2 and put the delay ptt on 10 MS and had no problem. Maybe there is also a problem in version 3.

**Comment by N8SDR007** [comment]
Happens on SSB as well and more noted in last 2 DEV releases
