### ISSUE TITLE
не правильная работа  Mic meter!!!!  The Mic meter is not working correctly

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#35]
Win 10 - 64 Home
Transceiver MB-1
ESDR3 0.10.0.Alpha Build 03112021
наблюдается  неправильные показания индикатора Mic meter  нижних приделах 
на вход передатчика ( вход  MIC PC ) был подан генератор 1000 Гц с входным уровнем 0 dB ,  при  этом регулятор усиления 
 по микрофонному входу  выставлен  в 0 dB по усилению, затем входной уровень ослаблялся с шагом минус 5 dB на вход передатчика , при этом сравнивались показания уровней на выходе генератора и входного уровня передатчика
ПОКАЗАНИЯ НА ПАН АДАПТОРЕ ПОЛНОСТЬЮ СОВПАДАЮТ  С ВЫХОДНЫМ УРОВНЕМ ГЕНЕРАТОРА ПОДАВАЕМОГО НА ВХОД ПЕРЕДАТЧИКА
![0dB input mic level](https://user-images.githubusercontent.com/93991940/141496932-29170563-355b-4b66-8c7b-e1429406f58a.jpg)
![0dB](https://user-images.githubusercontent.com/93991940/141496937-48a83072-18ab-44ac-818e-9c885ba27587.jpg)
![-5dB mic level ](https://user-images.githubusercontent.com/93991940/141496939-c38f7d99-31ff-4ed1-b603-877171a8f09b.jpg)
![-5dB](https://user-images.githubusercontent.com/93991940/141496941-cc97d162-f4fa-4962-beb4-628e4dd580e6.jpg)
![--15 input  mic level  ](https://user-images.githubusercontent.com/93991940/141496942-012b8f1e-9155-43ab-81bd-f00d501221d6.jpg)
![-15dB](https://user-images.githubusercontent.com/93991940/141496945-790a9b33-95dd-4ca3-944c-7b3f43501499.jpg)
![-20 input mic level ](https://user-images.githubusercontent.com/93991940/141496947-50a303b1-2df3-4773-911d-84c162c5975d.jpg)
![-20dB](https://user-images.githubusercontent.com/93991940/141496949-d42f7c74-364c-4f5d-875b-1e3faace2691.jpg)
![-30dB input mic level](https://user-images.githubusercontent.com/93991940/141496950-cfbb6ef9-a08b-4842-b046-b25c5cefde6a.jpg)
![-30dB](https://user-images.githubusercontent.com/93991940/141496952-ec2d79f6-daad-4c8c-b678-ffe890182daf.jpg)
![-35 input mic level](https://user-images.githubusercontent.com/93991940/141496953-1748e789-17d8-4bf9-baf6-3bc040e67c1b.jpg)
![-35dB](https://user-images.githubusercontent.com/93991940/141496956-6bfe9b8a-e758-4f13-b9a9-06e7656ec4cd.jpg)
![-10 mic level](https://user-images.githubusercontent.com/93991940/141497015-7fbeb7bd-6499-40da-ae36-b112b1fb63a1.jpg)
![-10dB](https://user-images.githubusercontent.com/93991940/141497020-7d152175-898f-4aaa-9e79-99dc796cb37e.jpg)
![-25dB input  mic level ](https://user-images.githubusercontent.com/93991940/141497021-054275b8-19c7-40b7-839e-68488cd416f4.jpg)
![-25dB](https://user-images.githubusercontent.com/93991940/141497022-85624bec-0907-4916-96af-127cb9f6745d.jpg)

there is an incorrect reading of the Mic meter indicator in the lower aisles
, a 1000 Hz generator with an input level of 0 dB was fed to the transmitter input ( MIC PC input ) , while the gain control 
 the microphone input was set to 0 dB in gain, then the input level was weakened in increments of minus 5 dB at the transmitter input, while the readings of the levels at the generator output and the transmitter input level were compared
THE READINGS ON THE PAN ADAPTER COMPLETELY COINCIDE WITH THE OUTPUT LEVEL OF THE GENERATOR SUPPLIED TO THE INPUT OF THE TRANSMITTER

**Comment by 1972igor** [comment]
на вход подаём  0 dB  MIC LEVEL  показывает  0dB
на вход подаём минус 5 dB  MIC LEVEL  показывает минус 2,5dB
на вход подаём минус 10 dB  MIC LEVEL  показывает минус 5dB
на вход подаём минус 15 dB  MIC LEVEL  показывает минус 7,5dB
на вход подаём минус 20 dB  MIC LEVEL  показывает минус 10dB
на вход подаём минус 25 dB  MIC LEVEL  показывает минус 12dB
на вход подаём минус 30dB  MIC LEVEL  показывает минус 15dB
на вход подаём минус 35dB  MIC LEVEL  показывает минус 17dB

**Comment by 1972igor** [comment]
the input is 0 dB MIC LEVEL shows 0dB
the input is minus 5 dB MIC LEVEL shows minus 2.5 dB
the input is minus 10 dB MIC LEVEL shows minus 5dB
the input is minus 15 dB MIC LEVEL shows negative 7.5 dB
the input is minus 20 dB MIC LEVEL shows minus 10dB
the input is minus 25 dB MIC LEVEL shows minus 12dB
the input is minus 30dB MIC LEVEL shows minus 15dB
the input is minus 35dB MIC LEVEL shows minus 17dB

**Comment by 1972igor** [comment]
при подаче внутреннего генератора одного тона, индикатор Mic Level отображает входной 0 dB . при подаче внутреннего генератора два тона индикатор MIC Level отображает входной уровень минус 3dB , вместо минус 6dB, 
ПАНАДАПТЕР ПРОГРАММЫ ОТОБРАЖАЕТ УРОВЕНЬ ПРАВИЛЬНО !!!! 
![Level One tones ](https://user-images.githubusercontent.com/93991940/141609427-671e7edc-0d1c-4add-9d1e-ad34d3d486b0.jpg)
![level Two tones ](https://user-images.githubusercontent.com/93991940/141609429-6de60100-33a9-4401-9f69-8e716033a6a9.jpg)

**Comment by 1972igor** [comment]
при подаче внутреннего генератора одного тона, индикатор Mic Level отображает входной 0 dB . при подаче внутреннего генератора два тона индикатор MIC Level отображает входной уровень минус 3dB , вместо 0 dB!!!
ПАНАДАПТЕР ПРОГРАММЫ, ПОКАЗЫВАЕТ УРОВЕНЬ ВХОДНОГО СИГНАЛА внутреннего генератора два тона МИНУС 6dB ВЕРНО!!!!
![Level One tones ](https://user-images.githubusercontent.com/93991940/141609659-c1cf9138-eb1f-4267-864c-97ac2f7f6b9c.jpg)
![level Two tones ](https://user-images.githubusercontent.com/93991940/141609660-16c947ae-ae22-4987-ae62-73700eac4dcd.jpg)

ПАНАДАПТЕР ПРОГРАММЫ ОТОБРАЖАЕТ УРОВЕНЬ ПРАВИЛЬНО !!!!

**Comment by 1972igor** [comment]
P.S При измерениях РЕГУЛЯТОР УСИЛЕНИЯ MIC PC НАХОДИЛСЯ В ПОЛОЖЕНИИ 0 dB! Производилось ослабление входного уровня  c шагом 5 dB с генератора подаваемого на вход передатчика от 0 dB до минус 35 dB !!!!

**Comment by bastonc** [comment]
Игорь, а блоки в секции proc при всем этом в байпасе или нет? Что-то вклчючено в секции proc?

**Comment by 1972igor** [comment]
все блоки ВЫКЛЮЧЕНЫ!!!  ПОДАН ТОЛЬКО ГЕНЕТОР НА ВХОД ПЕДАТЧИКА!!!!

**Comment by 1972igor** [comment]
все блоки ВЫКЛЮЧЕНЫ!!! ПОДАН ТОЛЬКО ГЕНЕРАТОР НА ВХОД ПЕДАТЧИКА!!!! РЕГУЛЯТОР УСИЛЕНИЯ MIC PC НАХОДИЛСЯ В ПОЛОЖЕНИИ 0 dB! Производилось ослабление входного уровня c шагом 5 dB с генератора подаваемого на вход передатчика от 0 dB до минус 35 dB !!!

**Comment by 1972igor** [comment]
все блоки в секции proc  ВЫКЛЮЧЕНЫ  !!! ПОДАН ТОЛЬКО ГЕНЕРАТОР НА ВХОД ПЕДАТЧИКА!!!! РЕГУЛЯТОР УСИЛЕНИЯ MIC PC НАХОДИЛСЯ В ПОЛОЖЕНИИ 0 dB! Производилось ослабление входного уровня c шагом 5 dB с генератора подаваемого на вход передатчика от 0 dB до минус 35 dB !!!

**Comment by 1972igor** [comment]
все блоки ВЫКЛЮЧЕНЫ!!! ПОДАН ТОЛЬКО ГЕНЕРАТОР НА ВХОД ПЕДАТЧИКА!!!! РЕГУЛЯТОР УСИЛЕНИЯ MIC PC НАХОДИЛСЯ В ПОЛОЖЕНИИ 0 dB! Производилось ослабление входного уровня c шагом 5 dB с генератора подаваемого на вход передатчика от 0 dB до минус 35 dB !!!

**Comment by 1972igor** [comment]
Методика проверки индикаторов уровней такова
1 В закладке "PROC" звуковые модули должны быть выключены !!!
2 РЕГУЛЯТОР УСИЛЕНИЯ MIC PC устанавливаем в уровень значения 0 dB (БОЛЬШЕ ЭТОТ ДВИЖОК НЕ ТРОГАЕМ !!!
3 Подаём с источника генератор с уровнем 0 dB и регулятором выхода источника добиваемся показаний индикатора MIC METER до уровня 0dB БОЛЬШЕ ЭТОТ ДВИЖОК НЕ ТРОГАЕМ !!
затем подаём остальные генераторы с шагом ослабления минус 5 dB ( НЕ трогая движок усиления MIC PC, MIC1, MIC2 ) и контролируем показания Mic meter, и показания на ПАНАДАПТОРЕ при одном тоне генератора эти индикаторы должны показывать одинаковые значения! !
КАЛИБРОВКА ПОКАНИЙ ПО ВХОДАМ MIC1 и MIC2 Аналогична!!!

**Comment by 1972igor** [comment]
>  Что за глупый вопрос ? все блоки ВЫКЛЮЧЕНЫ!!! ПОДАН ТОЛЬКО ГЕНЕРАТОР НА ВХОД ПЕДАТЧИКА!!!! РЕГУЛЯТОР УСИЛЕНИЯ MIC PC НАХОДИЛСЯ В ПОЛОЖЕНИИ 0 dB! Производилось ослабление входного уровня c шагом 5 dB с генератора подаваемого на вход передатчика от 0 dB до минус 35 dB !!!

**Comment by 1972igor** [comment]
Методика проверки индикаторов уровней такова
1 В закладке "PROC" звуковые модули должны быть выключены !!!
2 РЕГУЛЯТОР УСИЛЕНИЯ МИКРОФОН PC устанавливаем в уровень значения 0 дБ (БОЛЬШЕ ЭТОТ ДВИЖОК НЕ ТРОГАЕМ !!!
3 Подаём с источника генератор с уровнем 0 дБ и регулятором выхода источника добиваемся показаний индикатора MIC METER до уровня 0dB БОЛЬШЕ ЭТОТ ДВИЖОК НЕ ТРОГАЕМ !!
4 Подаём остальные генераторы с шагом ослабления минус 5 дБ ( НЕ трогая движок усиления MIC PC, MIC1, MIC2 ) и контролируем показания Mic meter, и показания на ПАНАДАПТОРЕ при одном тоне генератора эти индикаторы должны показывать одинаковые значения! !
КАЛИБРОВКА ПОКАНИЙ ПО ВХОДАМ MIC1 и MIC2 Аналогична!!!

**Comment by 1972igor** [comment]
Методика проверки индикаторов уровней такова
1 В закладке "PROC" звуковые модули должны быть выключены !!!
2 РЕГУЛЯТОР УСИЛЕНИЯ МИКРОФОН PC устанавливаем в уровень значения 0 дБ (БОЛЬШЕ ЭТОТ ДВИЖОК НЕ ТРОГАЕМ !!!
3 Подаём с источника генератор с уровнем 0 дБ и регулятором выхода источника добиваемся показаний индикатора MIC METER до уровня 0dB БОЛЬШЕ ЭТОТ ДВИЖОК НЕ ТРОГАЕМ !!
4 Подаём  генератор с шагом ослабления минус 5 дБ ( НЕ трогая движок усиления MIC PC, MIC1, MIC2 ) и контролируем показания Mic meter, и показания на ПАНАДАПТОРЕ при одном тоне генератора эти индикаторы должны показывать одинаковые значения! !
КАЛИБРОВКА ПОКАНИЙ ПО ВХОДАМ MIC1 и MIC2 Аналогична!!!

**Comment by 1972igor** [comment]
Методика проверки индикаторов уровней такова
1 В закладке "PROC" звуковые модули должны быть выключены !!!
2 РЕГУЛЯТОР УСИЛЕНИЯ МИКРОФОН PC устанавливаем в уровень значения 0 дБ (БОЛЬШЕ ЭТОТ ДВИЖОК НЕ ТРОГАЕМ !!!
3 Подаём с источника генератор с уровнем 0 дБ и регулятором выхода источника добиваемся показаний индикатора MIC METER до уровня 0dB БОЛЬШЕ ЭТОТ ДВИЖОК НЕ ТРОГАЕМ !!
4 Подаём генератор с шагом ослабления минус 5 дБ ( НЕ трогая движок усиления MIC PC, MIC1, MIC2 ) и контролируем показания Mic meter, и показания на ПАНАДАПТОРЕ при одном тоне генератора эти индикаторы должны показывать одинаковые значения! !
ПРОВЕРКА  ПОКАНИЙ ПО ВХОДАМ MIC1 и MIC2 Аналогична!!!

**Comment by 1972igor** [comment]
Методика проверки индикаторов уровней такова
1 В закладке "PROC" звуковые модули должны быть выключены !!!
2 РЕГУЛЯТОР УСИЛЕНИЯ МИКРОФОН PC устанавливаем в уровень значения 0 дБ (БОЛЬШЕ ЭТОТ ДВИЖОК НЕ ТРОГАЕМ !!!
3 Подаём с источника генератор с уровнем 0 дБ и регулятором выхода генератора добиваемся показаний индикатора MIC METER в программе ESDR3 до уровня 0dB БОЛЬШЕ ЭТОТ ДВИЖОК НЕ ТРОГАЕМ !!
4 Подаём генератор с шагом ослабления минус 5 дБ ( НЕ трогая движок усиления MIC PC, MIC1, MIC2 ) и контролируем показания Mic meter, и показания на ПАНАДАПТОРЕ при одном тоне генератора эти индикаторы должны показывать одинаковые значения! !
ПРОВЕРКА ПОКАНИЙ ПО ВХОДАМ MIC1 и MIC2 Аналогична!!!

**Comment by ExpertSDR3** [comment]
Индикатор Mic-метр отображает мощность сигнала в полосе, панорама отображает спектральную плотность амплитуд, разница будет вдвое, что на приведённых скриншотах и показано.
