### ISSUE TITLE
Problem on CW in the macOS ExpertSDR3 version.469

### ISSUE THREAD

**Issue by ct1drb** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#350]
Hello all,

my device is the EED06202100, I am using the ExpertSDR3 0.12.1 alpha, the OS is Mac, my computer is a Mac mini M1.

It seems that this problem only occurs in the macOS version of the ExpertSDR3. When the cw_macro_stops; command is used, when I hit the ESC key for instance, the CW stops to send out, it happens not always but very often.

it is a very annoying problem because I hit several times the ESC key or in other situations that the previous command is used. In the ExpertSDR2 version it does not happen.

Best regards.

CT1DRB/OK8RB
David Quental

**Comment by ExpertSDR3** [comment]
Can you attach a short video demonstrating this problem?

**Comment by ct1drb** [comment]
Hello all,

just to ask you to close my problem because it has been fixed by the programmer of the software and now works well.
Problem was the usage of 2 instructions to quit TRX when hit the ESC key for instance.
Now problem is gone.

Best 73 and tks all.

CT1DRB/OK8RB
David Quental
