### ISSUE TITLE
Transverter MB1

### ISSUE THREAD

**Issue by LA9AKA** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#352]
When selecting the different trasnsverter bands, all show the wrong frequency except band 5. For example the attached photo shows the 23cm band selected, and the radio is showing 17m band.

MB1 serial EED10241600059
ESDR3 0.13.0 alpha
Win10 64 32Gb RAM

73
Hans Christian LA9AKA

![Transverter](https://user-images.githubusercontent.com/96302801/171996628-6a22c59a-39b4-4c8a-a783-2bed87875770.JPG)

**Comment by LA9AKA** [comment]
Also noticed the other bands showing wrong on the spectrum scope.
![Transverter2](https://user-images.githubusercontent.com/96302801/171996971-5a0d69ad-c797-419c-beaf-67495523d3c2.JPG)

**Comment by LA9AKA** [comment]
Also noticed
![InkedTransverter2_LI](https://user-images.githubusercontent.com/96302801/171997002-a2a10bc2-e49f-4cb9-9bb3-926f14cbbdd0.jpg)
 the other bands (except 5 is showing wrong on the spectrum scope.

**Comment by LA9AKA** [comment]
Also noticed the other bands showing wrong band on the spectrum scope (except5). 
![InkedTransverter2_LI](https://user-images.githubusercontent.com/96302801/171997022-9780b58f-c894-44b5-b3d6-6b42ce0592ff.jpg)

**Comment by ExpertSDR3** [comment]
fixed
