### ISSUE TITLE
Total system GUI freeze/stutter at maximum horizontal zoom after tuning.

### ISSUE THREAD

**Issue by williamscody** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#354]
Environment:
Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz, 32GB RAM
Windows 11 Pro, 64-bit, version 21H2, OS Build 22000.675
AMD Radeon 580 Graphics Card (1 DVI monitor and 1 DP monitor connected)
SunSDR2DX, S/N EED06202100503, PCB Revision 1.1, Firmware 78.8
ESDR3 0.13.0 alpha, Build 03062022

Issue:  The entire Windows system GUI freezes, and stutters at a rate of approximately 0.25 Hz when increasing horizontal zoom to 100% after performing a tune operation.

THIS IS THE SAME ISSUE AS #94 which was incorrectly closed by EE.

ESDR3 Settings:
- Application is running in a window (not full screen)
- Application scale: 140%
- Sample rate: 312KHZ
- Horizontal zoom = 0% (zoomed all the way out to see maximum spectrum)
- Graphics API: ANY mode

Steps to recreate:
1) Tune to 40M band
2) Select CW mode
3) Set Drive and Tune levels to Zero
4) Toggle the TUNE button for about 3 seconds
5) Bring horizontal zoom to 100% and witness the issue.  

NOTE:
I tried this in Ubuntu Linux, the the issue did not occur.  I noted that the Linux version does not offer a selection of graphics API's.  This tells me the issue lies in the way ESDR3 app handles "optional" API's.  I would suggest eliminating this "feature" from this build to quickly help isolate this issue.

7/3/22 UPDATE:  Issue remains with build 01072022.

7/10/22 UPDATE:  Issue remains with build 08072022.

9/5/22 UPDATE: Issue remains with build 02092022.

9/15/22 UPDATE:  In build 15092022, the issue no longer occurs if the Graphics API is set to OpenGL.  In DirectX11 and Vulkan, the issue is slightly different.  While the entire system still freezes/stutters as before, the mouse cursor no longer freezes.

This is certainly an improvement.

**Comment by ExpertSDR3** [comment]
This problem exists only on windows OS, it is connected with the implementation of the graphics drivers or with errors inside Qt. We will try to find a solution to this problem by the public version 0.13.

**Comment by ExpertSDR3** [comment]
Fixed
