### ISSUE TITLE
Зависает ESDR3 при клике на кнопку Setup (шестеренка)

### ISSUE THREAD

**Issue by RX4HX2** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#355]
При подключенном SunSDR2 при клике на кнопку Setup (шестеренка) программа ESRD3 зависает, потом закрывается. Если SunSDR2 не подключен, то все нормально. Не уверен, но такое стало появляться, когда установил дополнительно на компьютер предыдущую версию ESDR2. Но после удаления с компьютера ESDR2 зависание не пропало.

**Comment by ExpertSDR3** [comment]
Приложите видео, пожалуйста, после аварийного закрытия приложите файл  backtrace.dump, который расположен в папке с настройками программы. Это поможет в обнаружении проблемы.
Настройки программы расположены:

- Для ОС Windows путь выглядит так: C:/Users/UserName/AppData/Local/Expert Electronics/ExpertSDR3

- Для ОС Linux путь выглядит так: /home/UserName/.config/Expert Electronics/ExpertSDR3

- Для ОС macOS путь выглядит так: /Users/UserName/Library/Preferences/Expert Electronics/ExpertSDR3

**Comment by RX4HX2** [comment]
Файла backtrace.dump нет. Вернее в папке был какой то старый файл, перед запуском я его удалил, после зависания программы он снова не появился. 
На счет видео - а что снимать то? Нажимаю на шестеренку, всплывает окно установок и все - программа сначала зависает и через пару секунд закрывается.
Для информации - эта проблема не только у меня, но как я понял у многих пользователей, кто установил себе на компьютер вместе с ESDR3 и ESDR2.

**Comment by VK6NX** [comment]
Проверено в 0.13 01072022 в W10 и W11 - ничего не зависает, все открывается и закрывается независимо от очередности включения.

Корелляции с папками ESDR2 тоже не замечено на версиях 0.13.

Устанавливать в винде альфу одновременно с предыдущим релизом - не самая хорошая идея. Но если уж устанавливать, то рекомендуется делать это только на абсолютно чистую систему, где обе версии запишут свои установки "набело".

**Comment by RX4HX2** [comment]
Зависает, и как я уже писал, не только у меня. Устанавливалось все на чистую Windows 11. 
Я использую версию ESDR3 скаченную с сайта.

**Comment by VK6NX** [comment]
Ну значит у меня какая-то специальная винда, что 10, что 11. И не падает. И не на "чистой". Чудеса-а-а.  

Ну что ж, коли видео писать не хотите, и дампа нет, то на нет и суда нет, полагаю.

Дождетесь 0.13 и проверите. Авось, все поправится.

**Comment by RX4HX2** [comment]
Да какие чудеса? Я программист, и знаю, что в программировании чудес не бывает!
Нужно не отмахиваться от  пользователей, а все же пытаться помочь!
Нашел сам в чем дело - 
файл 
C:\Users\Alexei\AppData\Local\Application Data\Expert Electronics\ExpertSDR3\108.json

секция
    "Gui": {
        "MainWindow": {
            "ExpandToolbar": true,
            "GuiScale": 6,
            "ScalableWaterfall": false,
            "TxAnalyzerSpectrumMode": true,
            "WaterfallSpeed": 2.3,
            "height": 360,
            **"horizontalMode": false,**

если параметр horizontalMode сменить на true, то зависает, меняешь на false - все работает.

И мой профессиональный совет - только очень плохие программисты свои ошибки на винду списывают!

**Comment by VK6NX** [comment]
Я, Алексей, такой же пользователь, как и вы. И не отмахиваться сюда зашел, а именно, помочь. Смотрю висит кейс открытый месяц почти без движения, дай, думаю проверю, что там на последней альфе. Ну отрепортил, что все проверил и работает. Кто ж знал, что вас так зацепит, наверное было лучше "не мешать".

А так-то, никто и не сомневается в том, что вы программист, причем именно виндузовый, как следует из нашей переписки несколькими годами ранее. Так что вам все карты в руки. И в способностях ваших никто не сомневается - вот, пожалуйста, не прошло и месяца, как вы сами нашли, что дело, оказывается, в драйверах видеокарты.

А видео, в следующий раз запишите. И заодно можно почитать хелп и попробовать данные указать, как просят (на заглавной страничке). Глядишь, не просто так просят, может поможет чем.

**Comment by RX4HX2** [comment]
To VK6NX: я прошу у Вас прощения! Писал на эмоциях, и к Вам это не имеет никакого отношения! Все выше мной написанное относится только к техподдержке, которые, на мой взгляд, весьма "небрежно" относятся к проблемам пользователей.

**Comment by VK6NX** [comment]
Вот это поворот...

А техподдержка-то тут каким боком? 

Ничего, что вы открыли кейс в разделе багрепортов группы тестеров программы ESDR3, которая находится в альфа-режиме? Мы тут, знаете ли, сами себе техподдержка. Сообщаем разработчику о замеченых багах, проверяем "починку" старых и тестируем новые версии. 

Собственно, в описаном выше ключе и следует понимать мои действия - четыре дня назад вышла закрытая альфа 01072022, я проверил на ней наличие бага, который вы зарепортили (как я понимаю из первой альфы 0.13) и отчитался, что с моей точки зрения все пофиксили. Попутно дал совет по поводу папок установок (хотя ЕЕ и говорит, что на последних версиях не должно влиять, но все равно, иногда полезно это учитывать). 

А официальная техподдержка ESDR3, IMHO, будет не ранее, чем появится релиз-кандидат, только разве что ЕЕ вдруг решит по-другому.

**Comment by ExpertSDR3** [comment]
Добрый день, сейчас появился в распоряжении SunSDR2 - проверяю на нём выше описанные баги, пока не обнаружил, нужен Ваш файл настроек и желательно виде демонстрации бага. Прикрепите, пожалуйста, файл настроек и желательно короткое виде на котором видно показано какие действия приводят к багу.

**Comment by RX4HX2** [comment]
Добрый день! Железо у меня самое обычное - Core i5-10500, материнка - Gigabyte H410M S2 V3, видео - GeForce GT 640. 
Пробовал переключать графические API - разницы нет.
Кстати, а что нужно включить в ESDR3, чтобы параметр horizontalMode стал true? Как то я его в свое время включил, а сейчас только ручками могу в файле прописать, включить в программе не получается.

**Comment by ExpertSDR3** [comment]
Переключать режим отображения можно правым кликом по кнопке RX2

**Comment by ExpertSDR3** [comment]
Был исправлен критический баг, который потенциально мог приводить к подобному поведению, исправления будут в версии опубликованной после 25.10.2022

**Comment by R9MA-Serge** [comment]
Начал переход с ESDR2 на ESDR3. Установил ESDR3 1.0.5 beta. И столкнулся с тем же самым, что описал выше Алексей RX4HX. 
При клике на кнопку Settings (шестеренка), ESDR3 зависает и закрывается. Только следует дополнить: закрывается программа только если включены 2 радио и они находятся в горизонтальном расположении. Если одно радио, либо два, но в вертикальном расположении, то все нормально, ничего не закрывается...
Установил версию 1.0.3, глюк повторился.
Графический API перед запуском переключал во все варианты.

Радио: SunSDR2DX EED06202110006
ПО: ExpertSDR3 v.1.0.5 beta, прошивка - 86.8
ОС: Windows 10x64
ПК: Mother: ASUS H110M-C, CPU: Core i7-6700K 4х4,0 GHz, RAM: 16 Gb, Video: NVIDIA GeForce GT 710

Файл backtrace.dump в папке: C:/Users/UserName/AppData/Local/Expert Electronics/ExpertSDR3 отсутствует.
