### ISSUE TITLE
Dev Build V 13 06062022- Headphone and TCI do not stay enabled

### ISSUE THREAD

**Issue by N8SDR007** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#356]
TCI and Audio settings lower control panel are not retained after shutdown and new startup

You most reenable them, when restarting application

![Screenshot 2022-06-10 131653](https://user-images.githubusercontent.com/94698375/173118221-b6f08fd0-3548-4422-89ef-97752250500a.jpg)

**Comment by G4POP** [comment]
The setting is persistent here! SUNSDR 2 DX with e-controller and Log4OM on Win 11 PC

**Comment by N8SDR007** [comment]
> The setting is persistent here! SUNSDR 2 DX with e-controller and Log4OM on Win 11 PC

Terry, are you using PC audio sound card for your playback source or some other option- just trying to nail this down as a couple others also have this from Dev group as well-, I am using the soundcard on Pc out to studio monitors, and every time I start the Dev release 08062022 even in a remote session I must re enable the Headphone Icon on lower control panel and sometimes TCI, but always the sound?

**Comment by G4POP** [comment]
Hi Rick,

I am using the PC soundcard with external speakers and also a headset connected to the SunSDR 2 DX Phones jack

 

SunSDR is connected direct to PC not on the router

 

This was a clean install

 

 

73 de Terry G4POP

Log4OM Developer

Free logging software at https://www.log4om.com/

**Comment by N8SDR007** [comment]
Thanks Terry- video coming of issues

**Comment by N8SDR007** [comment]
THIS ISSUE is Still Present in DEV V3 13 07012022 as well

**Comment by IU4JNR** [comment]
I have the same issue on SunSDR2 DX, it wont to stay on. 
On my SunSDR2 PRO it has a different behaviour: Turning off EESDR, sound card stop working with a message (see pic). Turning EESDR3 on again it have to be re-enabled and it works fine until i turn the rig off.
EESDR 3 0.13.0 Build 08072022 DEV (but is the very last uploaded on Telegram tester group). Win11pro Build 22000, Ryzen7 5800X, DDR4 32Gb, NVME SSD 

![image](https://user-images.githubusercontent.com/94228375/181249294-84231344-c196-43c5-82a2-d38f42b9cc9d.png)

**Comment by N8SDR007** [comment]
Update: Version 02092022 Build 3 13

I have not had this issue with either Soundcard not starting or TCI

Buttons stay on between relaunching - 

Wait for other inputs but seems to be solved

**Comment by IU4JNR** [comment]
build 02092022. I confirm audio TCI now stays on on my rigs too.
