### ISSUE TITLE
ExpertSDR3 0.12.1 Linux x64

### ISSUE THREAD

**Issue by belmont** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#357]
- TX button works but **no signal from handmic or no signal from USB headset mic** 
- **Not possible to select the Mic inputs**
- Remote is not working, the Cloud connection seems to be fine but the **radio screen shows the radio not available also the power on button inactive**

So the "ExpertSDR3 0.12.1 Linux x64" is unusable for linux users unfortunately.  Tested on Linux Mint 20.3 and Ubuntu 20.04

**Comment by danweecc** [comment]
this tracker is actually for EESDR3 and not the older EESDR2.

**Comment by belmont** [comment]
did you read it? i reported these for EESDR3 !!

**Comment by N8SDR007** [comment]
> * TX button works but **no signal from handmic or no signal from USB headset mic**
> * **Not possible to select the Mic inputs**
> * Remote is not working, the Cloud connection seems to be fine but the **radio screen shows the radio not available also the power on button inactive**
> 
> So the "ExpertSDR3 0.12.1 Linux x64" is unusable for linux users unfortunately. Tested on Linux Mint 20.3 and Ubuntu 20.04

**_Regarding Remote_** -There will soon be new version of the Remote Server available and also updated V3 with TX remote option as well when using the EESDR V3 application remotely- just a FYI
