### ISSUE TITLE
Drive power problem

### ISSUE THREAD

**Issue by ON3CQ** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#358]
After we have been able to work almost without problems for 2 hours, a problem arises. The Drive is at 35% is +/- 25w out.  Out of the blue the output power goes to +/- 70W.  Nothing changed were running QSO and problem popped up. I also find in the latest update version that the power spike is more present.

**Comment by N8SDR007** [comment]
Very inconsistent power settings

they seem to vary widely without readjusting the drive slider, you will see occasional spike sometimes 30+ watts from where you are set

Noticing this more on last couple DEV releases 08062022 and prior, and more on SSB then in prior releases, CW has had this issue as well
