### ISSUE TITLE
No audio volume control and ee-coder not recognised

### ISSUE THREAD

**Issue by vk3st** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#359]
SDR3 receiver working fine. When setting the audio output to the Benq monitor or even PC audio system, the dashboard volume control is not functional. Audio out put has to be controlled via the PC sound card.
ee Coder not recognised even when changing ports for connection.
Checked back with SDR2 and all is functioning 100%
System is Windows 10 Pro - version 21H2 with all updates current.
CPU i7@4gHz Intel running Asrock Z97 Extreme with Corsair dual 32gbyte
Always possible I have missed something and will re install and experiment.

**Comment by N8SDR007** [comment]
Which V3 release please?

**Comment by vk3st** [comment]
ExpertSDR3_x64_0.12.1_setup

 

Ian Foster – VK3ST

Ellington Street

Caulfield South 3162

0435 926 361
