### ISSUE TITLE
S meter bug

### ISSUE THREAD

**Issue by uc0a** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#36]
> Иногда исчезает ползунок с метра, лечиться только перезагрузкой.
![MVIMG_20211113_084323](https://user-images.githubusercontent.com/94206958/141601185-cfdcdd90-eb23-4523-ad58-649d2d7cc391.jpg)

**Comment by ExpertSDR3** [comment]
fixed, fixes will be in release 0.10 .
