### ISSUE TITLE
Dev Build V3 13 08062022 Meter not closing on Exit of 2nd RX

### ISSUE THREAD

**Issue by N8SDR007** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#360]
In Dev V3 13 Build 08062022

The new pop out meter function if you open your second reviver option and also enable the Pop pout panel meter when you close the 2ND RX meter is still displayed (it's not active but still displayed)

https://drive.google.com/file/d/16RT2qDHaa7F4VSP5_nA49TD2U-URCcOG/view?usp=sharing

**Comment by ExpertSDR3** [comment]
fixed

**Comment by N8SDR007** [comment]
Thank you!
