### ISSUE TITLE
linux glibc version build issue on the latest 13.0 drop from yesterday.  

### ISSUE THREAD

**Issue by kingsqueak** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#361]
Latest pre-release dropped yesterday not starting on Ubuntu 22.04 LTS current updates.  The last 13.0 build 08062022 runs fine.

ExpertSDR3/lib/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libxkbcommon.so.0)

22.04LTS is glibc 2.35

**Comment by ExpertSDR3** [comment]
fixed
