### ISSUE TITLE
PA select button disappears

### ISSUE THREAD

**Issue by W3FRG** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#367]
I have on two occasions, where my amplifier stopped being keyed.
I checked all settings and found that the "PA" Button was missing.
A PC restart or shut down or a restart of SDR3 did not correct the missing button. I had to completely delete & reinstall SDR3.

If and when this reoccurs, I will take a picture of it and post it here.

Tom W3FRG

**Comment by ExpertSDR3** [comment]
If in the Options, PA tab you set "Save by band", then the state of the PA key can be set from the Band.Manager window. In this case the PA button is not displayed in the main window. If you disable "Save by band" then the global PA button is visible and the key checkboxes are hidden from the Band.Manager.

![image](https://user-images.githubusercontent.com/93903520/177928256-de56a0aa-5530-4f0c-b166-50a4eca52b9d.png)

![image](https://user-images.githubusercontent.com/93903520/177928269-39370527-48c9-4168-942b-045991b15efa.png)
