### ISSUE TITLE
Playback over the air of recording in DEV 13 07012022 Produces more output power then your normal talk

### ISSUE THREAD

**Issue by N8SDR007** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#368]
When playing back a recording -over the air the output power- Gain can produce more power out then available under your normal SSB microphone gain output power

**Comment by 1972igor** [comment]
most likely there are different levels between the microphone and the operation of the tape recorder coming to the input of the transmitter

**Comment by jamesskala** [comment]
I have also experienced this with version 08072022.
