### ISSUE TITLE
Linux - Ubuntu 22.04 possible OpenSSL version issue

### ISSUE THREAD

**Issue by kingsqueak** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#369]
I'm unsure if this is important, but it appears there is an OpenSSL version conflict in the build as the current is OpenSSLv3 lately.

Ubuntu 22.04 and the build ID is 08072022

qt.tlsbackend.ossl: Incompatible version of OpenSSL (built with OpenSSL 1.x, runtime version is >= 3.x)
[2022-07-08 09:26:29.056] [info] supports ssl: false  
qt.network.ssl: The backend "cert-only" does not support QSslKey
qt.network.ssl: Active TLS backend does not support key creation
qt.network.ssl: The backend "cert-only" does not support QSslKey
qt.network.ssl: Active TLS backend does not support key creation
qt.network.ssl: The backend "cert-only" does not support QSslKey
qt.network.ssl: Active TLS backend does not support key creation
qt.network.ssl: The backend "cert-only" does not support QSslKey
qt.network.ssl: Active TLS backend does not support key creation

**Comment by ExpertSDR3** [comment]
Solution   https://linuxpip.org/install-openssl-linux/

**Comment by kingsqueak** [comment]
No, the build tree is using an old OpenSSL version the 1.x, current OpenSSL is OpenSSLv3

**Comment by kingsqueak** [comment]
cesser@Zippy-Ubuntu:~$ openssl version -a
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
built on: Mon Jul  4 11:20:23 2022 UTC
platform: debian-amd64
options:  bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -ffile-prefix-map=/build/openssl-Q8dQt3/openssl-3.0.2=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_TLS_SECURITY_LEVEL=2 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-3"
MODULESDIR: "/usr/lib/x86_64-linux-gnu/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_ia32cap=0x7ed8320b078bffff:0x209c01a9

**Comment by VK6NX** [comment]
https://forum.qt.io/topic/136022/ubuntu-22-04-with-qt-6-3-0-and-openssl/2

**Comment by kingsqueak** [comment]
I'm closing as apparently it is intended to work this way.
