### ISSUE TITLE
E-Coder issue on 2m band

### ISSUE THREAD

**Issue by IU4JNR** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#37]
When using the e-coder on 2 meter and rptr is selected, it currently works as on HF (VFO B changes for split) but on VHF it could be useful to have both RX and TX frequency changes in synch (according to the shift).  
Using the mouse it behaves correctly

https://user-images.githubusercontent.com/94228375/141645293-f4757f97-f934-4c4d-a41b-124fc9abd448.mp4

.

**Comment by ExpertSDR3** [comment]
исправлено, исправления будут в релизе 0.10
