### ISSUE TITLE
Problems about HF Power  : ERS 0.13.0 alpha Build 08072022 and Build 30092022, Sunsdr2 Pro

### ISSUE THREAD

**Issue by f6ctt** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#371]
i began to test the TX mode in ERS 

I have choosen opengl when i start the remote mode on my PC windows 11
but the others choice are OK too.

When i push TX, the level of the microphone is OK  but no HF power, if i move the slide Drive then i continue to speak, the level of the power go up  and it is OK

If i stop TX and push TX again (with the same level of drive) : no power,  if i move down or up the slide, the level of the power is OK

I have the same problem when i push Tune, if i move the slide, the power go up  if i push tune with the maximum position of the slide Tune : i have no power.

The HF power arrive well at the time when i move (up or down) the slides DRIVE or TUNE when i the SUNSDR2 Pro is in TX oper  

Today (with 01072022) i have noted that the HF power is about 2db down than at the radio, (when i work remote by ERS)   
but now, with 08072022, this seem OK on 40m,but on 17m the power is 2 db down, i checked again.  

Other problem :

- The AGC (Off, Norm, Fast) doesn't work. it seem (to me) that the AGC is always Off.

Other comment : 
i put 256 kbit Bitrate and i obtain 75 ko/s upload,  at the radio shack  (0.6 mb/s), the ping is about 30 to 50 ms
the reception responsiveness is excellent, as is the audio quality (receive and transmit)
i have a low speed ADSL (download 4 mb/s upload 0.8 mb/s) at the radio location.

At this time, It's a little bit difficult to do QSO with ERS but it's possible !
it's all for the present time (and maybe some others problems that i have not yet seen) 

PS: i use the Zip file ERS 06062022

![image](https://user-images.githubusercontent.com/100024771/178102372-5ffe7112-7579-41e2-8165-788aa5bbd189.png)

https://user-images.githubusercontent.com/100024771/178110831-aa7b41d3-970e-4e41-bf45-c7864e18e011.mp4

**Comment by ea5ccy** [comment]
I have exactly the same problem with remote transmit power on my SunSDR2 Pro. You have to move the sliding drive portenciometer or the Tune to get power to come out.

**Comment by f6ctt** [comment]
These problems are still present with the 2 last alpha versions 0109 and 0209 on my Sunsdr2 Pro with firmware 79.8
I wait the new firmware for ERS !

**Comment by f6ctt** [comment]
Other problem (Build 08072022)  :
The AGC (Off, Norm, Fast) doesn't work. it seem (to me) that the AGC is always Off.

Now with the version Aplha 0.13.0 Build : 30092022 the AGC (Off, Norm, Fast) works well

NB: The problem HF Power is still present.

**Comment by f6ctt** [comment]
tttt
