### ISSUE TITLE
Monitor output corrupted when using "Mic PC" for input

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#372]
EESDR3 0.13.0 alpha
Build: 08072022
Windows 10 64-bit

Description. When using the EESDR3 monitor function to listen to the microphone input audio, everything sounds corrupted. The waveform looks normal in the audio spectrum monitor (in Settings) and the PC monitor also sounds normal. This problem has been corroborated by at least one other user. To reproduce this problem:-

1. Use Mic PC as input. Select USB, LSB or AM
2. Turn on Monitor function in EESDR3
3. TX and speak into microphone. TX power can be set to 0W.

**Comment by N8SDR007** [comment]
If using Mic2 and external audio does not notice of distortion in monitor- perhaps a QT6 bug in the latest audio features with Windows and QT6

**Comment by danweecc** [comment]
This turns out to be related to the ASIO drivers for the various output devices and its compatibility with Qt.
