### ISSUE TITLE
Reproduceable TX spike in EESDR3

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#373]
EESDR3 0.13.0 alpha
Build: 08072022
Radio: SunSDR2DX
Windows 10 64-bit

A spike appears whenever the TUNE function is used. This can be seen in the initial burst before the carrier settles down. After you use the TUNE function, the first TX also exhibits this spike. To reproduce this:-

1. Set mode to CW
2. Set Tune power to something more than 0%, say 50%
3. Click on the TUNE to enable carrier. You may have to do this a few times while observing the spectrum display.
4. You should see something like the below imagine showing the spike
5. After disabling the TUNE, you can click on TX to enable TX and you should see the spike on the first time you do this. Thereafter it should not show up.

![image](https://user-images.githubusercontent.com/13930571/178145747-8a600b7a-39aa-4cde-8aee-3ff5052c4c7d.png)

**Comment by sm6usu** [comment]
Is this problem on all screens 39kHz and up? 
sm6usu Svante

**Comment by danweecc** [comment]
It appears to be happening on all bandwidths from 39kHz to 312kHz but it is more easily visible on higher bandwidths.

**Comment by N8SDR007** [comment]
Also see this on 
Dev Build 08072022 with 2DX and Windows 11

**Comment by danweecc** [comment]
Just confirmed that this happens ONLY in CW mode.

**Comment by LA3QMA** [comment]
Tested this today and can confirm the findings. Have not tried to measure/record anything going out on RF

**Comment by danweecc** [comment]
Problem still present in EESDR3 0.13.0 build 01092022.
