### ISSUE TITLE
Suggestion for input

### ISSUE THREAD

**Issue by G4POP** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#374]
For third party software perhaps provide a line in for soundcards/VAC

Something like my image below perhaps?

![Line in suggestion](https://user-images.githubusercontent.com/101397850/178296266-9a475c92-b95c-4d68-86ba-9612158bf160.jpg)

**Comment by VK6NX** [comment]
Move this request to proper section, please: https://github.com/ExpertSDR3/ExpertSDR3-SUGGESTIONS

**Comment by N8SDR007** [comment]
In a way this is already there it is / can be achieved when you select PC MIC and then below in (Headphone) icon lower right select the VAC input, I do this for a few programs that require me using Virtual audio- the other option is using RigSYNC

![Screenshot 2022-08-17 073237](https://user-images.githubusercontent.com/94698375/185108317-82b847e3-3649-4ac5-8af8-12dccf344764.jpg)
