### ISSUE TITLE
Sound card - stop working message

### ISSUE THREAD

**Issue by IZ0JNY** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#375]
SunSDR2 PRO - EED05422100908
ExpertSDR3 0.13.0 alpha  - BUILD: 08072022
OS: Windows 11
i7-8650U CPU @ 1.90GHz, 4 cores, 8Gb RAM, 256SSD. DELL notebook with integrated sound card. 

Description: from time to time the pc sound card (no E-coder connected) stop working; the audio icon on the bottom bar became inactive, and audio stop working. Activating again the audio (headphone icon on the bottom bar) the audio starts again. But some time together with this error the SunSDR2 PRO disconnect and I have to re switch on again. 
Displayed message (see attachment): **Sound card not responding and was stopped!**  never saw this message with all previous versions of ESDR3. 

Correlations: occours randomly, some time also SunSDR disconnect from ESDR, not always. 
 
Reproduction steps: occours randomly, after 30/60 minutes of work. 
![be43778a-b5bf-459d-b8e0-eb62381364b6](https://user-images.githubusercontent.com/100196038/178529360-001a2aa4-afce-45f2-80d1-ee42848c307c.jpg)

**Comment by ExpertSDR3** [comment]
Fixed.
