### ISSUE TITLE
Missing file extension Export/Import Stations list under Linux

### ISSUE THREAD

**Issue by hb9bxr** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#376]
SunSDR2 DX - EED06421900061
ExpertSDR3 0.12.1 alpha - Build 05032022
OS: Linux Mint 20.3 Debian - Desktop

To export or import 'Stations' memory manually, the file extension is missing and not being saved. On import there are no files to see. Under Windows the extension for 'Stations' is *.sbj but not under Linux. Adding extension *.sbj to the exported file manually, it can be imported. This seems to be a bug under Linux.

![grafik](https://user-images.githubusercontent.com/109674087/179996466-dddcddfc-50a9-415c-8554-9c049a652d90.png)
Arrow up/down für Export/Import 'Stations' memory

![grafik](https://user-images.githubusercontent.com/109674087/179996687-02f33342-e399-4829-acbf-459477a05765.png)
Export/Import shows 'Stations' only

**Comment by ExpertSDR3** [comment]
Fixed.
