### ISSUE TITLE
Stations memory deletes top entry only

### ISSUE THREAD

**Issue by hb9bxr** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#377]
SunSDR2 DX - EED06421900061
ExpertSDR3 0.12.1 alpha - Build 05032022
OS: Linux Mint 20.3 Debian - Desktop

After adding entries to the 'Stations' list, the selected entry below the first entry cannot be deleted. Instead it deletes always the top entry from the total list!
On all entries it marks the stations with '1.'. Should it not be counted from 1 to n?
The only way for now is to edit the exported files manually by hand.
I would like to have different memory files to import for Broadcast, Ham-Radio HF and VHF.

**Comment by VK6NX** [comment]
Pls test under Ubuntu. Mint is not officially supported.

**Comment by hb9bxr** [comment]
Which Ubuntu version to take? Does it not show the above error under Ubuntu???

**Comment by hb9bxr** [comment]
So, installed latest LTS Ubuntu 22 on VBox for testing with ExpertSDR3. You are right it works under Ubuntu and Windows 11 but not with Mint. Thanks.
