### ISSUE TITLE
LPF/HPF for VHF (100 MHz)

### ISSUE THREAD

**Issue by hb9bxr** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#378]
SunSDR2 DX - EED06421900061
ExpertSDR3 0.12.1 alpha - Build 05032022
OS: Linux Mint 20.3 Debian - Desktop

Being on HF 29MHz on RX1 there is a strong broadcast hf AM-signal from Damascus Radio to heard on RX2 on 144.850MHz with S9+20. Any settings on ExpertSDR3 to eliminate this strong out-of-band signals? Happens only if RX1 and RX2 are active.

**Comment by hb9bxr** [comment]
Additional: Lots of BC-Stations in AM to heard on VHF-Band! Cannot use VHF for QSO on dual band RX1/RX2!

**Comment by hb9bxr** [comment]
Update:
- Out-of-band stations on VHF very strong:
        RX1 Only on HF HAM-Bands!!!
        RX2 VHF out-of-band broadcast stations very strong S9+40!
    Reverse:
        RX2 Only on HF HAM-Bands!!!
        RX1 VHF - no broadcast stations out-of-band to hear! Clean

**Comment by rvolchkov** [comment]
1. It's not a software question.
2. It's explained in FAQ, please carefully read the ESSENTIALS section - https://eesdr.com/en/faq-en - Q#6
