### ISSUE TITLE
RPTR Shift should be active on NFM only!

### ISSUE THREAD

**Issue by hb9bxr** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#379]
SunSDR2 DX - EED06421900061
ExpertSDR3 0.12.1 alpha - Build 05032022
OS: Linux Mint 20.3 Debian - Desktop

If RPTR with Shift in NFM-Mode (10m FM Repeater -100KHz) is activated, it is activated in all other modes as well, but RPTR does not show up in menu to be deactivated.
RPTR function needs to be deactivated for all modes expect on NFM. Otherwise Sift-Frequency becomes active using RIT in CW or SSB!

**Comment by ExpertSDR3** [comment]
Fixed
