### ISSUE TITLE
Некорректная индикация тока потребления  (sunsdr2 не про)

### ISSUE THREAD

**Issue by c0nsul** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#38]
Показывает 655,35

Я знаю что он не умеет и не должен. Но от версии к версии баг имеет место быть, уже все глаза намазолил :)

![Clip2Net Menu_211113214405](https://user-images.githubusercontent.com/3913429/141655558-6e3213b8-b5d2-4423-b81b-03c7d4aa93bc.jpeg)

**Comment by ExpertSDR3** [comment]
Индикатор тока потребления в SunSDR2 отсутствует, в релизе 0.10 будет убран индикатор из пользовательского интерфейса
