### ISSUE TITLE
RPTR 10m VFO2 active in last mode

### ISSUE THREAD

**Issue by hb9bxr** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#380]
SunSDR2 DX - EED06421900061
ExpertSDR3 0.12.1 alpha - Build 05032022
OS: Linux Mint 20.3 Debian - Desktop

Under Linux and Windows: If RPTR is set on 10m NFM to 'ON', change the mode to SSB or CW. Then change the band. STOP ExpertSDR3.
Then START ExpertSDR3 again. It starts on the last HF-Band set. Then go back to 10m. It shows the last mode set in SSB/CW on 10m. TX VFO2 is always active, only on the last mode set before ExpertSDR3 was stopped. All other modes, except NFM, shows VFO1 TX! This happens every time because I have RPTR (-100KHz) most of the time ON for 10m NFM repeaters.

**Comment by ExpertSDR3** [comment]
Fixed
