### ISSUE TITLE
Unable to get TX back

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#385]
EESDR3 0.13.0 build 08072022
Windows 10 64-bit
SunSDR2DX

To reproduce this problem:-
1. Set radio VFO1 to any valid frequency, and to non-split mode.
2. Set VFO2 to a valid frequency in the same band
3. Select split mode (TX on VFO2)
4. Change VFO2 frequency to out of band frequency
5. You should see the red TX light for VFO2 go out
6. But you cannot select TX on VFO1 now even though VFO1 is still in a valid TX frequency

This has been confirmed by others.

**Comment by ExpertSDR3** [comment]
Fixed
