### ISSUE TITLE
No response to sample rate selection at bottom left hand corner of ExpertSDR3 0.13.0 alpha with my SunSDR2DX

### ISSUE THREAD

**Issue by KC5SW** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#386]
The only sample rate that works is 39kHz.  Whenever any other is selected the pan adapter display immediately goes crazy and becomes unusable.

**Comment by N8SDR007** [comment]
Please list your PC specs,

processor, video card and resolution, ram, What operating system and the build number

**Comment by N8SDR007** [comment]
Copied from the EE Forum under this topic: 

with Link to Video taken by Rob showing the issue:

<html>
<body>


lz2aov wrote:Hi AllI did a Video and put the link here so anyone can see SORRY it's a not brill just done on my phone but you get what it's showing .Version 3RobRobwould you and Sam please open a GitHub issue tracker for this.please list as much as possible onPC specsHow you have the radio connected (direct /Switch/Router)As much detail as you can please-
--


<table style="max-width: 100%; background-color: rgb(255, 255, 255); border-collapse: collapse; border-spacing: 0px; padding: 0px; width: 1241.53px; margin: 0px; font-family: Arial, Helvetica, sans-serif; font-size: 14px; line-height: 20px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><thead><tr class="ksth" style="background-color: rgb(115, 115, 115); color: rgb(255, 255, 255); font-family: Arial, Helvetica, sans-serif;"><th colspan="2" style="font-family: Arial, Helvetica, sans-serif; font-size: 14px; line-height: 20px; padding: 3px 5px; text-align: center;">
</body>
</html>lz2aov wrote:
Hi All
I did a Video and put the link here so anyone can see SORRY it's a not brill just done on my phone but you get what it's showing .

[Version 3](http://photos.app.goo.gl/xy7V96aLhJJdf7fs9)

Rob

Rob

would you and Sam please open a GitHub issue tracker for this.

please list as much as possible on
PC specs
How you have the radio connected (direct /Switch/Router)
As much detail as you can please-

**Comment by rvolchkov** [comment]
Похоже, у некоторых пользователей возникают проблемы с частотой дискретизации выше 39. Они видят то, что Роб показывает на видео. Это странный хлопающий звук и сильный прыжок спектра, который происходит везде, где они работают. 
У Роба было это с V3 12, у Сэма, кажется, с 12, а теперь и с 13.
@ExpertSDR3

**Comment by KC5SW** [comment]
I found a solution to the problem.
Once I upgrade the firmware on my SunSDR2dx the ExpertSDR3 software works perfectly.
I no longer have a problem with noise in the sample rate.

Thanks,
KC5SW

**Comment by KC5SW** [comment]
This ticket may be closed as PROBLEM SOLVED!
