### ISSUE TITLE
Audio from PC soundcard does not mute when I transmit from MIC 2 using ExpertSDR3 0.13.0 alpha

### ISSUE THREAD

**Issue by KC5SW** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#387]
I use MIC to Transmit on my SunSDR2dx. The audio I am transmitting continues to come through the speakers connected to my PC running the ExpertSDR3 software. I can only use the phone jack on the SunSDR2dx for listening.

**Comment by N8SDR007** [comment]
You have Monitor turn on in either 1 or two places

1) you have monitor on in the V3 13 application
2) In windows (I am assuming since you did not say what O/S) you have option selected Monitor under soundcard settings for the MIC input

**Comment by KC5SW** [comment]
I found the source of the problem.
Firmware update solved all rhe problems.
