### ISSUE TITLE
V3 13 08072022 POP out Meter not displaying See possible fix below 

### ISSUE THREAD

**Issue by N8SDR007** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#388]
Those of you who are not seeing the POP out meters after selecting the Show s Meter option on V3 13 08072022

Please report the following

Edition of Windows and Version/Build   
Video card -
Video resolution
Monitor size 
Refresh rate

**_These items may help_**

**Comment by sm6usu** [comment]
Analog mic meter gone. But still in rx 2
Windows 10
I7 11370 H
Navidia geforce rtx 3070 Laptop
Ext, screen 27 inch hdr

**Comment by N8SDR007** [comment]
If it's still showing up for rx2 then your RX1 is just hidden somewhere most likely

When it doesn't show up it doesn't show up for any of them rx1 or rx2

⁣Get BlueMail for Android ​

On Aug 16, 2022, 9:10 AM, at 9:10 AM, sm6usu ***@***.***> wrote:
>Analog mic meter gone. But still in rx 2
>Windows 10
>I7 11370 H
>Navidia geforce rtx 3070 Laptop
>Ext, screen 27 inch hdr
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/issues/388#issuecomment-1216617909
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by sm6usu** [comment]
Ok But I have tried to find it but no luck. I still think it is not working
how it is supposed to work if it gets hidden somewhere.😕
sm6usu Svante ps. (Have installed again with no luck)

Den tis 16 aug. 2022 kl 15:34 skrev Rick N8SDR ***@***.***>:

> If it's still showing up for rx2 then your RX1 is just hidden somewhere
> most likely
>
> When it doesn't show up it doesn't show up for any of them rx1 or rx2
>
> ⁣Get BlueMail for Android ​
>

**Comment by N8SDR007** [comment]
I modified a script file that Eberhard, DK8JV wrote

You'll need to download it, unzip right click and run as administrator, you must have EESDR v3 13 running and the Show S meter selected, while you run this- Please let me know if this allows the S Meter to show up
[Show-S-Meter.zip](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/files/9352696/Show-S-Meter.zip)
-

**Comment by N8SDR007** [comment]
[Show-S-Meter1.zip](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/files/9352746/Show-S-Meter1.zip)

I think this has the size very close to what the default was by EESDR perhaps they can comment, I set meter size to 300X200

Again, you need to have V3 13 08072022 Running and you must have the box check for -Show S Meter - while running this

download the file -save it unzip it (you can in win 10/11 right click to uncompress it) then right click the EXE file and run as administrator - it should allow the S meter to be shown, you only need to do this once after wards it should appear wherever you have moved it to. upon restarting V3 13

**Comment by sm6usu** [comment]
Hallo again and thank you. Yes it works👍😊 But Windows Virus program
didnt like it. But I will see if it is still there tomorrow. If the virus
program scans and find it. I dont know. Anyway Thank you for your help.
Regards sm6usu Svante

Den tis 16 aug. 2022 kl 18:19 skrev Rick N8SDR ***@***.***>:

**Comment by sm6usu** [comment]
Hallo Rick. Now I have tested and it is still there and working perfekt.
Have restarted with the meter on and of and it always comes up when I want
it to do that. Can not be better.
Thank you very much.
Very best de sm6usu Svante

Den tis 16 aug. 2022 kl 19:58 skrev Rick N8SDR ***@***.***>:

> You should only have to run it that one time if you close it down and
> restart the application v3 13 the meter should show up let me know if you
> can try that I'd appreciate it. Most AV programs won't like it because it's
> an executable file. But like I said you should only have to run it one time
>
> ⁣Get BlueMail for Android ​
>

**Comment by N8SDR007** [comment]
Great to know 

Thank you much for the updated response

 

Rick

**Comment by jmweathe** [comment]
No analog meter on one computer, but works fine on my other one. Both are running Windows 11 Pro 22h2. 
The one that the meter works on has a Nvidia Geforce GTX 750 TI
29 inch monitor , 1920 x 1080 with 60 hz refresh
Intel Core I5-9600

The one that the meter doesnt work has a Nvidia Geforce GTX 1650 Super
32 curved monitor, 2560 x 1440 with 120hz refresh
Intel Core I7 11700
I have reduced the display resolution to 1920 x 1280 and 60 hz and still does not work.

**Comment by N8SDR007** [comment]
Did you try the file mentioned in this as possible fix.. look for the reply regarding zip file and follow those instructions 

⁣Get BlueMail for Android ​

On Aug 17, 2022, 11:56 AM, at 11:56 AM, jmweathe ***@***.***> wrote:
>No analog meter on one computer, but works fine on my other one. Both
>are running Windows 11 Pro 22h2. 
>The one that the meter works on has a Nvidia Geforce GTX 750 TI
>29 inch monitor , 1920 x 1080 with 60 hz refresh
>Intel Core I5-9600
>
>The one that the meter doesnt work has a Nvidia Geforce GTX 1650 Super
>32 curved monitor, 2560 x 1440 with 120hz refresh
>Intel Core I7 11700
>I have reduced the display resolution to 1920 x 1280 and 60 hz and
>still does not work.
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/issues/388#issuecomment-1218210137
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by jmweathe** [comment]
Yes I tried. Windows doesn’t like it and wont let me download it.

Sent from Mail for Windows

**Comment by N8SDR007** [comment]
Well I can't tell you it is safe file.
Everyone that's running this has success you can create your unscript file than needed items are listed above in a post if you're comfortable in doing so and know how nothing's changed in what was written there except for the fact I packaged it made it in exe file

⁣Get BlueMail for Android ​

On Aug 17, 2022, 12:58 PM, at 12:58 PM, jmweathe ***@***.***> wrote:
>Yes I tried. Windows doesn’t like it and wont let me download it.
>
>Sent from Mail for Windows
>
>From: Rick N8SDR
>Sent: Wednesday, August 17, 2022 11:18 AM
>To: ExpertSDR3/ExpertSDR3-BUG-TRACKER
>Cc: jmweathe; Comment
>Subject: Re: [ExpertSDR3/ExpertSDR3-BUG-TRACKER] V3 13 08072022 POP out
>Meternot displaying See possible fix below (Issue #388)
>
>Did you try the file mentioned in this as possible fix.. look for the
>reply regarding zip file and follow those instructions 
>
>⁣Get BlueMail for Android ​
>
>On Aug 17, 2022, 11:56 AM, at 11:56 AM, jmweathe ***@***.***> wrote:
>>No analog meter on one computer, but works fine on my other one. Both
>>are running Windows 11 Pro 22h2. 
>>The one that the meter works on has a Nvidia Geforce GTX 750 TI
>>29 inch monitor , 1920 x 1080 with 60 hz refresh
>>Intel Core I5-9600
>>
>>The one that the meter doesnt work has a Nvidia Geforce GTX 1650
>Super
>>32 curved monitor, 2560 x 1440 with 120hz refresh
>>Intel Core I7 11700
>>I have reduced the display resolution to 1920 x 1280 and 60 hz and
>>still does not work.
>>
>>
>>-- 
>>Reply to this email directly or view it on GitHub:
>>https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/issues/388#issuecomment-1218210137
>>You are receiving this because you authored the thread.
>>
>>Message ID:
>***@***.***>
>
>—
>Reply to this email directly, view it on GitHub, or unsubscribe.
>You are receiving this because you commented.Message ID: ***@***.***>
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/issues/388#issuecomment-1218274569
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by sm6usu** [comment]
Hallo again Rick The analog s-meter from you dissapear from me yesterday after working excellent for a couple of days. But I installed it again so all good
Regards sm6usu Svante

**Comment by sante66** [comment]
Hello,
thank to the N8SDR007's zip file, I've fixed the issue.

Lenovo Legion 5
AMD Ryzen 7 6800H with Radeon Graphics 
NVIDIA GeForce RTX 3060 Laptop GPU
Windows 11Pro
Version : 22H2
build : 22621.2283

ExpertSDR3
Version : 1.0.4 beta
Build : 24042023

Regards,
Sante
