### ISSUE TITLE
Start and stop remote window

### ISSUE THREAD

**Issue by sm6usu** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#390]
Restart remote window does not work
![ExpertSDR3 SunSDR2DX EED06202100558 (Remote) 2022-08-16 15_54_58](https://user-images.githubusercontent.com/101463570/184898571-a721b365-978d-4a04-947d-142db7bad163.png)
![ExpertSDR3 SunSDR2DX EED06202100558 (Remote) 2022-08-16 15_55_27](https://user-images.githubusercontent.com/101463570/184898613-5462990e-77b5-4fb6-ac68-09981ef2f3cc.png)

**Comment by HB9BMR** [comment]
The start button becomes active for a short time before the connection is established completely.
If you try to start the program during this time - the data stream will not start.
SDR3 sill hang. You have to close SDR3 and restart.

And then you have to wait until ping in the bottom line shows a number greater than 0, zero ms
Only then hit the start button and it will work.

It is a bug in the new starter 20220606 together with latest SDR3
The start button should only become active when connection is fully established and this is the case when ping shows a number other than 0

73, Lorenz, HB9BMR

**Comment by sm6usu** [comment]
Thank you I will retry👍

Den tis 16 aug. 2022 kl 17:51 skrev HB9BMR ***@***.***>:
