### ISSUE TITLE
Transverter function not working: V3 release 08072022

### ISSUE THREAD

**Issue by LA9AKA** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#391]
I am using a new Q5 transverter with common IF, it works FB on my Flex. it is connected to the XVTR port on the radio. 

1. No RX. 
2. The TX and Tune buttons are greyed out. 
3. The band manager says Band3 instead of 23cm.

MB1 serial EED10241600059
ESDR3 0.13.0 alpha 08072022
Win10 64 32Gb RAM

73
Hans Christian LA9AKA

![Transverter3new](https://user-images.githubusercontent.com/96302801/185199817-05200a09-0c69-4885-b227-735784bde644.JPG)

![Transverternew2](https://user-images.githubusercontent.com/96302801/185199783-1b314d6d-d234-4e53-8501-5af1542d3e0d.JPG)

![TransverterNew1](https://user-images.githubusercontent.com/96302801/185199758-ea44d4d5-a361-4e1c-addb-18b43143d8f6.JPG)

**Comment by N8SDR007** [comment]
This also applies to the 2DX as well

In previous DEV release before 08072022 2DX had TX/Tune available
 Not so now in DEV 08072022 or public release of 08072022

AS Hans posted above for 2DX models as well-

Hans perhaps change title "Transverter not working: V3 release 08072022"

**Comment by rvolchkov** [comment]
@ExpertSDR3 please take a look at this report.

**Comment by LA9AKA** [comment]
TX and tune buttons still greyed out on my MB1. 

![image](https://user-images.githubusercontent.com/96302801/189158989-718d6a85-6f44-443c-a48b-9aa5ce8dcb91.jpeg)

**Comment by LA9AKA** [comment]
Something is messed up here. I am also able to make it transmit on Band1. To be able to transmit on Band3 I have to have TX enabled on Band1. I have yet to try a real transverter to see if something is actually being transmitted or received. I have my doubts because last time I tried I could see no change in noise floor when turning on my 23cm transverter.

**Comment by LA9AKA** [comment]
![Trans1](https://user-images.githubusercontent.com/96302801/189295183-d119cbb5-7274-485c-b5f1-af636a587cf7.JPG)

When only band 3 is enabled TX and Tune buttons are greyed out.

**Comment by LA9AKA** [comment]
![trans2](https://user-images.githubusercontent.com/96302801/189295392-91716ae2-da83-4ba7-ba8e-3602779dc6db.JPG)

But when enabling TX on Band1, TX and Tune buttons on Band3 is not greyed out anymore.

**Comment by LA9AKA** [comment]
The PA PTT does not work either, for band 3 at least. After a brief test with my 23cm transverter there is still no RX or TX on my MB1 transverter port.

**Comment by LA9AKA** [comment]
I also find it confusing labeling the MB1 RX/TX antenna ADC/DAC when it's the XVTR port that's been used.

**Comment by LA9AKA** [comment]
So I was recently told by Roman that the XVTR port is not yet in use on the MB1. I don't have any split IF transverters so this sucks big time for me.
