### ISSUE TITLE
Remote transmit with MB1 ver 13 alpha

### ISSUE THREAD

**Issue by HB9FAR** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#392]
Operating remote with ERS on MB1 everything is working, but no RF out

**Comment by W3FRG** [comment]
Had the same issue on SDR2DX, the Headset Icon, lower right of the screen, needs to be activated.
That was found out from Rick N8SDR and a lot of tries, Hi.

GL Tom W3FRG

**Comment by HB9FAR** [comment]
Icon activated..full green..modulation perfect on monitor..but no rf out on all modes and tune

**Comment by ea5ccy** [comment]
I have the same problem with the remote on the SunSDR2 Pro. It only gets RF power if after activating TX you move the potentiometer of the driver left or right. You have to do this every time you push TX.
