### ISSUE TITLE
AM output low in 013.0 alpha SunSDR 2 Pro

### ISSUE THREAD

**Issue by PE1BIW** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#394]
In version 0.12 AM output was at least 10 Watts carrier.
In 0.13.0 alpha this is only around 3 Watts max.
It should be at least 5 Watts? (20 Watts PEP divided by 4)?)
firmware 78.8
![AM in 0 13](https://user-images.githubusercontent.com/106540497/185787953-00deaba4-f349-4ed7-a353-d0bf3ffa2954.jpg)

**Comment by PE1BIW** [comment]
Same issue with build 02092022 and firmware 79.8

**Comment by ExpertSDR3** [comment]
Fixed
