### ISSUE TITLE
looks as radio is transmiiting rtty while in reception after using another software

### ISSUE THREAD

**Issue by ON4ASG** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#396]
Hi,
A couple of days installes version 13.0 DEV.
I have a strange issue, radio is in reception. As long as I don't touch anything stays ok.
As soon as I try to use another window radio behaves in a strange way.

It looks as it is transmitting rtty, mark and space in waterfall, though shows S-meter.
Only way to get out is tab the TX button 2 times, so radio goes to transmit and back to receive.
Test was done in CW mode on 30m band

grts,

Hans
ON4ASG

**Comment by ExpertSDR3** [comment]
Can you attach a video demonstrating the problem?

**Comment by ON4ASG** [comment]
Hi ExpertSDR3 experts,I have re-updated the firmware and now everything is ok. Using firmware 78.8 and Sunsdr2Pro: EED05351600237 - ExpertSDR3 0.13.0 Alpha Alk working fine now...in case that the events repeat I will keep you informed.Thanks for fast action73HansON4ASGVerzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: EE ***@***.***> Datum: 26/08/2022  08:24  (GMT+01:00) Aan: ExpertSDR3/ExpertSDR3-BUG-TRACKER ***@***.***> Cc: ON4ASG ***@***.***>, Author ***@***.***> Onderwerp: Re: [ExpertSDR3/ExpertSDR3-BUG-TRACKER] looks as radio is transmiiting rtty while in reception after using another software (Issue #396) 
Can you attach a video demonstrating the problem?
