### ISSUE TITLE
Weak CW signal audio issue 

### ISSUE THREAD

**Issue by hb9bun** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#397]
SunSDR2DX. Windows 10
ESDR3 0.13.0 alpha, Build 08072022

I am testing this weekend a Yaesu FTDX 10 in comparison with the SunSDR2 DX with ESDR3. 

When comparing the RX I found that with CW signals that are more than 10 dB above the noise, there is no big difference. But weak CW signals nearer to the noise level are much clearer and better to read on the Yaesu, sure the traditional 300 Hz ZF roofing filter makes a little difference.
 
Anyway since a while I had the feeling that I can see weak CW signals on the SunSDR very clear on the Scope, but I do not hear copy them that well. Filter at 250 Hz. 

Having seen this difference between Yaesu and SunSDR I switched the RX Equalizer of the SunSDR ON and making 750 Hz +10 dB or more, the audio is much immediately much better to copy. Still not fully to the level of the Yaesu, but much nearer. 

Doing the same comparison using ESDR2 instead of ESDR3 (not as comprehensive) the weak signals' audio is much better to copy and there is practically no no effect of the ESDR2 equalizer on the CW reception. 

Is this only with me? 

73, Peter

**Comment by N8SDR007** [comment]
Actually, I think it's not only CW, but all modes

from what I have noticed, the last couple releases seem to have slightly less RX sensitivity. I would agree this seems to be more noticeable on CW.

**Comment by hb9bun** [comment]
Analyzing it more in detail we (thanks  HB9JND) found that AGC kicks in a bit too early and reduces the volume of weak signals only a couple of dBs above noise. This is different to ESDR2! It would be good if it kicked about 2 S-Level higher.

**Comment by N8SDR007** [comment]
I would agree
