### ISSUE TITLE
EESDR3 CW keying via TCI

### ISSUE THREAD

**Issue by VE3EY** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#399]
The character spacing while keying CW messages from 5M contest does not sound right in EESDR3. It sounds as if the letter spacing is way too short. No issues when keying from the paddle. 

This issue is evident from both EESDR3 v0.12 and v0.13.   The CW keying via TCI web sockets of EESDR2 is correct.

I contacted the author of 5M contest and he believes this is something that needs to be addressed within EESDR3 CW module.

Rig:  SunSDR2DX
OS: Windows 10 Pro 64 bit  Build 19044
RAM: 16Gb
CPU:  AMD Ryzen 5 3600 - 6 core
Graphics:   Nvidia GeForce GTX 960 w/2Gb of onboard RAM
5M contest version 8.0.7 Alpha 40

The attached zip file has a short MP3 audio clip demonstrating the CW keying audio via TCI. 

[eesdr3.zip](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/files/9456770/eesdr3.zip)

**Comment by NickL12345** [comment]
Some updates on this issue:
I was trying different things and I found out that by reducing Macros Delay setting within "Break.in" option from 30ms to 10ms, CW macros keying from 5M improved quite a lot. It sounded normal as far as I could tell. I was using 5M contest in some local contests and was quite happy with it.

Today, however I upgraded EESDR3 to V3 13 02092022 along with radio firmware to 79.8 and I discovered a new problem with 5m contest CW macros.
1. Any CW macro containing '>' or '<' (CW speed up and CW speed down) is ignored by EESDR3. At the first occurrence of such character, CW transmission stops and radio will remain in TX mode indefinitely until you either manually click on TX button or hit esc key to bring radio back to receive.
2. Messages such as "NR" or "QSL" would result in a brief silence at the end followed by a audio crackle pop and then radio would return to RX
3. Message such as "~[CALL]?" works fine. No audio artifacts and radio would return back to RX normally.
