### ISSUE TITLE
Настройка панелью с зумом

### ISSUE THREAD

**Issue by rvolchkov** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#4]
SunSDR2 DX
0.10
Windows 10

По прежнему не работает прокрутка панорамы влево/вправо за границы экрана панелью энкодера при зуме.

**Comment by ExpertSDR3** [comment]
В следующей версии 0.11 будет сделано, что бы курсор ZOOM следовал за фильтром VFOA если управление осуществляется из E-Coder или E-Coder2
