### ISSUE TITLE
incorrect S meters readings of the transmitter output power on all bands

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#400]
Обнаружил такую не принятую вещь стрелочный S-meters режим TX НЕПРАВИЛЬНО информирует пользователя о мощности излучения Измерения проводились на эквиваленте , приборы BK-7-9,MFJ 826B , направленный ответвитель датчик мощности NRP Z51 ROHDE&SCHWARC ITL
I found such an unacceptable thing the switch S-meters TX mode INCORRECTLY informs the user about the radiation power Measurements were carried out on the equivalent, BK-7-9 devices,MFJ 826B, directional coupler power sensor NRP Z51 ROHDE&SCHWARC ITL
![показания мощности](https://user-images.githubusercontent.com/93991940/187859887-6059bcdc-fe5c-4053-9e0d-7e21297a8ea2.jpg)

**Comment by ExpertSDR3** [comment]
Исправлено, исправления появятся в публичной версии 1.0.0 beta

**Comment by 1972igor** [comment]
спасибо!
