### ISSUE TITLE
ZOOM IF CHANGE 100% TO OTHER ESPR3 CLOSE

### ISSUE THREAD

**Issue by py5hot** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#405]
radio MB1..
ESPR3 0.13.0 ...02/09/2022

The default screm on espr3 is 100%, if you try change to any other 110% to max 140% ESPR3 CLOSE

**Comment by LA9AKA** [comment]
I can confirm this behavior. The software shuts down when zoom level is changed. 

MB1 serial EED10241600059
ESDR3 0.13.0 02092022
Win10 64 32Gb RAM

73
Hans Christian LA9AKA

**Comment by danweecc** [comment]
Confirmed on Windows 11 64-bit. Nvidia RTX3090 using Vulcan.

**Comment by 1972igor** [comment]
absolutely right ! There is such a problem!

**Comment by jamesskala** [comment]
Confirmed Win11Pro Nvidia GTX 1060p using  OpenGL

**Comment by Sergey-R5AU** [comment]
EE team confirmed this issue

**Comment by ExpertSDR3** [comment]
fixed
