### ISSUE TITLE
Bad audio in 13

### ISSUE THREAD

**Issue by dl7nb** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#407]
in 12.1 alpha everything works as expected.
in 13.0 alpha I get distorded audio. SSB is very bad and FT8 does not work at all.
It sounds and looks as if the HF is overloaded; too much signal...
Any help?
73 Wolfgang, dl7nb

**Comment by SM0MDG** [comment]
Is that local or via remote? I noticed that when accessing via remote AGC isn't active.

**Comment by dl7nb** [comment]
Problem solved!
Just installed the new firmware and everything is quite good!
73 de Wolfgang, dl7nb
