### ISSUE TITLE
ESDR3 Alfa 0.13.0 build 02092022

### ISSUE THREAD

**Issue by Sergey-R5AU** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#413]
Tranciever:
SunSDR2 DX, Firmware 79.8
( !!! actual version is 79.8 ,  named 79.9 is a wrong one  !!! )

PC:
Notebook Asus Duo  , I9, 23GB RAM, 1TB SSD, Gig Ethernet, Win11Home
Notebook DELL 7280, I5, 16GB RAM, 1 TB SSD, Gig Ethernet, Win10Pro

Just have collected a few issues with new Alfa:

1. SDR application could not be started in case scal in previous versian selected other instead of 100% -  necessary manually change Jason user profile or just delete folder Expert Electronics in   c:/users/...  .   After starting SDRapplication in any way selection of other scale pusah programm down. ))
2. !!! critical and mandatory to notice in user manual - firmware upgrade of Ecoder2 required power in USB over 500ma - external HUB mandatory, othervise you will get error with firmare preparing or error during firmware programming
3. NO CW manipulation on air at all with Ecoder2 fter FW upgrade , CW tone in the headsets present but ni signal in output with any transmission mode:  Break-In, by pedal, TX by SW.
4. **Radio Sync**  application - no audio transmission  in TX  via virtual audio cable (like in previous version of Radio Sync0

Give me pls advise for deep investigation

**Comment by 1972igor** [comment]
не работают драйвера MME WDM-KS WASAPI !!! нет возможности разделить устройства ввода вывода звука , звук при этом рвётся вот видео https://www.youtube.com/watch?v=kNleIoQqZKc кроме того RadioSynс  кроме того она не сохраняет выставленные настройки  при новом запуске  их проходится выставлять заново

**Comment by Sergey-R5AU** [comment]
"не работают драйвера MME WDM-KS WASAPI !!! нет возможности разделить устройства ввода вывода звука"
                        драйвера работают, не работает немного другое, но проблема внешне выглядит именно так
=====================

"RadioSynс кроме того она не сохраняет выставленные настройки при новом запуске их проходится выставлять заново"

                      сохраняет, возможно программа не имеет доступа к папке C:/Users/.... проверьте разрешения, папку, да и сами файлы Json относящиеся к Radio Sync

**Comment by danweecc** [comment]
E-Coder2 will need a firmware upgrade to be used with the 02092022 build. The firmware upgrade file can be found in the same directory as the EESDR3 executables.

**Comment by Sergey-R5AU** [comment]
sure, absolutely, Ecoder2 updated with new FW, btw in case push button ECODER in down border of app appeared 2 ECODER`s simultaniously instead phisically connected one - Ecoder2(1) and Ecoder2(2), managable still Ecoder2(1) only
