### ISSUE TITLE
Problems with sample rate 156 and 312 KHz

### ISSUE THREAD

**Issue by massunta** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#414]
Hi,
I'm using the Sunsdr2 dx S/n EED06521900168 ,expert version 0.13.0 apha 02092022,pc Laptop Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz , 1.99 GHz - 8,00 GB RAM.
I noticed that when I try to work with higher sample rates,it works good for a while after that it begins to give me some distorsions in the audio.
If I come back to the previous sample rates it works fine.
Cesare I7BNX

**Comment by Sergey-R5AU** [comment]
Cesare, are you using direct headphones connection to the radio  or ?

In my case i am utilized USB headsets  and no worry about audio in that case with any sample rates

**Comment by massunta** [comment]
Hi Sergey,
I am using the external speaker,so I’ve to try with USB headset?

Inviato da Posta per Windows

Da: Sergey R5AU
Inviato: mercoledì 7 settembre 2022 10:36
A: ExpertSDR3/ExpertSDR3-BUG-TRACKER
Cc: massunta; Author
Oggetto: Re: [ExpertSDR3/ExpertSDR3-BUG-TRACKER] Problems with sample rate 156and 312 KHz (Issue #414)

Cesare, are you using direct headphones connection to the radio or ?
In my case i am utilized USB headsets and no worry about audio in that case with any sample rates

**Comment by N8SDR007** [comment]
Are other applications running as well, when this occurs

What is CPU/GPU load?

running 312kHz here and haven't had issues with becoming distorted in RX, I also have all filtering set at Max available in Taps for RX as well

AMD Ryzen5 6 core 32Gb ram and GTX1650Ti

**Comment by jeremyhamlyn** [comment]
Latest Version 13 - running on AMD Ryzen 9 with 64 GB Ram  - AMD High Res Audio - AMD Radeon graphics - 
When moving to highest sample rate after a period of using the Graphics card overloads and everything runs VERY slowly  - not useable --- Reboot does nothing - rebooted and tried starting in multiple ways - always locks up and takes a long time for each task - Watching grphics load on Task Manager it sawtooth load shape to 100% - brick filter drop to zero - Sawtooth over 1 seconds to 100% . After waiting for 10 minutes able to change rate over the next minute --- then all runs ok at 39K

regards

Jeremy

**Comment by N8SDR007** [comment]
Jeremey

What is the firmware version you are running?

the last 3 releases have run well for me with Ryzen and Nvidia- I will note if you're using Win11 and have the latest Win 22H2 installed that could be an issue 22H2 has a crap load of issues- if you have 22H2 I would try and roll back to previous win 11 build and see if that resolves the issue for you. the last 2 releases (one which is in Test group) even the spectrum Zoom issue has been drastically improved.

**Comment by jeremyhamlyn** [comment]
I have multiple environments so will go back and test again The failure was running windows 12 updated with 15092022 0.13.0It’s running at the lower rate now with no problem The failure was gpu overload .. I will try on windows 10 Jeremy HamlynB Eng; M Inf Sc; PEPh +61 (0)8 8215 7120Mb +61 (0)433 910 493USA +1 469 491 ***@***.*** 10 Oct 2022, at 12:16 am, Rick N8SDR ***@***.***> wrote:﻿
Jeremey
What is the firmware version you are running?
the last 3 releases have run well for me with Ryzen and Nvidia- I will note if you're using Win11 and have the latest Win 22H2 installed that could be an issue 22H2 has a crap load of issues- if you have 22H2 I would try and roll back to previous win 11 build and see if that resolves the issue for you. the last 2 releases (one which is in Test group) even the spectrum Zoom issue has been drastically improved.
