### ISSUE TITLE
EESDR V13 02092022 - TCI server cw_macros aborts on CW speed change character 

### ISSUE THREAD

**Issue by VE3EY** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#417]
SunSDR2DX + EESDR V13 02092022.    
Windows 10 - AMD Ryzen 6 core + 16Gb of RAM
NVIDIA GeForce GTX 960

The radio aborts transmission whenever TCI cw_macros encounters a "<" or ">" character used to increase or decrease CW speed by 5WPM.    If such character is encountered when TCI client sends it within ascii string,  transmission stops and radio remains keyed until unkeyed manually: 

For example:   cw_macros message:    CQ TEST DE VE3EY 
TCI Log shows the following: 

20-12-36:366 client: cw_macros:0,CQ TEST DE VE3EY;
20-12-36:386 server: trx:0,true;
20-12-36:386 server: tx_enable:1,false;
20-12-42:198 server: trx:0,false;
20-12-42:198 server: tx_enable:1,true;

TCI  CW macro example which includes the speed change:   CQ >TEST< DE VE3EY
TCI logs shows as following: 

20-13-13:709 client: cw_macros:0,CQ >TEST
20-13-13:730 server: trx:0,true;
20-13-13:730 server: tx_enable:1,false;
---- NB:  From this point on the radio remains keyed until I hit keyboard ESC key ----
20-13-31:520 client: cw_macros_stop;
20-13-31:542 server: trx:0,false;
20-13-31:542 server: tx_enable:1,true;

This issue surfaced only after 02092022 release of EESDR3 was published.

**Comment by VK6NX** [comment]
Issue with special chars '<' and '>' is also confirmed on mac and linux versions with 3rd party TCI-based keyers.

**Comment by ExpertSDR3** [comment]
Fixed
