### ISSUE TITLE
Build 02092022 will crash on MB1 and some installs depending on video card and prior install with scaling other then 100%

### ISSUE THREAD

**Issue by N8SDR007** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#418]
if prior install of 02092022 is left in place and you have scaling set to anything but 100% on an MB1 and some video cards it will cause new version to crash:  

See findings, and workaround in comments below - copied from EESDR3 Discussion group members regarding david installs of 02092022 and John KC2QMA-

David WB5QFZ, [9/6/2022 5:54 AM]
I installed it last thing yesterday. It will not run. It all seems normal then when the main window opens it immediately closes so fast I cant even see it for more than 100ms.

David WB5QFZ, [9/6/2022 5:54 AM]
I will give it some time this morning to see if I did something wrong.

Terry Genes, [9/6/2022 5:54 AM]
[In reply to David WB5QFZ]
Did you update the firmware?

David WB5QFZ, [9/6/2022 5:55 AM]
yes

Terry Genes, [9/6/2022 5:56 AM]
[In reply to David WB5QFZ]
Very odd I had no issues with either the update, install or function on Win 11

David WB5QFZ, [9/6/2022 5:56 AM]
It indicated it was 79.8 is that correct?

David WB5QFZ, [9/6/2022 5:57 AM]
No prob installing. I use 4K screens exclusively. Could that be an issue?

Terry Genes, [9/6/2022 5:57 AM]
[In reply to David WB5QFZ]
Correct

Terry Genes, [9/6/2022 5:58 AM]
[In reply to David WB5QFZ]
So do I with twin screens

David WB5QFZ, [9/6/2022 5:59 AM]
QT6 should have no problem with that. Just re-checked the FW and still no-go.

Terry Genes, [9/6/2022 5:59 AM]
Have you tried re starting everything including PC?

David WB5QFZ, [9/6/2022 5:59 AM]
Just got in and booted up.

David WB5QFZ, [9/6/2022 5:59 AM]
its early morning here now

David WB5QFZ, [9/6/2022 6:01 AM]
I can try again but no change from yesterday. I had ver 12.1 & 13.0 both installed and running prior to installing this latest version. Could that cause an issue? Should I uninstall all the SDR3's and start over?

David WB5QFZ, [9/6/2022 6:02 AM]
I didn't have a problem with 12.1 & 13.0 being installed at the same time before.

Terry Genes, [9/6/2022 6:02 AM]
[In reply to David WB5QFZ]
I always prefer to do a clean install when testing development releases that way yhere are no conflicts with older files

**Daniel Wee (9V1ZV), [9/6/2022 6:03 AM]
[In reply to David WB5QFZ]
Are you able to install the previous version and have it work? One thing I found was that the latest version will crash immediately if the magnification is anything other than 100%. In one of my machines, I had previously set it to 70% so when the new version fired up, it crashed immediately because it cannot work with anything other than 100%. You can get around this by either saving your last magnification at 100% before installing build 02092022. Alternatively, you can rename the ExpertSDR3 user folder and let EESDR3 use the defaults.**

David WB5QFZ, [9/6/2022 6:03 AM]
Well me too but I wanted to be able to use the radio and have something as to fall back to.

David WB5QFZ, [9/6/2022 6:04 AM]
I think I am 150%.

David WB5QFZ, [9/6/2022 6:05 AM]
I will see if I can run a prior version and reset to 100%

93603, [9/6/2022 6:06 AM]
I had same problem with my MB one with this new install Rick and I worked together and found that the database is carrying data from prior installations over which causes some kind of issue. We found that doing a complete uninstall and clearing out all files related to this install and then re installing Fixed the booting issue

93603, [9/6/2022 6:06 AM]
Also you may find that you have to reset to reset firewall settings for for E ESD R3

David WB5QFZ, [9/6/2022 6:06 AM]
Build 08072022 works fine.

David WB5QFZ, [9/6/2022 6:07 AM]
WHat firewall setting exactly? Hi John.

David WB5QFZ, [9/6/2022 6:08 AM]
I am 115% on 0807

93603, [9/6/2022 6:08 AM]
Best thing to do to do is in the firewall settings all settings remove E ESD R3 Then when you go to relaunch it should ask you for firewall permissions again then just click OK and it should work Then when you go to relaunch it should ask you for firewall permissions again then just click OK and it should work

93603, [9/6/2022 6:08 AM]
There also is an issue with windows scaling currently in this new release when you try to raise the scaling above a 100% or below a 100% it will cause the application to crash

93603, [9/6/2022 6:09 AM]
So for now best to leave it set at 100%

David WB5QFZ, [9/6/2022 6:09 AM]
Oh you are talking about the Windows firewall. I have it turned off. I use a SOnic Wall enterprise grade unit.

93603, [9/6/2022 6:10 AM]
OK David then you may not experience the firewall issue

David WB5QFZ, [9/6/2022 6:10 AM]
Trying 100% standby

David WB5QFZ, [9/6/2022 6:12 AM]
That did it.

93603, [9/6/2022 6:12 AM]
Also be careful in this version if you try to zoom the window it will also cause the application to crash

**Comment by ExpertSDR3** [comment]
Fixed
