### ISSUE TITLE
No CW keying via RadioSync

### ISSUE THREAD

**Issue by DF2LH** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#419]
SunSDR2DX + EESDR V13 02092022.
Windows 11 - AMD Ryzen 7 + 32Gb of RAM
NVIDIA GeForce GTX750ti

Tryinig to use N1MM+ CW keying via com0com (Comport 10 to11) with RadioSync. I am able to PTT via DTR but no CW via RTS. When changing this (PTT RTS, Key DTR) no PTT and no keying is possible. 

This problem has already been mentioned in the forum and I just want to bring it into your focus. I think many users will miss this function. Thank you for your work!

Thomas, DF2LH

**Comment by ExpertSDR3** [comment]
The work of N1MM via RadioSync broke down due to the transition to a new CW core, now we are solving this problem.
