### ISSUE TITLE
RECORDER TX

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#42]
магнитофон  в режиме записи на передачу производит запись  когда нажата КНОПКА "MONI" при этом уровень запись зависит от положения регулятора "MONI"
![0dB input mic level](https://user-images.githubusercontent.com/93991940/141675166-26af9eb1-7544-4787-b289-5ad422e07090.jpg)
 При записи наблюдаются разные уровни 
 УРОВЕНЬ "РЕЖИМ RX" минус 3 dB
![Уровень RECORD RX  ](https://user-images.githubusercontent.com/93991940/141676053-5d3c83e7-804e-4aa8-b5c5-99d9a7d52f4f.jpg)

 УРОВЕНЬ "РЕЖИМ ТХ" минус 6 dB
![уровень record  TX ](https://user-images.githubusercontent.com/93991940/141676079-5d0243a1-2ab6-45fb-85e1-4514e1071c30.jpg)

**Comment by 1972igor** [comment]
При максимальном положении движка " УРОВЕНЬ MONI" уровень  записи ТХ составляет минус 3 dB!!!

**Comment by 1972igor** [comment]
При максимальном положении движка " УРОВЕНЬ MONI" уровень записи ТХ составляет минус 6 dB!!! Уровни Record - TX необходимо уровнять до уровня минус 3 dB!! В режиме RECORD TX запись производится в широкой полосе , а не  после фильтра ТХ

**Comment by 1972igor** [comment]
При максимальном положении движка " УРОВЕНЬ MONI" уровень записи ТХ составляет минус 6 dB!!! Уровни Record - TX необходимо уровнять до уровня минус 3 dB!! В режиме RECORD TX запись производится в широкой полосе низкочастотного спектра звука  , а не после фильтра ТХ!!! ПОЧЕМУ ???

**Comment by 1972igor** [comment]
При максимальном положении движка " УРОВЕНЬ MONI" уровень записи ТХ составляет минус 6 dB!!! Уровни Record - TX необходимо уровнять до уровня минус 3 dB!! В режиме RECORD TX запись производится в широкой полосе низкочастотного спектра звука , а не после фильтра передатчика !!! ПОЧЕМУ ??? В ESDR2 файловый магнитофон пишет после фильтра  передатчика, что правильно!!!

**Comment by 1972igor** [comment]
При максимальном положении движка " УРОВЕНЬ MONI" уровень записи ТХ составляет минус 6 dB!!! Уровни Record - TX необходимо уровнять до уровня минус 3 dB!! В режиме RECORD TX запись производится в широкой полосе низкочастотного спектра звука , а не после фильтра передатчика !!! ПОЧЕМУ ??? В ESDR2 файловый магнитофон пишет после фильтра передатчика, что правильно!!! Необходимо сделать запись TX после фильтра , что правильно!!! Это не обходимо для анализа звука в полосе пропускания  фильтра передатчика !!!!

**Comment by ExpertSDR3** [comment]
Исправлено, исправления появятся в релизе 0.10.

**Comment by 1972igor** [comment]
спасибо!!!
