### ISSUE TITLE
ExpertSDR3 0.13.0 alpha build 02092022, macOS, Failed to read the device calibrations! Crash after changing zoom level!

### ISSUE THREAD

**Issue by dd5md** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#420]
I have installed the new version "ExpertSDR3 0.13.0 alpha build 02092022" on my Macbook Pro (macOS Monterey 12.5.1). The firmware update to version 79.8 was successfully installed on my second SunSDR2 DX.

When I then start ExpertSDR3 I get the error message "Failed to read the device calibrations! I have performed a complete reset on my second SunSDR2 DX (SN: EED06012100430) before installing the firmware and then tested the bootloader mode. The error message remains the same.

After opening ExpertSDR3, I set the zoom from 100% to 75%, which closes ExpertSDR3 (see video).

If ExpertSDR2 is already installed, there is still the problem that macOS does not recognise ExpertSDR3 as a stand-alone programme and the USB microphone cannot be used.

Best regards

Mathias, DD5MD

https://user-images.githubusercontent.com/41026754/189495150-d939ed86-394d-4dad-aafe-926099045b4d.mp4

**Comment by VK6NX** [comment]
Delete ESDR3 settings from User/Libraty, start ESDR3, go to Settings-Transceiver in ESDR3 and click "Write" button once. Then close ESDR3 completely and power cycle DX.

**Comment by dd5md** [comment]
> Delete ESDR3 settings from User/Libraty, start ESDR3, go to Settings-Transceiver in ESDR3 and click "Write" button once. Then close ESDR3 completely and power cycle DX.
> 
> If you are not on direct ether cable, then also check if nothing in your network (except DX) uses UDP 50001 (like Anydesk, IC-9700, etc).

Hi VK6NX,

the error message "Failed to read the device calibrations!" has now disappeared.

Many thanks for that!

All that's missing now is a working "Mic PC" for a test.

**Comment by ExpertSDR3** [comment]
Fixed crash of the program when changing the scale
