### ISSUE TITLE
Calibrations, frequency correction not working

### ISSUE THREAD

**Issue by F1DJY** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#421]
F1DJY
Sunsdr2Pro EED02111800462, W11 21H2, HP Z2 I7 8700K, 16Go Ram, NVidia quadro K1200, 2 Display 4K 27 inch, ExpertSdr3 0.13 alpha 01091022, firmware 79.8, API Vulkan

I can change the coefficient from 0.000142 to 0.000000 and Write,, nothing changes at the listening frequency level
<img width="446" alt="Capture d’écran 2022-09-11 003500" src="https://user-images.githubusercontent.com/16072964/189504180-1a49df14-d6cd-4366-ba4e-b355b0315ebc.png">

**Comment by 1972igor** [comment]
Expert SDR3 v 0.13.0 alpha BUILD 02092022
1 The frequency calibration does NOT work , you calibrate the panorama does not move , the tone of the generator does not change the video is attached https://www.youtube.com/watch?v=mYkWQ66DZq8

**Comment by jmkr25** [comment]
No problem with Tone, work perfect
