### ISSUE TITLE
EESDR3 0.13.0 Build 02092022 // Do not save BW filter

### ISSUE THREAD

**Issue by GregTroar** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#422]
Probably a bug as I did not have it on previous version.
When I am on 20M for example with a user defined filter of let's say 3.3K, I switch to another band and when I come back on 20M, despite the fact that the filter 3.3K is the one selected in the GUI in reality the 2.7K filter is selected (I hear the difference by ear).
So I have to click on another filter and come back on 3.3K to actually get the 3.3K filter in action again.

It seems like change of band do not save the current filter used in reality while in the GUI it is saved as it is the one selected.

Hope this is clear enough.

Thanks

**Comment by N8SDR007** [comment]
Noted as well-

My 8K when I return is really my 4K until I click 4 then switch back to 8

**Comment by John-KC2QMA** [comment]
Can also confirm no RX filter persistence.

**Comment by ExpertSDR3** [comment]
Fixed, fixws will be in 1.0.4 version.
