### ISSUE TITLE
Receiver AGC

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#424]
when the gain decreases, the "teeth" disappear behind the filter band- AGC works correctly, but there is not enough sensitivity, when you do a normal level of sensitivity, teeth appear, the sound creaks at powerful stations! This is also observed in the AGC Automatic mode
![неправильная работа AGC](https://user-images.githubusercontent.com/93991940/189617459-05e6f9dc-536e-41c5-895d-5d91323a996a.jpg)
![уровень 69 % ](https://user-images.githubusercontent.com/93991940/189617755-976c2725-c5da-4ee3-abef-e9321fceff0e.jpg)
![нет перегруза AGC](https://user-images.githubusercontent.com/93991940/189617838-8c183e63-05b2-4751-af8b-b0a6e596ad77.jpg)
![AGC Norma](https://user-images.githubusercontent.com/93991940/189617861-818ef8fb-2e34-4230-87fc-0d54165e179e.jpg)

**Comment by ExpertSDR3** [comment]
As far as I understand correctly, you transmit an audio signal via vac. The new frequency components are the result of poor-quality resampling of the signal, this is a typical picture for a VAC program. If you record an audio signal in a wav file in ESDR3 and then open it in adobe audition and look at the spectrum, you will not see any unnecessary frequency components there.

На сколько я правильно понимаю вы передаёте аудио сигнал  через VAC. Новые частотные компоненты являются результатом некачественной передискретизации сигнала, это типичная картина для этой программы. Если вы запишите аудио сигнал в wav файл в ESDR3 и затем откроете его в adobe audition и посмотрите на спектр вы не увидите там лишних частотных составляющих.

**Comment by 1972igor** [comment]
спасибо ! ПРОВЕРИМ!!!
