### ISSUE TITLE
RadioSync 1.0.0 will not connect wiih any software not visible in window.

### ISSUE THREAD

**Issue by KC5SW** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#425]
I am using RadioSync 1.0.0 to sync my SunSDR2dx transciever with:
My ACOM 2000A Amplifier
My SteppIR SDA-100 Controller
My logging software N3FJP Amateur Contact Log

It assigns the COM port each time I start ExpertSDR3 software. It works beautifully except ofr one problem.
RadioSync will only assign ports to those application that is visible in the RadioSync window!

For instance, of the 3 syncronization I have in RadioSync, only 2 are visible. These 2 are immediately connected and syned.
The third item will not sync until I move the RadioSync scroll bar to make the third item visible in the RadioSync window..

There is a SCROLL BAR on the right side of the RadioSync window.
Within that window are 3 syncronization for the programs I mentioned earlier.
Of the 3 programs, 2 of them are visible.
Moving the RadioSync scroll bar to the bottom on the window will make the third syncronization visible.
Only at that point will the syncronization become active for the third program.

de KC5SW
Sam Walker

**Comment by ExpertSDR3** [comment]
Fixed
