### ISSUE TITLE
No straigth or WinKey CW with E-Coder 2

### ISSUE THREAD

**Issue by DF2LH** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#426]
SunSDR2DX + EESDR V13 02092022.
E-Coder 2 with Firmwareupdate provided with EESDR V13 02092022 on a 2.5 Ampere USB 3.1 Hub
Windows 11 - AMD Ryzen 7 + 32Gb of RAM
NVIDIA GeForce GTX750ti

While looking for a solution to send CW with n1mm+ (RadioSync does not work, see issue #419) I tried to connect my WinKey to my e-Coder 2. Lambic is off, but the CW characters are not sent. The test with a hand key shows that only every second press on the key leads to a signal. Unfortunately, this means that the e-coder 2 can still not be used. 
Since my SunSDR2DX is not in my shack, direct  CW key connection to the radio is not possible. I hope for a timely solution before the contest season.
vy 73, Thomas

**Comment by ExpertSDR3** [comment]
The work of N1MM via RadioSync broke down due to the transition to a new CW core, now we are solving this problem.

**Comment by ExpertSDR3** [comment]
Fixed
