### ISSUE TITLE
Калибровка частоты НЕ работает

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#427]
Expert SDR3 v 0.13.0 alpha BUILD 02092022
 Калибровка частоты НЕ работает, вы калибруете панораму, не двигаетесь, тон генератора не меняется, видео прилагается https://www.youtube.com/watch?v=mYkWQ66DZq8

Expert SDR3 v 0.13.0 alpha BUILD 02092022
 The frequency calibration does NOT work, you calibrate the panorama, do not move, the tone of the generator does not change, the video is attached

**Comment by ExpertSDR3** [comment]
Работает, но нужно стоп старт делать в программе, с обновлением прошивки это будет доработано.

**Comment by 1972igor** [comment]
Спасибо ! Понятно! Делал старт стоп ПО не помогает! В ПО ESDR2 видно куда смещается калибровка! Спасибо!
