### ISSUE TITLE
MacOS crash on exit

### ISSUE THREAD

**Issue by robinmatthews** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#428]
Mac: MacBook Pro (16-inch, 2019) - 2.6 GHz 6-Core Intel Core i7
MacOS: 12.6 (21G115)
Radio: SunSDR2DX
ExpertSDR3: 0.13.0 alpha, build 02092022

Scenario:
- Start ExpertSDR3
- Start the radio
- Start transceiver
- Stop transceiver
- Close radio window

Receive error:
<img width="328" alt="Screenshot 2022-09-14 at 17 52 24" src="https://user-images.githubusercontent.com/664137/190215339-06a452a3-3325-4f80-b4f8-7990b00803f4.png">

Thanks
Robin

**Comment by ExpertSDR3** [comment]
Fixed.
