### ISSUE TITLE
При отключении внешнего динамика , происходит одновременное отключение звука "PHONES"

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#43]
Win 10 - 64 Home
Transceiver MB-1
ESDR3 0.10.0.Alpha Build 03112021
MB1 Utility v 1.1.3
При отключении внешнего динамика , происходит одновременное отключение звука "PHONES"
![динамик](https://user-images.githubusercontent.com/93991940/141676741-9c8b7aa0-e436-49b0-a000-859588965128.jpg)

**Comment by ExpertSDR3** [comment]
Опишите подробней, непонятно, что вы имеете в виду.

**Comment by 1972igor** [comment]
когда я нажимаю эту кнопку одновременно происходит отключение звука  в наушниках и внешнего динамика !А должно я думаю быть так отключение динамика, а  в наушниках звук должен оставаться!!

**Comment by 1972igor** [comment]
когда я нажимаю эту кнопку одновременно происходит отключение звука в наушниках и внешнего динамика !А должно я думаю быть так, отключение динамика, а в наушниках звук должен оставаться!! По крайне мере в версии ESDR2 так всё и работает!  при отключении динамика звук в наушниках остаётся!

**Comment by 1972igor** [comment]
когда я нажимаю эту кнопку, одновременно происходит отключение звука в наушниках и внешнего динамика находящего внутри трансивера ! должно я думаю быть так, отключение динамика, а в наушниках звук должен оставаться!! По крайне мере в версии ESDR2 так всё и работает! при отключении динамика звук в наушниках остаётся!

**Comment by 1972igor** [comment]
когда я нажимаю эту кнопку, одновременно происходит отключение звука в наушниках и внешнего динамика находящего внутри трансивера ! должно я думаю быть так, отключение динамика, а в наушниках звук должен оставаться!! По крайне мере в версии ESDR2 так всё и работает! При нажатии кнопки с иконкой  "Динамик" отключение 
 внутреннего динамика в трансивере  производится, а звук  в наушниках остаётся!

**Comment by ExpertSDR3** [comment]
Эта кнопка выключает громкость во всей программе, она работает правильно. Управление громкоговорителем MB будет реализовано в следующих версиях.

**Comment by 1972igor** [comment]
СПАСИБО !ПОНЯТНО!!!
