### ISSUE TITLE
Network glitch occurs after sending a TCI CW macro

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#430]
EESDR3 0.13.0 alpha build 15092022
Windows 11 64-bit
SunSDR2DX

After sending a CW macro over TCI to the EESDR3 keyer, there is a brief network glitch. I use Log4OM2 connected to the TCI keyer and send my macros that way. This glitch does not happen when manually sending using the paddle.

This only happens when the system latency is higher (>4ms). My system is connected to the remote network via VPN over the internet. When I use a local system without VPN latencies, this problem does not show up.

https://user-images.githubusercontent.com/13930571/190398827-425900fe-9424-4320-9940-d157d19c6189.mp4

**Comment by ExpertSDR3** [comment]
Fixed
