### ISSUE TITLE
Audio artifact (glitch) at the end of TCI CW macro message

### ISSUE THREAD

**Issue by VE3EY** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#433]
SunSDR2DX serial EED06202100576
EESDR3 0.13.0 alpha build 15092022
Windows 10 64 bit - AMD Ryzen 6 core + 16Gb of RAM
NVIDIA GeForce GTX 960
Ecoder mini

CW keying via TCI client macro has an audio glitch at the end of each message.   Once the CW macro message finishes, the rig will unkey, briefly key (TX) and finally unkey again.   No RF is transmitted during the momentary TX. 

This can be confirmed by observing the "IND" led indicator on the front panel of the radio.  

Upon switching back to RX , the radio will briefly TX (red led on) and then return back to receive.  This results in annoying audio crack as the radio keys and unkeys after the message. 

Turning the "Break.In" off solves the issue but it obviously disables the keyer paddle.   Adjusting the Macro delay setting seems to have no effect.

**Comment by danweecc** [comment]
This problem seems to have been resolved by itself - not sure what changed but I will keep monitoring for a while.

**Comment by VE3EY** [comment]
Thanks for your feedback.  In my case this behaviour remains and is consistent across two computers.   I tried both 5m contest and log4om TCI macros and the result is the same.

**Comment by ExpertSDR3** [comment]
Fixed
