### ISSUE TITLE
Recorder AIR indicator Boost 

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#436]
there is not the correct operation of the tape recorder of the ether!!! The reason is as follows, the recorded signal should not be suppressed through the audio input device, namely through the sound card!!! https://www.youtube.com/watch?v=ZpwH1LAnKGo
наблюдается не правильная работа магнитофона эфира!!! Причина в следующем, записанный сигнал не должен подавятся через устройство ввода звука , а  именно через звуковую карту!!! Видео прилагается https://www.youtube.com/watch?v=ZpwH1LAnKGo

**Comment by VK6NX** [comment]
может быть ссылочку на стандарт, где написано, что "аписанный сигнал не должен подавятся через устройство ввода звука , а именно через звуковую карту"?

А если нет "звуковой карты"? А есть "устройство звука" - тогда как быть?

Ну и непонятно, с чего вдруг предполагается, что записанный эфир обязан воспроизводиться с тем же уровнем, с которым записан.

Имхо все что вы пытаетесь выдать за баг, багом не является. Это в пожелания все, в общую очередь

**Comment by 1972igor** [comment]
магнитофон не должен подаваться на устройство  ввода! там в нём работает аудио процессор! Это первое! Звуковая карта или прочие, что вы используете -это всё равно! Магнитофон должен подаваться на вход модулятора, а не через микрофонный усилитель !

**Comment by 1972igor** [comment]
the tape recorder must not be fed to the input device! there's an audio processor running in it! This is the first! The sound card or other things that you use - it's all the same! The tape recorder should be fed to the input of the modulator, and not through a microphone amplifier!

**Comment by VK6NX** [comment]
Ну а кроме этого вашего сугубо личного мнения "магнитофон не должен" есть что-то еще? Документ какой-нить?Стандарт?

Только не надо примеров "так сделано у Айкома (подставить нужное), поэтому это правильно).

**Comment by 1972igor** [comment]
Объяснять , что либо не собираюсь! Ошибка есть и должна быть исправлена! Обратите внимание на алгоритм работы магнитофона ESDR2 !

**Comment by VK6NX** [comment]
Вот и ладушки :)

Собственно, вопросы я вам задал именно для того, чтобы девелоперы (которым тоже наверняка непонятны ваши фантазии) послушали ваши аргументы. Но поскольку у вас только апломб и личное мнение, которое ничем (кроме собственно мнения) не подтверждено,  - то тут то все и ясно.

С хотелками - в Suggestions. В порядке очереди.

Ну и благодарность за очередной "розовый шум"

**Comment by 1972igor** [comment]
во первых  MIC Meters откалиброван производителем и даёт информацию о измерения уровня поступающий на вход модулятора  пользователю верно!!!
второе магнитофон эфира, производит запись сигнала после фильтра передатчика, при включении  микрофонного усилителя мы видим заметное увеличение  уровня с минус 24 dB на уровень минус 6dB этого не должно быть!!!
 записанный сигнал( воспроизводимый этим магнитофоном ) проходит обработку модулем Proc , через компрессоры ,эквалайзеры и прочие блоки обработки этого происходить не должно , в итоге мы получаем не  достоверную запись не только по уровням , но и добавляем экранизацию и компрессию в записанный сигнал! Так , что это не хотели , а ошибка в ПО 
Firstly, MIC Meters is calibrated by the manufacturer and gives information about the level measurement coming to the input of the modulator to the user correctly!!!
the second tape recorder of the ether, records the signal after the transmitter filter, when the microphone amplifier is turned on, we see a noticeable increase in the level from minus 24 dB to minus 6dB, this should not be!!!
the recorded signal (reproduced by this tape recorder) is processed by the Proc module, through compressors, equalizers and other processing units this should not happen, as a result, we get an unreliable recording not only by levels, but also add screening and compression to the recorded signal! So that it is not wanted , but an error in the software

**Comment by VK6NX** [comment]
Ну вы уж определитесь... а то "объясняю", "не объясняю".

Не надо второй раз (а потом еще 10) объяснять, что вы хотите записывать сигнал до обработки (эту хотелку вы уже озвучили два раза). 

Я просил вас подкрепить ваше мнение почему "так должно быть" чем-то объективным. Чтобы оно из частного мнения превратилось хотя бы в некое подобие best practices. У вас есть чем подкрепить? 

Я, например, могу считать, что записывать эфир надо так, как он смышен в наушниках. То есть после эквалайзеров, фильтров и прочего. Потому что магнитофон - это средство объективного контроля эфира, требующееся в основном контестменам и их судьям. Судьям интересно, что слышал спортсмен, а не то, что было "до фильтра". Вышеизложенное в этом абзаце - мое личное мнение и я не собираюсь отклонения от него представлять в виде бага.

**Comment by ExpertSDR3** [comment]
Сигнал из речевого магнитофона без обработки подаётся на вход модулятора с пиковой амплитудой 0 дБ для излучения максимальной мощностью.

**Comment by 1972igor** [comment]
Спасибо, за ответ! Тогда вопрос если он подавался на AGC затем  на модулятор , то при выключении звукового устройства меняется уровень , Почему ТАК?

**Comment by 1972igor** [comment]
Спасибо, за ответ! Тогда вопрос если он подаётся  на AGC затем на модулятор , то при выключении звукового устройства меняется уровень , Почему ТАК? Замечу на вход я подавал генератор с УРОВНЕМ МИНУС 12 dB  далее смотрите по видео

**Comment by 1972igor** [comment]
Почему при отключение звукового устройства  входа звука меняется уровень ? Уровень сигнала менятся НЕ ДОЛЖЕН , КАК ВЫ САМИ СКАЗАЛИ, ЧТО : " магнитофона без обработки подаётся на вход модулятора с пиковой амплитудой 0 дБ " тогда индикатор MIC Meters (который правильно откалиброван, за что спасибо ) должен показывать  пиковую амплитуду до 0 дБ

**Comment by 1972igor** [comment]
Спасибо, за ответ! Тогда вопрос если он подаётся на AGC затем на модулятор , то при выключении звукового устройства меняется уровень , Почему ТАК? Замечу на вход я подавал генератор с УРОВНЕМ МИНУС 12 dB далее смотрите по видео
Почему при отключение звукового устройства входа звука меняется уровень ? Уровень сигнала менятся НЕ ДОЛЖЕН , КАК ВЫ САМИ СКАЗАЛИ, ЧТО : " магнитофона без обработки подаётся на вход модулятора с пиковой амплитудой 0 дБ " тогда индикатор MIC Meters (который правильно откалиброван, за что спасибо ) должен показывать пиковую амплитуду до 0 дБ

**Comment by 1972igor** [comment]
Thank you for the answer! Then the question is, if it is fed to the AGC then to the modulator, then when the sound device is turned off, the level changes, Why IS THAT? I will note that I fed a generator with a LEVEL of MINUS 12 dB to the input, then watch the video
Why does the sound level change when the audio input device is turned off ? The signal level SHOULD NOT change, AS YOU YOURSELF SAID THAT : " a tape recorder without processing is fed to the input of a modulator with a peak amplitude of 0 dB " then the MIC Meters indicator (which is correctly calibrated, thanks for that) should show a peak amplitude of up to 0 dB

**Comment by 1972igor** [comment]
Спасибо, за ответ! Тогда вопрос если он подаётся на AGC затем на модулятор , то при выключении звукового устройства меняется уровень , Почему ТАК? Замечу на вход я подавал генератор с УРОВНЕМ МИНУС 12 dB далее смотрите по видео
Почему при отключение звукового устройства входа звука меняется уровень ? Уровень сигнала менятется НЕ ДОЛЖЕН , КАК ВЫ САМИ СКАЗАЛИ, ЧТО : " магнитофона без обработки подаётся на вход модулятора с пиковой амплитудой 0 дБ " тогда индикатор MIC Meters (который правильно откалиброван, за что спасибо ) должен показывать пиковую амплитуду до 0 дБ.. Почему регулятор усиления влияет на уровень магнитофона подаваемый на модулятор? Из Вашего сообщения этого не должно быть , а это есть! Магнитофон как Вы написали подаётся через AGC  передатчика на его вход

**Comment by 1972igor** [comment]
Thank you for the answer! Then the question is, if it is fed to the AGC then to the modulator, then when the sound device is turned off, the level changes, Why IS THAT? I will note that I fed a generator with a LEVEL of MINUS 12 dB to the input, then watch the video
Why does the sound level change when the audio input device is turned off ? The signal level SHOULD NOT change, AS YOU YOURSELF SAID THAT: " a tape recorder without processing is fed to the input of a modulator with a peak amplitude of 0 dB " then the MIC Meters indicator (which is correctly calibrated, thanks for that) should show a peak amplitude of up to 0 dB.. Why does the gain control affect the level of the tape recorder supplied to the modulator? From your message, this should not be, but it is! The tape recorder as you wrote is fed through the AGC of the transmitter to its input

**Comment by 1972igor** [comment]
Спасибо, за ответ! Тогда вопрос если он подаётся на AGC затем на модулятор , то при выключении звукового устройства меняется уровень , Почему ТАК? Замечу на вход я подавал генератор с УРОВНЕМ МИНУС 12 dB далее смотрите по видео
Почему при отключение звукового устройства входа звука меняется уровень ? Уровень сигнала меняется НЕ ДОЛЖЕН , КАК ВЫ САМИ СКАЗАЛИ, ЧТО : " магнитофона без обработки подаётся на вход модулятора с пиковой амплитудой 0 дБ " тогда индикатор MIC Meters (который правильно откалиброван, за что спасибо ) должен показывать пиковую амплитуду до 0 дБ.. Почему регулятор усиления влияет на уровень магнитофона подаваемый на модулятор? Из Вашего сообщения этого не должно быть , а это есть! Магнитофон как Вы написали подаётся через AGC передатчика на его вход
Замечено , что в эфире уровень магнитофона идёт нормально!

**Comment by 1972igor** [comment]
Thank you for the answer! Then the question is, if it is fed to the AGC then to the modulator, then when the sound device is turned off, the level changes, Why IS THAT? I will note that I fed a generator with a LEVEL of MINUS 12 dB to the input, then watch the video
Why does the sound level change when the audio input device is turned off ? The signal level SHOULD NOT change, AS YOU YOURSELF SAID THAT: " a tape recorder without processing is fed to the input of a modulator with a peak amplitude of 0 dB " then the MIC Meters indicator (which is correctly calibrated, thanks for that) should show a peak amplitude of up to 0 dB.. Why does the gain control affect the level of the tape recorder supplied to the modulator? From your message, this should not be, but it is! The tape recorder as you wrote is fed through the AGC of the transmitter to its input
It is noticed that the level of the tape recorder is normal on the air!

**Comment by 1972igor** [comment]
на основание Вашего ответа есть вопросы ,
1. подаётся на вход модулятора с пиковой амплитудой 0 дБ , значит чего? Амплитуду сигнала который воспроизводит магнитофон усиливают? Хочу заметить видимо это так и происходит, ведь на вход был подан одно тоновый генератор с уровнем минус 12 dB и этот генератор был записан , а затем воспроизведён и на панораме ( режим TX ) было четко видно наши минус 12 dB превратились в 0dB Это как то уж .....
2. сигнал с магнитофона подаётся на AGC затем на модулятор , но при включении и выключении звукового устройства меняется уровень , с минус 3dB PEAK ( минус 6dB RMS ) при включении )), а при выключении минус 39dB по PEAK , этого быть не должно!!! Ведь производитель четко ответил "Сигнал из речевого магнитофона без обработки подаётся на вход модулятора"
3 уровень воспроизводимого сигнала магнитофона, который подаётся на вход модулятора ЗАВИСИТ ОТ ПОЛОЖЕНИЯ РЕГУЛЯТОРА УСИЛЕНИЯ МИКРОФОНА это лишний раз доказывает , что сигнал магнитофона проходит через звуковое устройство, простите это очень смешно !Это не правильно ! Производитель четко заявил "Сигнал из речевого магнитофона без обработки подаётся на вход модулятора"
4 О пиковой амплитуде сигнала для излучения максимальной мощностью как пояснил производитель !ОК панорама ( режим TX ) было четко видно наши минус 12 dB превратились в 0dB , так почему наши минус 12 db не превратились в 0 dB на показания MIС meters ? Ведь САМ MIC Meters в первые за 7 лет откалиброван в показаниях правильно ,а также панорама режим ТХ тоже откалибрована правильно, что будет с сигналом одно тонового генератора, поданным с уровнем минус 6 dB или с сигналом 0 dB записанным на магнитофон и затем магнитофоном поданным вход передатчика ? 6 dB усилятся под уровень 0 AGC возможно немного подожмёт, а вот 0 dB усилятся до +++ при этом образуется эффект CLIP и наше AGC передатчика этот CLIP ещё подожмёт до не узнаваемости !!

**Comment by 1972igor** [comment]
there are questions based on your answer ,

it is fed to the input of a modulator with a peak amplitude of 0 dB, so what? Is the amplitude of the signal that the tape recorder reproduces amplified? I want to note that this is probably how it happens, because a single-tone generator with a minus 12 dB level was applied to the input and this generator was recorded and then reproduced and on the panorama ( TX mode) it was clearly visible that our minus 12 dB turned into 0dB.....
the signal from the tape recorder is being fed on the AGC, then on the modulator, but when the sound device is turned on and off, the level changes, from minus 3dB PEAK (minus 6dB RMS) when turned on)), and when turned off minus 39dB by PEAK, this should not be!!! After all, the manufacturer clearly replied "The signal from the voice recorder is fed to the input of the modulator without processing"
3 the level of the reproducible signal of the tape recorder, which is fed to the input of the modulator, DEPENDS ON the POSITION OF the MICROPHONE GAIN CONTROL, this once again proves that the signal of the tape recorder passes through the sound

**Comment by 1972igor** [comment]
it is fed to the input of a modulator with a peak amplitude of 0 dB, so what? Is the amplitude of the signal that the tape recorder reproduces amplified? I want to note that this is probably how it happens, because a single-tone generator with a minus 12 dB level was applied to the input and this generator was recorded and then reproduced and on the panorama ( TX mode) it was clearly visible that our minus 12 dB turned into 0dB.....
the signal from the tape recorder is being fed on the AGC, then on the modulator, but when the sound device is turned on and off, the level changes, from minus 3dB PEAK (minus 6dB RMS) when turned on)), and when turned off minus 39dB by PEAK, this should not be!!! After all, the manufacturer clearly replied "The signal from the voice recorder without processing is fed to the input of the modulator"
3 the level of the reproducible signal of the tape recorder, which is fed to the input of the modulator DEPENDS ON the POSITION OF the MICROPHONE GAIN CONTROL, this once again proves that the signal of the tape recorder passes through the sound device, sorry, this is very funny! 
This is not right ! The manufacturer clearly stated "The signal from the voice recorder without processing is fed to the input of the modulator"
4 About the peak amplitude of the signal for maximum power radiation as explained by the manufacturer!OK panorama ( TX mode ) it was clearly visible our minus 12 dB turned into 0dB , so why didn 't our minus 12 db turn into 0 dB on the MIC meters readings ? After all, the MIC Meters ITSELF was calibrated correctly in the readings for the first 7 years, as well as the panorama TX mode is also calibrated correctly, what will happen to the signal of a single-tone generator supplied with a level of minus 6 dB or with a 0 dB signal recorded on a tape recorder and then a tape recorder supplied to the transmitter input? 6 dB will be amplified to the level of 0 AGC, it will probably squeeze a little, but 0 dB will be amplified to +++ at the same time, the CLIP effect will be formed and our AGC transmitter will squeeze this CLIP even to recognition!!

**Comment by ExpertSDR3** [comment]
Действительно при передачи аудио сигнала из магнитофона ручка Mic Agc влияет на показания Мик метра, это ошибка в работе индикатора, а уровень самого сигнала никак не зависит от положения этой ручки, в следующей версии будет исправлена индикация мик метра

**Comment by 1972igor** [comment]
спасибо за ответ!
