### ISSUE TITLE
переключении источника звука, на выходе трансивера, 

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#44]
WIN 10
ESDR3 0.10.0 alpha
Transceiver MB-1
При переключении источника звука,( режим LSB ,USB ) на выходе
 трансивера, при использовании VAC и других звуковых карт ( тип драйвера MME, WDM-KS, WASAPI) отсутствует сигнал на входе передатчика (  отсутствует сигнал на входе ) хотя программа отображает, что переключение произведено!!!
![источник ВЫХОДА ](https://user-images.githubusercontent.com/93991940/141677472-f5df148e-2a9b-41cb-b0cd-1eeb947c3e06.jpg)
также наблюдается не четкое информация надписей в окне

**Comment by ExpertSDR3** [comment]
Повторяет #30
