### ISSUE TITLE
Frequency Coefficient has no effect

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#443]
EESDR3 0.13.0 alpha  build 15092022
Windows 11 64-bit
SunSDR2DX

The frequency coefficient setting has no impact on output or received frequency whatsoever. In EESDR2 it worked but in this latest build it does not work or appear to do anything. This has been confirmed by others.

**Comment by ExpertSDR3** [comment]
#421
