### ISSUE TITLE
Motorboating in receive audio

### ISSUE THREAD

**Issue by kxkayser** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#444]
Build: 15092022
Windows 10 pro
SunSDR2 DX
Intermittent motorboating noise starts up at random intervals.  A quick power cycle of the software corrects the audio until the next time.  Could be 5 minutes or a few hours.  Other users of this build have the same experience

**Comment by kxkayser** [comment]
I should have clarified this is in the received audio.  Also, what I mean by a power cycle of the software is you just have to click on the on/off button.  You don't have to reload the application.

**Comment by F1DJY** [comment]
I noticed the same thing here but only on start auto. With "normal start" no problem. F1DJY
