### ISSUE TITLE
 ECoder not working in Ubuntu 20.4 Mint 20.3

### ISSUE THREAD

**Issue by K6TWO** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#446]
EED06012100386
Dell Inspiron 
EESDR3 Build 15092022
The EESDR3 sees the ecoder as evidenced by the ecoder icon but it is not discovered by Firmware update program. Also I am unable to get Colibra Nono to be recognized. I've tried 2 different Dell system with the same Linux distro, no workie! All ok under Windows! Any ideas?

**Comment by ExpertSDR3** [comment]
To work with the E-Coder panel, you need to assign access rights to HID devices so that the USER can access them, this is done by the following commands:

_sudo chmod 664 /dev/hidraw*_
_sudo chgrp plugdev /dev/hidraw*_
