### ISSUE TITLE
Audio from radio output corrupted

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#448]
EESDR3 0.13.0 build 15092022
Windows 10/11 64-bit
SunSDR2DX

From time to time, the audio output direct from the radio phones connector becomes corrupted - it sounds scratchy. At the same time, the audio from the PC/Mac client sounds normal and without corruption. This happens from time to time in any mode. Usually restarting EESDR3 will resolve the issue. Going into TX and back to RX will also fix it for a while. Unable to reproduce this automatically though but I suspect it might be latency related. Anything that re-starts the audio stream tends to resolve the issue for a while.

This has been confirmed by several different users.

**Comment by u6710** [comment]
I too have the same problem as the previous user. I am attaching an audio file so you can hear what it is. Putting the radio speaker in mute does not disappear, you can only press the power on / off button of EESDR3.
From the reports received it happens both in transmission and reception.
73 de HB9MIR, Arturo

**Comment by kxkayser** [comment]
I believe this is the same as my issue #444

**Comment by danweecc** [comment]
This is a little different in that it doesn't make a motorboating sound but more like a scratchiness in the audio. 

On 10 Oct 2022, 8:35 am, at 8:35 am, kxkayser ***@***.***> wrote:
>I believe this is the same as my issue #444
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/issues/448#issuecomment-1272667611
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by kxkayser** [comment]
Perhaps it is a different issue. Next time it occurs I’ll switch the audio from the headphone jack to the sound card and see if it disappears.

**Comment by rvolchkov** [comment]
Артуро сделал запись проблемы @ExpertSDR3 
[Bug 448_Record from hb9mir.zip](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/files/9744251/Bug.448_Record.from.hb9mir.zip)

**Comment by kxkayser** [comment]
Update:  While the audio from the headphone jack was distorted, the audio from the soundcard was fine.  A quick press of the power button off and on cleared up the audio as usual.

**Comment by SV1RXI** [comment]
i have the same.In windows i fix it .In mac os is more terrible ,coming more often

**Comment by SV1RXI** [comment]
https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/discussions/118 
![sound](https://user-images.githubusercontent.com/92052946/218302929-cf3f0f81-6757-4343-bf49-963902586e00.png)
