### ISSUE TITLE
EQ TX

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#45]
WIN 10
ESDR3 0.10.0 alpha
Transceiver MB-1
При работе с EQ TX  при сдвиге движка в право или увеличении уровня наблюдается "ВОЗБУД"  ( в виде писка генератора) И ЗАВИСАНИЕ ПРОГРАММЫ, после  включения и выключения всё восстанавливается , но опят  при манипуляции с  движком на рисунке всё повторяется!!!
![noise Rozi analiz RADIO](https://user-images.githubusercontent.com/93991940/141677911-e6b64870-9fae-4537-bcf5-cc5f9466224d.jpg)

**Comment by ExpertSDR3** [comment]
Действительно, такой баг есть, исправлено, в релизе 0.10 будет работать правильно.

**Comment by 1972igor** [comment]
спасибо!!!
