### ISSUE TITLE
switching audio between RX1 and RX2 partially broken when using E-Coder buttons

### ISSUE THREAD

**Issue by ok1dsz** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#450]
Hi 
this is about issue #188, which is for quite long time marked as closed. But in the reality it is not resolved, the bug is still present in all 0.12 or 0.13 versions published so far. Any chance to have it really resolved?
regards
Zdenek OK1DSZ

**Comment by ExpertSDR3** [comment]
Can you write a sequence of actions to demonstrate the problem?
