### ISSUE TITLE
Timing Bug in CW "Break.In" Mode    (Build 05102022, FW 83.8)          >>> Obsolete - fixed in Build 25102022, FW 85.8

### ISSUE THREAD

**Issue by HB9JND** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#451]
Timing Bug in CW "Break.In" Mode

- CW operation with paddle and headphones connected directly to the E-Coder2.
- "Break.In" button activated.
  > The first time you touch the CW paddle, the transceiver correctly switches to transmit mode.
    > After releasing the CW paddle, the transceiver immediately switches back to receive (without delay).
**Bug:** The **time set** in the **"Break.IN" menu** is **not taken into account**, so Semi-Breakin dosen't really work.

Reproducibility: 100%

My Setup:

- 2 SunSDR2PRO EED05351600204 & EED054211100942
- ColibriNANO EED02091700110
- E-Coder2 (newest Firmware)
- ESDR3 Software Version 0.13.0. alpha, BUILD 05102022 / Firmware 83.8

- Windows 11 Pro, Version 21H2
- Processor Intel i9-10900 CPU @ 2.80 GHz
- RAM 32 GB
- NVIDIA GeForce RTX 2070 SUPER, Monitor 38" DELL U3818DW
- External USB Audiointerface MOTU M2

**Comment by py5hot** [comment]
SAME PROBLEM ON MB1, MACROS NOT WORK OKEY

**Comment by hb9bun** [comment]
EESDR3 0.13.0 alpha build 21102022 (and also with 05102022)
Firmware 84.8
SunSDR2DX
Windows 11

Using a straight keyer at the CW plug on the back of the SS2DX the display does switch from TX to RX with every individual dot and dash keyed. PTT works normal, also PTT for PA, and IND LED on the front gets red with normal break-in delay, But in the display of EESDR3 switches to RX mode with every single key press (every dot and dash transmitted). So normal operation but a UI issue here. Interestingly the red TX indicator on the e-Coder switches with the display and not with PTT (so like the display). 

In Build 05102022 the CW signal displayed in the scope was not properly shown (chaning too fast for the graphics card), in 21102022 the CW signal is not displayed anymore in the scope. 

From my point of view it is not a PTT issue, TX/RX display is just controlled from the CW keyer input and not from PTT in the case of straight keying.

**Comment by HB9BMR** [comment]
20221021 installed win 10
SDR2dx with EC2
Paddle in EC2
Break in
First letter comes as expected
Then rig goes to receive with the result that the second letter can only be started with a delay.
Does not matter if paddle is plugged into SDR2dx or EC2 - same result.
73, Lorenz, HB9BMR

**Comment by lc7x** [comment]
Same issue as reported above but on **SDRPRO2**
20221021 Installed on win 10
SDRPRO2 with EC2
Paddle in EC2
Break in

**Comment by HB9BMR** [comment]
Break-In not working as it should (see my earlier post on this subject):
My observation of today:
Time setting "Break in" from 1 ms to 1'000 ms has the effect that the relay in SDR2dx fall off faster or slower.
However, the "TX" button that goes on red with the first dit goes black again very fast. The above time setting has no effect on the "TX" button.
During a certain time, even when hitting the paddle again it does not go red.
TX button should stay red according to the above time setting.
73, Lorenz, HB9BMR

**Comment by HB9BMR** [comment]
With todays 25102022 the break in problem is solved.
Thank you!
73, Lorenz, HB)9BMR
