### ISSUE TITLE
ColibriNANO won't turn on.

### ISSUE THREAD

**Issue by K6TWO** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#452]
Ubuntu 20.04

I have modified the etc\undev\rules.d\ftdi.rules as Roman suggested and SDR3 now lists and launches the ColibriNANO but the power icon is faint and unresponsive to clicks. Power to USB is on. Any Ideas? I'm new to linux so detail help is needed? My SUNSDR2 DX works great under ubuntu! All other devices work great, mouse, keyboard, and thumb drives. Thanks. K6TWO

**Comment by ExpertSDR3** [comment]
Manual

_sudo rmmod ftdi_sio_
_sudo rmmod usbserial_

Now you need to lower access rights to the device, to do this create a file with rules

_/etc/udev/rules.d/ftdi.rules_
Insert the following line in the file (VID and PID of the device are marked with red, which can be known by entering the lsusb command and find the required device in the list)

**SUBSYSTEM=="usb", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6014", MODE="0666", GROUP="plugdev"**

And reload the rules in the linux kernel

_sudo udevadm control --reload-rules_

Disconnect the device from the PC and connect

_sudo rmmod ftdi_sio_

If everything is done correctly, then the device will be available to ESDR3 and should work

**Comment by K6TWO** [comment]
I have modified the ftdi.rules file, but the program launches as it should but the power icon is faint and non responsive. All other buttons respond normally. Attached is my ftdi.rules file. I'm still learning ubuntu so the rules file syntax is new to me. Thank you. I'm 83 and still learning!

BillK6TWO  

    On Sunday, October 9, 2022 at 11:35:05 PM PDT, EE ***@***.***> wrote:  
 
 


Manual

sudo rmmod ftdi_sio
sudo rmmod usbserial

Now you need to lower access rights to the device, to do this create a file with rules

/etc/udev/rules.d/ftdi.rules
Insert the following line in the file (VID and PID of the device are marked with red, which can be known by entering the lsusb command and find the required device in the list)

SUBSYSTEM=="usb", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6014", MODE="0666", GROUP="plugdev"

And reload the rules in the linux kernel

sudo udevadm control --reload-rules

Disconnect the device from the PC and connect

sudo rmmod ftdi_sio

If everything is done correctly, then the device will be available to ESDR3 and should work

**Comment by ExpertSDR3** [comment]
Today, we’ve published a new version of ExpertSDR3 for Linux (https://drive.google.com/drive/folders/1Uj-9FwZ9E9fLMCxaNkHkLHsKEu1oc_gt) (tested on Linux Ubuntu 22.04). The list of improvements: 
1. ExpertSDR3 is installed in the system folder /opt/ExpertSDR3 
2. After the installation, you’ll find shortcuts for ExpertSDR3 and RadioSync in the list of installed software 
3. Installation will automatically create a rule for USB-devices. This way ColibriNANO receiver and  
E-Coder2, E-Coder control panels will work without additional actions with the system 
4. To delete ExpertSDR3 start uninstal.sh, which is placed in the software folder, this also will cancel all mentioned above actions
