### ISSUE TITLE
Tune button emits tone through monitor

### ISSUE THREAD

**Issue by modstermail** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#454]
ESDR3 0.13.0 Build 15092022
Firmware 79.8
PCB 11

When I tune and monitor is on, I hear the tune signal in my speaker.  This never occurred in previous versions.  Can it be muted?  Thanks.

**Comment by ExpertSDR3** [comment]
Turn off monitor button

![image](https://user-images.githubusercontent.com/93903520/197485612-11333dae-4ca6-41b0-8761-b4d2e1e1465c.png)
