### ISSUE TITLE
Ecoder2 latest firmware update issue

### ISSUE THREAD

**Issue by G4POP** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#455]
07102022 release EESDR3-13 alpha - SunSDR 2 DX serial number EED06202110026 - firmware 84.8 PCB revision 11 - Win 11

Latest Ecoder 2 firmware update has caused issue with main program that radio continues to receive signals and play the audio even after EESDR is closed - Need to use task manager to kill software or power SunSDR 2 DX off

If I disable the ecoder in EESDR the program closes normally

Additionally, if the ecoder 2 is enabled the chosen frequency, modes etc in EESDR are not persistent upon a restart

Reverting to 05102022 and previous Ecoder2 firmware fixes issue

Using previous Ecoder2 firmware with 07102022 does not fix the issue

73 Terry G4POP Log4OM

**Comment by HB9BMR** [comment]
SDR2DX in local net. Win 10 PC. EC2. All updated to latest versions including firmware DX and EC2.
Problem: Receive audio does not  come out of EC2 as it used to  be before.
CW paddle wired to EC2. Sidetone comes out of EC2 audio port.
73, Lorenz, HB9BMR

**Comment by ExpertSDR3** [comment]
Fixed
