### ISSUE TITLE
ESDR3 freeze on TX  v. 07102022

### ISSUE THREAD

**Issue by IZ0JNY** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#456]
SunSDR2 PRO - EED05422100908
ESDR 0.13 alpha build 07102022 - firmware 84.8
OS: Windows 11 - 22H2
Ryzen 7 5700G 3.8 GHz , ATI Radeon, 32Gb RAM. SunSDR2 PRO and PC connected via eth switch with short ethernet cables, ping <1ms
Description: when TX is pressed, immediately after ESDR3 freeze and crash. 
Correlations: it happens with ESDR v 0.13 07102022, rolling back to v. 05102022 solve the issue. Changing firmware from 84.8 to 83.8 or previous, does not solve the problem. 
Reproduction steps - see video in my link: http://www.iz0jny.it/wp-content/uploads/2022/10/IMG_6335.mov

**Comment by ExpertSDR3** [comment]
fixed
