### ISSUE TITLE
Writing Calibration fails then disconnects EESDR3

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#459]
EESDR3 0.13.0 alpha build 05102022 and 07102022
Firmware 84.8
SunSDR2DX
Windows 11

Any attempt to write the calibration after any change has been made will result in a pop-up message that the write has failed. Shortly after this the radio will be disconnected. When you re-start the radio, the write actually succeeded.

After the radio is restarted - it sometimes goes into a dysfunctional state that persists through another restart. Changing bands seems to fix the problem though.

This, apparently, only happens with the SunSDR2DX and MB1 and not with the SunSDR2Pro.

https://user-images.githubusercontent.com/13930571/195075921-13978065-e639-4cae-87b9-c4dc46a271fe.mp4

**Comment by hb9bun** [comment]
EESDR3 0.13.0 alpha build **21102022:**
Firmware 84.8
SunSDR2DX
**Windows 10**

Same effect with Build 21102022, SunSDR2DX and Win10. After the failed attempt to write calibration clicking the pop-up allows to retry and then saving works. But the SunSDR2DX is in the dysfunctional state above. Stoping and restarting EESDR does not help to change. The device manager has to be closed and restarted.

**Comment by ExpertSDR3** [comment]
Fixed in firmware 85.8
