### ISSUE TITLE
Окно программы открывается без панели управления

### ISSUE THREAD

**Issue by rvolchkov** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#46]
SunSDR2 PRO
0.10.0
Windows 10

Cannot move the radio window once launched, cannot get the white bar on the top to click and drag it to my other monitor. I have a sunsdr2pro.. and a sunsdr2dx that both run on the same pc on different monitors. I can move the dx software to any position however the pro will not.
This is a youtube video link: https://youtu.be/HQ9e3ab5ceo

**Comment by ExpertSDR3** [comment]
fixed, fixes will be in version 0.11
