### ISSUE TITLE
звук поступающий на вход передатчика.mp3 который после прохождения через тракт передатчика получает НЕПРИЯТНЫЙ АРТТИФАКТ прикрепления в конце фраз в виде остатка шумового хвоста

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#461]
ExpertSDR3 Ver 0.13.0 alpha BUILD 15.09.2022
Win 10 64 ver 21H2
представляю исходный файл который был подан на вход передатчика[входной звук поступающий на вход передатчика.mp3 который после прохождения через тракт передатчика получает НЕПРИЯТНЫЙ АРТТИФАКТ прикрепления в конце фраз в виде остатка шумового хвоста ( это слышно и в эфире и в режиме MONI SSB ) при этом обращаю ВНИМАНИЕ МОДУЛЬ ОБРАБОТКИ PROC ВЫКЛЮЧЕН!!!! Данный файл прилагаю , файл был записан одновременно на SDR RW3PS программой ESDR3 Sound RX1 ( одинаково звучит на выходе PHONES ) файл прилагаю первая часть это запись SDR RW3PS , вторая часть это запись ESDR3 Sound RX1 там это более отчетливо слышно ( одинаково звучит на выходе PHONES ) и в конце сделана запись подаваемого на вход передатчика звук! 
I present the source file that was submitted to the input of the transmitter, the input sound coming to the input of the transmitter.mp3, which after passing through the path of the transmitter receives an UNPLEASANT ARTFACT of attachment at the end of phrases in the form of a residual noise tail (this can be heard both on the air and in MONI SSB mode) at the same time, I pay ATTENTION to the PROC PROCESSING MODULE is TURNED OFF!!!! I attach this file , the file was recorded simultaneously on SDR RW3PS by the ESDR3 Sound RX1 program ( PHONES output sounds the same ) I attach the file the first part is a recording of SDR RW3PS , the second part is a recording of ESDR3 Sound RX1 there it is more clearly audible ( PHONES output sounds the same ) and at the end a recording of the sound supplied to the transmitter input is made!
[входной звук поступающий на вход передатчика.mp3.zip](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/files/9795490/mp3.zip)

**Comment by ExpertSDR3** [comment]
Исправлено
