### ISSUE TITLE
VFO A/B switch via mouse has no effect

### ISSUE THREAD

**Issue by DF2LH** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#464]
SunSDR2DX + EESDR V13 15092022 
Windows 11 - AMD Ryzen 7 + 32Gb of RAM 
NVIDIA GeForce GTX750ti

Hello
I do not know if this behavior has already been corrected since the 15092022 version. If I switch between VFO A and B in split mode with the middle mouse button, the VFO A/B change is displayed on the mouse cursor on the panadapter. If I now turn the mouse wheel, the frequency of VFO A is always changed, never VFO B. 

vy 73 Thomas

https://user-images.githubusercontent.com/26204043/196249696-b03d169a-62d1-490c-b80d-295c0080cf10.mp4

**Comment by ExpertSDR3** [comment]
Fixed
