### ISSUE TITLE
Ошибка в прошивке 79.8

### ISSUE THREAD

**Issue by Nick1953** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#465]
Нет "манипуляции" из  лога N1MM+ с прошивкой 79.8. При установке прошивки 78.8 манипуляция есть.
Также не работает правильно "миксер" при включении двух приемников, т.е. не возможно устанавливать 
сигнал в разные каналы (А или В).
I7700 - 16 GB - 1030 - WIN-10PRO

**Comment by ExpertSDR3** [comment]
Манипуляция работает начиная с версии прошивки 83.8
