### ISSUE TITLE
Issue 453 closed Okej

### ISSUE THREAD

**Issue by sm6usu** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#471]
But it is still half power level when using remote. Tried today with my amplifire Acom 1010. To get 150 watt I have to put in 62% drive level. Normally that gives me 600 watt on the same band (80) So it is still same problem the audio level is between 40-55 % in different bands of my normal 100. (When using without remote.) I having all set in tuning and drive level at Max but still, output about no more than 40-55 %
Other stations can barely hear me. So it is not possible to make a qso. Maybe it will change in the next update? Keep up the good work.
Regards sm6usu Svante

**Comment by ExpertSDR3** [comment]
Fixes will be in the version published after October 24.
