### ISSUE TITLE
Tx  Audio cuts out randomly

### ISSUE THREAD

**Issue by K6TWO** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#475]
Tx  Audio cuts out randomly while using vox. I've played with the vox setting and the noise-gate settings with out solving. It happens on my two dell I7 computer with Windows 10. While talking along, with vox tripped, while the display shows passband audio in red but power output drops to 0! Release of vox reinstates transmit. No discernible patterns has been observed for this behavior, any thoughts.

**Comment by W3FRG** [comment]
I also have exactly the same occurring with my SDR2 Dx, running SDR3 Ver13 build 16092022, FW 80.8.

Tom W3FRG

**Comment by K6TWO** [comment]
EESDR Ver 1.0.3 Beta, Build 10022023 Latest firmware installed, SDR2DX Ser EED06121000386
Dell Alienware  AMD Ryzen 7 6800H With Radeon Graphics Card

Attached is a freeze screen shot of the loss of RF output while still keyed in VOX and Modulation shown in the spectrum display. This occurred near the end of a 6 minute video  captured in Windows  10. However the same phenomenon is present under Ubuntu 20.04 and all versions for the EESDR3 versions, AND it happen under EESDR2 all versions also. It has happened using PTT or VOX with no discernible pattern! 
![No power out2](https://user-images.githubusercontent.com/96986632/229326610-b3e48084-b586-4568-922e-878468b2b020.JPG)

**Comment by K6TWO** [comment]
First off my current system:
EESDR2DX with ESDR1.0.3 BETA Build 10022023
Dell AlienWare M17R5 CPU RYZEN 7 6800H 3.2GH 16GBmem 64 Bit
GPU RYZEN 6700M 10GB mem
EESDR2DX Via Ethernet to ATT Router via Ethernet to Alienware Computer.
Windows 11 Build ? latest Update 2023-04 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5025239)
I've us Ethernet cable direct to the computer during testing with no change in outcomes.

Now here is a key data point. This is the fourth Dell computer that I have used with EESDR3, all flavors and EESDR2 Ver 1.3.1 update 11 and I have noticed the same phenomenon on all systems, hardware and software! And I've tried it in UBUNTU 22.04 with the same RF dropout occurring.

Now the results of changing priority settings for EESDR3: on this Alieonware system, Winn11, I increased the priority to "(High and again later to Realtime)" and still had failures of RF drop out during transmit! I've tested the above named changes on two different computers and get the same results. It is random and unless your watching the Power output meter, you will not know RF output stopped! Unkeying or VOX time out will restore RF Output. Changing VOX sensitivity, delay, or threshold have no impact. When using a hand mic PTT keeping it keyed, while talking several sentences over a ten minute period will generally produce the phenomenon. It is not the PA timeout feature in the DX.

I've noticed that it seems more frequent when, at the pause between sentences, while speaking in a flowing verbalization of a subject.

This should help other to verify my findings or disprove them .

**Comment by K6TWO** [comment]
Okay here are some more data points:  Nine Dell  Programs running in processes Dell Data Manager, Dell Data  Vault Data Collector, Dell Data Vault Rules Processor, Dell Diagnostics, Dell instrumentation, Dell User Session Agent, Dell.D3WinSvc, Dell.DCF.UA.Bradbury.APSub..., And Dell TechHub. The most active while I transmit is the Dell Diagnostics at  an intermittent .2% CPU.  I tried a new VOX delay parameter of 1 sec to capture and hold the RF  dropout.  I was able, while speaking a fully detailed description of my  HAM setup, to capture and hold the RF output dropout while inspecting  the complete Dell  APPs CPU usage, but there were no changes before the  RF dropout and after the dropout while VOX was active. I did a second  run and when the dropout occurred, I scanned the remaining processes CPU  activity with nothing apparently different than a non-dropout  as far  as CPU usage. However with the VOX delay set at 1 sec I was able to  capture the RF dropout within a couple to three minutes of talking!  AND  when the RF dropped out so did the Monitor signal!! Yet the meter  showed 0 RF output AND it showed the the Mic signal going up to 0 dbm  and the red spectrum for the RF! was normal!!  Thanks again for your time. I'm looking for the root cause so I can continue to use this fine piece of hardware and software!
--

**Comment by K6TWO** [comment]
I have now de-serviced all Dell bloatware found in msconfig system. I rebooted and relaunched V3 and I still am having RF Dropouts. It is not the Dell Bloatware. This happens whether I use Ethernet direct to PC or via router from SDR2DX.

Thanks for your input. I'm still looking for a path to solve this problem. It may occur in other SDR2DX but yet detected by the user.

**Comment by GregTroar** [comment]
Hello,

This is duplicating the post on the forum here: [Topic](https://eesdr.com/en/forum-en/connection-to-third-party-software-esdr3/10229-random-loss-of-rf-output-during-ssb-exchanges-while-using-vox-ptt?limitstart=0)

Mine happens with virtual audio cable a lot !
It is completely unusable.

I am on windows 11 with all updates up to date (30th November 2023).
TCI works perfectly fine.

When I need to use audio cables I use the VAC software [VAC](https://vac.muzychenko.net/en/)
I have created 2 audio cables and I do confirm that these 2 cables works absolutely fine with a Hermes Lite 2 with Thetis I face no issues at all.

When I start transmitting a FT8 Signal (same with RTTY or any other digitial mode) the power jumps from 50w down to 0 then up to 10 watts and down to 0 and up to 20 watts and so on... in one 15 second transmission. Sometimes it goes to 0 for the entire 15 sec period.
I could do a video if you need !??!?

My config is:

MSI Carbon X399
AMD Threadripper 2920x
32Gb Ram
SSD 512Go
Windows 11 22H2
ESDR3 1.0.5 Beta
I am using a SunSDR2DX Serial: EED06202100638

Exactly the same issue using RigSync with TCI + Audio with same virtual audio cables.

Any other info needed please let me know.

I cannot use digi modes at all with the SunSDR2DX, I have to use another radio unless I have TCI available in the application I use but which is not the case for a lot of them.

Thanks

**Comment by W3FRG** [comment]
I deleted the EESDR3 Ver 1.0.5 Beta using REVO uninstaller and then running
CCleaner.
I also deleted all downloads of EESDR3 SW in the Downloads directory.
Restarted PC.
I then reinstalled the EESDR3 Ver 1.0.5 Beta.
It's working better than ever, no issues as previously found.
My PC is a DELL 7040 Intel i7 Proc. running W10 Pro.

Its less than a month and the EESDR3 Ver 1 should be released
That should be interesting.

Tom W3FRG

**Comment by W3FRG** [comment]
I neglected to state that I also use TCI and run FT8 .
My SunSDR2 Dx is a Gen 5 unit.
I'm running EESDR3 Ver 1.0.5 Beta
I also found that no RF is transmitted if you select the FT8 box,
instead use USB, and you will see the Transmit on the display.
I only run 60-70w maximum transmit power on the weak signal programs.
Tom W3FRG

**Comment by GregTroar** [comment]
Tom,

Which FT8 box are you refering to ?
I will try to do a clean uninstall of EESDR3 and see if I am lucky as well but I have always had this issue of no RF while using VAC in EESDR3, I thought it was coming from my AUdio cables until I got a Hermes Lite and used the same VAC without any issue in Thethis.

Obviously I much prefer the look and design of EESDR3 but if I cannot get the VAC to work it is kind of a deal breaker :(

**Comment by W3FRG** [comment]
It's under the MODE Box adjacent to the frequency readout on the main
display.
I have no working knowledge of VAC or the Hermes Lite.

**Comment by GregTroar** [comment]
ok you are talking about the FT8 mode, yes it is in the manual that it has not been implemented

**Comment by GregTroar** [comment]
Dunno why this was marked as completed. Definitely not working on my side.
FT8 in USB with VAC is unusable

**Comment by VK6NX** [comment]
> Dunno why this was marked as completed. Definitely not working on my side. FT8 in USB with VAC is unusable

Because it is fixed in 1.0.6 beta. 

You have to understand how the bugfix flow works in programming:
- you reported it, devs are looking into it and closing when fixed. 
- When fix version (1.0.6 in this case) is published (in few days), you are expected to test it
- if bug is still present - reopen the bug report with proper data.
