### ISSUE TITLE
ESDR3 crash on TX v. 25102022

### ISSUE THREAD

**Issue by IZ0JNY** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#477]
unSDR2 PRO - EED05422100908
ESDR 0.13 alpha build 25102022 - firmware 85.8
OS: Windows 11 - 22H2
Ryzen 7 5700G 3.8 GHz , ATI Radeon, 32Gb RAM. SunSDR2 PRO and PC connected via eth switch with short ethernet cables, ping <1ms
Description: when TX is pressed, immediately after ESDR3 freeze and crash.

this issue: https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/issues/456  fixed with version 21102022 already, is now present again in my configuration with new version of ESDR3. 

The only difference is that is not freezing, but is going directly on crash. Tried several times, I had to roll-back to version 21102022 in order to continuing using ESDR3.

**Comment by ExpertSDR3** [comment]
More information is required, since it is not possible to reproduce it at home.
Could you attach a video showing the connection of the equipment to SunSDR2PRO and the action leading to the crash of the program?

**Comment by IZ0JNY** [comment]
I followed suggestion of VK6PI on EE telegram chat, saying that: 

it was discussed numerous times - do not use 22H2. Divert it to 21H2 and freeze there (use any kind of "tweaker" to stop automatic updates). 
Example of tweaker to use: https://www.w10privacy.de/english-home/

after installed the software he suggest, to modify privacy settings of Win11, the ESDR3 did not give any problem anymore. 

I'll close the ticket considering is a O.S. related topic and not ESDR3.
