### ISSUE TITLE
не правильная работа индикатора Boost в модуле PROC!!!!

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#48]
не правильная работа индикатора Boost в модуле PROC !!!
на вход передатчика подан  сигнал генератор 1000Гц с уровнем 0 dB! ВСЕ  УСТРОЙСТВА В МОДУЛЕ ОТКЛЮЧЕНЫ!!!
 При этом ИНДИКАТОР  BOOST  отображает , что уровень  сигнала  составляет около минус 8 dB 
![input 0 dB](https://user-images.githubusercontent.com/93991940/141800194-ce89edfc-916e-42ac-b0aa-06ad082b3249.jpg)
![input 0 dB BOOST](https://user-images.githubusercontent.com/93991940/141800254-56291562-0fef-4a2c-b46e-3b9756c22e1d.jpg)
Индикатор Boost проверен на калибровку показаний!!! показывает НЕ ПРАВИЛЬНО!!!
Подан сигнал генератор минус -12 dB 
![bandicam 2021-11-15 16-50-45-295](https://user-images.githubusercontent.com/93991940/141800900-3c030794-d7e7-4f0d-bab9-bb9cec7137d3.jpg)
при этом индикатор Boost показал НЕ ПРАВИЛЬНО!!!
![-12 индикатор Boost](https://user-images.githubusercontent.com/93991940/141801094-88a45387-a838-46e3-b74a-566db7b09c6b.jpg)
Подан сигнал с генератора  уровнем минус 24 dB 
![bandicam 2021-11-15 16-53-35-802](https://user-images.githubusercontent.com/93991940/141801734-76beb376-4cba-450b-bddd-06cc13799868.jpg)
 ПОКАЗАНИЯ ИНИКАТОРА BOOST НЕ ВЕРНЫ!!!!
![-25dB индикатор Boost](https://user-images.githubusercontent.com/93991940/141801977-d486214e-dd15-4885-a4bc-419c7f068fbb.jpg)
Подан сигнал с генератора уровнем минус 36dB
![bandicam 2021-11-15 16-55-19-634](https://user-images.githubusercontent.com/93991940/141804072-41ebc8dd-1443-49c4-850a-2c0bb122b4cd.jpg)
 ПОКАЗАНИЯ ИНИКАТОРА BOOST НЕ ВЕРНЫ!!!!
![-35 индикатор Bost ](https://user-images.githubusercontent.com/93991940/141804438-56ffc4be-2274-4e78-b65c-be39588657f4.jpg)
УРОВЕНЬ МИНУС 48dB  ПОКАЗАНИЯ  ОТСУСТВУЕТ ВООБЩЕ!!!

**Comment by 1972igor** [comment]
Методика регулировки такова
1 РЕГУЛЯТОР УСИЛЕНИЯ MIC PC устанавливаем в уровень значения 0 dB (БОЛЬШЕ ЭТОТ ДВИЖОК НЕ ТРОГАЕМ !!!
2 Подаём  с источника  генератор  с уровнем 0 dB и регулятором выхода источника добиваемся показаний индикатора MIC METER до  уровня 0dB  БОЛЬШЕ ЭТОТ ДВИЖОК НЕ ТРОГАЕМ !!
затем подаём остальные  генераторы ( НЕ трогая  движок усиления ) и программе корректируем показания Mic meter, индикатор Boost. показания на ПАНАДАПТОРЕ !
КАЛИБРОВКА ПОКАНИЙ ПО ВХОДАМ MIC1 и MIC2 Аналогична!!!

**Comment by 1972igor** [comment]
Методика регулировки такова
1 РЕГУЛЯТОР УСИЛЕНИЯ MIC PC устанавливаем в уровень значения 0 dB (БОЛЬШЕ ЭТОТ ДВИЖОК НЕ ТРОГАЕМ !!!
2 Подаём с источника генератор с уровнем 0 dB и регулятором выхода источника добиваемся показаний индикатора MIC METER до уровня 0dB БОЛЬШЕ ЭТОТ ДВИЖОК НЕ ТРОГАЕМ !!
затем подаём остальные генераторы ( НЕ трогая движок усиления MIC PC, MIC1, MIC2 ) и контролируем показания  Mic meter, индикатор Boost. показания на ПАНАДАПТОРЕ при одном тоне генератора эти индикаторы должны показывать одинаковые значения! !
КАЛИБРОВКА ПОКАНИЙ ПО ВХОДАМ MIC1 и MIC2 Аналогична!!!

**Comment by 1972igor** [comment]
Методика проверки индикаторов уровней  такова
1 В закладке  "PROC" звуковые модули должны быть выключены !!!
2 РЕГУЛЯТОР УСИЛЕНИЯ MIC PC устанавливаем в уровень значения 0 dB (БОЛЬШЕ ЭТОТ ДВИЖОК НЕ ТРОГАЕМ !!!
3 Подаём с источника генератор с уровнем 0 dB и регулятором выхода источника добиваемся показаний индикатора MIC METER до уровня 0dB БОЛЬШЕ ЭТОТ ДВИЖОК НЕ ТРОГАЕМ !!
затем подаём остальные генераторы ( НЕ трогая движок усиления MIC PC, MIC1, MIC2 ) и контролируем показания Mic meter, индикатор Boost. показания на ПАНАДАПТОРЕ при одном тоне генератора эти индикаторы должны показывать одинаковые значения! !
КАЛИБРОВКА ПОКАНИЙ ПО ВХОДАМ MIC1 и MIC2 Аналогична!!!

**Comment by 1972igor** [comment]
Методика проверки индикаторов уровней такова
1 В закладке "PROC" звуковые модули должны быть выключены !!!
2 РЕГУЛЯТОР УСИЛЕНИЯ МИКРОФОН PC устанавливаем в уровень значения 0 дБ (БОЛЬШЕ ЭТОТ ДВИЖОК НЕ ТРОГАЕМ !!!
3 Подаём с источника генератор с уровнем 0 дБ и регулятором выхода источника добиваемся показаний индикатора MIC METER до уровня 0dB БОЛЬШЕ ЭТОТ ДВИЖОК НЕ ТРОГАЕМ !!
затем подаём генератор с нужным шагом ослабления  ( НЕ трогая движок усиления MIC PC, MIC1, MIC2 ) и контролируем показания Mic meter, индикатор Boost. показания на ПАНАДАПТОРЕ при одном тоне генератора эти индикаторы должны показывать одинаковые значения! !
КАЛИБРОВКА ПОКАНИЙ ПО ВХОДАМ MIC1 и MIC2 Аналогична!!!

**Comment by 1972igor** [comment]
Методика проверки индикаторов уровней такова
1 В закладке "PROC" звуковые модули должны быть выключены !!!
2 РЕГУЛЯТОР УСИЛЕНИЯ МИКРОФОН PC устанавливаем в уровень значения 0 дБ (БОЛЬШЕ ЭТОТ ДВИЖОК НЕ ТРОГАЕМ !!!
3 Подаём с источника генератор с уровнем 0 дБ и регулятором выхода источника добиваемся показаний индикатора MIC METER до уровня 0dB БОЛЬШЕ ЭТОТ ДВИЖОК НЕ ТРОГАЕМ !!
4 Подаём генератор с нужным шагом ослабления ( НЕ трогая движок усиления MIC PC, MIC1, MIC2 ) и контролируем показания Mic meter, индикатор Boost. показания на ПАНАДАПТОРЕ при одном тоне генератора эти индикаторы должны показывать одинаковые значения! !
КАЛИБРОВКА ПОКАНИЙ ПО ВХОДАМ MIC1 и MIC2 Аналогична!!!

**Comment by 1972igor** [comment]
Методика проверки индикаторов уровней такова
1 В закладке "PROC" звуковые модули должны быть выключены !!!
2 РЕГУЛЯТОР УСИЛЕНИЯ МИКРОФОН PC устанавливаем в уровень значения 0 дБ (БОЛЬШЕ ЭТОТ ДВИЖОК НЕ ТРОГАЕМ !!!
3 Подаём с источника генератор с уровнем 0 дБ и регулятором выхода источника добиваемся показаний индикатора MIC METER до уровня 0dB БОЛЬШЕ ЭТОТ ДВИЖОК НЕ ТРОГАЕМ !!
4 Подаём генератор с нужным шагом ослабления ( НЕ трогая движок усиления MIC PC, MIC1, MIC2 ) и контролируем показания Mic meter, индикатор Boost. показания на ПАНАДАПТОРЕ при одном тоне генератора эти индикаторы должны показывать одинаковые значения! !
ПРОВЕРКА ПОКАНИЙ ПО ВХОДАМ MIC1 и MIC2 Аналогична!!!

**Comment by ExpertSDR3** [comment]
исправлено

**Comment by 1972igor** [comment]
СПАСИБО !!! НАКОНЕЦ  ИСПРАВИЛИ УРА!!!
