### ISSUE TITLE
Sounds terrible

### ISSUE THREAD

**Issue by sm6usu** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#480]
The new Beta autostart does not work good. The audio is terrible when tranceiver starts. So I have to start as earlier with start button and then all is good. (No big deal)

Windows 11
Navidia 3090 ti
 Regards sm6usu Svante

**Comment by sm6usu** [comment]
Hi sm6usu  again I am using setting directx 11 and tried Vulcan and problem disapeard. Back to Directx and problem is there. Started my laptop with the new Beta with windows 10 and Directx11 no problem with audio in autostart. So it is only when I have directX 11 in Windows 11 the problem is there in autostart.
73 de sm6usu Svante

**Comment by sm6usu** [comment]
Hmmm I was wrong it is same problem Vulcan and DirectX11
sm6usu Svante

**Comment by OK2WY** [comment]
the same behavior here. Distorted audio, spectrum displayed erraticaly and refreshed slowly. After changing sampling freq. to another value (or switching off and on by on/off button in user interface) everything is okay until switched off.

**Comment by sm6usu** [comment]
Yes I have same experience. But using my Laptop with windows 10 I have no problems. Only in windows 11
73 de sm6usu Svante

**Comment by VK6NX** [comment]
just wonder - if it is no problems on "Laptop with windows 10" and only problems on windows 11 (presuming different PC??) - then how it is ESDR3 problem? 

Congradulations on Topic header. Really informative and attractive.

**Comment by VK6NX** [comment]
I guess you are miss interpreting the purpose of this tool. 

[ExpertSDR3-BUG-TRACKER] is about bugs in ESDR3.

For Windows 11 bugs perhaps it s better to log the case with Microsoft. Because EE is certainly not responsible for whatever MS does in Win11, specifically in 22H2 and further updates.

**Comment by sm6usu** [comment]
To OK2WY Have a couple of quick test starts with auto start and OpenGl in Windows 11. It seems to work. Future will tell.
sm6usu Svante
