### ISSUE TITLE
ESDR3 1.0 beta "падает" в режиме CW

### ISSUE THREAD

**Issue by RX3RZ** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#481]
Трансивер SunSDR2DX
ОС - Windows 11 x64
ExpertSDR3 1.0 beta
После установки версии beta в режиме CW программа "падает" (закрывается) с периодичностью около 5 минут. В телефоне и цифре всё работает как положено.

**Comment by ExpertSDR3** [comment]
Напишите, какое ПО подключено к TCI и примерно как работаете, что бы мы могли воспроизвести у себя вашу ситуацию и найти проблему.

**Comment by RX3RZ** [comment]
Провёл сегодня эксперимент. Имеем ПК, ОС Виндовс 11, трансивер SSDR2DX и программа ESDR3 1.0 beta. В трансивере выбран режим CW, манипулятор подключен непосредственно к трансиверу через штатное гнездо. Работкаю на передачу (даю общий вызов) с паузами на приём. Где-то через три минуты во время передачи изображение на экране монитора замирает, но при этом трансивер ещё остаётся в режиме передачи и манипуляция работает. Потом через несколько секунд слышен звук релюшек в трансивере, программа "падает", т.е. закрывается (у трансивера на передней панели горит зелёный светодиод). Вот так.
Примерно так же происходило в связке SSDR2DX+ESDR3+LogHX3/5MContest+SDC в субботу.
ESDR3 обновил в пятницу после стрима с перепрошивкой трансивера.
До этого использовал июльскую версию SSDR3 13 alfa, всё работало как часы.

**Comment by RX3RZ** [comment]
Трансивер и ПК общаются по TCI, патч-кордом соединяясь на прямую трансивер-сетевая карта ПК.

**Comment by YL3BU** [comment]
Подтверждаю, та же ситуация c трансивером SunSDR2PRO и ExpertSDR3 1.0.0 beta 28.10.2022:
РС: AMD Ryzen7 5800H 3.20 GHz, 16G RAM, Display adapter NVidia GeForce RTX 3050 Laptop GPU (в системе прописана для ExpertSDR3 жёстко).
OS: Windows 11 Home x64, Version 21H2, OS build 22000.1098 .
PC - SunSDR2PRO сетевое соединение напрямую.
E-Coder2 подключен с последней версией прошитой утилитой "Ecoder2Firmware.exe" 28.10.2022.
Подключенные по TCI программы: SDC 152401x64 (2021) и LogHX v3.0 build 704.
Проверял именно в CW, в других режимах не работаю. 
ExpertSDR3 запускается, какое-то время работает. Может сама "слететь" (закрывается окно), но чаще при передаче причём не сразу, а в середине QSO. Именно примерно так, как описывает создатель этой темы RX3RZ.
После рестарта программы все установленные настройки E-Coder2 утеряны - необходимо его включать и абсолютно всё прописывать заново.
P.S. В соседней ветке немецкий радиолюбитель (правда работающий SSB) предположил, что виноват подключенный E-Coder2 - нужно будет проверить. Кстати, вот уже около часа сижу с отключенным E-Coder2, читаю GitHub, пишу этот текст и слушаю ExpertSDR3 1.0.0 - не слетает. Но нужно ещё передачу проверить.

**Comment by VK6NX** [comment]
@YL3BU 
@RX3RZ

Попробуйте, пожалуйста, будет ли подобная картина без Ecoder2? Если можно - оба варианта: с Ecoder2 включенным в USB но не включенным в программе и Ecoder2 выключенным полностью (не воткнутым в USB).

@ExpertSDR3 - взял (временно) у знакомого Ecoder2 потестить - у меня падает (без закономерности) только когда Ecoder2 включен в программе. Когда выключен в программе или вынут из USB (без предварительного выключения в программе) - все работает штатно.

**Comment by RX3RZ** [comment]
после установки версии от 1 ноября проработал телеграфом 20 минут, баг не проявился. Спасибо за исправление. 73!

**Comment by YL3BU** [comment]
@VK6NX 
Отключил E-Coder2 (SN: EEA125121000121) и проработал около 4-х часов - нет проблем, ESDR3 не зависала, не отключалась - ОК. 
Вторую часть предложенного эксперимента (Кодер подключен физически, но отключен программно) не успел.
Вышла новая версия ESDR3 1.0.0 beta 01112022. Конечно обновил её и, на всякий случай, ещё раз перепрошил свой E-Coder2 с помощью "Ecoder2Firmware.exe".
@ExpertSDR3 
После обновления, ESDR3 1.0.0 beta 01112022 действительно перестала "виснуть" и продолжает работать - можно пользоваться мышкой.
ОДНАКО, сама панель E-Coder2 "зависает". Где-то посредине первого же CW QSO  она перестаёт работать, не реагирует даже на основной валкодер перестройки по диапазону, ну и также на все остальные кнопки и малые валкодеры. Также горит постоянно красный светодиод напротив среднего малого валкодера. После закрытия ESDR3, и даже выключения компа, зелёная подсветка на нём горит. Также после рестарта ESDR3 все настройки E-Coder2 кнопок и всех валкодеров слетают и всё нужно строить заново.
@RX3RZ
Пожалуйста проверьте подольше, с реальными QSO, работу ESDR3 1.0.0 beta 01112022 совместно с Вашим E-Coder2.
Подтвердите, что Ваш E-Coder2 не зависает (проведите 1...3 QSO хотя-бы) и не теряет всех настроек при рестарте или повторном запуске ESDR3.
@ExpertSDR3
На странице ExpertSDR3 пишется, что софт тестируется на процессорах Intel, но у меня и коллег здесь, как я понял, компьютеры с процессорами AMD Ryzen (смотрите моё описание выше). 
Насколько это влияет на работоспособность программы ExpertSDR3? 
Нужно ли мне менять компьютер чтобы пользоваться трансиверами SunSDR2 ?
P.S. ESDR2 у меня работает стабильно, правда без всех новых "вкусностей"...

**Comment by VK6NX** [comment]
ExpertSDR3 software is being tested on the latest versions of Windows 10, Linux Ubuntu 22.04, and macOS 12 (with Intel CPU) - про Intel имеется в виду  только "под маком" (просто потому что у ЕЕ сейчас нет компа под М1). Но параллельно софт тестируется внешними тестерами (не сотрудниками ЕЕ) и на М1-М2 и под виндой на разных версиях процессоров.

Так что никакие компы менять не надо, все должно работать. Потому что фреймворк Qt6 на котором ЕЕ пишет - универсальный и должен работать под любой платформой. У меня ESDR3 даже на виртуальной arm64 под экспериментальной кривой Вин11 работает. Другое дело, что у винды есть свои нюансы и привычные настройки (как в винде с ESDR2) могут не работать и будут требовать изменения подхода. Как пример - ASIO драйвера под виндой не будут работать до тех пор, пока либо Винда не внесет их в список официально поддерживаемых, либо пока производители этих ASIO драйверов не озаботятся обновить свой софт и сделать его совместимым с Qt6. У мака с этим делом гораздо проще, но только за счет того, что маку никакие внешние аудио драйвера никогда нужны не были.

С Ecoder2 - пока что он не вылизан до конца, так что глюки могут быть и их надо плотно тестировать на каждой выходящей версии, потому что их правят, что назыввется, вот "прямо сейчас". И любые отклонения от нормы - сюда на Гитхаб постить с максимально подробным описанием. Ecoder2 очень сильно отличается от всех остальных версий Ecoder, и это буквально "комп в компе" со своим отдельным софтом.

**Comment by RX3RZ** [comment]
@RX3RZ Пожалуйста проверьте подольше, с реальными QSO, работу ESDR3 1.0.0 beta 01112022 совместно с Вашим E-Coder2. Подтвердите, что Ваш E-Coder2 не зависает (проведите 1...3 QSO хотя-бы) и не теряет всех настроек при рестарте или повторном запуске ESDR3. 

Провёл вчера 3 полных QSO телеграфом. Манипулятор подключен к трансиверу, а не к E-Coder2. Всё работает, ПО не "падает", E-Coder2 функционирует и настройки уже очень давно не слетали. Правда был вечером в самом начале случай, описанный вами. Как он начался я не могу вспомнить, но горел диодик по центру и реакции от E-Coder2 не было. Закрыл программу ESDR3, выключил трансивер, но E-Coder2 оставался включенным - повис. Я отсоединил его от порта USB. Подсветка на E-Coder2 погасла. Снова подключил екодер, включил трансивер и запустил ESDR3. Более никаких глюков не было.
С ESDR2 не работал совсем. С ESDR3 использовал два системника - оба на процессорах от AMD: RYZEN 5 и 7. Нареканий в принципе нет.

**Comment by ExpertSDR3** [comment]
[YL3BU](https://github.com/YL3BU) Подобное замечание с зависанием панелью, что сама панель зависает, есть в единственном случае, возможно питание USB порта недостаточное, можно попробовать использовать другой порт USB.

**Comment by VK6NX** [comment]
Да, с последней бетой все работает, вроде.

Ну и нашелся вредитель по питанию, заодно. На маке порты USB все больше ампера, так поди ж ты, корейский кабель на котором по спецификкации 1А должен быть - держит аккурат 480мА. Самсунг его в качаль. Екодер пришлось товарищу отдать, так что надежда по вылову багов на нем остается только на вас :)

**Comment by YL3BU** [comment]
@ExpertSDR3 Купил простой [USB-тестер UNI-T UT658](https://uni-t.ua/ru/catalog/usb-tester-uni-t-ut658/) и проверил подключение своего E-Coder2 (SN: EEA125121000121) к порту USB 3.2Gen1 своего Lenovo Legion 5 (спецификация выше):
1. Ничего не подключено: на USB порту U=5.06 V ну и конечно I=0mA;
2. Подключен E-Coder2, но программа ESDR3 не запущена: U=5.03V, I=370mA;
3. Подключен E-Coder2 и ESDR3 запущена: U=5.02V, I=400...430mA (интерфейсы самого E-Coder2 не используются).

Я думаю, что с питанием E-Coder2 от USB порта всё ОК.
Кстати, может в E-Coder2 сделать физическую кнопку Вкл./Выкл. питания?

Программа ESDR3 (1.0.0 beta 01112022) с подключенным E-Coder2 радовала меня спектром и водопадом минут 30, пока мы ужинали и пили чай, а потом сама закрылась. Когда вернулся на место и перезапустил программу, обнаружил, что настройки е-кодера не слетели, как это было раньше - это хорошо.

**Проверил TX.** Пошёл на 40м, Tune 20% (кнопкой на панели) подстроил авт. антенный тюнер до SWR 1.2, Drive 94%, CW, наушники Kenwood HS-5 и ключ подключены в трансивер, 2 метра CAT6 кабеля PC-TRCVR, почти всё обвешано ферритовыми защёлками. На панели запрограммированными кнопками: LOCK заблокировал частоту, кнопкой первого валкодера включил RIT и проверил. Буквально на второй серии короткого CQ (по два раза CQ и Call) заметил, что я передаю либо ключём, либо макросом из LogHX и потом слушаю эфир, но на панели E-Coder2 постоянно горит красный светодиод посредине. Проверил - ни кнопки, ни валкодеры панели не работают. Панель можно отставить в сторону и продолжать работать мышкой - сама ESDR3 не зависла, и это радует. 
Чтобы оживить E-Coder2 мне потребовалось полностью рестартовать программу вместе с первым окном загрузчика.
Вот как-то так.
Извиняюсь за много букв (не всегда есть столько времени для этого), но может действительно я что-то не учитываю или пропускаю. У всех работает, а у меня нет :)
P.S. Кстати, спасибо @ExpertSDR3 и Роману за разъяснения по поводу процессора PC !

**Comment by VK6NX** [comment]
430 мА = мало. Потому и падает и зависает. 

А тестер показывает 430мА скорее всего потому что порт просто не не может отдать больше. Второй екодер требует минимум 0.5А. У меня в тестах порт показывал от 0.570А до 0.610А в зависимости от того, подключались ли в Екодер уши и манипулятор или нет.

Попробуйте найти USB хаб с внешним питанием и гарантированными >0.5A на порту и попробовать включить Екодер через него.

Ну или ищите подробную спецификацию своей модели компа, бывает (но редко) что производитель указывает сколько он подает максимально тока через какой порт. Увы, но к сожалению, спецификация, что такой-то порт = USB3 совсем не означает, что на нем будет именно 1.5A, особенно на ноутбуках. Практика показывает, что запросто может быть меньше.

**Comment by YL3BU** [comment]
@VK6NX  Да-а-а... Я Вас понял!
Спасибо за инфо о реальных токах потребления вторым е-кодером.
Теперь у меня возникает мысль, что **было бы хорошо снабдить E-Coder2 также гнездом подачи внешнего питания 5 вольт от розетки через адаптер**. Для меня это было бы **гораздо проще**, чем искать USB-хаб с внешним питанием который гарантированно обеспечит заданный ток.
P.S. Да, я перерыл интернет и сайт Lenovo чтобы найти для своего Lenovo Legion 5 информацию о токах в USB интерфейсах - всё тщетно :(

**Comment by VK6NX** [comment]
Ну модификацию вам никто не мешает сделать, только с гарантией вопрос. По хорошему еще и USB порт надо делать на всех Екодерах, чтобы юзер сам нужный шнур подбирал. Мне, например, чтобы в мак воткнуть - надо еще и переходник на USB-C, а они тоже не всегда спецификации соответствуют по току.

Учтите только, что токи которые я намерял - это с того Екодера, который я брал потестить (у меня свой основной ECoder Plus). Не уверен, что токи будут в этих пределах на других "двойках" - наверное будет зависеть и от режима, и от того, сколько в него периферии воткнуто и какой.

**Comment by YL3BU** [comment]
@VK6NX Проверил USB порт ноутбука: 
Взял свой подразряженный Samsung S10+ и померил ток его зарядки этим же тестером I=1.5A при U=5.01V.
Переключил телефон на испытуемый USB порт ноутбука и зарядка продолжилась с параметрами U=4.97V  I=950mA.
Так что USB порт ноутбука может обеспечить до 950mA,
Тут же подключил свой E-Coder2, запустил все программы и включил трансивер. Ток потребления моего е-кодера плавает от 400 до 430 mA при U=5.02V и более он просто сам не хочет потреблять.
Может мне попался какой-то новый, модернизированный и экономичный E-Coder2 (SN: EEA125121000121) ?
Куда теперь копать?

**Comment by VK6NX** [comment]
Программисты говорят, что ваши измерения ближе к тому, что должно быть. Скорее всего либо я что-то неправильно мерял, либо у меня что-то дополнительно грузит +100мА. 

В ближайшее время должна новая версия беты быть. Я бы долждался ее и снова протестировал.

**Comment by YL3BU** [comment]
@VK6NX , @ExpertSDR3 , @rvolchkov 
Часа два назад установил сегодняшний релиз ExpertSDR3 1.0.1 Beta. 
Полчаса понаблюдал на приём - вроде ОК.
Позвал на 40м финна, посредине QSO заметил постоянно горящий красный светодиод посредине E-Coder2. Покрутил валкодеры, понажимал кнопки - панель "повисла". Её включение/отключение в ESDR3 программе ничего даёт. Закрыл все программы и выключил комп. Панель так и стоит с красным светодиодом и подсвеченным большим валкодером. Нужно её физически отключать от компьютера. 
В этом смысле ExpertSDR3 1.0.1 Beta версия ничего, к сожалению, конкретно у меня, не поменяла.

**Comment by VK6NX** [comment]
Если вы до беты ставили любую альфу - попробуйте удались все настройки (в Appdata/Local и Roaming, перегрузиться и протестить снова.

Только перед удалением настроек запишите или сделайте скриншоты - удаление этих папок это жесткий сброс настроек к дефолтным.

Если альфу не ставили, а толькоо беты - то это  смысла сбрасывать настройки нет, там не будет конфликтов. Но в этом случае я пока идей не имею больше.

**Comment by YL3BU** [comment]
@VK6NX  Да, альфы ставил и чуть-чуть на них работал - переключался то на ESDR2,то на ESDR3. Но потом у меня появился E-Coder2...
Но переставлять ОС я, конечно, страшно не хотел бы.

**Comment by VK6NX** [comment]
Ну тогда удаление настроек стоит пропрбовать. В нескольких последних альфах было изменения ряда параметров, которые могут не только с бетой конфликтовать, но и с ESDR2.

**Comment by RX3RZ** [comment]
Поставил ESDR3 1.0.1 beta телеграф работает - проблема ушла. Но появилась новая пару раз зависал E-Coder2 наглухо, но при этом софт работает. Е-кодер зависал в режиме работы сплитом. Я ни три кнопочки закрепил SPLIT, A>B, A<>B. При работе с DX сплитом активно использую A<>B, т.к. необходимо слушать где зовут корреспонденты с целью стать на частоту того, кому DX ответил.
Для восстановления работы зависшего E-Soder недостаточно его переключить по usb. Приходится гасить трансивер и ПО.

**Comment by YL3BU** [comment]
@RX3RZ Судя по Вашему описанию, ситуация намного лучше, чем у меня. 
Я понял, что Вы можете минутами или, даже, получасами проводить обычные CW связи. 
E-Coder2 у Вас зависает только когда Вы начинаете гоняться за DX-ом, в режиме Split, активно переключаясь между VFO и активно работая на передачу.
Интересно, а если Вы попробуете просто на диапазоне без прохода настроиться подальше от всяких DX частот, выставить мощность TX 2 ватта (вообщем чтобы никому не мешать) и ключом или макросом попередавать фразу "v v v de RX3RZ k" делая паузу между фразами 4...5 сек. примерно. 
Сколько полных раз Вам удастся передать эту фразу до зависания е-кодера?

**Comment by YL3BU** [comment]
@VK6NX Вчера сделал такой эксперимент, отписываю сегодня по памяти.
1) Удалил программы ExpertSDR2 и ExpertSDR3. 
2) В системе включил опцию видеть скрытые системные файлы.
3) В папке Appdata/Local удалил вообще все файлы и фолдеры, включая "головной" Expert Elecnronics.
4) В папке Appdata/Roaming ничего от ЕЕ не было.
5) Пробежался по другим системным папкам и ничего вроде не нашёл.
6) Снёс ExpertElectronics уже пустой фолдер в Program Files (ну это так, по инерции...)
7) В Documents нашёл и удалил сохранённые файлы профилей ESDR. 
8) В Explorer включил поиск по ключевым фразам - вроде больше ничего не нашёл.
9) Установил ExpertSDR3 1.0.1 Beta.
10) С файрволом и 5000х портами всё ОК.
11) Запустил ExpertSDR3 - всё как с чистого листа.
12) Быстро сделал некоторые настройки настройки программы, E-Coder2 и т.д.
13) На закрытой без прохода 10-ке, мощностью 2..3 ватта, с КСВ 1.2, ключом мне удалось 2 раза полностью передать фразу "v v v de YL3BU k". На 3-ем разе е-кодер "завис".

**Comment by VK6NX** [comment]
Что-то мне думается, что пока что далее мучать E-Coder2 с данной бетой и данным firmware E-Coder2 - нет. Программистам ЕЕ уже из имеющейся информации ясно, скорее всего, куда копать и что править. Надо ждать апдейта.

**Comment by YL3BU** [comment]
@VK6NX , да. Я просто думал, что только у меня проблемы. Или с моим E-Coder2 есть проблемы.
Поставлю обратно ExpertSDR2 и послушаю эфир на PRO варианте друга, в ожидании своего DX :)
Кстати, даже перепрошитый под 3-ю версию E-Coder2, как я успел заметить, работает и со второй. Я имею в виду настройку кнопок и валкодеров, не физические интерфейсы для переферии. Ладно, 73!

**Comment by RX3RZ** [comment]
> @RX3RZ Интересно, а если Вы попробуете просто на диапазоне без прохода настроиться подальше от всяких DX частот, выставить мощность TX 2 ватта (вообщем чтобы никому не мешать) и ключом или макросом попередавать фразу "v v v de RX3RZ k" делая паузу между фразами 4...5 сек. примерно. Сколько полных раз Вам удастся передать эту фразу до зависания е-кодера?

Александр, сделал как ВЫ описали. Глубоким вечером на 28 МГц с мощностью 3 Вт, манипулятор подключен к трансиверу. Начал CQ CQ CQ de RX3RZ RX3RZ RX3RZ K и так с паузами в 5-10 секунд между вызовами. Количество вызовов не считал, но E-Coder2 наглухо завис где-то через 6 минут в режиме передачи (горит средний светодиод на Е-кодере). Интерфейс ESDR3 работает, но пользоваться Е-кодером нет никакой возможности, т.к. он висит. Просто передёрнус его из порта USB ситуацию не спасает. Светодиод гаснет, но ПО Е-кодер не видит. Спасает только полное отключенике системного болка. Именно, отключение. Перезагрузка не помогает. Только выключив системный блок, включаю секунд через 5, всё загружается и Е-кодер работает как ни в чём не бывало. После продолжил передавать посылки телеграфом, но Е-кодер не хотел виснуть повторно. Минут 30 просикулял и начал обычную работу в эфире. Потом отвлёкся, но трансивер был включен и находился в режиме приёма. Через пару чвсов заметил, что E-Coder2 снова в режиме зависания с горящим средним светодиодом.
В общем, надо создавать новый вопрос про зависающий E-Coder2. А эту тему закрывать, т.к. обозначенный баг в первом сообщении устранён.

**Comment by rvolchkov** [comment]
Добрый день @RX3RZ @YL3BU 
На Google Drive опубликована новая версия программы с исправлением работы с панелью E-Coder2
https://drive.google.com/file/d/1Bl3eI97TYuBJvuP1IS7pPNlCdSQrTppi/view?usp=share_link

Просим Вас проверить работу данной версии программы.
Прошивать ничего не нужно, изменена только работа программы.

**Comment by YL3BU** [comment]
@rvolchkov Здравствуйте!
Погонял примерно 4...5 часов с сетапом описанном выше. Гонял и на общий вызов, и на поиск, с RIT, с XIT, со сменой диапазонов, оставлял в покое (отходил и возвращался) - вобщем мой E-Coder2 отработал без зависаний с версией ESDR3 предложенной Романом в предыдущем сообщении.

**Comment by RX3RZ** [comment]
> Добрый день @RX3RZ @YL3BU На Google Drive опубликована новая версия программы с исправлением работы с панелью E-Coder2 https://drive.google.com/file/d/1Bl3eI97TYuBJvuP1IS7pPNlCdSQrTppi/view?usp=share_link
> 
> Просим Вас проверить работу данной версии программы. Прошивать ничего не нужно, изменена только работа программы.

Только сегодня увидел ваш ответ. Завтра вечером погоняю.

**Comment by RX3RZ** [comment]
Погонял вчера вечером более 30 минут. E-Coder2 отработал без зависаний.
