### ISSUE TITLE
ExperSDR3 V1beta - RadioSync

### ISSUE THREAD

**Issue by tjasperme** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#483]
Implemented TCI commands transfer via CAT will not work. Using MixW like <CATCMD:TC:volume-6;> gives no result.

**Comment by ExpertSDR3** [comment]
Has been implemented: TC:volume-6
I added what would work: CATCMD:TC:volume-6;
The next release will be with support: ATCMD:TC
