### ISSUE TITLE
Transverter ExtCTL & DAC output

### ISSUE THREAD

**Issue by Mark678** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#484]
Hi

I have a couple of issues since ESDR3 V0.13 ...

- ExtCTL & "by band" PA don't work for transverter bands, all others seem to be OK
- After initial power-up, the DAC output is completely missing - switching to another band & back restores output however occasionally the level is severely reduced - 100% drive gives -24dBm at the DAC output, regardless of selected band

SunSDR2 pro
Win10 16Gb
Dedicated network adapter

Regards,
Mark M1DMX

**Comment by ExpertSDR3** [comment]
Fixed. 
Fixes will appear in 1.0.1 beta.
