### ISSUE TITLE
ExpertSDR 28102022 quits with Ecoder2 activ

### ISSUE THREAD

**Issue by DF2LH** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#485]
SunSDR2DX + EESDR Beta 1.0.0 28102022.
E-Coder 2 with Firmwareupdate provided with EESDR Beta 1.0.0 28102022 on a 2.5 Ampere USB 3.1 Hub
Windows 11 - AMD Ryzen 7 + 32Gb of RAM
NVIDIA GeForce GTX750ti

Hello around : )
I decided to use Beta 1.0.0 in CQWW SSB last weekend. It worked flawless, but only without the Ecoder 2 activated.
The Ecoder is plugged in the whole time, but kills ExpertSDR complete when i switch him on in the console window and try to use some of the sliders in ExpertSDR. This is a new behavior who did not happen the whole time before Beta 1.0.0. Same wth Vulcan oder OpenGL.
Please see my video. This is a complete new installed ExperSDR. Before install i deleted the ~\AppData\Local\Expert Electronics directory.
After the crash, i find many files named ExpertSDR.xxxxxx in the ~\AppData\Local\Temp directory.
vy 73 Thomas

https://user-images.githubusercontent.com/26204043/199015418-e19e0980-1910-4641-9169-0b23715feb6d.mp4

**Comment by ExpertSDR3** [comment]
Fixed
