### ISSUE TITLE
Не правильная манипуляция в SSDR2-QRP из лога на выходе НЧ трансивера.

### ISSUE THREAD

**Issue by Nick1953** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#487]
SunSDR2-QRP №3201700058
ESDR3-1.0.0.1BETA
i7700-16Gb-1030-WIN10PRO
При работе CW и манипуляции из лога N1MM+ при самоконтроле непосредственно на выходе трансивера, "пропадает
первая точка". Выставленная задержка РТТ в логе составляет 60-100 мс, относительно сигнала и не влияет на "искажение информации". Изменение задержек в "ВМ" не влияет.
При контроле на выходе звуковой карты компьютера, искажения в манипуляции отсутствуют.

**Comment by Nick1953** [comment]
Уточнение к сообщению выше - Прошивка 11.0 в трансивере № 3201700058.

**Comment by Nick1953** [comment]
Разобрался с "манипуляцией". Необходимо в настройках программы "Break.in" установить значение -
"PTT-CW-Delay" - меньше, чем задержка CW в логе !!!!! В моем случае это - лог 60 мс, программа - 10 мс.

**Comment by VK6NX** [comment]
Просто рекомендация: если вы сами нашли решение, то, наверное, стоит оценить - нужно ли держать открытым "баг"? Как бы хороший тон.

Ну и уж совсем здорово, если вы информацию о том, как настроить N1MM на форуме ЕЕ напишете.
