### ISSUE TITLE
Feature Request: Panadapter Callsign Spotting From Telnet Connection(s)

### ISSUE THREAD

**Issue by KV4TT** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#488]
Please add this function as from EESDR2 with color selection to differentiate calls from multiple telnet spot feeds.

**Comment by ExpertSDR3** [comment]
This functionality is needed in Logger, we did not plan to embed it in ESDR3, but you can offer this feature in the [suggestions](https://github.com/ExpertSDR3/ExpertSDR3-SUGGESTIONS), if a lot of people vote for it, then we will consider the possibility of implementing it in ESDR3.
