### ISSUE TITLE
Sun Sdr Pro2 в приёмнике баг 

### ISSUE THREAD

**Issue by 1951alex** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#49]
![bandicam 2021-11-16 14-04-21-198](https://user-images.githubusercontent.com/94466287/142012502-0722febd-ae34-4c80-8a4e-b8474d5a22bc.jpg)
![bandicam 2021-11-16 14-04-16-556](https://user-images.githubusercontent.com/94466287/142012528-86196d28-e73f-47a6-861b-3fb2148ae6cb.jpg)
 win10 pro 64
![bandicam 2021-11-16 14-04-52-368](https://user-images.githubusercontent.com/94466287/142011306-be41ca4e-7605-4e0c-a1d8-cdc04db2c077.jpg)
![bandicam 2021-11-16 14-04-59-265](https://user-images.githubusercontent.com/94466287/142011383-53d077e9-88fb-496f-b7d3-275112039137.jpg)
   Я у себя в ExpertSDR3 нашёл маленький баг в программе,версия ExpertSDR3 0.10.0. Каждый раз при включении компьютера и загрузки программы ExpertSDR3, маленький уровень принимаемых станций, стоит перезагрузить программу, уровень восстанавливается.И так, программа будит работать правильно пока не выключишь компьютер.  С уважением, Александр.

**Comment by ExpertSDR3** [comment]
повторяет #3
