### ISSUE TITLE
'Show S Meter' focus remains at the front when selecting another application

### ISSUE THREAD

**Issue by reflectingme** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#490]
ExpertSDR3 1.0.0 beta 28102022
Firmware 86.8
iMac running MacOS Monterey 12.6

<img width="290" alt="Screenshot 2022-11-01 at 11 22 57" src="https://user-images.githubusercontent.com/47534300/199223108-00cf6427-6969-4c57-acbc-ef526de3c3e4.png">

When using the 'Show-S-Meter', if I select another running application on my desktop, EESDR3 correctly moves backwards in the focus stack, whereas the focus of the S Meter remains at the front i.e. in front of any other selected application.  

Screenshots show the meter working with EESDR3 then when attempting to write this new issue in Safari.

UPDATE and addition: When wanting to select a value from the tuning step drop down, if the meter is positioned on the left, the drop down appears behind the drop down and cannot be selected.  Not a huge issue, but one has to move the meter to select a new tuning step.   

<img width="2153" alt="Screenshot 2022-11-01 at 11 28 31" src="https://user-images.githubusercontent.com/47534300/199223081-33b13dd4-487f-4d80-a228-55248d39636a.png">
<img width="1773" alt="Screenshot 2022-11-01 at 11 28 43" src="https://user-images.githubusercontent.com/47534300/199223091-21b3ccda-2cdc-4e93-b625-251b0c463972.png">

**Comment by ExpertSDR3** [comment]
Starting from version 1.0.1 beta, the S-Meter window will be on top of the main ESDR3 window, but will overlap under the windows of other programs
