### ISSUE TITLE
Distorion/Noise in audio stream

### ISSUE THREAD

**Issue by SM0MDG** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#493]
I am experiencing noise in the EC2 audio output. It sounds like ignition noise from an engine but softer. It sometimes appear after transmitting and always after the radio has been sitting idle in RX for a while. The cure is to restart EC2.

The problem is the same in DirectX and Open GL and is not captured in audio recordings.

ESDR3 1.0.1 beta

OS Name	Microsoft Windows 10 Pro
Version	10.0.19044 Build 19044
Processor	Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz, 3408 Mhz, 4 Core(s), 8 Logical Processor(s)
Installed Physical Memory (RAM)	16,0 GB

**Comment by lc7x** [comment]
Same issue as Bjorn have written in this report. Another SUNSDR user from Canada is also reporting this issue.

Here I am using:

SUNSDR PRO2
ESSDR1.0.1 beta
WIN 10PRO
Version 10.0.18363 Build 18363
Prosessor	Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz, 3201 Mhz, 4 Core(s), 4 Logical Processor(s)
Installed Physical Memory (RAM) 8,0 GB
