### ISSUE TITLE
 в DIGI modes - не отключен микрофон

### ISSUE THREAD

**Issue by rm6lw** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#497]
Бета 101
SUNSDR2PRO 
Win10x64 I-5 104400F 16 GB 
в DIGI modes - не отключен микрофон
Просьба - отключите mike - ну в диги - зачем он нужен???

**Comment by ExpertSDR3** [comment]
Это не ошибка, в некоторых случаях это необходимо.

**Comment by rm6lw** [comment]
Например, в каких?
Если я переключил в DIGI, зачем мне микрофон?
Вот в SSB там TCI или VAC audio нужно, чтоб работать макросами из логов, а в DIGI- всегда и у всех трансиверов давно  MIKE отключен.
Так что это баг/невнимательность программистов/постановщиков задач. 
Предлагаю в следующем релизе исправить!

**Comment by rm6lw** [comment]
в версии 1.0.8 тоже самое!
Если я переключил в DIGI, зачем мне микрофон?
Вот в SSB там TCI или VAC audio нужно, чтоб работать макросами из логов, а в DIGI- всегда и у всех трансиверов давно MIKE отключен.
Так что это баг/невнимательность программистов/постановщиков задач.
Предлагаю в следующем релизе исправить!
