### ISSUE TITLE
Scratchy noise and no audio output.

### ISSUE THREAD

**Issue by sm6usu** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#498]
EESDR V3 Beta 1.0.1 Morning 4 Nov. Autostart worked whitout scratchy noise. Afternoon it starts With scratchy noise impossible to hear anything but noise
and Donald duck like voices. After several tries. It worked again but I had lost my output ( Mic direct in tranciver and also earphones).
Only way to fix my audio was go back to NO auto start. Regarding to the forum I am not alone about those problems.
Windows 11 22H2
Proc.i9 12900K 3.20 GHz
Ram 64 GB
Nvidia GeForce RTX 3090 Ti
SunsdrDX 2
Regards Svante sm6usu

**Comment by W3FRG** [comment]
I am also experiencing this same anomaly with my SunSDR2 Dx when autostart is turned on, so when radio starts up, what I get is a scratchy sound on the audio.
I have to turn radio off and then back on again and the audio is perfect. I'm using Win 10 system using Log4OM / TCI.
Beta 1.0.1 Build 03112022
Dell 7040 i7 32G Ram
Tom W3FRG

**Comment by sm6usu** [comment]
Hallo Tom Yes sometimes it is enough switching between LSB and USB and Back
and sometimes switching bandwidth is enough and also switching sample
rate down in left corner.
I do not use autostart until next update and we will see.
So far only problem in Win 11 here. Have same Beta in my Laptop with
windows 10 and it seems to work. But I am back to manual start, also on my
Laptop.
On laptop I use about 75 % Vara hf/VarAC and have also setup for remote
from laptop but it is to long delay today. But it is Beta so I am glad to
every progress I see I
think it works extremely well for me using ssb and sometimes Vara.
Regards sm6usu Svante

Den sön 6 nov. 2022 kl 14:01 skrev W3FRG ***@***.***>:

**Comment by John-KC2QMA** [comment]
I also have the "AutoStart" issue.
My gut tells me it’s an initialization timing issue. I think esdr3 needs just a few more miliseconds startup delay time to allow the software to take control of the hardware properly especially the audio.
I find on the first try of AutoStart it will fail with what looks like some kind of sample rate conflict but then sometimes if I close esdr3 and try to AutoStart it might work? 
Anyway that’s just a guess.

**Comment by sm6usu** [comment]
Yes I agree with this. No big problem. I am using the startbutton until
next upgrade
Vy best 73 de sm6usu Svante

Den ons 30 nov. 2022 kl 20:42 skrev John_KC2QMA ***@***.***>:
