### ISSUE TITLE
Фризы с максимальным зумом

### ISSUE THREAD

**Issue by rvolchkov** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#5]
SunSDR2 DX
0.10
Windows 10

При максимальном зуме начинает всё тормозить, звук затыкается, панорама обновляется раз в несколько секунд.

**Comment by rvolchkov** [comment]
Пользователь из Франции писал о подобном и еще видосов наснимал:
Here are 2 videos taken shortly after turning on ESDR3 and LogHX.
-The first everything seems normal. By turning the VFO the CPU switches from 14 to 26%. The GPU remains at 10%. Spectrum and waterfall scroll normally.
-The second I open Log view. By turning the VFO the CPU goes to 36%, the GPU goes from 14 to 1% then 1.3%, Spectrum, and waterfall are blocked.
I observe the same thing without opening Log view, while letting the 2 programs run. After about ten minutes, by turning the VFO, movement is jerky on the spectrum and the Waterfall stops. When I stop turning the optical encoder of the E-Coder everything goes back to normal.
If I run SDC with ESDR3 (without LogHX) then as soon as I open Log view and turn the VFO, then the waterfall stops, spectrum only slows down and GPU goes from 11 to 4%

https://user-images.githubusercontent.com/90688941/140751798-f7e723a2-d49d-4836-8a51-f96a72ac667f.mp4

**Comment by ExpertSDR3** [comment]
К релизу 0.10 проблема будет решена

**Comment by ExpertSDR3** [comment]
Закрыто
