### ISSUE TITLE
ПРОБЛЕМА РАБОТА EQ TX

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#50]
При изменении ПАРАМЕТРА Q ( добротность ) происходит изменение уровня !
При этом сама регулировка уровня не работает ,
что в плюс , что в минус.
 Это наблюдается в работе первого ( кране левый ) и последнего фильтра ( крайне правый )
![работа q ](https://user-images.githubusercontent.com/93991940/142185441-be9654dc-2c28-4832-ba99-dc5b82e3f747.jpg)
![работа Q](https://user-images.githubusercontent.com/93991940/142185443-8ff0afa4-1049-4cca-b734-80737f9f193d.jpg)

**Comment by 1972igor** [comment]
> При изменении ПАРАМЕТРА Q ( добротность ) происходит изменение уровня !
> При этом сама регулировка уровня не работает ,
> что в плюс , что в минус Это наблюдается в работе первого ( кране левый ) и последнего фильтра ( крайне правый )

**Comment by 1972igor** [comment]
> При изменении ПАРАМЕТРА Q ( добротность ) происходит изменение уровня ! При этом сама регулировка уровня не работает , что в плюс , что в минус. Это наблюдается в работе первого ( кране левый ) и последнего фильтра ( крайне правый ) ![работа q ](https://user-images.githubusercontent.com/93991940/142185441-be9654dc-2c28-4832-ba99-dc5b82e3f747.jpg) ![работа Q](https://user-images.githubusercontent.com/93991940/142185443-8ff0afa4-1049-4cca-b734-80737f9f193d.jpg)

**Comment by ExpertSDR3** [comment]
Это не баг, а особенность работы цифрового фильтра. Можно изучать его работу [тут](https://www.earlevel.com/main/2021/09/02/biquad-calculator-v3/)

**Comment by 1972igor** [comment]
понятно , что это LPF по звуку ,( которые задаются стандартно минус 6dB, минус, 12dB и минус 24 dB),   по уровню , но НО я думаю, что нужно было предусмотреть и работу регулировки уровня, уж больно похожи эквалайзеры  https://www.instagram.com/p/CGSONzxDxmg/?igshid=u804r1tic2oc #
![EQ](https://user-images.githubusercontent.com/93991940/142195692-428563a2-9480-422c-ae5f-5ea0bd3d9c2c.jpg)
