### ISSUE TITLE
E-Coder2 "наглухо зависает" в ESDR3 1.0.1 beta

### ISSUE THREAD

**Issue by RX3RZ** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#502]
Имеется:
SunSDR2DX #1002
E-Coder2 EEA1235210003
ExpertSDR3 ver.1.0.1 beta
Firmware 86.8

Системный блок:
CPU: AMD Ryzen 7 5700G
MB: MSI B-550-A PRO
RAM: 32G Kingstom
Video: NVIDIA GeForce GTX 1050Ti 4G
ОС Windows 11 x64 build 22000.1098

После установки ESDR3 версии beta и устранения падения ПО при работе телеграфом стал "наглухо зависать" E-Coder2.
Об этом частично говорилось в #481.
Почему наглухо - из этого состояния можно вывести только если выключить системный блок.
Вчера, 5 ноября, провёл эксперимент.
Глубоким вечером на 28 МГц с мощностью 3 Вт, манипулятор подключен к трансиверу. Начал CQ CQ CQ de RX3RZ RX3RZ RX3RZ K и так с паузами в 5-10 секунд между вызовами. Количество вызовов не считал, но E-Coder2 наглухо завис где-то через 6 минут в режиме передачи (горит средний светодиод на Е-кодере). Интерфейс ESDR3 работает, но пользоваться Е-кодером нет никакой возможности, т.к. он висит. Просто передёрнуть его из порта USB ситуацию не спасает. Светодиод гаснет, но ПО Е-кодер не видит. Спасает только полное отключение системного блока. Именно, отключение. Перезагрузка не помогает. Только выключив системный блок, включаю секунд через 5, всё загружается и Е-кодер работает как ни в чём не бывало. После продолжил передавать посылки телеграфом, но Е-кодер не хотел виснуть повторно. Минут 30 просикулял и начал обычную работу в эфире. Потом отвлёкся, но трансивер был включен и находился в режиме приёма. Через пару часов заметил, что E-Coder2 снова в режиме зависания с горящим средним светодиодом.
Сегодня, 6 ноября, так же было "глухое зависание" E-Coder2 во время работы в эфире.

**Comment by ExpertSDR3** [comment]
Исправлено, исправления появятся в версии 1.0.2 beta

**Comment by RX3RZ** [comment]
> Исправлено, исправления появятся в версии 1.0.2 beta

Понял. Спасибо. Жду обновления. :)
