### ISSUE TITLE
TX spectrum and screen flickering at CW - break in operation

### ISSUE THREAD

**Issue by OK2WY** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#506]
Condition: W10, EESDR3 1.0.1, CW keying from external key connected to KEY input on TRX, Break.IN active with Break in delay 500 ms.
PTT relay works correctly with set delay, but display switches randomly betwen TX and RX state even before Bk.in period expired, it caused flickering of the display which pulling my eyes from head. Also red TX spectrum in CW mode does useless flickering of display very unpleasant for eyes. See linked video, which shows behavior of EESDR during sending continuous dihs... https://youtu.be/jszweZDmYuA
Displaying of the TX spectrum should be configurable as optional at least for CW mode.

**Comment by n5oe** [comment]
Have to agree, exact setup here but on Linux 64 system and includes EESDR 1.0.2 beta too. Would really like option to remove TX spectrum, cw ops with zoom screen really un enjoyable flickering. 
Thank you for all the work, just my observations and experimentation
