### ISSUE TITLE
ESDR3 Betta1/01 звуковые устройства вывода разделяются но звук на передачу идёт рваный 

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#507]
https://www.youtube.com/watch?v=Vzwnh6sSGVA
драйвера ASIO USB карта 1 
драйвера WDM-KS  карта 2 или VAC идёт рваный звук на передачу ( в самоконтроле слышен характер рваного звука) ( видео прилагаю)

**Comment by rm6lw** [comment]
Я вообще ASIO, WDS-KM  не могу включить - устройство unavailable
