### ISSUE TITLE
Band jump When changing sample rate .TX on 160M  but display 40M !!   ESDR3

### ISSUE THREAD

**Issue by oz1ctz** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#508]
Running ESDR3 on 40m  , every thing is OK sample rate is set to 156 Khz.
frequency display show working frequency  7050.000 Khz .
my power amplifier works on 40m.

If I change samplerate to 39 KHZ .. samplerate change and frequency readout still 7050.000 Khz

BUT tx frequency change to 160 Meters .. my power amplifier detect a 160m signal and switches over to 160 M .

...only FIX is to close software and select new samplerate before tunring on ..

Only change sample rate if software is sw off .! not during on state..

73 de Brian

**Comment by lb5va** [comment]
Confirmed todag. I have it also, and produced with OFF - ON in software.
I made a new bug report on the matter. But a small change in frequency fixes it here.
TX FRQ BUG! 1.0.4 beta (similar reported earlier by OZ1CTZ) #601
Stig

**Comment by lb5va** [comment]
They should have fixed this bug in 1.0.4 beta that came in may 2023...
