### ISSUE TITLE
RX2 antenna selection missing, Port changes 50003 to 50001 when restart 2nd radio on same PC. Bandscope not operational. TCI JTDX does not support two devices on one PC

### ISSUE THREAD

**Issue by n3qq** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#509]
RX2 antenna selector button is grayed out when RX 2 is activated. Should be available switch ANT 2/ANT 3 for RX2
When 2 devices run on same PC after restart port changing to default 50001. Should stay as selected. In device selector shows correct port (50003), but second radio starts with 50001.
Can't select/adjust center on the bandscope.

Date (right lower corner) when switching to GMT shows yesterday's date. Current time PST in N. America. Should be removed or corrected. Local time/date already shows in lower tab of Windows. Redundant information.
The split button just flashes yellow in CW when activated, but not stays active. In order to turn off split have to open settings and set 0 HZ. Should be On/off with split button and indicate SPLIT when active.

JTDX version 2.2.159-32A does not support running 2 devices on one PC "Rig name must be different" error. No way to change the rig name, it is TCI Client in Radio selector. Would be nice to have 2 or even better 3 options TCI A TCI B TCI C for 3 devices.
TCI client RX2 refers to RX2, not to the second physical device.
Selections should be :
TCI Client A RX1 
TCI Client A RX2 
TCI Client B RX1 
TCI Client B RX2
TCI Client C RX1 
TCI Client C RX2
MSHV 2.68 is working with 2 physical devices via TCI on one PC, but occasionally disconnects for no reason.

Thank you!
73, Yuri N3QQ

**Comment by n3qq** [comment]
Correction:

JTDX is working with two hardware devices on one laptop. See settings at Addendum, page 51 for JTDX connection.

**Comment by DK8JV** [comment]
> RX2 antenna selector button is grayed out when RX 2 is activated. Should be available switch ANT 2/ANT 3 for RX2

I doubt this is possible. Since the device has got only one ADX, RX1 and RX2 must always share the same antenna.
Please correct me if I'm wrong.

Best 73
Eberhard, DK8JV

**Comment by n3qq** [comment]
Good morning Eberhard,

 If you can select RX 2 or 3 for the main RX/VFO, you should be able to
select ANT2 or ANT3 in the 2nd RX as well.
Hardcoded ANT2.

Thank you,
73,
Yuri Sushkin
N3QQ
www.na-234.com
