### ISSUE TITLE
EESDR3 automaticly shuts down after plugging in USB from E-coder Plus.

### ISSUE THREAD

**Issue by PD0DH** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#510]
Device and serial number
E-coder Plus 02102100482

ExpertSDR3 version and build number
ExpertSDR3 Version 1.0.1 Build 03112022

OS: Windows 10/ macOS/ Linux Ubuntu - under which OS you have confirmed the issue
Windows 11 Home Build 22621

Your PC parameters briefly
HP ENVY laptop X360 i7 10510U 4 cores, 24 GB RAM, SSD

Description: full and most descriptive information about the bug/issue
See Youtube link here: https://youtu.be/7kXbgeY3D8I
ExpertSDR2 works fine with E-coder. ExpertSDR3 works fine without E-coder. When plugging in the USB plug, the application shuts down automaticly after 3-5 seconds. Startscreen with hardware starts without a problem and stays on the screen. By clicking start AFTER plugging in USB will shut down. Clean install doesn`t work. Also plugging in first then start application does not help. In Win logbook there is an application error with sdrapplication.exe and ecoder.dll.

Correlations: indicate if you found any dependencies or conditions under which issue/bug occurs
The problem is always when i use ExpertSDR3 in combination with E-coder.

There is no backtrace dumpfile available. How do i produce this file??

[Fault1.docx](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/files/10117323/Fault1.docx)
![Fault1](https://user-images.githubusercontent.com/48188022/204648473-021d7da8-45d7-448a-86ac-afdf3b767d86.jpg)
[Fault2.docx](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/files/10117324/Fault2.docx)
![Fault2](https://user-images.githubusercontent.com/48188022/204648482-55c1b28e-fdf9-42b9-9b9d-61de925c848f.jpg)

**Comment by VK6NX** [comment]
Pls stand by for ver Beta 1.0.1, issue already addressed in it.

**Comment by PD0DH** [comment]
This issue is solved by the new version! Thank you very much.
