### ISSUE TITLE
Кнопка выключения самоконтроля не работает в CW режиме

### ISSUE THREAD

**Issue by JedyAndy** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#514]
Кнопка выключения самоконтроля в режиме  CW
- корректно работает для разъема на морде трансивера
- не работает для выхода на звуковую карту PC

Хотя уровень самоконтроля регулируется движком в обоих случаях корректно

Версия для Windows ExpertSDR3_x64_1.0.1_beta_setup.zip
Win 10 Professional, Lenovo ThinkPad 470p  i7, 32Gb RAM

**Comment by VK6NX** [comment]
Тот же баг под MBP под OS12/OS13. На старом интеле можно выключить через cmd, под "силиконом" - уже нет.

Похоже баг кроссплатформенный.
