### ISSUE TITLE
PTT>Excessive POWER error when using Tune (PA operational)

### ISSUE THREAD

**Issue by IU4JNR** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#517]
I found that when I push tune with PA operational, my SS PA returns an error of excessive power or hi SWR.  SWR is in range and the power is between 5-10W up to 15W
There is no adjustable delay between PTT and Tune. 
This of course brings to protection my SS PA.
The BM Bands delay is ineffective with the Tune button. The delays for CW are ineffective, but what I guess is mostly a RF Spike ONLY when using TUNE
EESDR3 V B1.01 SunSDR2 Pro, SunSDR2 DX, Acom 600S
Ryzen7 5800x, DDR4 128Gb, 1TB M2, RTX2060OC, Win11Pro

**Comment by ExpertSDR3** [comment]
The delay of RX->TX really didn't work for TUNE, it's fixed, a version with a fix will be published soon.

**Comment by ExpertSDR3** [comment]
Fixed
