### ISSUE TITLE
FT8 wide bandwidth in the start and end of the transmission

### ISSUE THREAD

**Issue by oh4mvh** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#519]
My FT8 modulation has wide  bandwidth in the start and end of the transmission period. This happens when SunSDR2 Pro is connected to PC from its physical mic and speaker connectors and through audio isolators. See figure red circles where openwebrx sdr is displaying the spectrum approx 10km away from transmitter site:
![eesdr3 FT8 analog](https://user-images.githubusercontent.com/121118276/208743547-dca759fa-5151-4f6f-91e1-687d44c59124.png)
Changing the delays rx->tx, tx->rx changes the time how long time bandwidth is wide, but I don't want to decrease delay values too much due to external relays switching times. 

If I change the sound interface to TCI in mshv, then I don't see any wide bandwidth modulations in the start and end of the transmission period. Unfortunately TCI is not stable yet so it is not very suitable for long time monitoring. See figure below in TCI audio mode:
![eesdr3 FT8 TCI](https://user-images.githubusercontent.com/121118276/208743644-eea55d5b-e4e8-493d-897f-fe9797f920ff.png)

For comparison reasons, I attach also figure how modulation start and end looks like for MSK144 when using analog mic and speaker connection as in first figure.
![eesdr3 MSK144 analog](https://user-images.githubusercontent.com/121118276/208743681-6fdf6186-2d37-4699-b67d-1f6810445e6b.png)

Computer is Dell Optiplex 7010 and I'm using built in sound card.
Processor	Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz   3.20 GHz
Installed RAM	8,00 GB (7,89 GB usable)
System type	64-bit operating system, x64-based processor
Edition	Windows 10 Pro
Version	21H2
OS build	19044.2364
Experience	Windows Feature Experience Pack 120.2212.4190.0

**Comment by ExpertSDR3** [comment]
It looks like you have AGC enabled in the sound card for the microphone input, when there is no signal at the input, AGC amplifies the noise. Also, mic gain could be set to a max level which amplifies noises while there is no signal.

P.S.
Please provide a thorough description of your setup, what is connected to what and how?

**Comment by oh4mvh** [comment]
If sound card AGC is reason then I don't still understand why this happens on FT8 but not in MSK144 when settings are equal? 
MIC2 and AGC sliders are both set in maximum value. If you mean AGC slider close to MIC2 slider is the sound card AGC, it is not selected to auto gain if I right click it. I think it is set in its default value.  

My physical analogue audio connection is equal to as using non-SDR radio seen in block diagram below. 

![image](https://user-images.githubusercontent.com/121118276/225384158-a54d20ec-96d4-4477-a6ef-0b618d3c1e5e.png)

P.S.
I have evaluated MSHV v2.67 and ExpertSDR3 v1.0.3 beta for a while and TCI gets more stable but not perfect yet. Only drawback with TCI is that FSK441 and JT6M modes cannot be used over TCI. Those modes are popular in meteor scatter.
