### ISSUE TITLE
Автоматическая смена порта трансивера , если он занят на компьютере

### ISSUE THREAD

**Issue by amiko-zz** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#521]
Предлагаю решение проблемы надоевшей уже многим пользователям, это занятый порт на компьютере другими приложениями и как следствие получение ошибки типа  **"Failed to read the device calibrations"** и прочих неинформативных ошибок. Считаю необходимым добавить в ExpertSDR  проверку занятости порта на компьютере и если такое обнаружено, то предложить тут же пользователю сменить порт на другой в трансивере одним нажатием кнопки согласия, например с шагом 50 вверх или вниз и тут же перенастроить ExpertSDR на этот порт новый и сам трансивер.  
_Быстро и эффективно и без глобальных переделок._  и снимет много проблем.

**Comment by VK6NX** [comment]
Дражайший вы наш, спасибо вам большое! И ведь никто не догадался за столько-то лет...

К вашему сведению: 
- Сообщение "Failed to read the device calibrations" относится к информативным. Прям из раздела debug info.
- То как вы предлагаете "менять порты" - это так не работает. Тут у вас что-то не так с пониманием принципов работы TCP/IP в целом и UDP в частности.

Вот что дейстивтельно настораживает порой - это отсутствие привычки читать документацию. FAQ в частности. Который аккурат под вас был написан. Но отдельное спасибо, что вы всему форуму в нескольких топиках сразу сообщили: "я не читаю FAQ, это для слабаков".

**Comment by amiko-zz** [comment]
> 
Ого как! Однако должен заметить, что Ваше ЧСВ настолько огромно и безмерно, что Вы не удосужились углубиться в тему, но успели нахамить вот так с ходу. Не годиться так.  Много слов -  ноль конструктива.
Я написал решение которое точно проверено в деле  и вполне с понимаем дела написано и не надо лапшу раздавать по ночам, пожалуйста, я вас очень прошу. ЧСВ стоит отрабатывать на форумах с подростками. Ладно?

**Comment by amiko-zz** [comment]
Теперь по делу:
1) "Failed to read the device calibrations" - Покажите пожалуйста убогим нам, где в выдаче поиска (Google?) где обнаруживается эта фраза приводящая в **FAQ** на EESDR?   Вот на форуме мающихся людей с поисками траблов - это пожалуйста! 
2) Что Вас смущает в  смене UDP портов собственно? На форуме пишут, так же как и я , о том что надо сменить порт и все заработает, что собственно я и предлагаю автоматизировать проверкой локально на компьютере при помощи ExpertSDR 

Я только за последние сутки неоднократно натыкался на ужас того, что запустив сервер ERS получаю при запуске те же ошибки "Failed to read the device calibrations" от ExpertSDR по той же причине занятости портов локально на моей машине.  ### Так себе дружелюбное и продуманное юзабилити вышло, хотя если бы ExpertSDR  сразу проверял бы порты и по итогу выдал бы внятное сообщение , мол проверьте порт 50001 у себя на компьютере, т.к. как он занят программой "XXX" было бы куда в сто раз легче для понимания пользователю и облегчило бы решение проблем, а то и вообще ExpertSDR  мог бы не только уведомить об этом, но м и автоматически по согласию предложить сменить порт

Так что я же я тут предлагаю не так?
**Еще раз прошу, без ЧСВ и фанатизма пишите ответы. Уважайте других людей и членов сообщества.**

**Comment by VK6NX** [comment]
Знаете, в чем прелесть Гитхаба? В том, что первичное сообщение в нем тоже сохраняется. Со стилистикой и орфографией :) Учтите это на будущее.

Прежде чем требовать к себе уважения, для начала проявите его сами. Вы пишите "предложения" в раздел "баги", при том, что раздел "предложения" существует отдельно, давно и "предложения" производитель просил всех (вас в том числе) писать туда . Раздел тут: https://github.com/ExpertSDR3/ExpertSDR3-SUGGESTIONS
Надеюсь, с этим вопросом все ясно? 

Меня ничего не смущает в UDP. Ответ вам уже дан выше. Повторю второй раз: так как вы предлагаете -  так не работает. Так что прекратите нести ерунду, лучше прочтите FAQ и в точности ему следуйте. Мануалам и дебагам вам будет проще рассказывать, какое у них ЧСВ.

**Comment by amiko-zz** [comment]
Да, это уже диагноз таки...

**Comment by amiko-zz** [comment]
> "баги", при том, что раздел "предложения"

ага, это не баг, это фитча :)  Да?
