### ISSUE TITLE
Beta 1.0.2 crashes on startup

### ISSUE THREAD

**Issue by mmaseda12** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#522]
Beta 1.0.2 crashes on startup with MacOS 13.1 on Intel Mac.

**Comment by jwluiten** [comment]
Same here running MacOS 13.1 on Apple silicon (M1-Max)
Looks like QT  libs are missing.

**Comment by mmaseda12** [comment]
Fixed now.  Thanks.
