### ISSUE TITLE
ExpertSDR3 1.0.2 Beta crashes if RX2 is used and N1MM sends CW macro trough CAT

### ISSUE THREAD

**Issue by HA1AH** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#523]
Hi All,

With SunSDR2DX if I use ExpertSDR3 1.0.2 Beta only with RX1 the system is rather stale.
But if RX2 is switched on and N1MM is connected in SO2R mode through virtual COM port pairs if I send CW macro message the entire GUI freezes and after some seconds the message appears: Lost connection with SunSDR2DX.

This setup works with ExpertSDR2 without any problem.

OS is Windows 10 Home version 10.0.19044

A video record of the problem is here: https://drive.google.com/file/d/1wIMdGISobaBcsMEJmQGQk1aiwSN9T5kb/view?usp=sharing

A shown in the video CW was sent to RX1 3-4 times before the program crashes, however, if it is sent to RX2 the crash happens immediately. It's independent from the baud rate of the com ports.

**Comment by UD2F** [comment]
Turn off "Break In"
See https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/issues/513
