### ISSUE TITLE
Using Remote with beta 1.0.2 gets "Busy" message

### ISSUE THREAD

**Issue by W3FRG** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#524]
Remote attempts to connect but getting "Busy" message.
Starter starts fine and remote logs in fine. The cloud appears and I click on start, and it tries and then I get a " BUSY" message.
This was working fine with Beta 1.0.1.
Using x64  1.0.2.
![Starter Remote Msgs](https://user-images.githubusercontent.com/94790391/209467670-f5de8380-416d-4157-9fae-73590c338504.jpg)

**Comment by sm6usu** [comment]
Same here
sm6usu Svante
Windows 11 22H2
Proc.i9 12900K 3.20 GHz
Ram 64 GB
Nvidia GeForce RTX 3090 Ti
SunsdrDX 2
Remote Laptop Windows 11 22H2
Ram 16 GB Geforce 3070
