### ISSUE TITLE
В версии клиента для удаленки все так же есть неправильный показатель ТОКА для НЕ ПРО.

### ISSUE THREAD

**Issue by c0nsul** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#53]
![Clip2Net Menu_211119172644](https://user-images.githubusercontent.com/3913429/142638726-d7e82604-a3e3-4bd0-b2e3-8c72dcf44f11.jpeg)

**Comment by ExpertSDR3** [comment]
Исправлено, исправления будут в версии 0.11.
