### ISSUE TITLE
EESDR3 1.0.2 beta : Не запоминается полоса растяжения панорамы, для каждого из пяти поддиапазонов

### ISSUE THREAD

**Issue by UA0SM** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#530]
EESDR3 1.0.2 beta : Не запоминается полоса растяжения панорамы, для каждого из пяти поддиапазонов.

**Comment by ValeraMikhaylovsky** [comment]
Такая функциональность не предполагалась

**Comment by ExpertSDR3** [comment]
Такая функциональность не предполагалась

**Comment by UA0SM** [comment]
Зачем тогда сделали ПЯТЬ поддиапазонов ? 
Оставили бы ТРИ но с запоминанием растяжения как было в ESDR2/
Где логика ?
 
 

UA0SM Евгений
