### ISSUE TITLE
Microphone not working on macOS

### ISSUE THREAD

**Issue by jwluiten** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#531]
Hi,

As you are probably well aware, the microphone on macOS is not working. Both ExpertSDR3 and ExpertSDR2 do not properly request access.

In `info.plist` I saw the `NSMicrophoneUsageDescription` key. With that, you're almost there. Three more lines of code and it works.

I'd also like to inform you that the workaround offered under previous versions of macOS no longer works under macOS Ventura 13.1. Basically, macOS users are now stuck and need to use the physical microphone attached to the SunSDR device.

**Comment by ExpertSDR3** [comment]
Dublicate #254
With the latest published version is attached README.txt with the solution of the problem of access to the microphone.
