### ISSUE TITLE
Start-Up delay

### ISSUE THREAD

**Issue by W3FRG** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#532]
During startup of ESDR3 V 1.0.2 Beta, the program stops and a "50%" appears on the left side of the GUI.
The program takes minutes to resolve itself and then complete the startup.
Running W10 on a Dell 7040 i7-6700
This just started. When version 1.0.2. Beta was originally installed this was not present and all went normally during startup.

![start-up 50%](https://user-images.githubusercontent.com/94790391/210074407-a295bc3a-013b-4cbe-912b-2713d6878908.jpg)

**Comment by sm6usu** [comment]
Hallo Tom Yes it was the exact problem I had. You can also see every parameters up in picture is 50 %. I did a reboot of my windows 11 and today I have 99 % of my pc programs back. All is working today. But of course it also worked a couple of days before the strange delay you are describing. So we will se how many days it will work now. I certainly hope it will work now.

**Comment by kxkayser** [comment]
I am having the same issue. Started several days after I installed the latest Beta (1.0.2) but I have even gone back and installed the latest Alpha and have same problem. If I delete all the settings from Appdata, it comes up fine with the default profile. If I restore some old profiles, like from October, it still works. However, If I export a working profile and then import it again, it hangs. Obviously from other people's posts, it seems to have something to do with Windows (I'm running latest build of Win 10). Hope Expert comes up with a solution.

**Comment by W3FRG** [comment]
I have since cleaned the Dell7040 (W10 PRO, i7-6700, 32Gb Ram, SSD250Gb, V22H2) of all EESDR Beta SW using Revo Uninstaller, CCleaner, Command prompt Pgms DISM & SFC.
I then reinstalled ESDR Ver 1.0.2 Beta build 23122022
I see the 50% flash as the GUI Installs but no hesitation to complain about.

Tom W3FRG

**Comment by sm6usu** [comment]
Hallo Tom I deleted app data settings and then it worked but if try a new profile it hangs again. New profiles set in already made profiles seems to work  at least a couple of times. I do not now if you have also played with profiles when the problem started . ESDR Beta 1.0.2 Has made the hang delay  3 times  now for me. Always after playing with Profiles.
Svante sm6usu

**Comment by W3FRG** [comment]
I previously used profiles from Beta 1.0.1 but since reinstalling I have stayed with my one and only profile created/updated in 1.0.2 and have had zero issues.
Tom W3FRG
