### ISSUE TITLE
Version 1.0.2  beta up/down buttons next to number fields overlap in MacOS

### ISSUE THREAD

**Issue by PE1BIW** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#534]
In the new beta version 1.0.2 buld 23.12.2022 on MacOS the up/down buttons next to number fields in the configuration dialogs overlap with the text:

![buttons-102](https://user-images.githubusercontent.com/106540497/210149614-33e9dea6-80d3-44e2-b8ec-0f15d9c8bd19.png)

**Comment by PE1BIW** [comment]
Notice this was already mentioned elsewhere

**Comment by ExpertSDR3** [comment]
Dublicate #525
