### ISSUE TITLE
ExpertSDR3 crashes when sent a rx_filter command with negative values

### ISSUE THREAD

**Issue by n4py** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#538]
ExpertSDR3 crashes when sent a rx_filter command with negative values.

Any value positive or negative for high and low rx-filter is not accepted initially.  My code retries until the value is finally accepted.
But for negative values, once the values are accepted, ExpertSDR3 then crashes.

Here's a trace from my software.  the time in milliseconds is the left hand column.

04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,700;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,225;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,225;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,225;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,225;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,225;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,225;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,225;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,225;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,225;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,225;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,225;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,225;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,225;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,225;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,225;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,225;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,225;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,225;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,225;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,225;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,225;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,225;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04731 TCIMessageParse rx_filter_band:0,10,225;, tuningk3 1, tuningtci 1, g_tuning 0
04731 Send to WHTP rx_filter_band:0,-225,225;
04747 TCIMessageParse rx_filter_band:0,-225,225;, tuningk3 1, tuningtci 1, g_tuning 0
04747 TCIMessageParse rx_filter_band:0,-225,225;, tuningk3 1, tuningtci 1, g_tuning 0
04747 TCIMessageParse rx_filter_band:0,-225,225;, tuningk3 1, tuningtci 1, g_tuning 0
04778 TCIMessageParse rx_filter_band:0,-225,225;, tuningk3 1, tuningtci 1, g_tuning 0
07840 Send to WHTP rx_filter_band:0,-600,-150;
07840 Send to WHTP rx_filter_band:0,-2850,-150;
07840 TCIMessageParse rx_filter_band:0,-600,10;, tuningk3 1, tuningtci 1, g_tuning 0
07840 Send to WHTP rx_filter_band:0,-2850,-150;
07840 TCIMessageParse rx_filter_band:0,0,50;, tuningk3 1, tuningtci 1, g_tuning -1
07840 Send to WHTP rx_filter_band:0,-2850,-150;
07840 TCIMessageParse rx_filter_band:0,0,50;, tuningk3 1, tuningtci 1, g_tuning 0
07840 Send to WHTP rx_filter_band:0,-2850,-150;
07840 TCIMessageParse rx_filter_band:0,0,50;, tuningk3 1, tuningtci 1, g_tuning 0
07840 Send to WHTP rx_filter_band:0,-2850,-150;
07840 TCIMessageParse rx_filter_band:0,0,50;, tuningk3 1, tuningtci 1, g_tuning 0
07840 Send to WHTP rx_filter_band:0,-2850,-150;
07840 TCIMessageParse rx_filter_band:0,0,50;, tuningk3 1, tuningtci 1, g_tuning 0
07840 Send to WHTP rx_filter_band:0,-2850,-150;
07840 TCIMessageParse rx_filter_band:0,0,50;, tuningk3 1, tuningtci 1, g_tuning 0
07840 Send to WHTP rx_filter_band:0,-2850,-150;
07840 TCIMessageParse rx_filter_band:0,0,50;, tuningk3 1, tuningtci 1, g_tuning 0
07840 Send to WHTP rx_filter_band:0,-2850,-150;
07840 TCIMessageParse rx_filter_band:0,0,50;, tuningk3 1, tuningtci 1, g_tuning 0
07840 Send to WHTP rx_filter_band:0,-2850,-150;
07840 TCIMessageParse rx_filter_band:0,0,50;, tuningk3 1, tuningtci 1, g_tuning 0
07840 Send to WHTP rx_filter_band:0,-2850,-150;
07840 TCIMessageParse rx_filter_band:0,-2850,-150;, tuningk3 1, tuningtci 1, g_tuning 0
07840 TCIMessageParse rx_filter_band:0,-2850,-150;, tuningk3 1, tuningtci 1, g_tuning 0
07872 TCIMessageParse rx_filter_band:0,-10,0;, tuningk3 1, tuningtci 1, g_tuning 0
07872 Send to WHTP rx_filter_band:0,-2850,-150;
07872 TCIMessageParse rx_filter_band:0,-2850,-150;, tuningk3 1, tuningtci 1, g_tuning 0
07903 TCIMessageParse rx_filter_band:0,-10,0;, tuningk3 1, tuningtci 1, g_tuning 0
07903 Send to WHTP rx_filter_band:0,-2850,-150;
07903 TCIMessageParse rx_filter_band:0,-2850,-150;, tuningk3 1, tuningtci 1, g_tuning 0
07934 TCIMessageParse rx_filter_band:0,-10,0;, tuningk3 1, tuningtci 1, g_tuning 0
07934 Send to WHTP rx_filter_band:0,-2850,-150;
07934 TCIMessageParse rx_filter_band:0,-2850,-150;, tuningk3 1, tuningtci 1, g_tuning 0
07965 TCIMessageParse rx_filter_band:0,-10,0;, tuningk3 1, tuningtci 1, g_tuning 0
07965 Send to WHTP rx_filter_band:0,-2850,-150;
07965 TCIMessageParse rx_filter_band:0,-2850,-150;, tuningk3 1, tuningtci 1, g_tuning 0
07997 TCIMessageParse rx_filter_band:0,-10,-10;, tuningk3 1, tuningtci 1, g_tuning 0
07997 Send to WHTP rx_filter_band:0,-2850,-150;
07997 TCIMessageParse rx_filter_band:0,-2850,-150;, tuningk3 1, tuningtci 1, g_tuning 0
08028 TCIMessageParse rx_filter_band:0,-10,-10;, tuningk3 1, tuningtci 1, g_tuning 0
08028 Send to WHTP rx_filter_band:0,-2850,-150;
08028 TCIMessageParse rx_filter_band:0,-2850,-150;, tuningk3 1, tuningtci 1, g_tuning 0

**Comment by ExpertSDR3** [comment]
fixed
