### ISSUE TITLE
ESDR3 отображение частоты смещения при использовании RIT и XIT

### ISSUE THREAD

**Issue by ub3dqy** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#545]
SUNSDR2DX, S/N EED06121000432
ESDR3 1.0.2 Beta
Прошивка 86.8
Windows10Pro x64
Gigabyte X58A-UD7, Xeon X5675, RAM 24 ГБ, SSD Samsung 250 ГБ, Nvidia NVS 315, трансивер подключен к роутеру Keenetic.

Будет ли добавлено в функционал ESDR3 отображение частоты смещения при использовании расстроек RIT и XIT? При использовании панели ECODER каждый раз щелкать правой клавишей мышки на кнопки RIT и XIT что бы посмотреть частоту смещения не очень удобно. Удобнее когда значение смещения будет отображать постоянно при активации расстройки, например на на курсоре расстройки. 
Ранее писал об этом, но конкретного ответа так и не получил.

**Comment by UD2F** [comment]
Давно уже просили об этом на форуме и телеграмм канале, так и не сделали. Приходиться использовать сторонние приложения ( в частности LogHX).
Поддерживаю, крайне не удобно и не информативно...

**Comment by ub3dqy** [comment]
Спасибо за поддержку! У меня не получается через LOGHX,  показывает частоту, но неверную и при смещении частота не меняется. Поделитесь, может что-то нужно настроить?

**Comment by ExpertSDR3** [comment]
В Версии 1.0.4 появится отображение RIT и XIT
![rit_xit](https://user-images.githubusercontent.com/93903520/223968463-db1c7722-fd04-48eb-8835-744382b728a7.png)
