### ISSUE TITLE
TCI command "sql_enable:0,true;" does not work in ExpertSDR3 1.0.2 beta, build 23122022

### ISSUE THREAD

**Issue by DK8JV** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#548]
ExpertSDR3 1.0.2 beta, build 23122022, Windows 11, 
Issuing the sql_enable:0... command via TCI does not work. The TCI server just reports the current sql status.
Issuing the sql_enable:1... command for RX2, instead, does work.

Tested both on SunSDR2DX (EED06202100483, Firmware 79.8) and SunSDR2pro (EED05262100871, Firmware 87.8)

![image](https://user-images.githubusercontent.com/96922207/214033311-95a08525-18c9-4b2c-96e9-80ce7b305181.png)

Best 73
Eberhard, DK8JV

**Comment by ExpertSDR3** [comment]
Fixed

**Comment by DK8JV** [comment]
Thank you so much!

Best 73,
Eberhard, DK8JV

 

Von: EE ***@***.***> 
Gesendet: Freitag, 3. Februar 2023 09:39
An: ExpertSDR3/ExpertSDR3-BUG-TRACKER ***@***.***>
Cc: DK8JV ***@***.***>; Author ***@***.***>
Betreff: Re: [ExpertSDR3/ExpertSDR3-BUG-TRACKER] TCI command "sql_enable:0,true;" does not work in ExpertSDR3 1.0.2 beta, build 23122022 (Issue #548)

 

Fixed
