### ISSUE TITLE
Неисправленная ошибка параметра фильтра , режим CW при переходе с диапазона на диапазон.

### ISSUE THREAD

**Issue by uc0a** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#552]
При переходе с диапазона на диапазон , параметры фильтра приёмника F. WIDTH  переключаются на узкую полосу , чем установлен активной кнопкой , правильно работает только фильтр 500 hz. остальные фильтры: 400 hz переключается в 300 hz.
300 hz переключается в 100 hz.  250 hz переключается в 50 hz. 600 hz переключается в 400 hz.

**Comment by ExpertSDR3** [comment]
Исправлено, исправления будут в версии 1.0.4.
