### ISSUE TITLE
1.0.3

### ISSUE THREAD

**Issue by ra4lp** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#555]
Загрузил 1.0.3 ,в инфо версия 1.0.2 build 08022023.

**Comment by ra4lp** [comment]
![есдр](https://user-images.githubusercontent.com/93971152/218045794-09e3aed1-e1c0-405f-b21e-86942f0f0dc0.jpg)

**Comment by rvolchkov** [comment]
Windows installer updated on Google Drive
