### ISSUE TITLE
(MB1) Power setting in B.M. not showing ESDR3 1.0.3 Beta

### ISSUE THREAD

**Issue by LA9AKA** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#556]
As you can see in the picture, the power setting at the end of the row is missing.  I can drag the window vertically, but not horizontally. 

MB1 serial EED10241600059
ESDR3 1.0.3 Beta
Win10 64 32Gb RAM

73 de LA9AKA :) 

![BMmenu](https://user-images.githubusercontent.com/96302801/218195235-41e1e5eb-d3c4-4d3a-95f6-5a424806614d.JPG)

**Comment by py5hot** [comment]
I have same, use MB1 and not appear power settings on B.M.

**Comment by ExpertSDR3** [comment]
Fixed, it will be published soon.
