### ISSUE TITLE
Пропадает кнопка E-Coder в окне ExpertSDR3 0.10.0 Alfa

### ISSUE THREAD

**Issue by RX3RZ** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#56]
Перепрошил аппарат SSDR2DX и установил ESDR3 0.10.0
Если в окне ESDR3 щёлкнуть ЛКМ по кнопке E-Coder2, то это кнопка исчезает....
Если перезапустить программу - кнопка появляется.

**Comment by ExpertSDR3** [comment]
Подтверждено, будет исправлен в версии 0.11
