### ISSUE TITLE
Bug MB1 with Beta 1.0.3

### ISSUE THREAD

**Issue by DK2ST** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#560]
Hello, with the new beta 1.03 version there is the following problem on my MB1:

Almost every time after starting, the TRX does not transmit on the displayed frequency, sometimes it is 3Khz off, but sometimes more. The transmitter output power is also set to maximum. 
Sometimes it modulates in SSB when talking to the microphone, but then it doesn't transmit HF. If I turn the frequency briefly or switch it off and on in the software, everything is back to normal. 
And this happens almost every time I start the radio.

Bug ESDR3 Vers. Beta 1.03 / MB1 Ser.Nr. 10231500028, 16MB RAM, WIN10

**Comment by ExpertSDR3** [comment]
Fixed
