### ISSUE TITLE
MacOS Ventura with Beta 1.0.3

### ISSUE THREAD

**Issue by mmaseda12** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#561]
The S-meter window will no longer stay on top of the main window.

**Comment by SV1RXI** [comment]
Yes same here

**Comment by SV1RXI** [comment]
https://youtu.be/1XMdxxXlgLo

**Comment by M0mws** [comment]
Same here.

**Comment by reflectingme** [comment]
This is a duplicate of an already reported issue folks, you may want to place your feedback in the existing issue.

https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/issues/490

**Comment by mmaseda12** [comment]
You might be describing a different S-meter window behavior problem.  Everything worked fine here until 1.0.3.  Your issue seemed to be happening before 1.0.3.  There are a lot of reported issues to Apple about window focus.  Perhaps some of these issues are beyond the control of EE.  I would just like for EE to acknowledge there is still an issue in 1.0.4.  Everything works fine in Windows.Manuel W4SSBOn May 13, 2023, at 8:39 AM, John ***@***.***> wrote:﻿
This is a duplicate of an already reported issue folks.
#490

**Comment by mmaseda12** [comment]
Problem still exist in Sonoma.

**Comment by ExpertSDR3** [comment]
Fixed
