### ISSUE TITLE
ExpertSDR3 1.0.3  Ext Control not working

### ISSUE THREAD

**Issue by oz1ctz** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#562]
Using Sunsdr2pro   and win 10

In v 1.0.3 the external controls DO NOT WORK any more ,you can not switch them on and off in the Bandmanger anymore ..
They are always off

FIX :going back to V 3.0.0  EXT CTRL works again 

regards Brian /OZ1CTZ

**Comment by OK1YA** [comment]
Hi,
I have the same findings, in version ESDR3 1.0.3 - beta you cannot save Band manager settings and ExtControl outputs are still OFF
When ESDR3 1.0.3 - beta is restarted, the settings saved in previous versions of ESDR3 will be uploaded to BM again and usually works...
73!  Mek, OK1YA

**Comment by lb5va** [comment]
Yes, this happens to me also. 
And the PA-control also do not work or saved. 
Reported also on email info@sunsdr.com, answer from Roman Volchkov, was to try reinstall all.
That did not help. All ok with Esdr2.
LB5VA, Stig

**Comment by ExpertSDR3** [comment]
Fixed, fixes will be in 1.0.4 version.
