### ISSUE TITLE
XVTR setup - Incorrectly displayed frequency of the transverter for the 24GHz band

### ISSUE THREAD

**Issue by OK1YA** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#567]
HI,
 ESDR31 1.0.3 - beta, Win10, 16GB RAM
When in the XVTR settings, I enter RX / TX frequency 24048.000 MHz and IF 145.000 MHz, the display shows the wrong frequency 11.999.980, 480
The setting of 10,368,000 (3cm band) and lower XVTR bands is correct

**Comment by OK1YA** [comment]
sorry my setup:
Device: SunSDR2PRO EED05341700337
Firmware: 86.8
ExpertSDR3: 1.0.3 beta 10022023
OS: WIN 10
PC: Dell Intel(R) Xeon(R) CPU E3-1240 V2 @ 3.40GHz
RAM 16GB
73 Mek, OK1YA

**Comment by ExpertSDR3** [comment]
Fixed, fixes will be in version 1.0.4 .
