### ISSUE TITLE
JTDX does not detect audio TCI with ExpertSDR3

### ISSUE THREAD

**Issue by IU2NUB-Roberto** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#569]
Good morning
I'm Roberto IU2NUB,
I use a Sunsdr2 pro SN:EED05521000830, vers. 72.8, PCB rev:4
ExpertSDR3 Vers:1.0.3 beta Build 10022023
Bootcamp Vers:6.1 -Intel i9-9880H, 16Gb ram W10 with latest updates installed.
Jtdx V2.2.159 improved does not detect the TCI audio while if I activate the ExpertSDR2 version without changing any parameter the sound is detected.
Best regards
Roberto

**Comment by ExpertSDR3** [comment]
For ExpertSDR3 Vers:1.0.3 beta to need firmware up to 86.8.

**Comment by IU2NUB-Roberto** [comment]
Ok tnx
now all ok
Roberto
