### ISSUE TITLE
EESDR3 start up CW filter abnormal

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#570]
EESDR3 1.0.3 beta
Windows 11 64-bit
SunSDR2DX

When I start EESDR3 up in CW, the initial filter appears to be abnormal. For example, if I had the filter set to 500Hz bandwidth when I launch EESDR3, it shows 500Hz but the audio suggest that the filter setting is something narrower. If I click on the 500Hz bandwidth button, nothing changes but if I switch to some other bandwidth such as 250Hz, and revert to 500Hz I can then hear the normal sound of the filter. Once I do this, the problem does not show up until I shut down EESDR3 and re-launch it. Even using the soft-power on/off cycle will not bring the problem back until a relaunch of EESDR3.

This behaviour has been confirmed by other testers as well.

https://user-images.githubusercontent.com/13930571/222334055-cab06d89-e041-4a2b-9c23-1237810f2d21.mp4

**Comment by ExpertSDR3** [comment]
Fixed, fixes will be in 1.0.4 version.
