### ISSUE TITLE
ExpertSDR3  v1.0.3 Beta: audio record playback problem (on Windows 10 with SunSDR2DX)

### ISSUE THREAD

**Issue by HA1AH** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#572]
I detected this bug during the recent ARRL DX SSB contest.
Both TX1 and TX2 are active. TX1 is for run, TX2 is for calling back stations spotted in the dx cluster.
I play recorded CQ message in TX1.
I click on a spot in N1MM or directly in the TX2 band spectrum  of the ExpertSDR TX2 spectrum view to put the spot into the N1MM second entry window and jump TX2 to the frequency (SO2R setup).
This action is immediately stops the playback CQ message in TX1.
Similarly, if I'm speaking through MIC1 on TX1 and click something on the view of TX2, it stops transmitting my voice in TX1.

This is only in SSB mode, on CW it works correctly.

Expected behavior: if I click something in the view of TX2, it mustn't affect the transmission in TX1.

**Comment by ExpertSDR3** [comment]
Fixed, fixes will appear in version 1.0.4 .

**Comment by HA1AH** [comment]
Thank you very much for the quick solution!
