### ISSUE TITLE
Zoom cursor does not follow VFO

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#582]
EESDR3 1.0.3 beta
Windows 11 64-bit

When I select "Zoom cursor follows VFO", this only works when I'm tuning with the E-Coder2. When I tune using the mouse wheel, the zoom cursor does not follow the VFO even with the option selected.

**Comment by ExpertSDR3** [comment]
This is not a bug, there is a description of how this function works in the ESDR3 documentation.
