### ISSUE TITLE
Break-in "Macros Speed" setting is not retained

### ISSUE THREAD

**Issue by williamscody** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#583]
Environment:
Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz, 32GB RAM
Windows 11 Pro, 64-bit, version 21H2, OS Build 22621.1555
AMD Radeon 580 Graphics Card (1 DVI monitor and 2 DP monitor connected)
SunSDR2DX, S/N EED06202100503, PCB Revision 11, Firmware 86.8
ESDR3 1.0.3 beta, Build 10022023

Issue: Changes to the Break.In "Macros Speed" setting are not retained.  Any change in WPM speed reverts to 30 WPM.

Steps to reproduce:
1) Tune to any band (20M for example)
2) Enable CW mode 
3) Right-click on Break.In button.  Witness that Macros Speed is set to 30 WPM.
4) Change Macros Speed to 25 WPM, press enter.
5) Right-click on Break.In button, and witness that Macros Speed is now 25 WPM.
6) Switch to any other band (40M for example), and then back to original band (20M)
7) Right-click on Break.In button.  Witness that Macros Speed has changed back to 30 WPM.

**Comment by VK6NX** [comment]
Seems fixed in 1.0.4

**Comment by williamscody** [comment]
Agreed.  Appears to be fixed in 1.0.4.
