### ISSUE TITLE
Waterfall moves in opposite direction of signal in GEN2 Band

### ISSUE THREAD

**Issue by pborges** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#585]
**Description:**
When I drag to the left, the signals in the waterfall move to the right. 
Seems to only do this in the "GEN 2" band.

**Device**
SunSDRDX2 
Firmware: 86.8

**Software**
ExpertSDR3 Version: 1.03 beta
BUILD: 10022023

**OS**
Win 11

**Video of problem**
https://imgur.com/WtxSAqF

**Comment by ExpertSDR3** [comment]
This happens if TX1 and TX2 are in different Nyquist zones, at the moment the program does not block TRX2 switching to another Nyquist zone
