### ISSUE TITLE
Serious bug in 1.0.4 beta, which didn't exist in 1.0.3: frequency of TX2 goes out of sync

### ISSUE THREAD

**Issue by HA1AH** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#588]
Dear Expert Electronics,

I already reported this bug to Roman about a month ago, but unfortunately it 
hasn't been fixed. It definitely didn't exist n previous versions, including 1.0.3.

So the bug in the 1.0.4 beta version:
I use TX1 for CQing. Additionally I use TX2 for clicking on dx cluster spots shown its spectrum view to call back stations.
While I'm CQing on TX1 I sometimes drag or resize the view of TX2 with the mouse and scroll it to go to other segments of the band .

And here is the problem: the shown frequency and the band scope get out of synchrony, i.e. the stations are shown on totally invalid frequencies.
I made a demonstrating video which is available here: https://photos.app.goo.gl/ZKgtbmPRSZoTtQLR8

!!!!!!!! Additionally, the TX and RX frequencies of TX2 will be different.

It makes the software sometimes unusable in contests.

So, please fix it.

**Comment by ExpertSDR3** [comment]
Fixed

**Comment by HA1AH** [comment]
Hm. Interesting bug fix.
Now moving the TX2 screen with mouse drag and move is disabled during TX1 is transmitting.
So, user really can't cause any asynchrony.

BUT I THINK THAT IS NOT THE SOLUTION THAT WE DISABLE A FUNCTIONALITY WHICH WORKED IN VERSION 1.0.3 BACK CORRECTLY!!!!!

I think, the correct solution would be, like it was still in 1.0.3, that user can modify TX2 display and it doesn't cause any problem 
in its frequency handling! Could you have a look at what was done between 1.0.3 and 1.0.4, which caused this bug? And would it be possible correcting really that bug instead of disabling a feature?
