### ISSUE TITLE
ExpertSDR 3 Since V 0.12 No Longer Works with SDC TCI CLient Rig-Emulator for CW DTR 

### ISSUE THREAD

**Issue by makidoja** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#590]
ExpertSDR 3 Any version after 0.12
SDC Sends the following to SDR over TCI and it worked in V0.12 but not in later versions

19-02-33:454 client: keyer:0,true;
19-02-33:598 client: keyer:0,false;
19-02-33:649 client: keyer:0,true;
19-02-33:790 client: keyer:0,false;
19-02-33:937 client: keyer:0,true;
19-02-34:079 client: keyer:0,false;
19-02-34:129 client: keyer:0,true;
19-02-34:273 client: keyer:0,false;
19-02-34:321 client: keyer:0,true;
19-02-34:465 client: keyer:0,false;
19-02-34:513 client: keyer:0,true;
19-02-34:657 client: keyer:0,false;
19-02-34:705 client: keyer:0,true;
19-02-34:849 client: keyer:0,false;
19-02-34:996 client: keyer:0,true;
19-02-35:140 client: keyer:0,false;
19-02-35:191 client: keyer:0,true;
19-02-35:236 client: keyer:0,false;
19-02-35:284 client: keyer:0,true;
19-02-35:428 client: keyer:0,false;
19-02-35:479 client: keyer:0,true;
19-02-35:525 client: keyer:0,false;
19-02-35:671 client: keyer:0,true;
19-02-35:815 client: keyer:0,false;
19-02-35:863 client: keyer:0,true;
19-02-35:911 client: keyer:0,false;
19-02-35:959 client: keyer:0,true;
19-02-36:103 client: keyer:0,false;
19-02-36:247 client: keyer:0,true;
19-02-36:295 client: keyer:0,false;
19-02-36:541 client: trx:0,false,tci;

Looking at when I use RadioSync I see that this now has a number after the  true or flase which I suspect is MS

19-03-14:806 client: keyer:0,true,0;
19-03-14:949 client: keyer:0,false,142;
19-03-14:999 client: keyer:0,true,49;
19-03-15:141 client: keyer:0,false,142;
19-03-15:286 client: keyer:0,true,145;
19-03-15:430 client: keyer:0,false,143;
19-03-15:479 client: keyer:0,true,48;
19-03-15:622 client: keyer:0,false,143;
19-03-15:670 client: keyer:0,true,47;
19-03-15:814 client: keyer:0,false,143;
19-03-15:863 client: keyer:0,true,48;
19-03-16:006 client: keyer:0,false,143;
19-03-16:054 client: keyer:0,true,47;
19-03-16:199 client: keyer:0,false,144;
19-03-16:342 client: keyer:0,true,143;
19-03-16:487 client: keyer:0,false,144;
19-03-16:534 client: keyer:0,true,47;
19-03-16:583 client: keyer:0,false,48;
19-03-16:631 client: keyer:0,true,48;
19-03-16:774 client: keyer:0,false,143;
19-03-16:822 client: keyer:0,true,47;
19-03-16:870 client: keyer:0,false,48;
19-03-17:015 client: keyer:0,true,144;
19-03-17:159 client: keyer:0,false,143;
19-03-17:209 client: keyer:0,true,49;
19-03-17:255 client: keyer:0,false,45;
19-03-17:303 client: keyer:0,true,48;
19-03-17:449 client: keyer:0,false,145;
19-03-17:592 client: keyer:0,true,143;
19-03-17:641 client: keyer:0,false,48;
19-03-17:887 client: trx:0,false;

I cannot see anything in the TCI specification that requires a MS figure to be used for the CW keying.

Jim M0CKE

**Comment by ExpertSDR3** [comment]
The keyer command was modified after updating the CW core in the transceiver firmware
