### ISSUE TITLE
ExpertSDR 1.0.3+: TX via RadioSync not working anymore!

### ISSUE THREAD

**Issue by BuddyButterfly** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#592]
# Description
ESDR3 is connected via 2 VACs:
![Screenshot_20230514_003440](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/8482998/7c10461e-fc32-41f7-9b73-f2218d60dafb)

The audio setup can be seen in the following screenshot.

PortAudio-149: RadioSync
sunsdr_vac2_ext: Sink of external program
sunsdr_vac2: Sink of sunsdr
![Screenshot_20230514_003106](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/8482998/b3431e23-4ef7-49f7-89c5-1238662161e7)

RX works perfect and other software like fldigi or wsjt is receiving audio perfectly!
What does not work, is the TX side.

When providing a tuning signal (1kHz) to the input of RadioSync (in18/in19) the signal does not appear in ESDR3.
When wiring the output of sunsdr_vac2_ext to the pc speakers, it can be verified that the signal is there:
![Screenshot_20230514_003358](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/8482998/fc76a28b-24aa-4b3f-a2f6-498075f54112)

This is the sound configuration with, for example, wsjt-x connected (here QtPulseAudio device). The right side (input to wsjt-x) works perfectly. The left side (input to RadioSync to ESDR3) does not work, although the tuning tone can be heard (wire to PC speaker).
![Screenshot_20230514_004922](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/8482998/7869b522-2d14-4ff9-b841-67611219a983)

I have tried to vary configuration a lot to get it working. Created the VACs with different sampling rates from 8k to 48k. 
RadioSync only shows green when selecting 48k. 

ESDR3 RX2 is configured to use Microphone 2:
![Screenshot_20230514_004112](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/8482998/24e817c1-f903-4346-be49-fbc0eb33cca4)

**Any Help is really appreciated, as I am not able to work any digital modes anymore!**

# System Setup
<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">

<colgroup>
<col  class="org-left" />
</colgroup>

<colgroup>
<col  class="org-left" />
</colgroup>

<colgroup>
<col  class="org-left" />
</colgroup>

<colgroup>
<col  class="org-left" />
</colgroup>

<colgroup>
<col  class="org-left" />
</colgroup>

<colgroup>
<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">Transceiver</th>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-left">Software</th>
<th scope="col" class="org-left">&#xa0;</th>
<th scope="col" class="org-left">PC and OS</th>
<th scope="col" class="org-left">&#xa0;</th>
</tr>

<tr>
<th scope="col" class="org-left">Item</th>
<th scope="col" class="org-left">Value</th>
<th scope="col" class="org-left">Item</th>
<th scope="col" class="org-left">Value</th>
<th scope="col" class="org-left">Item</th>
<th scope="col" class="org-left">Value</th>
</tr>
</thead>
<tbody>
<tr>
<td class="org-left">Serial</td>
<td class="org-left">EED06442100723</td>
<td class="org-left">Software</td>
<td class="org-left">ExpertSDR3</td>
<td class="org-left">OS</td>
<td class="org-left">Kubuntu 22.04 Jammy</td>
</tr>

<tr>
<td class="org-left">Transceiver</td>
<td class="org-left">SunSDR2DX</td>
<td class="org-left">SW Version</td>
<td class="org-left">x64 1.0.4 beta</td>
<td class="org-left">CPU</td>
<td class="org-left">i7-8750H</td>
</tr>

<tr>
<td class="org-left">Firmware</td>
<td class="org-left">86.8</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">Memory</td>
<td class="org-left">32GB</td>
</tr>

<tr>
<td class="org-left">PCB revision</td>
<td class="org-left">11</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">GPU</td>
<td class="org-left">Nvidia GTX 1070 Mobile</td>
</tr>

<tr>
<td class="org-left">PA version</td>
<td class="org-left">13</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">Sound Driver</td>
<td class="org-left">Pipewire</td>
</tr>

<tr>
<td class="org-left">PA revision</td>
<td class="org-left">2</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">+ pipewire-pulse</td>
</tr>

<tr>
<td class="org-left">ATU</td>
<td class="org-left">disconnected</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">+ pipewire-jack</td>
</tr>

<tr>
<td class="org-left">PLL</td>
<td class="org-left">OK</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-left">Reference mode</td>
<td class="org-left">Internal</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-left">Internal Reference</td>
<td class="org-left">OK</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-left">External Reference</td>
<td class="org-left">NO</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-left">PLL1 Lock</td>
<td class="org-left">OK</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-left">PLL2 Lock</td>
<td class="org-left">OK</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-left">PLL2 REF clock</td>
<td class="org-left">OK</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-left">PLL2 FB clock</td>
<td class="org-left">OK</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>

<tr>
<td class="org-left">VCXO statu</td>
<td class="org-left">OK</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>
</tbody>
</table>

**Comment by rvolchkov** [comment]
Hello.
Here is the snippet from the User Manual, which will be released soon. It describes how to set up such connections.
[ExpertSDR3_User_Manual_ENG_DX-082-089.pdf](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/files/11998880/ExpertSDR3_User_Manual_ENG_DX-082-089.pdf)

**Comment by BuddyButterfly** [comment]
Please see #598. Please do not quickly close tickets till they are solved to the customers/users satisfaction.
