### ISSUE TITLE
TCI 1.9 missing argument

### ISSUE THREAD

**Issue by sveit** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#593]
TCI 1.9 is missing the channel argument in RX_SENSORS_ENABLE:arg1,arg2;
Is it possible to enable it please?
In previous releases of TCI this was enabled. 
I have an SSDR driver with a display and two windows VFO A and VFO B. 
VFO B does not show a working S-meter.
Thank you 
Stan OK1AU
![SUN](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/7374296/af8bf327-278b-414e-962f-1907642d8b7e)

**Comment by ExpertSDR3** [comment]
In TCI 1.10 will be added new command **rx_channel_sensors**. This command will work similarly to **rx_sensors**, but will be sent for each channel separately. The new version of the TCI 1.10 protocol will appear in version 1.0.6
