### ISSUE TITLE
RIT XIT и Split

### ISSUE THREAD

**Issue by RL6C** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#599]
В режимах RIT и XITнет плавной настройки валкодером только дискретно с помощью предустановки и мышкой, а должно быть как в ESDR2 при выборе RIT XIT частота приема или передачи соответствено перестраивается плавно валкодером.
Режим Split при включении нет постоянно подсветки кнопки включения режима и не отключается режим Split повторным нажатием на кнопку Spit,

**Comment by ExpertSDR3** [comment]
В Версии 1.0.8 управление RIT/XIT будет 10 Гц по умолчанию и 1 Гц для режима Fine tune
При повторном нажатии на кнопку SPLIT передача будет возвращаться на VFOA
