### ISSUE TITLE
Line-out settings do not fit on screen

### ISSUE THREAD

**Issue by rvolchkov** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#6]
SunSDR2 PRO
0.10.0 build 0311021
Windows 10

Line-out settings do not fit on screen if options are expanded.
In Audio settings, if you expand too many options, RX1 to WAV, RX2 to WAV, RX1 to Soundcard or RX2 to Soundcard, the options lower in the list disappear off the visible panel.
![LineOut_options](https://user-images.githubusercontent.com/90688941/140724147-a8a16668-d0f0-43fd-9fe4-2fe7a8be26c9.jpg)

**Comment by ExpertSDR3** [comment]
Vertical scrolling of settings works for line audio output settings

**Comment by ExpertSDR3** [comment]
Закрыто
