### ISSUE TITLE
TX FRQ BUG! 1.0.4 beta (similar reported earlier by OZ1CTZ)

### ISSUE THREAD

**Issue by lb5va** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#601]
TX FRQ BUG! 1.0.4 beta
This happens with my SunSDR2pro, FW86.8:
After turning the Sun radio-task with software-switch OFF and ON again, this bug apear:
Beeing on 80m or whatever, It transmitt on 1.900MHz! (?)
My SWR then shows 1:9.9. This is with TX (SSB), not TUNE.
With TUNE it transmit on the correct frequency. Or, after a small change of the frequency, I hear a click in the SUN and it transmits correctly. 
I suspected it transmitted somwhere else than the VFO frequency because of the high swr shown. I checked on my local KIWI SDR receiver and found that it transmitted on 1.900MHz sharp. It uses the mode that is set.
If I close the Rig window and restart it with START from the ExpertSDR3 Device manager, everything is ok. It happans only with the Off/On function witch seems as a "stop and sleep" device action. After reading other bug-reports; I tested changing the sample-rate, it also happens. Same as Bug report from OZ1CTZ reported Nov 23, 2022
Stig - LB5VA

**Comment by ExpertSDR3** [comment]
Fixed
