### ISSUE TITLE
Issue displaying spots on panorama

### ISSUE THREAD

**Issue by makidoja** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#602]
Sending spots to the Panorama for EESDR should not need to have any comment,  however unless the comment is set to Demo the display does not show the spot

Format is
05-23-06:735 client: spot:PB2T,CW,3517000,4294909677,Demo;

Format should be
05-23-06:735 client: spot:PB2T,CW,3517000,4294909677,;

Jim M0CKE

**Comment by ExpertSDR3** [comment]
Fixed
