### ISSUE TITLE
Работа с внешним усилителем в режима "TONE"

### ISSUE THREAD

**Issue by Nick1953** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#604]
При работе с внешним усилителем для настройки в режиме "TONE", формирование сигнала РТТ в трансивере происходит одновременно с формированием высокочастотного сигнала без какой-либо задержки, что приводит с срабатыванию системы защиты в усилителе, т.к. реле в усилителе не успевают переключиться.
В программе ESDR-3 предусмотрено формирование  задержек на вкладке "ВМ", но это не совсем удобно и правильно при работе с различными внешними программами и Логами ( там есть установки задержек для различных случаев работы).
Предлагается Разработчиками программы ESDR-3 формировать ПОСТОЯННУЮ ЗАДЕРЖКУ формирования высокочастотного выходного сигнала относительно сигнала РТТ при работе трансивера в режиме "TONE" в размере 100 мс, что будет достаточно для переключения всех реле в усилителях мощности даже изготовленных в прошлом веке. Также сделать не возможным в режиме "TONE" формирование задержек, установленных на вкладке "ВМ".
Все это позволит исключить срабатывание защит в усилителях, подключенных к трансиверу, в режиме настройки, а также в работе с различными внешними программами и Логами.

**Comment by rm6lw** [comment]
"...формирование сигнала РТТ в трансивере происходит одновременно с формированием высокочастотного сигнала без какой-либо задержки,..."
У меня и в TONE и при работе SSB/CW/DIGI - нет проблем - везде установлены 10 ms - все работает, транзисторный усилитель EB500 (все защиты, и не срабатывают - значат все ОК) - один раз в BM установил задержки и забыл...
