### ISSUE TITLE
New Feature: Layout change to make space between power button and TX/Tune

### ISSUE THREAD

**Issue by ttierney** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#61]
Could the layout be modified so that the TX & Tune buttons are moved away from the main Power On/Power off button. Sometimes, when intending to TX I have powered off the radi
![Layout](https://user-images.githubusercontent.com/61117386/142685438-3ad8c8e9-dcda-40ff-8c3d-48e28256580d.png)
o.

**Comment by ExpertSDR3** [comment]
[Move to](https://github.com/ExpertSDR3/ExpertSDR3-SUGGESTIONS/issues/11)
