### ISSUE TITLE
SunSDR2pro no RF output on VHF after Power off/on in EESDR3

### ISSUE THREAD

**Issue by DK8JV** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#615]
Device: SunSDR2 pro
Serial #: EED05262100871
Firmware: 86.6
Software: EpertSDR3, 1.0.4 beta / Build: 24042023 
Running on Windows 11, 64bit, Intel NUC i7

Symptom:
EESDR3 is started, set to 2m. --> Transmitting works without any problems.
SunSDR2 pro is stopped by clicking the "Stop transceiver" button in EESDR3.
SunSDR2 pro  is started again by clicking the "Start transceiver" button in EESDR3. 

After having done the above:
Reception works as usual, but there is no RF output generated. (There is absolutely no RF present when transmitting)
However, the power meter in EESDR does show RF output. This happens independent from the modulation type. (CW not tested)

This situation can be cured by:
Either closing and restarting EESDR3 or by changing the band from 2m to any shortwave band and switching back to 2m.

The problem occurs no matter what mic input, including using TCI. 
Also, it is independent from the band manager settings / PA settings.

The error can also be reproduced on another SunSDR2pro (same FW and EESDR3 software, serial number unknown to me) at a ham friend's location.

The problem does not occur on my SunSDR2 DX (EED06202100483) with the same software configuration.

vy 73
Eberhard, DK8JV

P.S: A transceiver reset, deep reset with new FW install, and deleting all configuration files for the transceiver in EESDR3 didn't cure the error.

**Comment by ExpertSDR3** [comment]
Fixed
