### ISSUE TITLE
RadioMacros: Failed to create GUI! error on macOS

### ISSUE THREAD

**Issue by tudor-v** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#617]
When attempting to open RadioMacros (released today with the 1.0.5 beta), I get this error: **Failed to create GUI!**
The app stays open, but since there's no GUI, it's useless.

macOS Sonoma 14.0 (23A344)
Mac mini M1

**Comment by themagoose** [comment]
Same thing here with MacOS Ventura 13.6.1
MacBook Pro mid 2017

**Comment by m0euk** [comment]
Same here 2023 M2 Mac Mini Ventura 13.4.1

**Comment by robin-vss** [comment]
Same issue confirmed here on Apple M1 Pro and MacOS 14.1.

**Comment by ExpertSDR3** [comment]
Fixed
