### ISSUE TITLE
New Feature: Step up/down

### ISSUE THREAD

**Issue by ttierney** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#62]
Would it be possible to include a new control to enable the frequency to be moved up/down using the mouse based on the current Step setting. This would be very useful on VHF. 
![Up Down buttons](https://user-images.githubusercontent.com/61117386/142688704-ce7b75bb-ea33-449c-9745-fbe41bed365a.png)
.

**Comment by ExpertSDR3** [comment]
[Move to](https://github.com/ExpertSDR3/ExpertSDR3-SUGGESTIONS/issues/10)
