### ISSUE TITLE
E-coder not working on MacOS14.1.1 with new beta software 1.0.5

### ISSUE THREAD

**Issue by ea1aha** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#620]
I have an E-coder mini working perfectly on Windows with beta version 1.0.5. Today I installed beta version 1.0.5 on my Mac Book Pro with M2 Chip, running MacOS Sonoma 14.1.1 and it has stopped working. The program detects it and is activated, but it does not do any of the programmed functions. Before installing beta 1.0.5, Ecoder worked perfectly with beta 1.0.4

EA1AHA
Juan Carlos

**Comment by diorich** [comment]
I have exactly the same issue it works fine on windows but had to revert back to 1.0.4 to use the ecoder2   I am also using a iMac

**Comment by M0mws** [comment]
Same here.

**Comment by OK1BR** [comment]
I have same problem, Mac Studio (M1), MacOS Sonoma.

**Comment by ExpertSDR3** [comment]
Fixed in 1.0.6
