### ISSUE TITLE
Radio Spot crashes in macOS

### ISSUE THREAD

**Issue by esteban-sk** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#623]
When adding a cluster server that does not connect properly, it cannot be deleted, because each time you try disconnect it first, RadioSpot crashes. Using macOS 13.6 Ventura

It happens with: telnet.reversebeacon.net:7000 which I was unable to connect (yellow light).

The added server cannot be saved, but have to be exported and imported each time the program is started.

**Comment by ExpertSDR3** [comment]
Fixed
