### ISSUE TITLE
Blue Triangle moves autonomously after tx

### ISSUE THREAD

**Issue by kgmpwg** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#625]
When I move the blue triangle below the frequency axis according to my needs, then after returning from transmit to receive mode the blue triangle returns to the old position from where I moved it from and the whole frequency scale is shifted back to the old position. Especially in conjunction with JTDX.
Windows 10, 1.0.3 Beta expertsdr
Thanks and best regards,
Kurt

**Comment by ExpertSDR3** [comment]
![image](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/93903520/fda68ccc-4666-4cbb-a339-e3a333b8d645)

Switch off the function of following the cursor behind the filter
