### ISSUE TITLE
Pop out  S-Meter in MacOS

### ISSUE THREAD

**Issue by mmaseda12** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#628]
The pop out S-meter with MacOS doesn’t work.  While the problem is still around in 1.05 beta the follow temporary workaround has been found.  It has been tested with Intel and M1 Mac’s running Ventura and Sonoma.

Bob Thomas wrote on Facebook support forum:

I think I found a way to make the pop out S-Meter work with MacOS and V3 1.05.  I’m running Sonoma with a 2020 Intel I7 iMac.  Start V3 and make sure the pop out S-Meter is not selected.  Close V3 completely.  Start V3 using the start button in the Device Manager.  When the V3 application starts up don’t press the ON button yet.  Go ahead and enable the pop out S-Meter.  It should pop out properly and remain on the screen.  You can now use the ON button on the app and it should stay there and not disapear when you mouse click any buttons.  You just need to disable the pop out S-Meter when you want to close the application so it will work properly the next time you run the V3.

**Comment by ExpertSDR3** [comment]
Fixed
