### ISSUE TITLE
New Feature: Switching to the repeater input frequency

### ISSUE THREAD

**Issue by ttierney** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#63]
Could you add a new control so that when listening to a repeater output on 2M you are able to switch to the repeater input. e.g. Repeater is on 145.650. Click a button to listen on 145.050. (-600kHz)
![Repeater Input](https://user-images.githubusercontent.com/61117386/142690727-81c9724d-0abb-4c87-953a-440a233197dd.png)

**Comment by ExpertSDR3** [comment]
[Move to](https://github.com/ExpertSDR3/ExpertSDR3-SUGGESTIONS/issues/9)
