### ISSUE TITLE
Ошибки в работе аудио миксера.

### ISSUE THREAD

**Issue by UA6AA** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#634]
При работе в режиме SO2R (используются оба приемника) в версии ExpertSDR3 1.0.5 Beta найден BUG.
1. Откройте оба приёмник (RX1 и RX2)
2. Запрограммируйте в E-Coder на отдельные кнопки: Listen RX1 only, Listen RX2 only, Listen RX1 in left ear and RX2 in right ear.
3. Нажмите  Listen RX1 only. В обоих наушниках будет слышно только RX1
4. Нажмите  Listen RX2 only. В обоих наушниках будет слышно только RX2
5. Нажмите  Listen RX1 in left ear and RX2 in right ear. В левом наушнике слышно RX1, а в правом RX2.
6. Нажмите **Listen RX1 only  и его будет слышно только в левом наушнике, а должно быть в обоих**. **Тоже самое если нажать 
Listen RX2 only.**

**Comment by ExpertSDR3** [comment]
Исправлено
