### ISSUE TITLE
TCI command "keyer" doesn't work

### ISSUE THREAD

**Issue by DK8JV** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#639]
TCI version 1.9, EESDR 1.05 beta, current firmware:

The command, when issued through TCI,  is simply ignored.

KEYER                   Informs about CW Key state (not automatic). 
Install                   KEYER:arg1,arg2;                       arg1 – transceiver periodic number. 
                                                                               arg2 – CW key state (pressed -true, not pressed – false). 
Type                     Unidirectional control 
Example               KEYER:0,true;

Note                    Sent only by the TCI client.

**Comment by ExpertSDR3** [comment]
The Keyer command has been changed, the description will appear in the document version 1.10
