### ISSUE TITLE
EESDR3 TCI protocol problems

### ISSUE THREAD

**Issue by UA6AA** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#640]
В протоколе явные ошибки.
В частности не все все команды от логера N1MM передаются в SunSDR2 pro.
В частности не передается управление расстройкой RIT.
В N1MM в режиме Run (режим работы на CQ) стрелками вверх и вниз (Arrow UP/Arrow down) должна включаться расстройка на трансивере. Она не включается.
Проверил на TS-590, TS-890 все включается.
Там где трансивер обычный и управление CAT через com port, а не через симбиоз com порт и TCI все нормально.

**Comment by ExpertSDR3** [comment]
Исправлено, в версии 1.0.6 будут исправления

**Comment by UA6AA** [comment]
Не исправлено. Не работает.
Давайте я проверять все баги что пишу проверять буду?
