### ISSUE TITLE
Expert SDR v 1.0.6 osx error

### ISSUE THREAD

**Issue by IU2NUB-Roberto** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#643]
error 3840 when opening the dmg
downloaded 2 times same problem
iu2nub Roberto

![Screenshot 2023-12-28 alle 10 52 29](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/126553986/d9b75d53-6da7-4869-ace9-a86b19a68cb7)

**Comment by m0euk** [comment]
I've not seen this problem here on M2 Mini running Sonoma, installed and operating fine.

**Comment by IU2NUB-Roberto** [comment]
Now is ok

Il giorno gio 28 dic 2023 alle 11:39 m0euk ***@***.***> ha
scritto:
