### ISSUE TITLE
ExpertSDR3 1.0.6 невозможно сменить микрофон из TCI

### ISSUE THREAD

**Issue by R1BLH** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#647]
Если остался выбран микрофон TCI (после работы с JTDX, к примеру), то невозможно сменить его на физический микрофон (Mic,1/Mic.2/Mic.PC). Правый клик не вызывает меню.

![изображение](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/16667173/26442d87-2ac6-43b9-99c3-79107e544b00)

Удалось переключить, только редактируя сохранённый .json в рабочем каталоге программы.

Для повторения ситуации необходимо:
1. инициировать включение передачи по TCI (к примеру из JTDX).
2. принудительно завершить сессию ExpertSDR3 (закрыть окно приложения).
3. при следующем запуске будет выбран микрофон TCI.

**Comment by ExpertSDR3** [comment]
Исправлено, исправление будет в версии  1.0.7
