### ISSUE TITLE
No build number on current release

### ISSUE THREAD

**Issue by G4ENZ-Martin** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#65]
![image](https://user-images.githubusercontent.com/94721418/142697687-8c994adf-fb67-416f-9ce0-594815b15172.png)
![image](https://user-images.githubusercontent.com/94721418/142697718-26b5d566-2ca4-49ea-9930-16775f06af40.png)

**Comment by ExpertSDR3** [comment]
The build number is displayed in intermediate versions that are used in closed beta tests.
