### ISSUE TITLE
Не исправлено. Не работает.

### ISSUE THREAD

**Issue by UA6AA** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#651]
Не исправлено. Не работает.
Давайте я проверять все баги что пишу проверять буду?

_Originally posted by @UA6AA in https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/issues/640#issuecomment-1872550792_

**Comment by UA6AA** [comment]
В режиме Run расстройка на eesdr3 не включается. Работает только в режиме S&P. но там не расстройка. а просто изменение частоты.
Свяжитесь со мной. если Вам нужна проверка перед выпуском релиза...

**Comment by ExpertSDR3** [comment]
Здравствуйте, вам на почту Роман отправил ссылку на тестовую версию с доработками, если проблема в той версии устранена, дайте знать.

**Comment by UA6AA** [comment]
Исправили. RIT работает правильно.

**Comment by UA6AA** [comment]
done
