### ISSUE TITLE
Нет приема после переключения на 160 в AM ( No reception after switching to AM on 160)

### ISSUE THREAD

**Issue by UA6AA** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#654]
windows 10
EESDR3 1.06
Застарелая ошибка. Если включишь амплитудную модуляцию ( AM) на 160, то эфира нет. Приема нет.
И переключение на другие виды излучения не помогают.
Только перезапуск eesdr3

**Comment by R1BLH** [comment]
> Застарелая ошибка. Если включишь амплитудную модуляцию ( AM) на 160, то эфира нет. Приема нет.
> И переключение на другие виды излучения не помогают

Win11Pro, SunSDR2 повторить не получилось.
![изображение](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/16667173/5e7d3229-e5f9-44fc-8121-d085693569d1)
![изображение](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/16667173/37d7f706-09fc-4f94-b3cb-b72b0593cd13)

**Comment by UA6AA** [comment]
Перейдите на 160. включите АМ. Потом уйдите на другой диапазон. Затем вернитесь на 160.

**Comment by ExpertSDR3** [comment]
Исправлено
