### ISSUE TITLE
TX2 screen is blocked while TX1 is transmitting

### ISSUE THREAD

**Issue by HA1AH** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#655]
Dear EE Developers,

you made a fix for the #588 bug in V1.0.6 beta, which solved the out of sync problem, but it also causes serious fall back in functionality.
You simply blocked the RX2 display. Now if RX1 is transmitting, I am not able
-to jump to a new multiplier with RX2 if I click on the callsign in N1MM.
-to fine tune the RX2 frequency by rolling the mouse wheel to go to the exact frequency of a station.
-to jump to random frequency by clicking on it on the RX2 display.

This is a serious fall back, which really makes S&P more difficult in contests.

Please fix this issue so, as it was available in version 1.0.3 beta. There worked everything properly:
I could do the actions I listed above and if I moved the RX2 display by mouse drag and move or I resized it, it didn't lose its correct frequencies. So, please check, what was made in 1.0.4, that made the out of frequency sync issue and roll back to the functionality of 1.0.3.

Now I had to install back the previous 1.0.5 version, as it was better with its all weaknesses.

73:
Tibor
HA1AH

**Comment by rvolchkov** [comment]
Hello Tibor.
Now the software works as it should, tuning should be locked while the transmission is active. We've been asked to lock it several times by other developers. Otherwise, it is dangerous for third-party PAs connected to the TRX via TCI, for example.
It'll be unlocked when we implement Duplex, the whole software will operate differently and it'll be available.

**Comment by HA1AH** [comment]
Hi Roman,

I understand. Thank you for the explanation.

73:
Tibor

**Comment by rvolchkov** [comment]
Вы согласны получать наши рассылки?  На связи компания ООО "Эксперт Групп", Российский производитель SMT-оборудования.Приглашаем вас подписаться на нашу новостную рассылку. В ней мы будем делиться с вами информацией о новых моделях нашего SMT оборудования, разработках и других новостях. Мы гарантируем отправку только полезной и актуальной информации, не чаще раза в месяц.Если вам когда-либо покажется, что эта информация вам больше не интересна, вы всегда сможете отказаться от получения рассылки.Мы будем рады видеть вас в числе наших
подписчиков. Спасибо за доверие!С уважением,ООО "Эксперт Групп"     Получать:
https://mailinternetsub.com/ru.b24-bl55aw/pub/mail/consent.php?consent=apply&type=mail&tag=%7B%22CODE%22%3A%22reply%2Bavt43lpnects4h7f3iokmfwdwtbojevbnhhhvvn3ae%40reply.github.com%22%2C%22CONTACT%22%3A%22822%22%2C%22RECIPIENT%22%3A%2227726%22%2C%22POSTING%22%3A%228%22%2C%22CONSENT%22%3A8%7D.1715164817.2e001c2b5c776f2c7b2a4ffd996280cf6a3e381600e2d1a3f2572463c5ff4459
Нет, не присылайте мне ничего:
https://mailinternetsub.com/ru.b24-bl55aw/pub/mail/consent.php?consent=reject&type=mail&tag=%7B%22CODE%22%3A%22reply%2Bavt43lpnects4h7f3iokmfwdwtbojevbnhhhvvn3ae%40reply.github.com%22%2C%22CONTACT%22%3A%22822%22%2C%22RECIPIENT%22%3A%2227726%22%2C%22POSTING%22%3A%228%22%2C%22CONSENT%22%3A8%7D.1715164817.2e001c2b5c776f2c7b2a4ffd996280cf6a3e381600e2d1a3f2572463c5ff4459


---------alt69066166c9
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 8bit

<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
	<!--[if gte mso 9]>
	<xml>
		<o:OfficeDocumentSettings>
			<o:AllowPNG/>
			<o:PixelsPerInch>96</o:PixelsPerInch>
		</o:OfficeDocumentSettings>
	</xml>
	<![endif]-->
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="x-apple-disable-message-reformatting">
	<!--[if !mso]><!-->
	<meta http-equiv="X-UA-Compatible" content="IE=edge"><!--<![endif]-->
	<title></title>

	<style type="text/css">
		a {
			color: #0000ee;
			text-decoration: underline;
		}
		.u-paragraph {margin-bottom: 25px; color: #555D6B; font-size: 17px; font-family: 'HelveticaNeue', Arial, Helvetica, sans-serif;}

		@media (max-width: 480px) {
			#u_content_button_1 .v-size-width {
				width: auto !important;
			}
		}

		@media only screen and (min-width: 520px) {
			.u-row {
				width: 500px !important;
			}

			.u-row .u-col {
				vertical-align: top;
			}

			.u-row .u-col-50 {
				width: 250px !important;
			}

			.u-row .u-col-100 {
				width: 500px !important;
			}

		}

		@media (max-width: 520px) {
			.u-row-container {
				max-width: 100% !important;
				padding-left: 0px !important;
				padding-right: 0px !important;
			}

			.u-row .u-col {
				min-width: 320px !important;
				max-width: 100% !important;
				display: block !important;
			}

			.u-row {
				width: calc(100% - 40px) !important;
			}

			.u-col {
				width: 100% !important;
			}

			.u-col > div {
				margin: 0 auto;
			}
		}

		body {
			margin: 0;
			padding: 0;
		}

		table,
		tr,
		td {
			vertical-align: top;
			border-collapse: collapse;
		}

		p {
			margin: 0;
		}

		.ie-container table,
		.mso-container table {
			table-layout: fixed;
		}

		* {
			line-height: inherit;
		}

		a[x-apple-data-detectors='true'] {
			color: inherit !important;
			text-decoration: none !important;
		}

	</style>


	<!--[if !mso]><!-->
	<link href="https://fonts.bitrix24.ru/css?family=Open+Sans:400,700&display=swap" rel="stylesheet" type="text/css"><!--<![endif]-->

</head>

<body class="clean-body" style="margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #ffffff">
<!--[if IE]>
<div class="ie-container"><![endif]-->
<!--[if mso]>
<div class="mso-container"><![endif]-->
<table
	style="border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #ffffff;width:100%"
	cellpadding="0" cellspacing="0">
	<tbody>
	<tr style="vertical-align: top">
		<td style="word-break: break-word;border-collapse: collapse !important;vertical-align: top">
			<!--[if (mso)|(IE)]>
			<table width="100%" cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td align="center" style="background-color: #ffffff;"><![endif]-->


			<div class="u-row-container" style="padding: 0px;background-color: transparent">
				<div class="u-row" style="Margin: 0 auto;min-width: 320px;max-width: 500px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;">
					<div style="border-collapse: collapse;display: table;width: 100%;background-color: transparent;">
						<!--[if (mso)|(IE)]>
						<table width="100%" cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td style="padding: 0px;background-color: transparent;" align="center">
									<table cellpadding="0" cellspacing="0" border="0" style="width:500px;">
										<tr style="background-color: transparent;"><![endif]-->

						<!--[if (mso)|(IE)]>
						<td align="center" width="500" style="width: 500px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;" valign="top"><![endif]-->
						<div class="u-col u-col-100" style="max-width: 320px;min-width: 500px;display: table-cell;vertical-align: top;">
							<div style="width: 100% !important;">
								<!--[if (!mso)&(!IE)]><!-->
								<div
									style="padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;">
									<!--<![endif]-->

									<table style="font-family:arial,helvetica,sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
										<tbody>
										<tr>
											<td style="overflow-wrap:break-word;word-break:break-word;padding:10px 50px 10px 10px;font-family:arial,helvetica,sans-serif;" align="left">

												<table width="100%" cellpadding="0" cellspacing="0" border="0">
													<tr>
														<td style="padding-right: 0px;padding-left: 0px;" align="center">

															<img align="center" border="0" src="https://b24-bl55aw.bitrix24.ru/bitrix/images/sender/preset/consent/mail.png"
															alt="Image" title="Image"
															style="outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 100%;max-width: 243px;"
															width="243"/>

														</td>
													</tr>
												</table>

											</td>
										</tr>
										</tbody>
									</table>

									<!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->
							</div>
						</div>
						<!--[if (mso)|(IE)]></td><![endif]-->
						<!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->
					</div>
				</div>
			</div>


			<div class="u-row-container" style="padding: 0px;background-color: transparent">
				<div class="u-row" style="Margin: 0 auto;min-width: 320px;max-width: 500px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;">
					<div style="border-collapse: collapse;display: table;width: 100%;background-color: transparent;">
						<!--[if (mso)|(IE)]>
						<table width="100%" cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td style="padding: 0px;background-color: transparent;" align="center">
									<table cellpadding="0" cellspacing="0" border="0" style="width:500px;">
										<tr style="background-color: transparent;"><![endif]-->

						<!--[if (mso)|(IE)]>
						<td align="center" width="500" style="width: 500px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;" valign="top"><![endif]-->
						<div class="u-col u-col-100" style="max-width: 320px;min-width: 500px;display: table-cell;vertical-align: top;">
							<div style="width: 100% !important;">
								<!--[if (!mso)&(!IE)]><!-->
								<div
									style="padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;">
									<!--<![endif]-->

									<table style="font-family:arial,helvetica,sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
										<tbody>
										<tr>
											<td style="overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:arial,helvetica,sans-serif;" align="left">

												<div>
													<h2 style="text-align: center; font-size: 34px; font-family: 'Open Sans Light', 'HelveticaNeue', Arial, Helvetica, sans-serif; color: #000000;">Вы согласны получать наши рассылки?</h2>
													<p class="u-paragraph">На связи компания ООО &quot;Эксперт Групп&quot;, <b>Российский производитель SMT-оборудования</b>.</p>
<p class="u-paragraph">Приглашаем вас подписаться на нашу новостную рассылку. В ней мы будем делиться с вами информацией о новых моделях нашего SMT оборудования, разработках и других новостях. Мы гарантируем отправку только полезной и актуальной информации, <b>не чаще раза в месяц</b>.</p>
<p class="u-paragraph">Если вам когда-либо покажется, что эта информация вам больше не интересна, <b>вы всегда сможете отказаться от получения рассылки</b>.</p>
<p class="u-paragraph">Мы будем рады видеть вас в числе наших подписчиков. Спасибо за доверие!</p>
<p class="u-paragraph">С уважением,
ООО &quot;Эксперт Групп&quot;</p>
												</div>

											</td>
										</tr>
										</tbody>
									</table>

									<!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->
							</div>
						</div>
						<!--[if (mso)|(IE)]></td><![endif]-->
						<!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->
					</div>
				</div>
			</div>


			<div class="u-row-container" style="padding: 0px;background-color: transparent">
				<div class="u-row" style="Margin: 0 auto;min-width: 320px;max-width: 500px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;">
					<div style="border-collapse: collapse;display: table;width: 100%;background-color: transparent;">
						<!--[if (mso)|(IE)]>
						<table width="100%" cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td style="padding: 0px;background-color: transparent;" align="center">
									<table cellpadding="0" cellspacing="0" border="0" style="width:500px;">
										<tr style="background-color: transparent;"><![endif]-->

						<!--[if (mso)|(IE)]>
						<td align="center" width="500" style="width: 500px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;" valign="top"><![endif]-->
						<div class="u-col u-col-100" style="max-width: 320px;min-width: 500px;display: table-cell;vertical-align: top;">
							<div style="width: 100% !important;">
								<!--[if (!mso)&(!IE)]><!-->
								<div
									style="padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;">
									<!--<![endif]-->

									<table style="font-family:arial,helvetica,sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
										<tbody>
										<tr>
											<td style="overflow-wrap:break-word;word-break:break-word;padding:25px 10px 40px;font-family:arial,helvetica,sans-serif;" align="left">

												<table height="0px" align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #eeeff0;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
													<tbody>
													<tr style="vertical-align: top">
														<td style="word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%">
															<span>&#160;</span>
														</td>
													</tr>
													</tbody>
												</table>

											</td>
										</tr>
										</tbody>
									</table>

									<!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->
							</div>
						</div>
						<!--[if (mso)|(IE)]></td><![endif]-->
						<!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->
					</div>
				</div>
			</div>


			<div class="u-row-container" style="padding: 0px;background-color: transparent">
				<div class="u-row"
				     style="Margin: 0 auto;min-width: 320px;max-width: 500px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: transparent;">
					<div style="border-collapse: collapse;display: table;width: 100%;background-color: transparent;">
						<!--[if (mso)|(IE)]>
						<table width="100%" cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td style="padding: 0px;background-color: transparent;" align="center">
									<table cellpadding="0" cellspacing="0" border="0" style="width:500px;">
										<tr style="background-color: transparent;"><![endif]-->

						<!--[if (mso)|(IE)]>
						<td align="center" width="250" style="width: 250px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;" valign="top"><![endif]-->
						<div class="u-col u-col-50" style="max-width: 320px;min-width: 250px;display: table-cell;vertical-align: top;">
							<div style="width: 100% !important;">
								<!--[if (!mso)&(!IE)]><!-->
								<div
									style="padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;">
									<!--<![endif]-->

									<table id="u_content_button_1" style="font-family:arial,helvetica,sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
										<tbody>
										<tr>
											<td style="overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:arial,helvetica,sans-serif;" align="left">

												<div align="center">
													<!--[if mso]>
													<table width="100%" cellpadding="0" cellspacing="0" border="0" style="border-spacing: 0; border-collapse: collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;font-family:arial,helvetica,sans-serif;">
														<tr>
															<td style="font-family:arial,helvetica,sans-serif;" align="center">
																<v:roundrect xmlns:v="urn:schemas-microsoft-com:vml"
																		xmlns:w="urn:schemas-microsoft-com:office:word"
																		href=""
																		style="height:36px; v-text-anchor:middle; width:230px;"
																		arcsize="5.5%" stroke="f"
																		fillcolor="#bbed21">
																	<w:anchorlock/>
																	<center
																		style="color:#535c69;font-family:arial,helvetica,sans-serif;">
													<![endif]-->
													<a href="https://mailinternetsub.com/ru.b24-bl55aw/pub/mail/consent.php?consent=apply&type=mail&tag=%7B%22CODE%22%3A%22reply%2Bavt43lpnects4h7f3iokmfwdwtbojevbnhhhvvn3ae%40reply.github.com%22%2C%22CONTACT%22%3A%22822%22%2C%22RECIPIENT%22%3A%2227726%22%2C%22POSTING%22%3A%228%22%2C%22CONSENT%22%3A8%7D.1715164817.2e001c2b5c776f2c7b2a4ffd996280cf6a3e381600e2d1a3f2572463c5ff4459" target="_blank" class="v-size-width" style="box-sizing: border-box;display: inline-block;font-family:arial,helvetica,sans-serif;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #535c69; background-color: #bbed21; border-radius: 2px; -webkit-border-radius: 2px; -moz-border-radius: 2px; width:100%; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;">
														<span style="display:block;padding:10px 20px;line-height:120%;"><strong><span
															style="font-size: 12px; line-height: 14.399999999999999px; font-family: 'Open Sans', sans-serif;">Получать</span></strong></span>
													</a>
													<!--[if mso]></center></v:roundrect></td></tr></table><![endif]-->
												</div>

											</td>
										</tr>
										</tbody>
									</table>

									<!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->
							</div>
						</div>
						<!--[if (mso)|(IE)]></td><![endif]-->
						<!--[if (mso)|(IE)]>
						<td align="center" width="250" style="width: 250px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;" valign="top"><![endif]-->
						<div class="u-col u-col-50" style="max-width: 320px;min-width: 250px;display: table-cell;vertical-align: top;">
							<div style="width: 100% !important;">
								<!--[if (!mso)&(!IE)]><!-->
								<div
									style="padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;">
									<!--<![endif]-->

									<table style="font-family:arial,helvetica,sans-serif;" role="presentation" cellpadding="0" cellspacing="0" width="100%" border="0">
										<tbody>
										<tr>
											<td style="overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:arial,helvetica,sans-serif;" align="left">

												<div align="center">
													<!--[if mso]>
													<table width="100%" cellpadding="0" cellspacing="0" border="0" style="border-spacing: 0; border-collapse: collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;font-family:arial,helvetica,sans-serif;">
														<tr>
															<td style="font-family:arial,helvetica,sans-serif;" align="center">
																<v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="" style="height:34px; v-text-anchor:middle; width:225px;"
																		arcsize="6%" strokecolor="#c6cdd3"
																		strokeweight="1px" fillcolor="#ffffff">
																	<w:anchorlock/>
																	<center
																		style="color:#535c69;font-family:arial,helvetica,sans-serif;">
													<![endif]-->
													<a href="https://mailinternetsub.com/ru.b24-bl55aw/pub/mail/consent.php?consent=reject&type=mail&tag=%7B%22CODE%22%3A%22reply%2Bavt43lpnects4h7f3iokmfwdwtbojevbnhhhvvn3ae%40reply.github.com%22%2C%22CONTACT%22%3A%22822%22%2C%22RECIPIENT%22%3A%2227726%22%2C%22POSTING%22%3A%228%22%2C%22CONSENT%22%3A8%7D.1715164817.2e001c2b5c776f2c7b2a4ffd996280cf6a3e381600e2d1a3f2572463c5ff4459" target="_blank" class="v-size-width" style="box-sizing: border-box;display: inline-block;font-family:arial,helvetica,sans-serif;text-decoration: none;-webkit-text-size-adjust: none;text-align: center;color: #535c69; background-color: #ffffff; border-radius: 2px; -webkit-border-radius: 2px; -moz-border-radius: 2px; width:auto; max-width:100%; overflow-wrap: break-word; word-break: break-word; word-wrap:break-word; mso-border-alt: none;border-top-width: 1px; border-top-style: solid; border-top-color: #c6cdd3; border-left-width: 1px; border-left-style: solid; border-left-color: #c6cdd3;
border-right-width: 1px; border-right-style: solid; border-right-color: #c6cdd3; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: #c6cdd3;">
														<span
															style="display:block;padding:9px 19px;line-height:120%;"><strong><span
															style="font-size: 12px; line-height: 14.399999999999999px;">Нет, не присылайте мне ничего</span></strong></span>
													</a>
													<!--[if mso]></center></v:roundrect></td></tr></table><![endif]-->
												</div>

											</td>
										</tr>
										</tbody>
									</table>

									<!--[if (!mso)&(!IE)]><!--></div><!--<![endif]-->
							</div>
						</div>
						<!--[if (mso)|(IE)]></td><![endif]-->
						<!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->
					</div>
				</div>
			</div>


			<!--[if (mso)|(IE)]></td></tr></table><![endif]-->
		</td>
	</tr>
	</tbody>
</table>
<!--[if mso]></div><![endif]-->
<!--[if IE]></div><![endif]-->
</body>

</html>


---------alt69066166c9--
