### ISSUE TITLE
Transceiver doesn't lock to EXT.REF external frequency after first EESDR3 start.

### ISSUE THREAD

**Issue by DK8JV** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#658]
ExpertSDR3 1.0.6 beta, build 28122023
SunSDR2pro and sunSDR2RX

After first program start, the transceiver doesn't lock to the EXT.REF frequency signal, even when the button was previously  activated.
The button shows up as activated after program start.

Only after disabling and re-enabling EXT.REF, the transceiver locks.

Applies to both my DX and pro devices.

Best 73
Eberhard, DK8JV

**Comment by ExpertSDR3** [comment]
We checked the initialization of EXT.REF on the Sunsdr2 and SunSDR2 pro transceivers with firmware 86.8, no problems were found

**Comment by DK8JV** [comment]
Thank you very much for the fast feedback.
I will further investigate and try with different external reference sources. Maybe the problem is related to signal amplitude, then.

 

Best 73
Eberhard, DK8JV

 

Von: EE ***@***.***> 
Gesendet: Donnerstag, 11. Januar 2024 07:49
An: ExpertSDR3/ExpertSDR3-BUG-TRACKER ***@***.***>
Cc: DK8JV ***@***.***>; Author ***@***.***>
Betreff: Re: [ExpertSDR3/ExpertSDR3-BUG-TRACKER] Transceiver doesn't lock to EXT.REF external frequency after first EESDR3 start. (Issue #658)

 

We checked the initialization of EXT.REF on the Sunsdr2 and SunSDR2 pro transceivers with firmware 86.8, no problems were found
