### ISSUE TITLE
MB1 Panel buttons for bands incorrectly mapped

### ISSUE THREAD

**Issue by rofacurion** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#660]
Device and serial number: MB1, EED10261800180
ExpertSDR3 version and build number: 1.0.6 beta
OS: Windows 10/ macOS/ Linux Ubuntu – under which OS you have confirmed the issue: Windows 10 Pro 22H2
Your PC parameters briefly.
Device name SDRMB1
Processor Intel(R) Core(TM) i7-7700T CPU @ 2.90GHz 2.90 GHz
Installed RAM 32.0 GB (31.7 GB usable)
Device ID AE231CC6-7A92-41CC-A581-96B67784F2B7
Product ID 00330-81492-94366-AA954
System type 64-bit operating system, x64-based processor
Pen and touch Touch support with 10 touch points
Edition Windows 10 Pro
Version 22H2
Installed on ‎12/‎10/‎2022
OS build 19045.3803
Experience Windows Feature Experience Pack 1000.19053.1000.0

MB1 PCB rev 3, firmware 86.8

The MB1 front panel buttons for band switching are off by one because 60m band does not have a button.

Pushing 160m panel button switches to 160m.
Pushing 80m panel button switches to 80m.
Pushing 40m panel button switches to 60m.
Pushing 30m panel button switches to 40m.
Pushing 20m panel button switches to 30m.
Pushing 17m panel button switches to 20m.
Pushing 15m panel button switches to 17m.
Pushing 12m panel button switches to 15m.
Pushing 10m panel button switches to 12m.
Pushing 6m panel button switches to 10m.
Pushing 2m panel button switches to 6m.

Selecting the bands using the on-screen buttons in EESDR3 works correctly.

**Comment by rofacurion** [comment]
Here is a video of how to reproduce this issue.
Shared from OneDrive [https://1drv.ms/v/s!AjZ9Bouvf7IxiPE2rhlkn34T8tK2yg?e=6hFRUc](url)

**Comment by ExpertSDR3** [comment]
Fixed. The fixes will be in ESDR3 1.0.7

**Comment by rofacurion** [comment]
> Fixed. The fixes will be in ESDR3 1.0.7

Thanks. Is that the same case for [defect 408](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/issues/408)?

**Comment by rofacurion** [comment]
I have validated that this defect is fixed in ESDR3 1.07.
