### ISSUE TITLE
Ошибки при смене IP адреса SunSDR2 DX

### ISSUE THREAD

**Issue by R2BLM** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#667]
SunSDR2 DX  EED06292301XXX
ExpertSDR3_x64 1.0.7 beta, Version: 86.8
Windows 10 Pro 64
AMD Ryzen 7 5800X 8-Core Processor 3.80 GHz; 16.0 ГБ

Смена IP адреса в 3-й версии программы работает некорректно. IP трансивера вроде бы меняется, программа видит блок трансивера по новому IP и порту, но при включении выдаёт на экране сообщение о невозможности считать калибровки, а в полях остались старые IP и порт. И сам приём отсутствует.
Пытался сменить IP много раз, после чего, для возобновления работы приходилось делать Reset блоку. Сложилось впечатление, что программа не хочет работать не с 16-й подсетью.
При смене IP внутри подсети 16 - всё отлично меняется, как только меняю подсеть на какую-то другую - ошибка считывания калибровок.
После смены IP SunSDR2 DX пинговался по новому адресу и порту, программа его находит и в начальном окне верно указывает адрес и порт введённый при смене.  Зелёная цепочка в левом нижнем углу присутствует. Блокировок брандмауэрами и антивирусами нет. AnyDesk тоже не установлена.
Если указываешь 192.168.16.ххх и любой порт - всё работает.
Если указываешь 192.168.ххх.200: 50001 не работает.
При нажатии кнопки применить новый IP адрес выводится сообщение типа: 
**_I**_P адрес применён_** и следом всем нам уже знакомое - **_Ошибка чтения калибровок_**. 
И всёёё.....
При запуске через секунд 10  на начальном экране ЕxpertSDR3 появляется трансивер с указанным (изменённым) 192.168.1.200 и портом 50001. Т.е. он его находит в сети.
При нажатии на старт - запускается основное окно, но без водопада и наличия сигнала, через 3 секунды выскакивает сообщение об ошибке чтения калибровок.
При запуске основного окна трансивер релюшками не щёлкает.
Трансивер подключаю напрямую в порт системника. Естественно при смене IP трансивера меняю адрес компа, чтобы быть в одной сетке.
Если зайти в настройки программы, там вместо  текущего адреса 192.168.1.200:50001 будет указан старый 192.168.16.200 и 50001.
Меня напрягает факт наличия старого IP и порта в настройках основной программы после их смены. Такое впечатление, что порт и IP для тушки меняется, начальное окно программы это видит и их показывает правильно, а вот при запуске основная программа пытается найти тушку по старому IP и порту, который остался поле в программы, отсюда и невозможность считать калибровки.
**В общем получилось поменять IP адрес.** 
Что сделал в очередной раз после чего трансивер включился и заработал:
После нажатия кнопки смены IP и выдачи программой сообщений, о удачной смене IP и невозможности чтения калибровок ****НЕ ЗАКРЫВАЯ** окна программы нажал на кнопку (Write) записи калибровок**. На экране появилось сообщение "Вы хотите записать калибровки?" И после утвердительного ответа получаем сообщение "Калибровки записаны". До этого раза всегда после смены IP закрывал основное окно.
После таких действий программа начала соединяться и работать с SunSDR2 DX без вывода сообщения об ошибке считывания калибровок

https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/157927844/a97add13-bd31-4dcd-ba7f-d289bd36b05e

https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/157927844/dc2d2237-b860-4167-a576-707809eea0aa

https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/157927844/c2b961e1-9b36-4921-869e-8f6f3e2d45a7

**Comment by ExpertSDR3** [comment]
Исправлено, исправления будут в версии 1.0.8
