### ISSUE TITLE
WSPR requires usb to Transmit/receive

### ISSUE THREAD

**Issue by W3FRG** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#668]
I have wspr operating with the sunsdr2 Dx using jtdx.
However, usb must be selected over wspr to have receive and transmit work.
I am using ver 1.0.7 Beta.

Tom W3FRG

**Comment by ExpertSDR3** [comment]
the jtd program chooses the modulation, wspr works initially in LSB, in JTD it is most likely configured to work with USB.
