### ISSUE TITLE
В трансвертерном режиме невозможна передача при промежуточной частоте не равной частотам любительских диапазонов

### ISSUE THREAD

**Issue by rm6lw** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#669]
В трансвертерном режиме невозможна передача при промежуточной частоте не равной частотам любительских диапазонов, даже при применении IN_ADC/OUT_DAC - подтверждено инженером компании! 
![rxonly](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/116196382/0f5448d3-ce03-445c-a266-8c688e095445)

**Comment by rm6lw** [comment]
Для решения проблемы, по предложению сотрудников EE было произведено открытие на передачу - за пределами любительских диапазонов.
Получилось следующее:
Открылись диапазоны 60м, 6м и работа за пределами любительских диапазонов, в том числе и 2м - за пределами 144-146 мГц. Но в трансвертерном режиме все равно не дает на передачу работать за пределами любительского диапазона по ПЧ!
Если частота 435 мгц— в пределах 70 см диапазона, а ПЧ в моей конструкции получается 135 мгц— передача не работает — неактивны кнопки TUNE и TX и невозможно выбрать TX (A1,A2,A3,DAC ). В BandManager и XVTR все проставлено и установлено!  
Если частота 445 мгц — за пределами 70 см диапазона, включается работа радио без XVTR — передача начинает работать — активны кнопки TUNE и TX, есть выбор TX (A1,DAC )
Данная проблема подтверждена инженером EE.
Скриншоты прилагаю:
![70 см  445 vuw - промежуточная 145 в пределах 2м TX работает](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/116196382/7d3996d9-e553-4741-86f6-5e05988e5701)
![70 см в пределах 430_440 - промежуточная 130_140 нет TX](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/116196382/8f67ea78-14c8-458e-b2ce-f4d40fae6bff)
![147 мгц перешел на передачу](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/116196382/d45df1f7-dc7e-4ee7-b340-f1c9c9faa09d)
![bm](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/116196382/f6d98904-609a-46d1-b355-2f5d9f3048ab)
![rxonly](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/116196382/bcf690fb-71ad-409d-9993-d33a46038840)
![настройки XVTR](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/116196382/05003c98-d0d6-410f-9bdc-5aa6499aa89f)

**Comment by ExpertSDR3** [comment]
Исправлено, в версии 1.0.8 будут исправления.

**Comment by rm6lw** [comment]
Версия 1.0.8 - нет исправлений, все осталось как было

**Comment by rm6lw** [comment]
Версия 1.0.8 - нет исправлений, все осталось как было

**Comment by rm6lw** [comment]
Версия 1.0.9 - нет исправлений, все осталось как было

**Comment by rm6lw** [comment]
Версия 1.0.10 от 14.02.2025 - если ПЧ = 144 мГц (в моем случае) - то передача идет, даже если ПЧ выходит за пределы 144-146мГц.
![Image](https://github.com/user-attachments/assets/bc3e26d5-42f8-4fdb-9585-3e80b8ede17e)
Проверено на 70см и 23 см.
Если ПЧ изначально отличается от 144-146 мГц - передача блокируется - но можно изменить границы диапазона и тогда вот оно счастье - обращу внимание на 70 см в следующем рисунке:
ПЧ - 144 мгц - а диапазон выбираю 444-446 мгц и все начинает работать. Вроде неправильно, но пока хоть так.

![Image](https://github.com/user-attachments/assets/1c999fbd-2029-4912-90ec-55f88a1c8aa0)

**Comment by rm6lw** [comment]
Нет все-таки изменение диапазона нужно дополнить разблокировкой на передачу - нужно попробовать!

**Comment by rm6lw** [comment]
Все работает и на 70 см - с моим опорником 300 мГц - передаю на частоте 438500, при этом промежуток - 138500
Так что как-то так .
Просто понял как обмануть неправильно сделанную XVTR - теперь в этой версии получилось

**Comment by rm6lw** [comment]
В версии 1.0.11 все сломали, теперь трансвертерный режим не работает!
In ver 1.0.11 XVTR not woking

**Comment by rm6lw** [comment]
Осмелюсь сделать предложение:
1. В режиме трансвертера при выборе вход/выход - ADC/DAC отключить ограничение/контроль за значением ПЧ в пределах любительских диапазонов. При выборе A1, A2, A3 - понятно контроль должен быть.

**Comment by yanishevskiy** [comment]
Версия 1.0.11, SunSDR2. У меня трансвертер 432-28 МГц, промежуточная 404 МГц, получается ADC и DAC может работать только в диапазоне 432-433.7 МГц. Если установить Begin или End за этим диапазоном (430-440 МГц), то не только передача не доступна, но и прием перестает нормально работать - отображает RX.ADC (других вариантов нет), но скоммутирован на A3 вместо ADC.
Для ADC/DAC нужен контроль передачи на частотах трансвертера (Begin-End), а не трансивера. Если указаны Begin-End за пределами разрешенных, то для приема разрешать выбор ADC/A1/A2/A3 или исправить принудительное переключение на ADC.

**Comment by rm6lw** [comment]
Starter 1.1.8
ESDR 1.2.1
 а так же
Starter 1.1.9
ESDR 1.3.1
 - НЕ ИСПРАВЛЕННО !!!
 Нижняя частота ПЧ 134 мГц, если получается ниже - не работает!!!
Что-то сделали, нао 134 мГц не победить!
Обещали ответить, -стоит ли в схеме ФВЧ с частотой среза 130-134 мГц. Не понимаю зачем он нужен для DAC/DUC.
Разделить зоны Найквиста - ну для DAC/DUC - он должен быть внешним, иначе либо 1-ю, либо 2-ю зону на них теряем.
Вообщем, пока ждем, в том числе ответа от команды EESDR, есть ли на DAC/DUC - КАКИЕ-ЛИБО ФИЛЬТРА!!!
