### ISSUE TITLE
SPOT setting

### ISSUE THREAD

**Issue by IK2XDE** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#673]
Can you please increase the number of spots managed
and also their life.
Depending on the time of use, (CONTEST or DAILY USE)
it might be appropriate to increase the life up to 60 minutes, and not 20 like now,
then in some contests such as CQWW or CQ WPX, 200 spots are very few,
the ideal would be to increase them to at least 500.

But how is it currently handled?
are there 200 spots in total or 200 for each single band....??

Thanks in advance
73 de IK2XDE Andrea

**Comment by py5hot** [comment]
hello
same problem becouse mb1 respect spot limit and no time limit, and you have many spots from cluster 
normaly over 200. think EE need not need spot limit, but time limit
PY5HOT

**Comment by ExpertSDR3** [comment]
In 1.0.8 version added up to 500 spots maximum and lifetime up to 60 minutes. A large number of spots can negatively affect performance.
