### ISSUE TITLE
Malfunction switching TCI-Mic and Mic1

### ISSUE THREAD

**Issue by DL3DW** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#675]
Hi,

i am right now in the cq160ssb. On Mic1 my headset mic is plugged in. Via TCI-Mic i send my CQ routine to the radio.
It happened twice that the software hangs in TCI-Mic with no slider and no possebility to change it to mic1 back.

i have to delete all folders on my ssd by hand and re-install the software to fix the problem.

Maybe there is another solution.

greating
Daniel DL3DW

**Comment by ExpertSDR3** [comment]
Fixed, changes will appear in version 1.0.8.
