### ISSUE TITLE
E-Coder ring light not activated

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#68]
E-Coder is properly recognized and functioning but the ring light on the tuning knob does not come on.

**Comment by VK6NX** [comment]
ESDR version?
OS version?
Reproduction steps?
Is just Encoder LED is not functioning or Key LED also affected?

**Comment by danweecc** [comment]
All versions of EESDR3 under Windows 10 64-bit. The current version of EESDR3 has no build number to reference.
No steps to reproduce. Just plug the E-Coder in and activate it in EESDR3 - it works but the ring light around the tuning knob does not light up. I've not checked the function of the other LEDs though but I don't remember seeing them light up either.

**Comment by danweecc** [comment]
Okay, I found the problem - my mistake. I had not set the options for the E-Coder correctly. It is done now.
