### ISSUE TITLE
only RX A1/ADC or TX A1/DAC for external 2 m Transverter possible

### ISSUE THREAD

**Issue by suedwind** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#682]
Under XVTR I can add a 2 m Transverter with all data on Band 1:

![grafik](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/131479646/eac6f17b-8391-409f-a759-779010874f94)

In the band manager I can chosse A3 (or A2) for RX and TX:

![grafik](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/131479646/77f5ee9f-393f-4a56-879c-7c760e20d3a6)

But when I switch on the 2 m Transverter there is only A1/ADC for RX and A1/DAC for TX:

![grafik](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/131479646/2dcb7e27-0b2c-45f4-add6-8338839c85d0)

But I need A2/A3 as Input/Output. The 70 cm Transverter is running with no issues (can choose A2/A3). 

![grafik](https://github.com/ExpertSDR3/ExpertSDR3-BUG-TRACKER/assets/131479646/92356bfa-027a-4309-b71d-21b7119b2db0)

- ExpertSDR3 1.0.7 Beta, FW 86.8
- Windows11, HP-470 G8 Notebook, 32 GB RAM, 512 GB-SSD
- sunSDR2pro is running with no problems

73, Henry (DF6LH)

**Comment by ExpertSDR3** [comment]
Fixed, fixes will appear in version 1.0.8
