### ISSUE TITLE
EESDR3 does not fully quit when closing application windows

### ISSUE THREAD

**Issue by williamscody** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#69]
Device: SunSDR2dx
S/N: EED06202100503
EESDR3 version 0.10.0
Windows 10 Pro, version 21H1

Problem: after quitting EESDR3 by closing open application windows (using the Windows taskbar), a "hidden" copy of the application remains running.  This is evident by attempting to relaunch EESDR, and encountering the error: "There are other ExpertSDR3 instances running."

Steps to reproduce:
1) Launch ExpertSDR3
2) Click START to launch the main application
3) Witness there are TWO EESDR3 icons in the Windows taskbar
4) Close the EESDR3 application by right-clicking on each EESDR3 icon, and selecting "Close Window"
5) Relaunch ExpertSDR3
6) Witness the error dialog box "There are other ExpertSDR3 instances running."
7) Confirm in the Windows Task Manager that indeed another instance is running.
8) Right-click on this instance in Task Manager and End Task.  After this, re-launch is possible.

![Screenshot 2021-11-19 195357](https://user-images.githubusercontent.com/16505794/142712524-30c1cf70-ae32-4a25-ac8d-8b897e1c6db4.jpg)

![Screenshot 2021-11-19 195716](https://user-images.githubusercontent.com/16505794/142712531-2676101c-e077-4f4e-b53e-3a000aa8b9bd.jpg)

**Comment by danweecc** [comment]
I think this is normal. The EESDR3 has a launcher app that continues to sit in the bottom right icon tray. You have to quit that as well. Alternatively, you can restart the application from there.

![image](https://user-images.githubusercontent.com/13930571/142712933-de96bbcb-3ec3-4bc3-8d93-3138a9ea2fe7.png)

If you click on that, it brings this up and you can start the application here:-
![image](https://user-images.githubusercontent.com/13930571/142712955-b7490112-cb23-4d01-aaa3-d7eb62607b64.png)

To completely close it, right click on the tray icon and select "Quit":-
![image](https://user-images.githubusercontent.com/13930571/142712974-10c604ed-d5f4-4acd-a988-1d79b15ebb9f.png)

**Comment by williamscody** [comment]
Ah, yes.  Welcome to Windows.

Steve Jobs once described the Windows OS as "unpredictable."  Not much has changed.

At the very least, control of the EESDR3 app via the System Tray should be included in the upcoming documentation.  

Thanks Dan.
