### ISSUE TITLE
RIT problem with EESDR 1.0.8 beta

### ISSUE THREAD

**Issue by HA1AH** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#697]
Dear Developers!

I use a SunSDR2DX for contesting. 
There is a change in the version 1.0.8, which is mentioned in the release notes:
"Now RIT and XIT tuning step equals 10 Hz or 1 Hz while tuning with E-Coder or E-Coder-2"

This change made the RIT unusable in contests! Please revert to the previous settings or make the RIT step configurable.

Thank you and 73:
Tibor
HG5E / HA1AH

**Comment by ExpertSDR3** [comment]
В Версии 1.0.9 добавится выбор шага для RIT и XIT, который будет влиять на перестройку частоты из панелей E-Coder/E-Coder2.
![Снимок экрана от 2024-09-18 14-49-13](https://github.com/user-attachments/assets/706af315-f54f-411b-8143-60c00527a03a)
![Снимок экрана от 2024-09-18 14-49-27](https://github.com/user-attachments/assets/2577e380-56f7-4da2-a10b-06d85e212d9f)

**Comment by HA1AH** [comment]
Unfortunately, not fully OK in 1.0.9 beta.
See video:
https://youtu.be/VfN6mcHkA0k

Description: now the RIT (and XIT) uses always 10Hz as step.
Better than in previous versions (where the step always was 1Hz), but the selected step value is fully ignored.
In the video you can see that the VFO itself has 10 Hz step, then the RIT has also 10 Hz step, then after setting it to 250Hz, the actual RIT step remains 10Hz. It is tested with my SunSDR2DX and E-Coder.
