### ISSUE TITLE
No warning not to mix sound drivers

### ISSUE THREAD

**Issue by rvolchkov** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#7]
SunSDR2 PRO
0.10.0 build 0311021
Windows 10

In ESDR2 there was a warning not to mix the sound drivers when setting up VAC. IN ESDR3 there is no warning when setting up. If you do choose mixed drivers, it just doesn't work.
![Audio_drivers_mixed](https://user-images.githubusercontent.com/90688941/140725056-3d3777a5-69a6-4354-9443-f03e63211a10.jpg)

**Comment by ExpertSDR3** [comment]
In version 0.11, it will be possible to select devices with different drivers

**Comment by ExpertSDR3** [comment]
Закрыто
