### ISSUE TITLE
Bandwidth does not persist through band change

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#70]
When I set a receive bandwidth, for example 3.3K in FT8 on 20M and switch to another band - say 30M and then come back to 20M, the bandwidth is no longer 3.3K but switched to "USER". This only happens for modes FT8, FT4, JT65 and JT9. For other modes like WSPR and standard modes, this does not appear to be a problem.

Before:-
![image](https://user-images.githubusercontent.com/13930571/142712760-e39f8f5e-09a7-4a9b-ace7-c5611571241a.png)

Switch:-
![image](https://user-images.githubusercontent.com/13930571/142712777-74362751-f3ce-4bde-b8db-e2aa0509fdcf.png)

After:-
![image](https://user-images.githubusercontent.com/13930571/142712789-60a45c2e-7c33-470a-9b2e-1e0a0af6a597.png)

**Comment by ExpertSDR3** [comment]
Fixed, fixes will be in version 0.11.
