### ISSUE TITLE
Реализовать управление SAM с помощью панели E-coder

### ISSUE THREAD

**Issue by denis-volodin** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#701]
При прослушивании вещательных АМ станций, очень удобно пользоваться режимом синхронного АМ (SAM). Но при перестройке между станциями, его лучше отключать, чтобы не было противного писка, пока детектор не синхронизируется с несущей. 
Включать/выключать этот режим мышкой с помощью кнопки SAM на панели в программе не очень удобно и оперативно. 
Хочется, чтобы это можно было делать с панели E-coder.

**Comment by ExpertSDR3** [comment]
Добавлено в версию 1.0.9.
![Снимок экрана от 2024-09-18 10-42-35](https://github.com/user-attachments/assets/e017b3fb-0c87-4c9e-a8e0-2a3127dcdaa2)
