### ISSUE TITLE
V1.0.9 beta: Frequency correction for Colibri NANO does not work

### ISSUE THREAD

**Issue by HB9JND** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#703]
In the Calibration window of the ColibriNANO, the value for the frequency correction can be entered, but the value is not adopted with write, so that the NANO is about 230Hz off the target frequency.

My Setup:

- SunSDR2 Pro
- ColibriNANO
- ECoder2
- ESDR3 Version 1.0.9 beta
- Windows 11 Pro, Version 23H2

**Comment by ExpertSDR3** [comment]
Fixed, the changes will appear in the next build.
