### ISSUE TITLE
V1.0.9 beta: IZoomUp and ZoomDown do not work with E-Coder2

### ISSUE THREAD

**Issue by HB9JND** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#704]
No matter which key I configure in the E-Coder2, ZoopUp and ZoomDown to, the zoom function does not work.
The other functions work fine.

My Setup:

SunSDR2 Pro
ColibriNANO
E-Coder2
ESDR3 Version 1.0.9 beta
Windows 11 Pro, Version 23H2

**Comment by ExpertSDR3** [comment]
Fixed, the fixes will appear in the next build.
