### ISSUE TITLE
V1.0.9 beta:  The ColibriNANAO software lacks the ability to define the CW pitch

### ISSUE THREAD

**Issue by HB9JND** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#705]
There is no way to set the CW pitch in the ColibriNANO software. 
However, this is essential for correct reproduction of the CW pitch, especially if the ColibriNANO is synchronized with 
another transceiver via E.Sync.

My Setup:

SunSDR2 Pro
ColibriNANO
E-Coder2
ESDR3 Version 1.0.9 beta
Windows 11 Pro, Version 23H2

**Comment by ExpertSDR3** [comment]
![image](https://github.com/user-attachments/assets/0bf778fe-c2a3-4d43-a512-759b703291d8)
In the next build, the CW Pitch setting will be added for all receivers.
