### ISSUE TITLE
V1.0.9 beta:  Some program parameters are not saved when the program is closed

### ISSUE THREAD

**Issue by HB9JND** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#706]
The following settings are not saved by closing the program, although it would be useful:

1) The dBm scale on the left edge of the spectrum window (the one which is only visible during transmission).

2) The status of the mute button (It is often annoying when the loudspeaker automatically starts to make noise when starting the 
    program).

My Setup:

SunSDR2 Pro
ColibriNANO
E-Coder2
ESDR3 Version 1.0.9 beta
Windows 11 Pro, Version 23H2

**Comment by ExpertSDR3** [comment]
Fixed, the fixes will appear in the next build.
