### ISSUE TITLE
AGC missing "SLOW"

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#71]
When I left-click the AGC, I toggle between "FAST" and "NORM" (which I assume to be MED) but there is no "SLOW" option.

**Comment by ExpertSDR3** [comment]
Based on many reviews in ExpertSDR2, we left 2 modes of operation of the AGC in ExpertSDR 3, normal and fast. Normal - used almost all the time. When a powerful station appears, a fast AGC is required, in which case a weak station is heard after a powerful one. 
In future versions of ExpertSDR3, AGC settings will appear, then you can set comfortable settings for yourself.
