### ISSUE TITLE
VFO lock prevents CAT frequency changes

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#73]
I've noticed a change in the lock behaviour for the VFO frequency lock. In EESDR2, the lock only locks out manual or E-Coder frequency changes but allows CAT/TCI frequency changes (eg. via JTDX). This allows those CAT functions to operate while preventing accidental mouse or dial frequency changes.

In EESDR3, however, the lock also prevents CAT frequency changes. I'm not sure if this is intentional but the EESDR2 lock behaviour is likely preferable for many.

**Comment by ExpertSDR3** [comment]
After discussing this feature with third-party software developers, it was decided to lock any frequency control if lock is enabled.
