### ISSUE TITLE
Received frequency changes when repositioning spectrum display

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#76]
When I reposition the display (without changing the frequency) by right-clicking and dragging the red frequency marker line in the spectrum, I noticed that the received audio is affected. I'm not sure if this is a side-effect of the repositioning even though the received frequency has not changed, technically.

**Comment by ExpertSDR3** [comment]
This is not a bug.
With such a frequency adjustment, there is a change in the central frequency of the receiver and a change in the frequency inside the receiver band, so this introduces distortion into the audio signal.
