### ISSUE TITLE
New Enhancement Request: IQ recorder.

### ISSUE THREAD

**Issue by ttierney** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#77]
One of my favourite features of the ExpertSDRv2 software is the ability to record an IQ stream. This also needs the separate Player software for playback. Tonight, 80M is buzzing and I would love to be able to record what I am hearing. I hope there are plans to include the IQ recorder in the v3 software.
![Lively_80M](https://user-images.githubusercontent.com/61117386/142735804-bf9d090a-e011-4f7a-aa1b-0673308b64dc.png)

**Comment by ExpertSDR3** [comment]
[Move to](https://github.com/ExpertSDR3/ExpertSDR3-SUGGESTIONS/issues/8)
