### ISSUE TITLE
Feature Request: E-Coder Plus/E-Coder2: 1) Encoder(s) steps editable, 2)Top Panel LEDs editable

### ISSUE THREAD

**Issue by VK6NX** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#79]
1. In earlier SW versions (E-coder v.1.0.1) there was an option to change the encoder steps per one encoder turn. It would be nice to have that option back and implemented in combination/cooperation with Tuning Step function of ESDR3

2. Please make LED indicators of E-coder editable, so the function can be assigned. This is only if HW allows.

**Comment by ExpertSDR3** [comment]
[Move to](https://github.com/ExpertSDR3/ExpertSDR3-SUGGESTIONS/issues/7)
