### ISSUE TITLE
GPU load increase

### ISSUE THREAD

**Issue by rvolchkov** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#8]
Windows 10 64 bits
Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   1.99 GHz TO 4,5Ghz
16GO RAM
GPU: Intel UHD Graphics 620

Видео по ссылке: https://drive.google.com/drive/folders/1JGAgObmLTxyZuFQyK_1Si5544oV8i3By?usp=sharing

Here are 2 videos taken shortly after turning on ESDR3 and LogHX.
-The first everything seems normal. By turning the VFO the CPU switches from 14 to 26%. The GPU remains at 10%. Spectrum and waterfall scroll normally.
-The second I open Log view. By turning the VFO the CPU goes to 36%, the GPU goes from 14 to 1% then 1.3%, Spectrum, and waterfall are blocked.
I observe the same thing without opening Log view, while letting the 2 programs run. After about ten minutes, by turning the VFO, movement is jerky on the spectrum and the Waterfall stops. When I stop turning the optical encoder of the E-Coder everything goes back to normal.
If I run SDC with ESDR3 (without LogHX) then as soon as I open Log view and turn the VFO, then the waterfall stops, spectrum only slows down and GPU goes from 11 to 4%

Here you can see what is happening by turning the encoder of the E-Coder, then stopping the rotation, then resuming. ESDR3 is connected to LogHX by TCI. This appears about 10 to 15 minutes after starting the 2 software. If I switch off TCI, everything goes back to normal. If I shut down LogHX, and restart it with ESDR3 on, it happens again. If I stop ESDR3 and leave LogHX on, the phenomenon occurs again after about 10 minutes.
LogHX is on another PC at ESDR3. SDC is on the same PC as ESDR3.

**Comment by ExpertSDR3** [comment]
This problem relates to the internal implementation of graphics in Qt, with the release of new versions of the framework, the situation will improve
