### ISSUE TITLE
Feature request: E-Coder adjustments

### ISSUE THREAD

**Issue by danweecc** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#80]
When I use the E-Coder knobs to adjust, say the CW keyer speed or AGC levels, the value isn't displayed like is when I use the mouse-scroll wheel to adjust them. Having this is quite helpful and would be nice if the feature could be included.

![image](https://user-images.githubusercontent.com/13930571/142750298-470b1139-8688-4076-8902-dd48ee278449.png)

**Comment by ExpertSDR3** [comment]
[Move to](https://github.com/ExpertSDR3/ExpertSDR3-SUGGESTIONS/issues/6)
