### ISSUE TITLE
Remote problem

### ISSUE THREAD

**Issue by SM6BGA** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#81]
I have registered in the cloud.
When I start starter.exe at the "radioPC" a window comes up saying  Connect succesfully. 
So it seems OK.
When I start the ExpertSDR3x64 program at the controlPC the windows that comes up says
under remote  Successfully authorized but in the left part of that window no transceiver shows up
so I can't get any connection.
I have also tried to start the starter program with command prompt but then a text comes up saying:
impossible to get user data from config file:  Create file config.json: Impossible to find file
But I am sure I have the config file configured OK
What to do ?

**Comment by danweecc** [comment]
When you start the ExpertSDR3, there is window where you need to also enter your username and password and click "Login". When you do this, I think that is when the remote will show up:-

![image](https://user-images.githubusercontent.com/13930571/142761206-e360af29-bbc6-4eae-a72f-df358db8a736.png)

**Comment by SM6BGA** [comment]
Yes I have done this.
Otherwise I don't get the message  Succesfully authorized
But no transceiver shows up

**Comment by danweecc** [comment]
If you have the json file configured properly, I heard that you may have to start up the Starter in admin mode. Can you try that - start it with "Run as administrator".

**Comment by N8SDR007** [comment]
I have gone over his Config.Json file we have been messaging and emailing back last couple months, It looks tyo be correct, the other day I had also suggested the start in Admin mode, he had same results
I also have him move the directory to the root of his operating system drive to avoid a potential Windows blocking the script because of location of files- that did not help either
and he has added exceptions to router/firewall and any antivirus.

not sure what else to suggest here. 
I can get this working here with no issues and have done video on it as well

**Comment by danweecc** [comment]
Have you tried disabling Windows firewall on both the remote and the client? Sometimes that can block things unknowingly.

**Comment by SM6BGA** [comment]
I start  starter.exe first at radioPC and then I start  ExpertSDR3x64 at controlPC. The same result.
I can start ExpertSDR3x64 at radioPC and in that window, transceiver shows up and I can get connection directly via the router
and not via the cloud. Then I can use TeamViewer for control but I want connection via the Cloud.

**Comment by danweecc** [comment]
Okay, I am also having a problem with the Windows 20210702 version of the Starter. I tried it on two different Windows 10 64-bit machine. It does start up and say "Connect successful" but nothing shows up in the client side. After a while, it crashes back to commandline with the following message:-
![image](https://user-images.githubusercontent.com/13930571/142768168-c1403187-c6da-4ae9-aa5b-0d2f2368f3fa.png)

This happens whether I start it normally or run as administrator.

**Comment by SM6BGA** [comment]
Yes, I have done this also

Den sön 21 nov. 2021 kl 15:43 skrev danweecc ***@***.***>:

**Comment by danweecc** [comment]
There is a poster on the EESDR FB page who posted this. Not sure if this might be helpful:-

![image](https://user-images.githubusercontent.com/13930571/142800887-8b3f31e7-2381-47de-820f-f793c0706a41.png)

**Comment by danweecc** [comment]
If nothing else works, I would suggest completely turning off the Firewall just for testing. In your case, I think it's more on the remote machine.

**Comment by SM6BGA** [comment]
Yes, I have also done that, but it did not help

**Comment by SM4IVE** [comment]
When connecting my MB1 i get this errors 
Connect successful
2021/12/02 08:12:50.856188 /home/nww/Work/Projects/Go/src/eesdr.com/remoteSystem/starter/worker/scanner/colibriDDC/searcher.go:100: error send search packet, reason: write udp4 0.0.0.0:60570->169.254.255.255:60570: wsasendto: A socket operation was attempted to an unreachable network.
2021/12/02 08:12:51.889358 /home/nww/Work/Projects/Go/src/eesdr.com/remoteSystem/starter/worker/scanner/sunsdr2dx/searcher.go:100: error send search packet, reason: write udp4 0.0.0.0:60571->169.254.255.255:60571: wsasendto: A socket operation was attempted to an unreachable network.
2021/12/02 08:12:52.913664 /home/nww/Work/Projects/Go/src/eesdr.com/remoteSystem/starter/worker/scanner/sunsdr2qrp/searcher.go:101: error send search packet, reason: write udp4 0.0.0.0:60572->169.254.255.255:60572: wsasendto: A socket operation was attempted to an unreachable network.
2021/12/02 08:12:53.932594 /home/nww/Work/Projects/Go/src/eesdr.com/remoteSystem/starter/worker/scanner/sunsdr2pro/searcher.go:106: error send search packet, reason: write udp4 0.0.0.0:60573->169.254.255.255:60573: wsasendto: A socket operation was attempted to an unreachable network.
2021/12/02 08:12:54.951251 /home/nww/Work/Projects/Go/src/eesdr.com/remoteSystem/starter/worker/scanner/mb1/searcher.go:102: error send search packet, reason: write udp4 0.0.0.0:60574->169.254.255.255:60574: wsasendto: A socket operation was attempted to an unreachable network.
2021/12/02 08:16:13.294445 /home/nww/Work/Projects/Go/src/eesdr.com/remoteSystem/starter/worker/scanner/sunsdr2dx/searcher.go:100: error send search packet, reason: write udp4 0.0.0.0:53477->169.254.255.255:53477: wsasendto: A socket operation was attempted to an unreachable network.
2021/12/02 08:16:14.314796 /home/nww/Work/Projects/Go/src/eesdr.com/remoteSystem/starter/worker/scanner/sunsdr2qrp/searcher.go:101: error send search packet, reason: write udp4 0.0.0.0:53478->169.254.255.255:53478: wsasendto: A socket operation was attempted to an unreachable network.
2021/12/02 08:16:15.345934 /home/nww/Work/Projects/Go/src/eesdr.com/remoteSystem/starter/worker/scanner/colibriDDC/searcher.go:100: error send search packet, reason: write udp4 0.0.0.0:53479->169.254.255.255:53479: wsasendto: A socket operation was attempted to an unreachable network.
2021/12/02 08:16:16.387935 /home/nww/Work/Projects/Go/src/eesdr.com/remoteSystem/starter/worker/scanner/sunsdr2pro/searcher.go:106: error send search packet, reason: write udp4 0.0.0.0:53480->169.254.255.255:53480: wsasendto: A socket operation was attempted to an unreachable network.
2021/12/02 08:16:17.406641 /home/nww/Work/Projects/Go/src/eesdr.com/remoteSystem/starter/worker/scanner/mb1/searcher.go:102: error send search packet, reason: write udp4 0.0.0.0:53481->169.254.255.255:53481: wsasendto: A socket operation was attempted to an unreachable network.
2021/12/02 08:16:17.551981 /home/nww/Work/Projects/Go/src/eesdr.com/remoteSystem/starter/cloudConnector.go:164: Cell started successful
2021/12/02 08:16:18.571316 /home/nww/Work/Projects/Go/src/eesdr.com/remoteSystem/starter/worker/scanner/sunsdr2dx/searcher.go:100: error send search packet, reason: write udp4 0.0.0.0:53482->169.254.255.255:53482: wsasendto: A socket operation was attempted to an unreachable network.
2021/12/02 08:16:19.615846 /home/nww/Work/Projects/Go/src/eesdr.com/remoteSystem/starter/worker/scanner/colibriDDC/searcher.go:100: error send search packet, reason: write udp4 0.0.0.0:65084->169.254.255.255:65084: wsasendto: A socket operation was attempted to an unreachable network.
2021/12/02 08:16:20.658916 /home/nww/Work/Projects/Go/src/eesdr.com/remoteSystem/starter/worker/scanner/sunsdr2pro/searcher.go:106: error send search packet, reason: write udp4 0.0.0.0:65085->169.254.255.255:65085: wsasendto: A socket operation was attempted to an unreachable network.
2021/12/02 08:16:21.683403 /home/nww/Work/Projects/Go/src/eesdr.com/remoteSystem/starter/worker/scanner/sunsdr2qrp/searcher.go:101: error send search packet, reason: write udp4 0.0.0.0:65086->169.254.255.255:65086: wsasendto: A socket operation was attempted to an unreachable network.
2021/12/02 08:16:22.700828 /home/nww/Work/Projects/Go/src/eesdr.com/remoteSystem/starter/worker/scanner/mb1/searcher.go:102: error send search packet, reason: write udp4 0.0.0.0:65087->169.254.255.255:65087: wsasendto: A socket operation was attempted to an unreachable network.

And when starting  the sw it works but unable to To get any out put power Tune and TX button works but no power out
