### ISSUE TITLE
Problems during the LZ DX Contest.

### ISSUE THREAD

**Issue by ct1drb** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#84]
Hello all,

with ExpertSDR3 0.10.0 alpha I had 2 problems:

1) time to time software lost the CW TCI connectivity with the Contest software, I had to refresh my radio (contest software is RUMlogNG by DL2RUM);

2) during time I was working with it, maybe 1 hour or even less, software lost connectivity with radio once. Most probably if I would have used it longer had more this kind of problem.

To me software works well for a normal day of activity, during contests with such problems is not usable. However, it is yet in an Alpha state so it could be improved.

Best 73.

CT1DRB
David Quental

**Comment by ExpertSDR3** [comment]
It looks like problems in RUMlog, we will contact the author to solve this problem.
