### ISSUE TITLE
E-coder2 with ESDR3 and Windows11

### ISSUE THREAD

**Issue by Sergey-R5AU** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#85]
E-coder2 working improperly unfortunately with audio:
in reception -continiously distrorted audio with pulse abt. 10-15hz
in transmit CW monitor is very strange - alway at extremely low speed)) independently with CWspeed slider

btw, in case press button E-coder on GUI ESDR3 0.10.0 this button disappeared upon apps next start

OS WIN11  build 22000.348

**Comment by ExpertSDR3** [comment]
The E-Coder and E-Coder 2 indicator is displayed if the panel is connected to the PC. 
When the wrong sound is heard, does restarting the program help?

**Comment by Sergey-R5AU** [comment]
No , ESDR3 restart doesn`t help here, BTW on ESDR2 rel11 RX audio running properly. CW issues with the same symptoms 


I have both types of E-coder`s. Button disappeare only with E-coder2 type by click on E-coder button with left mouse button. Restart of esdr3 mandatory to get back button. Issue valid for all types of API.
GPU - NVIDIA 3070 for notebooks with latest Game Driver

Also i would like indicate wrong CW manipulation withi bith type of E-coders: ex. in case trying transmit letter Z, ex.: QRZ  i hear in monitor QRM  both DITS are lost. with some other leetter other cases but cw core running wrong. To manipultae in woth correct symbols need to add additional pause after second DOT in letter Z


additionally with described distorted audio in the first post - after a time and couple of manupulation with ESDR features during recetpion sporadically apear kind of microphone signal  on e-coder level indicator - restart esdr3 mandatory. Issue valid for  ESDR2 and ESDR3.

**Comment by Sergey-R5AU** [comment]
I did home work with different network latency and jitter. ESDR3 at least two times sensitive with latency&jitter   in compare to ESDR2. Tested in different envirionment and different network adapters

**Comment by danweecc** [comment]
I didn't see this but I just made a report on exactly the same issues as you are describing here. All of them - shortened elements in CW, different speed from E-Coder2 compared to EESDR2/3, choppy audio sometimes. In my case, I disconnected and reconnected the E-Coder2 from the USB and the problem went away.

**Comment by ExpertSDR3** [comment]
fixed, the fixes will be in version 0.11.
