### ISSUE TITLE
No 60m Band with Windows Region Settings German (Switzerland) 

### ISSUE THREAD

**Issue by hb9bun** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#86]
SunSDR2DX EED06221900148
ExpertSDR3 0.10.0 alpha
Windows 10

I was changing regional format settings in Windows 10 from English (United States) to German (Switzerland) and then had not 60m band selectable anymore in ESDR3 after restarting ESDR3. Same for English (Switzerland). The country selection in Windows under Regional settings seems not to allow 60m for Switzerland. 
The change only applies after restarting ESDR3. So when switching from United States to Switzerland first 60m is available. Closing ESDR3 and starting it again with Settings for Switzerland will not show 60m anymore. 

73, Peter - HB9BUN

**Comment by ExpertSDR3** [comment]
Fixed, there will be fixes in version 0.11.
