### ISSUE TITLE
"розовая шумовая линия" неправильно

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#87]
Win 10 - 64 Домашний
Transceiver MB-1

ESDR3 0.10.0.Alpha последняя  с сайта EE
![141470173-597cf72c-fc1c-4090-9063-3fe96692f73e (1)](https://user-images.githubusercontent.com/93991940/142976289-61bd6519-adba-48f8-851c-19615b0ff6af.jpg)

На вход передатчика был подан с генератора сигнала розовый шум и произведено сравнение показания наклонной линии на анализаторе спектра самого генератора и наклонной линии анализатора радио ! Наклонная анализатора радио ( для настройки звука прорисована НЕ ВЕРНО!!!)
хотя программист "ЛЮБЕЗНО " всё исправил прислав отчет!! НЕ ПОНЯТНО ? ГДЕ ЧЕГО ИСПРАВИЛИ???
![141781743-394a61ee-8e05-4c5e-8a2f-0df933073652 (1)](https://user-images.githubusercontent.com/93991940/142976432-9b49c8d4-de81-4bfa-bdda-c4af391d739c.png)

**Comment by ExpertSDR3** [comment]
Вероятно у Вас работает версия не с сайта, а одна из ранних 0.10, удалите вручную программу, убедитесь, что папка ExpertSDR3 отсутствует в C:\Program Files\ExpertElectronics и выполните установку программы скаченной с сайта. Сейчас повторил у себя - всё отображается правильно.

**Comment by 1972igor** [comment]
![bandicam 2021-11-23 09-48-38-796](https://user-images.githubusercontent.com/93991940/142981413-96aeb134-6d77-41c1-9704-f6a300bc0cbc.jpg)
ну как же ? Программа полностью была удалена, из той папки которую вы указали!!! Затем установлена снова ( программа взята с сайта) https://eesdr.com/ru/software-ru/expertsdr3-ru

**Comment by ExpertSDR3** [comment]
Для проверки использовала программа audacity 2.3.3

Создаём розовый шум
![pink_noise_create](https://user-images.githubusercontent.com/93903520/142987638-b7c42c5f-33df-48ee-9c18-942b6fc02efc.png)

![pink_noise_spectrum](https://user-images.githubusercontent.com/93903520/142988088-f27bfd0b-605b-4423-b7a6-3013e0fb1851.png)

Через виртуальные кабели подаём розовый шум из audacity в ExpertSDR3 на MicPC убедившись, что нет никакой обработки сигнала

![pink_noise_1](https://user-images.githubusercontent.com/93903520/142988244-cec33d2c-987d-49f4-b7b2-a63f54a0aca5.png)

Если усилить розовый шум до прямой

![pink_noise_2](https://user-images.githubusercontent.com/93903520/142988324-d8893c1c-06c8-4807-8bc5-e23124691512.png)

Линия розового шума совпала с шумовой дорожкой.

**Comment by 1972igor** [comment]
ТО, что Вы показали , что линию прорисовали верно  Это да , а Вот Желтый спектр , вы подогнали регулятором "BOOST"при этом обратите "ВНИМАНИЕ" , что происходит с уровгнем MIc meter ? отвечу сразу Уровень возрос за , НОЛЬ, ЧТО ДЕЛАТЬ НЕЛЬЗЯ !!! ПРОИСХОДИТ "ПЕРЕГРУЗ" АЦП !!БОЛЬШЕ  ПЛЮС 3 dB!!!
![bandicam 2021-11-24 13-04-49-913](https://user-images.githubusercontent.com/93991940/143218697-78a61e5e-ef55-4811-ae58-d173976397e9.jpg) и  регулятором MIC PC  в ному не выставит !!
![bandicam 2021-11-24 13-04-49-913](https://user-images.githubusercontent.com/93991940/143218925-57d774d9-ed8d-492b-a2ae-2913ca784afd.jpg)
![bandicam 2021-11-24 13-04-55-945](https://user-images.githubusercontent.com/93991940/143218927-4a5ba6fb-82c2-4db7-aab3-39d08bc64f19.jpg)
![bandicam 2021-11-24 13-05-41-406](https://user-images.githubusercontent.com/93991940/143218930-128d068a-0724-48f4-b3a1-e9c94ebcf0c8.jpg)
Должно быть  так MIC PC усиление 0 dB ! индикатор   Boost показания 0dB ,  регулятор усиления выключен!!! Желтая линия должна быть к бардовой! А желтая при условий 0dB не дотягивает!!! СМ РИСУНКИ!!!
