### ISSUE TITLE
PA does not get PTT signal with PA switched on in ESDR3

### ISSUE THREAD

**Issue by hb9bun** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#88]
SunSDR2 DX
0.10.0 alpha 
Windows 10

Even though PA is on, my PA does not get the PTT signal to switch to TX when gong to TUNE or pushing TX in ESDR3. Same setup with ESDR2 works without issue.

**Comment by ra4lp** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/93971152/142980199-f67e62f7-878a-4210-8fc6-5401a31b42d6.png)

**Comment by hb9bun** [comment]
Thank you. This helped! ;-)
