### ISSUE TITLE
B.M. without 6m

### ISSUE THREAD

**Issue by hb9bun** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#89]
Resolved! It is just not visible that the window can be scrolled down ... ;-)

SunSDR2 DX
0.10.0 alpha 
Windows 10

Looking to find the source fot the PA PTT issue I saw that in BM 6m is missing.

**Comment by ExpertSDR3** [comment]
Remarks on the GUI will begin to be eliminated starting with beta versions.
