### ISSUE TITLE
Остановка работы программы Esdr3

### ISSUE THREAD

**Issue by Snakeva** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#9]
Ос win10pro X64 сборка 19043.1320, комп. I5 10400F ram16Гб, видео GTX1050ti . При работе связки лог НХ через TCI происходит остановка работы программы ESSDR3 0.10.0. в режиме CW. Для продолжения работы нужно нажать кнопку вкл в программе essdr.

**Comment by ExpertSDR3** [comment]
Подтверждаю, такой баг есть, занимаюсь поиском причины.

**Comment by Snakeva** [comment]
Может это поможет с решением проблемы. При остановке работы программы вылетает вот такое окно.
![Screenshot_1](https://user-images.githubusercontent.com/93965928/141667829-e18ec206-5832-440c-8067-f8d44ffc0824.jpg)

**Comment by ExpertSDR3** [comment]
Проблема устранена.
