### ISSUE TITLE
ESDR3 0.10.0.Alpha последняя с сайта EE ОТСУСТВУЕТ ПЕРЕСТРОЙКА ЧАСТОТЫ ВАЛКОДЕРОМ ТРАНСИВЕРА!!!

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#90]
ESDR3 0.10.0.Alpha последняя с сайта EE
Win 10 - 64 Домашний
Transceiver MB-1частота перестраивается только  при помощи мышки!!! ОТСУСТВУЕТ ПЕРЕСТРОЙКА ЧАСТОТЫ ВАЛКОДЕРОМ ТРАНСИВЕРА!!!
Программа полностью была удалена, из той папки которую вы указали!!! Затем установлена снова ( программа взята с сайта) https://eesdr.com/ru/software-ru/expertsdr3-ru
ПРОБЫВАЛ БРАТЬ ПРОГРАММУ С АНГЛО ЯЗЫЧНОЙ СТРАНИЦЫ САЙТА!!!
НАКЛОН "розового шума" У МЕНЯ НЕ ИЗМЕНИЛСЯ ВСЁ ТОТЖЕ НЕПРАВИЛЬНЫЙ !!!
![bandicam 2021-11-23 09-48-38-796](https://user-images.githubusercontent.com/93991940/142986981-96a201f0-4efb-4d45-a06e-20bc9bd8a230.jpg)

**Comment by ExpertSDR3** [comment]
Проблема не обнаружена, возможно параллельно запущен ESDR2, который монопольно захватил управление фронтальной панелью.

**Comment by 1972igor** [comment]
да ! СПАСИБО! ВСЁ ПОЛУЧИЛОСЬ!
