### ISSUE TITLE
УРОВНИ ESDR3 v 0.10.0

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#97]
WIN -10 HOME 64 
transceiver MB-1
Уважаемый ПРОГРАММИСТ! Простите Не знаю Вашего Имени!
Пожалуйста!! ВЫСТАВИТЕ ПРАВИЛЬНЫЕ ПОКАЗАНИЯ MIC meret, Показания Панорамы TX ( шаг клетки
в ПАНОРАМЕ Я ВЗЯЛ 5dB) ПРИ ОДНОТОНОВОМ ВНЕШНЕМ ГЕНЕРАТОРЕ подключённым на входа MIC Pc, MIC-1, MIC-2 должный совпадать!! А на сегодняшний день совпадают ТОЛЬКО ПРИ ВХОДНОМ 0dB!!! И то примерно !!!
регулятор усиления Mic PC находится в положении 0 дБ "ВСЕГДА". Все модули обработки "PROC" "ВЫКЛЮЧЕНЫ"
вход 0 дБ MICLEVEL показывает 0 дБ
вход минус 5 дБ -MIC LEVEL показывает минус 2.4 дБ вход минус
10 дБ- MIC LEVEL показывает минус 4.9 дБ 
вход минус 15 дБ - MIC LEVEL показывает отрицательный 7.4 дБ
вход минус 20 дБ -MIC LEVEL показывает минус -9.9 дБ
вход минус 25 дБ - MIC LEVEL показывает минус 12.4 дБ
вход минус 30 дБ - MIC LEVEL показывает минус 14.9dB
вход минус 35dB MIC LEVEL показывает минус 17.4dB
 Очень Вас прошу, НЕ ЗАБУДТЕ ПОЖАЛУЙСТА про правильность показаний индикатора "Boost" в режиме "BYPASS" на уровнях минус 12dB, минус 24dB, минус36dB, минус 48dB, минус 60dB!!! Уровень 0dB индикатора "Boost" полностью в показаниях совпадает MIC meret, при этом положение регулятора усиления "Boost" находится в 0dB"ВСЕГДА"!!!
Обратите внимание , что когда производится "ВКЛЮЧЕНИЕ " ГЕНЕРАТОРА ДВА ТОНА (самой программы ESDR3 . то уровень Mic meter минус 3 дБ , а это не правильно , генераторы два тона должны складываются амплитуде и вычитаться по уровню!!
А именно, на панораме передатчика должно быть показания минус 6dB! А индикатор MIC meter, программы ESDR3 при работе генератора двух тонов самой программыESDR3 . должен показывать 0dB!!! Я подал два тона с внешнего генератора , индикатор Mic meter 0 показывает! А вот панорама "ВРЁТ"
![bandicam 2021-11-24 12-11-37-864](https://user-images.githubusercontent.com/93991940/143208827-1c0731b6-6f4b-4e26-b124-ae7144314060.jpg)
![bandicam 2021-11-24 12-12-03-395](https://user-images.githubusercontent.com/93991940/143208830-49efefea-50f3-4468-9b09-6994c32611d7.jpg)
![bandicam 2021-11-24 12-12-10-017](https://user-images.githubusercontent.com/93991940/143208833-1f29d416-0320-417f-937f-d2da80a8144e.jpg)
 Как это сделано в ESDR2
P.S/ ЗВУК В ЭТОЙ ПРОГРАММЕ ВЫСТРАИВАЕТСЯ ХОРОШИЙ!!Лучше чем ESDR2-- МОЛОДЦЫ! ТОЛЬКО ВОТ ПОКАЗАНИЯ УВОНЕЙ,НУЖНО ТОЧНЕЕ ВЫСТАВИТЬ!! НА дворе 21 век, а у нас индикатор плюс минус лапоть показывает!
 СПАСИБОЗА ВАШ ТРУД!!!
 С УВАЖЕНИЕМ К КОМАНДЕ ЕЕ И ЛИЧНО К ВАМ!

**Comment by ExpertSDR3** [comment]
Дублирует #35
