### ISSUE TITLE
"Розовый шум "

### ISSUE THREAD

**Issue by 1972igor** [ExpertSDR3/ExpertSDR3-BUG-TRACKER#98]
Для проверки использовала программа audacity 2.3.3

Создаём розовый шум
![загрузка (1)](https://user-images.githubusercontent.com/93991940/143222216-6f83c52e-2c9a-4cf6-9061-79d48dee5595.png)
![загрузка](https://user-images.githubusercontent.com/93991940/143222221-63d0ff58-019c-419d-b602-039044d0e9e4.png)
во первых видно , что уровень не 0 dB!!!
Для проверки использовала программа audacity 2.3.3

Создаём розовый шум
![загрузка (2)](https://user-images.githubusercontent.com/93991940/143222550-43fec621-f3a9-47eb-bad6-b948b661fe08.png)
Для проверки использовала программа audacity 2.3.3
Если усилить розовый шум до прямой
![загрузка (3)](https://user-images.githubusercontent.com/93991940/143222766-a3e6ade6-a2f7-43db-8d4d-a6127951f05f.png)
то линию прорисовали верно Это да , а Вот Желтый спектр , вы подогнали регулятором "BOOST"при этом обратите "ВНИМАНИЕ" , что происходит с уровровем MIc meter ? отвечу сразу Уровень возрос за , НОЛЬ, ЧТО ДЕЛАТЬ НЕЛЬЗЯ !!! ПРОИСХОДИТ "ПЕРЕГРУЗ" АЦП !! БОЛЬШЕ ПЛЮС 3 дБ!!!
и регулятором MIC PC в ному не выставит !!
![bandicam 2021-11-24 13-04-49-913](https://user-images.githubusercontent.com/93991940/143223020-0a3ea653-eac1-4be2-bdfd-af89080506dd.jpg)
![bandicam 2021-11-24 13-04-55-945](https://user-images.githubusercontent.com/93991940/143223021-26f7e3d2-f6ca-4564-bb4b-9ed1a6df5b7b.jpg)
![bandicam 2021-11-24 13-05-41-406](https://user-images.githubusercontent.com/93991940/143223022-619cafeb-395e-44ca-aaf5-30dd908b6522.jpg)

индикатор Boost показания 0dB , регулятор выключен усиления!!! Желтая линия должна быть к бардовой! А желтая при условий 0dB не дотягивает!!! СМ РИСУНКИ!!!

**Comment by ExpertSDR3** [comment]
Дублирует #87
